### ISSUE TITLE
Stucked on setup.

### ISSUE THREAD

**Issue by alejandronanez** [semantic-release/semantic-release#101]
CLI is stucked after setting Travis CI. It's been like this for like 30 minutes now.
<img width="476" alt="screen shot 2015-09-28 at 7 10 27 pm" src="https://cloud.githubusercontent.com/assets/464978/10152141/b08e1414-6614-11e5-8485-dd6ca04d7060.png">

Any ideas what's going on?

**Comment by alejandronanez** [comment]
```shell
usr/local/lib/node_modules/semantic-release-cli/dist/lib/travis.js:42
    if (res.user.is_syncing) {
           ^

TypeError: Cannot read property 'user' of undefined
    at /usr/local/lib/node_modules/semantic-release-cli/dist/lib/travis.js:42:12
    at /usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21
    at Request._callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
    at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:148:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:886:14)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:837:12)
```

This is what I'm getting on my console after waiting for a long time.

**Comment by boennemann** [comment]
@christophwitzko Can you look into this?

**Comment by alejandronanez** [comment]
@boennemann @christophwitzko I haven't signed up for Travis and that was causing the problem. We still need to handle that scenario though.

**Comment by boennemann** [comment]
@alejandronanez Ah, nice, thanks for catching that :) I'm closing this in favor of an issue on the CLI repo:

https://github.com/semantic-release/cli/issues/38
