### ISSUE TITLE
EGITNOPERMISSION git push fail with GITLAB and LFS

### ISSUE THREAD

**Issue by samouds** [semantic-release/semantic-release#1047]
Hello,

I'm getting trouble with one of my gitlab repo, I'm using the same access token as another repo that works. I have two errors : 
- LFS not supported .
- cannot push to the repo (403)

```
[11:47:06 AM] [semantic-release] › ✔  Run automated release from branch master
2018-12-26T11:47:06.679Z semantic-release:git Error: Command failed: git push --dry-run https://gitlab-ci-token:[secure]@gitlab.com/example/example-api.git HEAD:master
remote: You are not allowed to upload code.
fatal: unable to access 'https://gitlab-ci-token:[secure]@gitlab.com/example/example-api.git/': The requested URL returned error: 403


    at makeError (/root/.npm/_npx/61/lib/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/root/.npm/_npx/61/lib/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2018-12-26T11:47:06.870Z semantic-release:git Error: Command failed: git push --dry-run https://gitlab-ci-token:[secure]@gitlab.com/example/example-api.git HEAD:master

This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.

error: failed to push some refs to 'https://gitlab-ci-token:[secure]@gitlab.com/example/example-api.git'


    at makeError (/root/.npm/_npx/61/lib/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/root/.npm/_npx/61/lib/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[11:47:07 AM] [semantic-release] › ✖  The command "git push --dry-run https://gitlab-ci-token:[secure]@gitlab.com/example/example-api.git HEAD:master" failed with the error message 
This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.

error: failed to push some refs to 'https://gitlab-ci-token:[secure]@gitlab.com/example/example-api.git'
.
[11:47:07 AM] [semantic-release] › ✖  EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch master on remote Git repository with URL https://gitlab-ci-token:[secure]@gitlab.com/example/example-api.git.

Please refer to the authentication configuration documentation (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) is configured with a valid Git URL (https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).

{ SemanticReleaseError: The push permission to the Git repository is required.
    at module.exports (/root/.npm/_npx/61/lib/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/root/.npm/_npx/61/lib/node_modules/semantic-release/index.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details:
   '**semantic-release** cannot push the version tag to the branch `master` on remote Git repository with URL `https://gitlab-ci-token:[secure]@gitlab.com/example/example-api.git`.\n\nPlease refer to the [authentication configuration documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) is configured with a [valid Git URL](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).',
  semanticRelease: true }ERROR: Job failed: exit code 1
```

**Comment by pvdlg** [comment]
It seems the user associated with the token you are using is not allowed to push to your remote repository. Easier you simply didn't allow that user to push or it might be related to the GitLab limitation described in https://github.com/semantic-release/gitlab/issues/19.

Regarding Git LFS, it seems related to your CI. semantic-release needs to run `git` commands such as `git push`. If those command doesn't work on your CI, semantic-release will error out.
I don't know the specifics of your CI and your repo, so I can't help much... According to the error message you have a Git hook that require Git LFS and its not installed on your CI.

**Comment by samouds** [comment]
@pvdlg Thanks for your answer. But the user is allowed to push to any branch of the remote repo.

It's normal to have a trailing slash at the end of the url ?
```
fatal: unable to access 'https://gitlab-ci-token:[secure]@gitlab.com/example/example-api.git/': The requested URL returned error: 403
```

**Comment by pvdlg** [comment]
Closing due to lack of follow up.
