### ISSUE TITLE
Semantic Release can not use my GitLab Token

### ISSUE THREAD

**Issue by fltrtsch** [semantic-release/semantic-release#1073]
Hey guys,

I need help to integrate Semantic Release to my GitLab + GitLab CI Runner Environment or I found a bug. I followed the instructions and I thought that not so much could possibly go wrong. But it seems like semantic releases can not use my GL_TOKEN. Here my complete configuration, all informations and the complete log the semantic release in my CI pipeline.
GitLab: 11.6.4-ee
GitLab Runner: 11.5.1
CI Docker Image: node:10.14.2
Semantic Release: 15.13.3
@semantic-release/gitlab 3.1.2
I created a personal access token named "Semantic Release" with the scope "api" in my profile. I'm administrator in my GitLab, owner of the group in which the project is. And so, I'm also the owner of the project. I entered my personal access token as "GL_TOKEN" in the Secret Variables of the group as well as directly in the variables of the project. I also tested my token with `git push --dry-run https://gitlab-ci-token:mysupersecrettoken@gitlab.mycompany.com/mygroup/my-project.git HEAD:master` and get `Everything up-to-date`.
Here's my `.releaserc` file in the projects root folder:
```
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    ["@semantic-release/gitlab", {
      "gitlabUrl": "https://gitlab.mycompany.com",
      "assets": [
        {"path": "dist/**", "label": "Library distribution"},
      ]
    }],
  ]
}
```
There's also a link to the repository in the `package.json` file:
```
[...]
  "repository": {
    "type": "git",
    "url": "https://gitlab.mycompany.com/mygroup/my-project.git"
  }
[...]
```
And here's my minimal `.gitlab-ci.yml` file:
```
image: node:10.14.2

stages:
  - deploy

before_script:
  - npm install

deploy:
  stage: deploy
  script:
    - npx semantic-release
  environment:
    name: production
```

For debugging, I also set the DEBUG variable in GitLab. The CI can read the variables, because DEBUG works as well as my NPM_TOKEN variable to publish the package.
Here's what my CI says:
```
Running on myrunner via gitlabrunner...
Fetching changes...
Removing node_modules/
HEAD is now at 123123 Commit message here.
From https://gitlab.mycompany.com/mygroup/my-project
 + 123123...456456 master     -> origin/master  (forced update)
Checking out 456456 as master...
Skipping Git submodules setup
$ npm install
added 1052 packages from 976 contributors and audited 8320 packages in 26.757s
found 0 vulnerabilities

$ npx semantic-release
[2:15:02 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.3
2019-01-17T14:15:02.616Z semantic-release:config load config from: /builds/mygroup/my-project/.releaserc
2019-01-17T14:15:02.621Z semantic-release:config options values: { branch: 'master',
  repositoryUrl: 'https://gitlab.mycompany.com/mygroup/my-project.git',
  tagFormat: 'v${version}',
  plugins:
   [ '@semantic-release/commit-analyzer',
     '@semantic-release/release-notes-generator',
     [ '@semantic-release/gitlab', [Object] ] ],
  _: [],
  '$0': 'node_modules/.bin/semantic-release' }
2019-01-17T14:15:02.835Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: { gitlabUrl: 'https://gitlab.mycompany.com',
  assets: [ { path: 'dist/**', label: 'Library distribution' } ] }
[2:15:02 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
2019-01-17T14:15:02.837Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[2:15:02 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2019-01-17T14:15:02.838Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[2:15:02 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2019-01-17T14:15:02.838Z semantic-release:plugins options for @semantic-release/gitlab/publish: { gitlabUrl: 'https://gitlab.mycompany.com',
  assets: [ { path: 'dist/**', label: 'Library distribution' } ] }
[2:15:02 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[2:15:02 PM] [semantic-release] › ✔  Run automated release from branch master
2019-01-17T14:15:03.804Z semantic-release:git Error: Command failed: git push --dry-run https://gitlab.mycompany.com/mygroup/my-project.git HEAD:master
remote: HTTP Basic: Access denied
remote: You must use a personal access token with 'api' scope for Git over HTTP.
remote: You can generate one at https://gitlab.mycompany.com/profile/personal_access_tokens
fatal: Authentication failed for 'https://gitlab.mycompany.com/mygroup/my-project.git/'


    at makeError (/builds/mygroup/my-project/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/builds/mygroup/my-project/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[2:15:04 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[2:15:04 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
2019-01-17T14:15:04.180Z semantic-release:gitlab repoId: 'mygroup/my-project'
2019-01-17T14:15:04.181Z semantic-release:gitlab apiUrl: 'https://gitlab.mycompany.com/api/v4'
[2:15:04 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.mycompany.com/api/v4)
[2:15:04 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/gitlab"
[2:15:04 PM] [semantic-release] › ✖  EMISSINGREPO The repository mygroup/my-project doesn't exist.
The semantic-release repositoryUrl option must refer to your GitLab repository. The repository must be accessible with the GitLab API (https://docs.gitlab.com/ce/api/README.html).

By default the repositoryUrl option is retrieved from the repository property of your package.json or the git origin url (https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes) of the repository cloned by your CI environment.

If you are using GitLab Enterprise Edition (https://about.gitlab.com/gitlab-ee) please make sure to configure the gitlabUrl and gitlabApiPathPrefix options (https://github.com/semantic-release/gitlab/blob/master/README.md#options).

[2:15:04 PM] [semantic-release] › ✖  EGLNOPERMISSION The GitLab token doesn't allow to push on the repository mygroup/my-project.
The user associated with the GitLab token (https://github.com/semantic-release/gitlab/blob/master/README.md#gitlab-authentication) configured in the GL_TOKEN or GITLAB_TOKEN environment variable must allows to push to the repository mygroup/my-project.

Please make sure the GitLab user associated with the token has the permission to push (https://docs.gitlab.com/ee/user/permissions.html#project-members-permissions) to the repository mygroup/my-project.

{ AggregateError: 
    SemanticReleaseError: The repository mygroup/my-project doesn't exist.
        at module.exports (/builds/mygroup/my-project/node_modules/@semantic-release/gitlab/lib/get-error.js:6:10)
        at module.exports (/builds/mygroup/my-project/node_modules/@semantic-release/gitlab/lib/verify.js:60:21)
    SemanticReleaseError: The GitLab token doesn't allow to push on the repository mygroup/my-project.
        at module.exports (/builds/mygroup/my-project/node_modules/@semantic-release/gitlab/lib/get-error.js:6:10)
        at module.exports (/builds/mygroup/my-project/node_modules/@semantic-release/gitlab/lib/verify.js:67:19)
    at /builds/mygroup/my-project/node_modules/semantic-release/lib/plugins/pipeline.js:53:11
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }ERROR: Job failed: exit code 1
```

I tried many things, but none of them worked. I'm pretty sure that there's no typo, because my colleagues get the same error.

I can provide more informations, if needed. Maybe you find out that's going wrong.

**Comment by fltrtsch** [comment]
I've not set the `GL_PREFIX` variable, because it should use the default `https://gitlab.mycompany.com/api/v4` endpoint. This should work according to the debug logs. `apiUrl` is set to `'https://gitlab.mycompany.com/api/v4'`. I've also curl-ed the API with the `Private-Token: <token>` header for a file in my-project and got a valid response.

**Comment by pvdlg** [comment]
What does `curl --header "X-Private-Token: ${GH_TOKEN}" https://gitlab.mycompany.com/api/v4/projects/mygroup/myrepo` returns?
The plugin does exactly that and that returns a 404 saying `mygroup/myrepo` doesn't exists.

**Comment by fltrtsch** [comment]
The calls
`curl --header "PRIVATE-TOKEN: mysupersecrettoken" https://gitlab.mycompany.com/api/v4/projects/mygroup/my-project` and 
`curl --header "PRIVATE-TOKEN: mysupersecrettoken" https://gitlab.mycompany.com/api/v4/projects/mygroup/my-project.git`
returning `{"error":"404 Not Found"}`.
`curl --header "PRIVATE-TOKEN: mysupersecrettoken" https://gitlab.mycompany.com/api/v4/projects/mygroup%2Fmy-project` and
`curl --header "PRIVATE-TOKEN: mysupersecrettoken" https://gitlab.mycompany.com/api/v4/projects/mygroup%2Fmy-project.git` with URL encoding returning
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /api/v4/projects/mygroup/my-group was not found on this server.</p>
<hr>
<address>Apache/x.x.x (Linux) Server at gitlab.company.com Port 443</address>
</body></html>
```

I also tried `curl --header "PRIVATE-TOKEN: mysupersecrettoken" https://gitlab.mycompany.com/api/v4/projects` and get an array with my repo inside. This array elements is slightly the same as the response with the project ID `curl --header "PRIVATE-TOKEN: mysupersecrettoken" https://gitlab.mycompany.com/api/v4/projects/93`
```
{
  "id": 93,
  "description": "Awesome description",
  "name": "my-project",
  "name_with_namespace": "MyGroup / my-project",
  "path": "my-project",
  "path_with_namespace": "mygroup/my-project",
  "created_at": "2018-12-27T10:05:30.623Z",
  "default_branch": "master",
  "tag_list": [],
  "ssh_url_to_repo": "git@gitlab.company.com:mygroup/my-project.git",
  "http_url_to_repo": "https://gitlab.company.com/mygroup/my-project.git",
  "web_url": "https://gitlab.company.com/mygroup/my-project",
  "readme_url": "https://gitlab.company.com/mygroup/my-project/blob/master/README.md",
  "avatar_url": null,
  "star_count": 0,
  "forks_count": 0,
  "last_activity_at": "2019-01-17T13:25:55.487Z",
  "namespace": {
    "id": 2,
    "name": "MyGroup",
    "path": "mygroup",
    "kind": "group",
    "full_path": "mygroup",
    "parent_id": null
  },
  "_links": {
    "self": "https://gitlab.company.com/api/v4/projects/93",
    "issues": "https://gitlab.company.com/api/v4/projects/93/issues",
    "merge_requests": "https://gitlab.company.com/api/v4/projects/93/merge_requests",
    "repo_branches": "https://gitlab.company.com/api/v4/projects/93/repository/branches",
    "labels": "https://gitlab.company.com/api/v4/projects/93/labels",
    "events": "https://gitlab.company.com/api/v4/projects/93/events",
    "members": "https://gitlab.company.com/api/v4/projects/93/members"
  },
  "archived": false,
  "visibility": "private",
  "resolve_outdated_diff_discussions": false,
  "container_registry_enabled": true,
  "issues_enabled": true,
  "merge_requests_enabled": true,
  "wiki_enabled": true,
  "jobs_enabled": true,
  "snippets_enabled": true,
  "shared_runners_enabled": true,
  "lfs_enabled": true,
  "creator_id": 2,
  "import_status": "none",
  "import_error": null,
  "open_issues_count": 0,
  "runners_token": "tokentokentoken",
  "public_jobs": true,
  "ci_config_path": null,
  "shared_with_groups": [],
  "only_allow_merge_if_pipeline_succeeds": false,
  "request_access_enabled": false,
  "only_allow_merge_if_all_discussions_are_resolved": false,
  "printing_merge_request_link_enabled": true,
  "merge_method": "merge",
  "permissions": {
    "project_access": null,
    "group_access": {
      "access_level": 50,
      "notification_level": 3
    }
  },
  "repository_storage": "default"
}
```

I have not changed or deleted any important information for you in the logs. Only the secrets, domain, group name and project name has been changed with the specials including a "-" in the projects name.

**Comment by fltrtsch** [comment]
Just found something. We proxy our GitLab with an Apache. Maybe the Apache does some URL encoding for the slashes between mygroup and my-project. I'll write you back. :)

**Comment by fltrtsch** [comment]
We added some parameters to the proxy config of Apache and it seems like it's working now. Here's the ticket link for the solution: https://stackoverflow.com/questions/4390436/need-to-allow-encoded-slashes-on-apache/9933890#9933890

Thank you very much for your quick responses Pierre! Absolutely amazing support for an open source project. Have a nice weekend!
