### ISSUE TITLE
npm ERR! Version not changed, might want --allow-same-version

### ISSUE THREAD

**Issue by samAbeywickrama** [semantic-release/semantic-release#1077]
Running semantic-release in circle throws this error. Please help me with this

> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/circleci/.npm/_logs/2019-01-19T15_58_22_394Z-debug.log
> [3:58:22 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/npm"
> [3:58:22 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: npm version 1.0.0 --no-git-tag-version
> npm ERR! Version not changed, might want --allow-same-version
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/circleci/.npm/_logs/2019-01-19T15_58_22_394Z-debug.log
> 
> 
>     at makeError (/home/circleci/tmp/node_modules/execa/index.js:174:9)
>     at Promise.all.then.arr (/home/circleci/tmp/node_modules/execa/index.js:278:16)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   code: 1,
>   stdout: '',
>   stderr:
>    'npm ERR! Version not changed, might want --allow-same-version\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/circleci/.npm/_logs/2019-01-19T15_58_22_394Z-debug.log\n',
>   failed: true,
>   signal: null,
>   cmd: 'npm version 1.0.0 --no-git-tag-version',
>   timedOut: false,
>   killed: false,
>   pluginName: '@semantic-release/npm' }
> { Error: Command failed: npm version 1.0.0 --no-git-tag-version
> npm ERR! Version not changed, might want --allow-same-version
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/circleci/.npm/_logs/2019-01-19T15_58_22_394Z-debug.log
> 
> 
>     at makeError (/home/circleci/tmp/node_modules/execa/index.js:174:9)
>     at Promise.all.then.arr (/home/circleci/tmp/node_modules/execa/index.js:278:16)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>   code: 1,
>   stdout: '',
>   stderr:
>    'npm ERR! Version not changed, might want --allow-same-version\n\nnpm ERR! A complete log of this run can be found in:\nnpm ERR!     /home/circleci/.npm/_logs/2019-01-19T15_58_22_394Z-debug.log\n',
>   failed: true,
>   signal: null,
>   cmd: 'npm version 1.0.0 --no-git-tag-version',
>   timedOut: false,
>   killed: false,
>   pluginName: '@semantic-release/npm' }Exited with code 1

**Comment by PaulRBerg** [comment]
In my case, this happened when the `yarn.lock` file (probably same behaviour for `package-lock.json`) was out-of-sync with the versions in `package.json`. That is, I initially set `1.0.0`, ran `yarn install`, then swapped `1.0.0` with `0.0.0-semantically-released` and then I pushed to origin *without* running `yarn install` again.

To ensure things will work fine, you'd better remove `node_modules` and the `yarn.lock`/ `package-lock.json` file.

**Comment by travi** [comment]
semantic-release only cares about the versions that have been stored in the repo as tags and determines the next version from the commit messages of the commits since the last tagged version. the version in the package.json is ignored by semantic-release and overwritten at publish time. node modules and lockfiles also have no impact on the version that semantic-release attempts to publish.

it is more likely that you had the version you mentioned in your package.json and published manually at some point without adding a tag for semantic-release to find. semantic-release always publishes v1.0.0 as the first version if it does not find a previous tag. if that version already exists on npm, npm will reject the attempt to publish the same version again.

**Comment by tobek** [comment]
> the version in the package.json is ignored by semantic-release and overwritten at publish time

Note the second part of the sentence, which results in it not entirely being ignored. If the version number determined by semantic-release matches the version number already in `package.json`, then, when it attempts to overwrite `package.json` at publish time, it will find it's the same version and throw the error that OP was seeing. Make sure you don't update `package.json` manually, just let semantic-release handle it.

**Comment by travi** [comment]
> If the version number determined by semantic-release matches the version number already in `package.json`

its not actually an issue with the version that is in the `package.json` at all. it is completely a matter of trying to _publish to npm_ a version that already exists in npm.

> npm ERR! Version not changed, might want --allow-same-version

that error results from the attempt to actually publish to the registry and is a response from the registry to report publishing failure.

there is a sync problem, but it is not a matter of the `package.json` being out of sync. it is a matter of the versions that are already published to the npm registry being out of sync with the tags in the git repository

**Comment by tobek** [comment]
In my case it really does seem like package.json was the culprit. I hit this error during an initial publish of a package that had never been published to the registry before, even privately. Because of a misunderstanding I had just manually updated package.json version from `1.0.0` to `1.4.0` (which was the version semantic release worked out would be next). It resulted in:

```
[12:26:45 PM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 1.4.0 to package.json in /home/circleci/project
npm ERR! Version not changed, might want --allow-same-version

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2019-06-04T12_26_45_932Z-debug.log
[12:26:45 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/npm"
[12:26:45 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: npm version 1.4.0 --no-git-tag-version
npm ERR! Version not changed, might want --allow-same-version
```

I then made one change, which was reverting package.json version back to `1.0.0`, and then the npm publish worked, publishing as `1.4.0`.

This very much makes it seem like the package.json version number was what generated the error.

Failed release: https://circleci.com/gh/joincivil/civil-sdk/83
Successful release: https://circleci.com/gh/joincivil/civil-sdk/85
npm package with only one version: https://www.npmjs.com/package/@joincivil/civil-sdk

**Comment by travi** [comment]
i appologize. you're correct. 

looks like the error is from the `npm version` command that is used by semantic-release to set the version. this is behavior that is inherited by semantic-release by using the core tools, so not really an issue with semantic-release itself.

it may be worth some clarification in the docs though. would you be interested in submitting a PR?

**Comment by mirismaili** [comment]
Isn't a way to add `--allow-same-version` to `semantic-release/npm` configurations?

For example:
```json
["@semantic-release/npm", {
  "allowSameVersion": true
}],
```

**Comment by XinYaanZyoy** [comment]
i solved this issue by removing npm extension from .releaserc for one release and then added back!
