### ISSUE TITLE
How to automatically pull changelog and git modules when issuing npx semantic-release?

### ISSUE THREAD

**Issue by dcs3spp** [semantic-release/semantic-release#1092]
Hi,

Apologies if posting this in the incorrect place....I am a newbie trying out semantic-release for use in a private gitlab CI environment without publishing to npm etc. The CI build uses ```npx semantic-release``` as suggested in docs for CI environment.

I am specifying plugins within the package.json file under the *release* key. As soon as I add the *changelog* and *git* plugins to package.json I receive an error from CI build explaining that module changelog could not be found when I issue the ```npx semantic-release``` command. This also happens for git plugin. If I remove both the changelog and git plugins it works, pulling in the commit-analyzer and release-notes-generator plugins.

I tried both the following commands, which were successful:
```npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release```
```npm -g install @semantic-release/changelog @semantic-release/git semantic-release && semantic-release```

I have included the package.json and CI error log below. 

Is there anyway of getting npx to pull the *changelog* and *git* repositories automatically when issuing ```npx semantic-release``` or do third-party plugins have to be installed additionally?

Kind regards,

dcs3spp

**package.json**:
```
"devDependencies": {
    "semantic-release": "^15.13.3",
    "@semantic-release/commit-analyzer": "^6.1.0",
    "@semantic-release/release-notes-generator": "^7.1.4",
    "@semantic-release/changelog": "^3.0.2",
    "@semantic-release/git": "^7.0.8",
    },
"release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      "@semantic-release/git"
    ]
}
```

**CI error log**:
```
npx: installed 781 in 23.633s
[2:04:40 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.3
[2:04:40 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Cannot find module '@semantic-release/changelog'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at resolveFileName (/root/.npm/_npx/14/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/root/.npm/_npx/14/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
    at module.exports (/root/.npm/_npx/14/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:41)
    at loadPlugin (/root/.npm/_npx/14/lib/node_modules/semantic-release/lib/plugins/utils.js:49:82)
    at options.plugins.castArray.reduce (/root/.npm/_npx/14/lib/node_modules/semantic-release/lib/plugins/index.js:17:37)
    at Array.reduce (<anonymous>)
    at module.exports (/root/.npm/_npx/14/lib/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/root/.npm/_npx/14/lib/node_modules/semantic-release/lib/get-config.js:83:35) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '@semantic-release/changelog'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:609:15)
    at resolveFileName (/root/.npm/_npx/14/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/root/.npm/_npx/14/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
    at module.exports (/root/.npm/_npx/14/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:41)
    at loadPlugin (/root/.npm/_npx/14/lib/node_modules/semantic-release/lib/plugins/utils.js:49:82)
    at options.plugins.castArray.reduce (/root/.npm/_npx/14/lib/node_modules/semantic-release/lib/plugins/index.js:17:37)
    at Array.reduce (<anonymous>)
    at module.exports (/root/.npm/_npx/14/lib/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/root/.npm/_npx/14/lib/node_modules/semantic-release/lib/get-config.js:83:35) code: 'MODULE_NOT_FOUND' }
```

**Comment by pvdlg** [comment]
I just tried you exact configuration and both command you mentioned works for me and the plugins load properly. So I don't know why it doesn't works for you....Maybe the npx version?

I'm using 6.5.0

**Comment by dcs3spp** [comment]
Thanks @pvdlg. I am running *npx* from *node:alpine* image in the gitlab CI job.
*npx* is same version, 6.5.0. 

Not sure why but ```npx semantic-release``` fails to pull the git and/or changelog plugins for me. The only way that I can get it to work from gitlab CI is to issue:
```
npx -p @semantic-release/changelog -p @semantic-release/git -p semantic-release semantic-release
```
Will update issue if I find reason why, otherwise will continue using npx -p ....

**Comment by pvdlg** [comment]
This is expected. If you semantic-release is installed globally you have to install the plugins globally as well.

**Comment by kentwongg** [comment]
> fails to pull the git and/or changelog plugins for me. The only way that I can get it to work from gitlab CI is to issue:

I had to do this as well on WSL2 using Ubuntu 19 LTS. I just have npm installed, a bit weird.
