### ISSUE TITLE
GH_TOKEN authentication working locally but not in Travis

### ISSUE THREAD

**Issue by lpatino10** [semantic-release/semantic-release#1110]
## Current behavior

I'm attempting to run `semantic-release` during my Travis deploy step. The release fails trying to authenticate with GitHub, giving the following errors:
```
EINVALIDGHTOKEN Invalid GitHub token
```
```
EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch bintray-deploy on remote Git repository with URL https://[secure]@github.com/watson-developer-cloud/java-sdk.git.
```
_However,_ deploying via the command line with `semantic-release --no-ci` works fine.

## Expected behavior

The release should work and behave the same both locally and through Travis.

## Environment

- **semantic-release** version: `15.13.4`
- CI environment: Travis CI
- Plugins used: `@semantic-release/commit-analyzer`, `@semantic-release/release-notes-generator`, `@semantic-release/git`, `@semantic-release/github`, and `@semantic-release/exec`
- **semantic-release** configuration:
```
{
  "branch": "bintray-deploy",
  "tagFormat": "java-sdk-${version}",
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/git",
    "@semantic-release/github",
    ["@semantic-release/exec", {
      "prepareCmd": "bumpversion --current-version ${lastRelease.version} --new-version ${nextRelease.version} --verbose --allow-dirty patch"
    }]
  ]
}
```
- CI logs: Full build log: https://travis-ci.org/watson-developer-cloud/java-sdk/jobs/499443806

Relevant section with debugging turned on:
```
[7:29:12 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.4
2019-02-27T19:29:12.875Z semantic-release:config load config from: /home/travis/build/watson-developer-cloud/java-sdk/.releaserc
2019-02-27T19:29:12.889Z semantic-release:config options values: { branch: 'bintray-deploy',
  repositoryUrl: 'git+https://github.com/watson-developer-cloud/java-sdk.git',
  tagFormat: 'java-sdk-${version}',
  plugins:
   [ '@semantic-release/commit-analyzer',
     '@semantic-release/release-notes-generator',
     '@semantic-release/git',
     '@semantic-release/github',
     [ '@semantic-release/exec', [Object] ] ],
  debug: true,
  _: [],
  '$0': '../../../.nvm/versions/node/v10.15.1/bin/semantic-release' }
2019-02-27T19:29:13.343Z semantic-release:plugins options for @semantic-release/git/verifyConditions: {}
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
2019-02-27T19:29:13.344Z semantic-release:plugins options for @semantic-release/github/verifyConditions: {}
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
2019-02-27T19:29:13.345Z semantic-release:plugins options for @semantic-release/exec/verifyConditions: { prepareCmd:
   'bumpversion --current-version ${lastRelease.version} --new-version ${nextRelease.version} --verbose --allow-dirty patch' }
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
2019-02-27T19:29:13.345Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2019-02-27T19:29:13.346Z semantic-release:plugins options for @semantic-release/exec/analyzeCommits: { prepareCmd:
   'bumpversion --current-version ${lastRelease.version} --new-version ${nextRelease.version} --verbose --allow-dirty patch' }
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
2019-02-27T19:29:13.346Z semantic-release:plugins options for @semantic-release/exec/verifyRelease: { prepareCmd:
   'bumpversion --current-version ${lastRelease.version} --new-version ${nextRelease.version} --verbose --allow-dirty patch' }
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
2019-02-27T19:29:13.347Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2019-02-27T19:29:13.347Z semantic-release:plugins options for @semantic-release/exec/generateNotes: { prepareCmd:
   'bumpversion --current-version ${lastRelease.version} --new-version ${nextRelease.version} --verbose --allow-dirty patch' }
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
2019-02-27T19:29:13.347Z semantic-release:plugins options for @semantic-release/git/prepare: {}
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
2019-02-27T19:29:13.348Z semantic-release:plugins options for @semantic-release/exec/prepare: { prepareCmd:
   'bumpversion --current-version ${lastRelease.version} --new-version ${nextRelease.version} --verbose --allow-dirty patch' }
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
2019-02-27T19:29:13.348Z semantic-release:plugins options for @semantic-release/github/publish: {}
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
2019-02-27T19:29:13.349Z semantic-release:plugins options for @semantic-release/exec/publish: { prepareCmd:
   'bumpversion --current-version ${lastRelease.version} --new-version ${nextRelease.version} --verbose --allow-dirty patch' }
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
2019-02-27T19:29:13.349Z semantic-release:plugins options for @semantic-release/github/success: {}
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
2019-02-27T19:29:13.349Z semantic-release:plugins options for @semantic-release/exec/success: { prepareCmd:
   'bumpversion --current-version ${lastRelease.version} --new-version ${nextRelease.version} --verbose --allow-dirty patch' }
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
2019-02-27T19:29:13.350Z semantic-release:plugins options for @semantic-release/github/fail: {}
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
2019-02-27T19:29:13.350Z semantic-release:plugins options for @semantic-release/exec/fail: { prepareCmd:
   'bumpversion --current-version ${lastRelease.version} --new-version ${nextRelease.version} --verbose --allow-dirty patch' }
[7:29:13 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
[7:29:13 PM] [semantic-release] › ✔  Run automated release from branch bintray-deploy
2019-02-27T19:29:13.870Z semantic-release:git Error: Command failed: git push --dry-run https://github.com/watson-developer-cloud/java-sdk.git HEAD:bintray-deploy
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/watson-developer-cloud/java-sdk.git/'
    at makeError (/home/travis/.nvm/versions/node/v10.15.1/lib/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/travis/.nvm/versions/node/v10.15.1/lib/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-02-27T19:29:14.309Z semantic-release:git Error: Command failed: git push --dry-run https://[secure]@github.com/watson-developer-cloud/java-sdk.git HEAD:bintray-deploy
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/watson-developer-cloud/java-sdk.git/'
    at makeError (/home/travis/.nvm/versions/node/v10.15.1/lib/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/home/travis/.nvm/versions/node/v10.15.1/lib/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[7:29:14 PM] [semantic-release] › ✖  The command "git push --dry-run https://[secure]@github.com/watson-developer-cloud/java-sdk.git HEAD:bintray-deploy" failed with the error message remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/watson-developer-cloud/java-sdk.git/'
.
[7:29:14 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[7:29:14 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[7:29:15 PM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
[7:29:15 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/exec"
[7:29:15 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/exec"
[7:29:15 PM] [semantic-release] › ✖  EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository watson-developer-cloud/java-sdk.
Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personal token.
[7:29:15 PM] [semantic-release] › ✖  EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch bintray-deploy on remote Git repository with URL https://[secure]@github.com/watson-developer-cloud/java-sdk.git.
Please refer to the authentication configuration documentation (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) is configured with a valid Git URL (https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).
{ SemanticReleaseError: The push permission to the Git repository is required.
    at module.exports (/home/travis/.nvm/versions/node/v10.15.1/lib/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/travis/.nvm/versions/node/v10.15.1/lib/node_modules/semantic-release/index.js:79:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details:
   '**semantic-release** cannot push the version tag to the branch `bintray-deploy` on remote Git repository with URL `https://[secure]@github.com/watson-developer-cloud/java-sdk.git`.\n\nPlease refer to the [authentication configuration documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) is configured with a [valid Git URL](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).'m,
  semanticRelease: true }Script failed with status 1
failed to deploy
```

**Comment by travi** [comment]
i can confirm that `GH_TOKEN` is working properly for my many packages that i publish from Travis. I would start by making extra sure that the token that you think is available as the `GH_TOKEN` environment variable on travis is actually the one that is there and that it has the appropriate permissions.

**Comment by lpatino10** [comment]
Thanks @travi, I'll take a closer look to make sure it's what I'm expecting. I've used it without any issues in other projects too so this was pretty weird to me.

**Comment by lpatino10** [comment]
Looks like it was an old key encrypted key in the Travis file that I didn't see that was overriding the one I set. Sorry for the false alarm!
