### ISSUE TITLE
mode is mandatory, which contradicts docs

### ISSUE THREAD

**Issue by gempain** [semantic-release/semantic-release#1111]
## Current behavior

With a basic configuration, semantic-release throws an error saying no mode is specified.

## Expected behavior

The [docs](https://github.com/semantic-release/semantic-release/blob/beta/docs/usage/configuration.md#ci) say that by default `ci`is set to `true`, so I would expect the "mode" to be set.

Side node, but I got confused by the word "mode" while reading the documentation. I though there there was a `mode` option to set in the configuration, as in:
```
{
  "mode": "ci"
}
```
but realised you were just talking about setting a combination of `ci`, `dry-run` and `debug` to `true` or `false`.

## Environment

- **semantic-release** version: 16.0.0-beta.18
- CI environment: DroneCI
- Plugins used: `@semantic-release/commit-analyzer`, `@semantic-release/release-notes-generator`, `@semantic-release/npm`
- **semantic-release** configuration:
```
module.exports = {
	branches: [
		'+([1-9])?(.{+([1-9]),x}).x',
		'master',
		'next',
		'next-major',
		{name: 'beta', prerelease: true},
		{name: 'alpha', prerelease: true}
	],
	plugins: [
		'@semantic-release/commit-analyzer',
		'@semantic-release/release-notes-generator',
		['@semantic-release/npm', {npmPublish: false}],
	],
};
```
- CI logs: 
```
+ npx semantic-release@16.0.0-beta.1
--
2 | npx: installed 796 in 28.097s
3 | [3:41:32 PM] [semantic-release] › ℹ Running semantic-release version 16.0.0-beta.1
4 | [3:41:32 PM] [semantic-release] › ✖ An error occurred while running semantic-release: ReferenceError: mode is not defined
5 | at Object.<anonymous> (/drone/src/.releaserc.js:1:63)
6 | at Module._compile (internal/modules/cjs/loader.js:689:30)
7 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
8 | at Module.load (internal/modules/cjs/loader.js:599:32)
9 | at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
10 | at Function.Module._load (internal/modules/cjs/loader.js:530:3)
11 | at Module.require (internal/modules/cjs/loader.js:637:17)
12 | at require (internal/modules/cjs/helpers.js:22:18)
13 | at module.exports.moduleId (/root/.npm/_npx/9/lib/node_modules/semantic-release/node_modules/import-fresh/index.js:28:9)
14 | at loadJs (/root/.npm/_npx/9/lib/node_modules/semantic-release/node_modules/cosmiconfig/dist/loaders.js:9:18)
15 | ReferenceError: mode is not defined
16 | at Object.<anonymous> (/drone/src/.releaserc.js:1:63)
17 | at Module._compile (internal/modules/cjs/loader.js:689:30)
18 | at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
19 | at Module.load (internal/modules/cjs/loader.js:599:32)
20 | at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
21 | at Function.Module._load (internal/modules/cjs/loader.js:530:3)
22 | at Module.require (internal/modules/cjs/loader.js:637:17)
23 | at require (internal/modules/cjs/helpers.js:22:18)
24 | at module.exports.moduleId (/root/.npm/_npx/9/lib/node_modules/semantic-release/node_modules/import-fresh/index.js:28:9)
```

**Comment by pvdlg** [comment]
It's a `ReferenceError` meaning that you refer to a JavaScript variable named `mode` that doesn't exists.
It seems it comes from your `.releaserc.js`.

**Comment by gempain** [comment]
@pvdlg Yes, I should've closed this yesterday, so sorry, I found that the issue was indeed coming from a typo in my config, which had `mode.exports = ` instead of `module.exports`. Greatest apologies !
