### ISSUE TITLE
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration

### ISSUE THREAD

**Issue by gempain** [semantic-release/semantic-release#1112]
## Current behavior

Semantic-release throws "A minimum of 1 and a maximum of 3 release branches are required in the branches configuration" as if it weren't grabbing my configuration. The same configuration works on other projects. This is running in GitLab CI.

## Expected behavior

No error is thrown.

## Environment

- **semantic-release** version: 16.0.0-beta.18
- CI environment: GitLab CI
- Plugins used: 
- **semantic-release** configuration:
```
module.exports = {
	branches: [
		'+([1-9])?(.{+([1-9]),x}).x',
		'master',
		'next',
		'next-major',
		{name: 'beta', prerelease: true},
		{name: 'alpha', prerelease: true}
	],
	plugins: [
		["@semantic-release/commit-analyzer", {
			"preset": "angular",
		}],
		["@semantic-release/release-notes-generator", {
			"preset": "angular",
		}],
		["@semantic-release/changelog", {
			"changelogFile": "CHANGELOG.md",
		}],
		['@semantic-release/npm', {
			"npmPublish": false,
		}],
		["@semantic-release/git", {
			"message": "chore(release): ${nextRelease.version} [ci skip]"
		}],
	],
};
```
- CI logs:
```
Git git version 2.18.1
Node v10.15.2a
Npm 6.4.1
Docker Docker version 18.06.1-ce, build d72f525745
$ npx semantic-release@16.0.0-beta.18
npx: installed 797 in 25.805s
[1:01:32 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.18
[1:01:32 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[1:01:32 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[1:01:32 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[1:01:32 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[1:01:32 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[1:01:32 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[1:01:32 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[1:01:32 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[1:01:32 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[1:01:32 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[1:01:32 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

Your configuration for the problematic branches is [].

{ AggregateError: 
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/get-error.js:6:10)
        at Object.entries.reduce (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:41:19)
        at Array.reduce (<anonymous>)
        at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:31:46)
    at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:63:11)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }
```

**Comment by pvdlg** [comment]
Can you run semantic-release with the `--debug` option and provide the logs?

Can you also provide the output of `git branch -a`?

**Comment by gempain** [comment]
@pvdlg Sure, here you go:


```
$ git branch -a
* (HEAD detached at 85e7274)
  dev
  remotes/origin/HEAD -> origin/dev
  remotes/origin/dev
$ npx semantic-release@16.0.0-beta.18 --debug
npx: installed 797 in 26.618s
[6:17:17 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.18
2019-03-04T18:17:17.831Z semantic-release:config load config from: /builds/internal/roadsense/roadsense-frontend/.releaserc.js
2019-03-04T18:17:17.854Z semantic-release:config options values: { branches:
   [ '+([1-9])?(.{+([1-9]),x}).x',
     'master',
     'next',
     'next-major',
     { name: 'beta', prerelease: true },
     { name: 'alpha', prerelease: true } ],
  repositoryUrl:
   'https://gitlab-ci-token:[secure]@gitlab.charlie-bravo.be/internal/roadsense/roadsense-frontend.git',
  tagFormat: 'v${version}',
  plugins:
   [ [ '@semantic-release/commit-analyzer', [Object] ],
     [ '@semantic-release/release-notes-generator', [Object] ],
     [ '@semantic-release/changelog', [Object] ],
     [ '@semantic-release/npm', [Object] ],
     [ '@semantic-release/git', [Object] ] ],
  _: [],
  debug: true,
  '$0': '/root/.npm/_npx/25/bin/semantic-release' }
2019-03-04T18:17:18.392Z semantic-release:plugins options for @semantic-release/changelog/verifyConditions: { changelogFile: 'CHANGELOG.md' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
2019-03-04T18:17:18.394Z semantic-release:plugins options for @semantic-release/npm/verifyConditions: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
2019-03-04T18:17:18.395Z semantic-release:plugins options for @semantic-release/git/verifyConditions: { message: 'chore(release): ${nextRelease.version} [ci skip]' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
2019-03-04T18:17:18.396Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: { preset: 'angular' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2019-03-04T18:17:18.397Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: { preset: 'angular' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2019-03-04T18:17:18.398Z semantic-release:plugins options for @semantic-release/changelog/prepare: { changelogFile: 'CHANGELOG.md' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
2019-03-04T18:17:18.398Z semantic-release:plugins options for @semantic-release/npm/prepare: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
2019-03-04T18:17:18.399Z semantic-release:plugins options for @semantic-release/git/prepare: { message: 'chore(release): ${nextRelease.version} [ci skip]' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
2019-03-04T18:17:18.400Z semantic-release:plugins options for @semantic-release/npm/publish: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
2019-03-04T18:17:18.401Z semantic-release:plugins options for @semantic-release/npm/addChannel: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
2019-03-04T18:17:18.658Z semantic-release:get-tags found tags: []
[6:17:18 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

Your configuration for the problematic branches is [].

{ AggregateError: 
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/get-error.js:6:10)
        at Object.entries.reduce (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:41:19)
        at Array.reduce (<anonymous>)
        at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:31:46)
    at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:63:11)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }Git git version 2.18.1
Node v10.15.2a
Npm 6.4.1
Docker Docker version 18.06.1-ce, build d72f525745
ERROR: Job failed: exit code 1
```

The weird things is it does not crash on all of my projects. I haven't been able to figure out what the difference between those projects is because I copy-pasted the setup for each of them, so it couldn't come from this I guess.

PS: I don't have enough words to thank your for this amazing ecosystem ;)

**Comment by gempain** [comment]
@pvdlg Sure, here you go:


```
$ git branch -a
* (HEAD detached at 85e7274)
  dev
  remotes/origin/HEAD -> origin/dev
  remotes/origin/dev
$ npx semantic-release@16.0.0-beta.18 --debug
npx: installed 797 in 26.618s
[6:17:17 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.18
2019-03-04T18:17:17.831Z semantic-release:config load config from: /builds/internal/my-project/my-project-repo/.releaserc.js
2019-03-04T18:17:17.854Z semantic-release:config options values: { branches:
   [ '+([1-9])?(.{+([1-9]),x}).x',
     'master',
     'next',
     'next-major',
     { name: 'beta', prerelease: true },
     { name: 'alpha', prerelease: true } ],
  repositoryUrl:
   'https://gitlab-ci-token:[secure]@gitlab.my-site.com/internal/my-project/my-project-repo.git',
  tagFormat: 'v${version}',
  plugins:
   [ [ '@semantic-release/commit-analyzer', [Object] ],
     [ '@semantic-release/release-notes-generator', [Object] ],
     [ '@semantic-release/changelog', [Object] ],
     [ '@semantic-release/npm', [Object] ],
     [ '@semantic-release/git', [Object] ] ],
  _: [],
  debug: true,
  '$0': '/root/.npm/_npx/25/bin/semantic-release' }
2019-03-04T18:17:18.392Z semantic-release:plugins options for @semantic-release/changelog/verifyConditions: { changelogFile: 'CHANGELOG.md' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
2019-03-04T18:17:18.394Z semantic-release:plugins options for @semantic-release/npm/verifyConditions: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
2019-03-04T18:17:18.395Z semantic-release:plugins options for @semantic-release/git/verifyConditions: { message: 'chore(release): ${nextRelease.version} [ci skip]' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
2019-03-04T18:17:18.396Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: { preset: 'angular' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2019-03-04T18:17:18.397Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: { preset: 'angular' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2019-03-04T18:17:18.398Z semantic-release:plugins options for @semantic-release/changelog/prepare: { changelogFile: 'CHANGELOG.md' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
2019-03-04T18:17:18.398Z semantic-release:plugins options for @semantic-release/npm/prepare: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
2019-03-04T18:17:18.399Z semantic-release:plugins options for @semantic-release/git/prepare: { message: 'chore(release): ${nextRelease.version} [ci skip]' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
2019-03-04T18:17:18.400Z semantic-release:plugins options for @semantic-release/npm/publish: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
2019-03-04T18:17:18.401Z semantic-release:plugins options for @semantic-release/npm/addChannel: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
2019-03-04T18:17:18.658Z semantic-release:get-tags found tags: []
[6:17:18 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

Your configuration for the problematic branches is [].

{ AggregateError:
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/get-error.js:6:10)
        at Object.entries.reduce (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:41:19)
        at Array.reduce (<anonymous>)
        at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:31:46)
    at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:63:11)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }Git git version 2.18.1
Node v10.15.2a
Npm 6.4.1
Docker Docker version 18.06.1-ce, build d72f525745
ERROR: Job failed: exit code 1
```

The weird things is it does not crash on all of my projects. I haven't been able to figure out what the difference between those projects is because I copy-pasted the setup for each of them, so it couldn't come from this I guess.

PS: I don't have enough words to thank your for this amazing ecosystem ;)

**Comment by gempain** [comment]
@pvdlg Sure, here you go:


```
$ git branch -a
* (HEAD detached at 85e7274)
  dev
  remotes/origin/HEAD -> origin/dev
  remotes/origin/dev
$ npx semantic-release@16.0.0-beta.18 --debug
npx: installed 797 in 26.618s
[6:17:17 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.18
2019-03-04T18:17:17.831Z semantic-release:config load config from: /builds/internal/my-project/my-project-repo/.releaserc.js
2019-03-04T18:17:17.854Z semantic-release:config options values: { branches:
   [ '+([1-9])?(.{+([1-9]),x}).x',
     'master',
     'next',
     'next-major',
     { name: 'beta', prerelease: true },
     { name: 'alpha', prerelease: true } ],
  repositoryUrl:
   'https://gitlab-ci-token:[secure]@gitlab.my-site.com/internal/my-project/my-project-repo.git',
  tagFormat: 'v${version}',
  plugins:
   [ [ '@semantic-release/commit-analyzer', [Object] ],
     [ '@semantic-release/release-notes-generator', [Object] ],
     [ '@semantic-release/changelog', [Object] ],
     [ '@semantic-release/npm', [Object] ],
     [ '@semantic-release/git', [Object] ] ],
  _: [],
  debug: true,
  '$0': '/root/.npm/_npx/25/bin/semantic-release' }
2019-03-04T18:17:18.392Z semantic-release:plugins options for @semantic-release/changelog/verifyConditions: { changelogFile: 'CHANGELOG.md' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
2019-03-04T18:17:18.394Z semantic-release:plugins options for @semantic-release/npm/verifyConditions: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
2019-03-04T18:17:18.395Z semantic-release:plugins options for @semantic-release/git/verifyConditions: { message: 'chore(release): ${nextRelease.version} [ci skip]' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
2019-03-04T18:17:18.396Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: { preset: 'angular' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2019-03-04T18:17:18.397Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: { preset: 'angular' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2019-03-04T18:17:18.398Z semantic-release:plugins options for @semantic-release/changelog/prepare: { changelogFile: 'CHANGELOG.md' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
2019-03-04T18:17:18.398Z semantic-release:plugins options for @semantic-release/npm/prepare: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
2019-03-04T18:17:18.399Z semantic-release:plugins options for @semantic-release/git/prepare: { message: 'chore(release): ${nextRelease.version} [ci skip]' }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
2019-03-04T18:17:18.400Z semantic-release:plugins options for @semantic-release/npm/publish: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
2019-03-04T18:17:18.401Z semantic-release:plugins options for @semantic-release/npm/addChannel: { npmPublish: false }
[6:17:18 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
2019-03-04T18:17:18.658Z semantic-release:get-tags found tags: []
[6:17:18 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

Your configuration for the problematic branches is [].

{ AggregateError:
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/get-error.js:6:10)
        at Object.entries.reduce (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:41:19)
        at Array.reduce (<anonymous>)
        at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:31:46)
    at module.exports (/root/.npm/_npx/25/lib/node_modules/semantic-release/lib/branches/index.js:63:11)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }Git git version 2.18.1
Node v10.15.2a
Npm 6.4.1
Docker Docker version 18.06.1-ce, build d72f525745
ERROR: Job failed: exit code 1
```

The weird things is it does not crash on all of my projects. I haven't been able to figure out what the difference between those projects is because I copy-pasted the setup for each of them, so it couldn't come from this I guess.

**Comment by priyajeet** [comment]
I have also started to notice this problem. Specially from clean yarn installs.

**Comment by priyajeet** [comment]
@gempain What does git remote -v show for you? Does the `origin` **remote** repo have the branch semantic-release is trying to use from the branches list? I am asking because it seems can get around this above problem by git cloning the whole repo again.

I wonder if this is related to https://spectrum.chat/semantic-release/general/how-to-make-semantic-release-use-a-different-remote-than-origin~c7a31922-ac18-4fe7-b512-04d02b8ad5bc

**Comment by gempain** [comment]
@priyajeet so far I have it working on only one project in my GitlabCI runner. It's failing on pretty much every other project. Note that some of those projects are configured to run in DroneCI as well, and they work fine in Drone, so it seems to be varying between CI setups and I can't figure out the difference between those setups as I usually copy-paste most config.

Here is the log on a repo that's failing:
```
$ git remote -v
origin	https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.my-site.com/internal/my-project/my-repo.git (fetch)
origin	https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.my-site.com/internal/my-project/my-repo.git (push)
$ git branch -a
* (HEAD detached at 3de7bd6)
  dev
  remotes/origin/HEAD -> origin/dev
  remotes/origin/dev
  remotes/origin/feat/road-list
```

and now on the repo that is succeeding:
```
$ git remote -v
origin	https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.my-site.com/internal/my-project/my-repo.git (fetch)
origin	https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.my-site.com/internal/my-project/my-repo.git (push)
$ git branch -a
* (HEAD detached at 0526aef)
  master
  remotes/origin/HEAD -> origin/master
  remotes/origin/dev
  remotes/origin/feat/feat1
  remotes/origin/feat/feat2
  remotes/origin/master
$ npx semantic-release@16.0.0-beta.18 --debug
npx: installed 797 in 23.96s
[9:17:48 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.18
2019-03-05T21:17:48.416Z semantic-release:config load config from: /builds/internal/my-project/my-repo/.releaserc.js
2019-03-05T21:17:48.430Z semantic-release:config options values: { branches:
   [ '+([1-9])?(.{+([1-9]),x}).x',
     'master',
     'next',
     'next-major',
     { name: 'beta', prerelease: true },
     { name: 'alpha', prerelease: true } ],
  repositoryUrl:
   'https://gitlab-ci-token:[secure]@gitlab.my-site.com/internal/my-project/my-repo.git',
  tagFormat: 'v${version}',
  plugins:
   [ [ '@semantic-release/commit-analyzer', [Object] ],
     [ '@semantic-release/release-notes-generator', [Object] ],
     [ '@semantic-release/changelog', [Object] ],
     [ '@semantic-release/npm', [Object] ],
     [ '@semantic-release/git', [Object] ] ],
  _: [],
  debug: true,
  '$0': '/root/.npm/_npx/26/bin/semantic-release' }
2019-03-05T21:17:48.900Z semantic-release:plugins options for @semantic-release/changelog/verifyConditions: { changelogFile: 'CHANGELOG.md' }
[9:17:48 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
2019-03-05T21:17:48.902Z semantic-release:plugins options for @semantic-release/npm/verifyConditions: { npmPublish: false }
[9:17:48 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
2019-03-05T21:17:48.903Z semantic-release:plugins options for @semantic-release/git/verifyConditions: { message: 'chore(release): ${nextRelease.version} [ci skip]' }
[9:17:48 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
2019-03-05T21:17:48.904Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: { preset: 'angular' }
[9:17:48 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2019-03-05T21:17:48.905Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: { preset: 'angular' }
[9:17:48 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2019-03-05T21:17:48.905Z semantic-release:plugins options for @semantic-release/changelog/prepare: { changelogFile: 'CHANGELOG.md' }
[9:17:48 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
2019-03-05T21:17:48.906Z semantic-release:plugins options for @semantic-release/npm/prepare: { npmPublish: false }
[9:17:48 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
2019-03-05T21:17:48.907Z semantic-release:plugins options for @semantic-release/git/prepare: { message: 'chore(release): ${nextRelease.version} [ci skip]' }
[9:17:48 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
2019-03-05T21:17:48.907Z semantic-release:plugins options for @semantic-release/npm/publish: { npmPublish: false }
[9:17:48 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
2019-03-05T21:17:48.908Z semantic-release:plugins options for @semantic-release/npm/addChannel: { npmPublish: false }
[9:17:48 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
2019-03-05T21:17:49.316Z semantic-release:get-tags found tags: []
2019-03-05T21:17:49.316Z semantic-release:get-tags found tags for branch master: []
[9:17:49 PM] [semantic-release] › ℹ  This test run was triggered on the branch feat/road-list, while semantic-release is configured to only publish from master, therefore a new version won’t be published.
Git git version 2.18.1
Node v10.15.2a
Npm 6.4.1
Docker Docker version 18.06.1-ce, build d72f525745
Creating cache default...
node_modules/: found 10192 matching files
No URL provided, cache will be not uploaded to shared cache server. Cache will be stored only locally.
Created cache
Job succeeded
```

**Comment by priyajeet** [comment]
@gempain In your list of branches, I see `master` but I don't see `dev`. The ones that failing has `remotes/origin/HEAD -> origin/dev` while thats passing has `remotes/origin/HEAD -> origin/master`. I wonder if thats the difference?

**Comment by gempain** [comment]
@priyajeet good one ! Found the issue: the common thing between all the projects that were failing is that they did not have a master branch, only `dev`. Just doing the following fixed it:
```
git checkout -b master
git push --set-upstream origin master
```
Looking back at it, the message makes sense, but I guess it could be clearer by saying something like `semantic-release could not find a release branch. May be you don't have a master branch ?`. Providing a list of expected release branches would be great as well, since you probably have them as `branches.filter(b => typeof b === 'string ' || !b.prerelease)` ?

By the way, I looked through the code trying to find where the error message was originally coming from, but couldn't find the words "maximum", "minimum", "required" or "release branches configuration" anywhere in the repositories `semantic-release/semantic-release`, `semantic-release/git`, `semantic-release/npm` (I gave up after those three). Can you point me to where the error was thrown ?

Thanks a lot for the help, really appreciated ! I'm closing this issue as it is resolved, but would suggest adding a hint to the error message.

**Comment by MikeYermolayev** [comment]
Facing the same issue. I don't have `master` branch but I have `main`.
I forked repo from github to gitlab and trying to setup CI there. 

```
➜ git remote -v
origin  git@gitlab.com:get1st/api-plugin-authorization-simple.git (fetch)
origin  git@gitlab.com:get1st/api-plugin-authorization-simple.git (push)
```

```
git branch -a
* main
  trunk
  remotes/origin/HEAD -> origin/main
  remotes/origin/main
  remotes/origin/trunk
```

```
➜ npm run semantic-release --debug                                                                           

> @get1st/api-plugin-authorization-simple@0.0.0-development semantic-release /Volumes/Workspace/pets/get1st/api-plugin-authorization-simple
> semantic-release

[14:33:54] [semantic-release] › ℹ  Running semantic-release version 17.2.3
[14:33:55] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[14:33:55] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[14:33:55] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[14:33:55] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[14:33:55] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[14:33:55] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[14:33:55] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[14:33:55] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[14:33:55] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[14:33:55] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[14:33:55] [semantic-release] › ⚠  This run was not triggered in a known CI environment, running in dry-run mode.
[14:33:56] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].

AggregateError: 
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/Volumes/Workspace/pets/get1st/api-plugin-authorization-simple/node_modules/semantic-release/lib/get-error.js:6:10)
        at /Volumes/Workspace/pets/get1st/api-plugin-authorization-simple/node_modules/semantic-release/lib/branches/index.js:44:19
        at Array.reduce (<anonymous>)
        at module.exports (/Volumes/Workspace/pets/get1st/api-plugin-authorization-simple/node_modules/semantic-release/lib/branches/index.js:34:46)
        at async run (/Volumes/Workspace/pets/get1st/api-plugin-authorization-simple/node_modules/semantic-release/index.js:57:22)
        at async module.exports (/Volumes/Workspace/pets/get1st/api-plugin-authorization-simple/node_modules/semantic-release/index.js:260:22)
        at async module.exports (/Volumes/Workspace/pets/get1st/api-plugin-authorization-simple/node_modules/semantic-release/cli.js:55:5)
    at module.exports (/Volumes/Workspace/pets/get1st/api-plugin-authorization-simple/node_modules/semantic-release/lib/branches/index.js:66:11)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async run (/Volumes/Workspace/pets/get1st/api-plugin-authorization-simple/node_modules/semantic-release/index.js:57:22)
    at async module.exports (/Volumes/Workspace/pets/get1st/api-plugin-authorization-simple/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/Volumes/Workspace/pets/get1st/api-plugin-authorization-simple/node_modules/semantic-release/cli.js:55:5)npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @get1st/api-plugin-authorization-simple@0.0.0-development semantic-release: `semantic-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @get1st/api-plugin-authorization-simple@0.0.0-development semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ermolaev/.npm/_logs/2021-11-30T13_33_56_518Z-debug.log
```

.releaserc.json
```
{
  "branches": ["main"],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/gitlab",
    "@semantic-release/npm",
    [
      "@semantic-release/git",
      {
        "assets": ["package.json"],
        "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
      }
    ]
  ]
}

```
