### ISSUE TITLE
Git authentication failed on Azure Pipelines 16.0.0-beta.18

### ISSUE THREAD

**Issue by steffeli** [semantic-release/semantic-release#1115]
## Current behavior

Hey!

So after trying to upgrade to 16.0.0-beta to incorporate pre-release functionality I hit a snag running semantic-release on our CI. For some reason it fails to authenticate to our git repository. I have checked that both the GH_TOKEN and NPM_TOKEN are present and that they contain the current non-expired tokens for both. I verified this by releasing a new package version with the semantic-release version 15.x.x that we have on the master branch.

After push to our feature branch we merge the branch into our alpha branch via a pull request. This triggers a build and an upload of the artifact with all the files we need. Azure then triggers a release from here on out it fails.

I'm not quite sure why this is failing. Is it a combination of the plugin versions that I need to be aware of?

Edit: Forgot to mention that it works running the same command locally in a dry-run without problems.

## Expected behavior

Go through the rest of the steps with a release as pre-16.0.0.

## Environment

- **semantic-release** version: 16.0.0-beta.18
- CI environment: Azure Pipelines
- Plugins used:
```
changelog: 3.02
commit-analyzer: 7.0.0-beta.1
git: 7.1.0-beta.3
npm: 5.2.0-beta.6
release-notes-generator: 7.1.4
```
- **semantic-release** configuration:
```
module.exports = {
    plugins: [
        '@semantic-release/commit-analyzer',
        "@semantic-release/release-notes-generator",
        "@semantic-release/changelog",
        "@semantic-release/npm",
        ["@semantic-release/git", {
            "assets": ["CHANGELOG.md", "package.json"],
            "message": "chore(release): ${nextRelease.version} ***NO_CI***\n\n${nextRelease.notes}"
        }]
    ]
}
```
- CI logs:
```
2019-03-05T11:01:23.5042996Z ##[section]Starting: yarn release
2019-03-05T11:01:23.5046898Z ==============================================================================
2019-03-05T11:01:23.5046962Z Task         : Command Line
2019-03-05T11:01:23.5047001Z Description  : Run a command line script using cmd.exe on Windows and bash on macOS and Linux.
2019-03-05T11:01:23.5047039Z Version      : 2.146.1
2019-03-05T11:01:23.5050374Z Author       : Microsoft Corporation
2019-03-05T11:01:23.5050459Z Help         : [More Information](https://go.microsoft.com/fwlink/?LinkID=613735)
2019-03-05T11:01:23.5050497Z ==============================================================================
2019-03-05T11:01:23.6537876Z Generating script.
2019-03-05T11:01:23.6568830Z Script contents:
2019-03-05T11:01:23.6570517Z yarn release
2019-03-05T11:01:23.6599612Z [command]/bin/bash --noprofile --norc /home/vsts/work/_temp/49c05dbb-204e-4cce-83d9-b2943b9ea353.sh
2019-03-05T11:01:23.9130283Z yarn run v1.13.0
2019-03-05T11:01:23.9804342Z $ semantic-release
2019-03-05T11:01:24.5903308Z [11:01:24 AM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.18
2019-03-05T11:01:24.7567339Z [11:01:24 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
2019-03-05T11:01:24.7569496Z [11:01:24 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
2019-03-05T11:01:24.7572728Z [11:01:24 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
2019-03-05T11:01:24.7576257Z [11:01:24 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2019-03-05T11:01:24.7579799Z [11:01:24 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2019-03-05T11:01:24.7583036Z [11:01:24 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
2019-03-05T11:01:24.7585540Z [11:01:24 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
2019-03-05T11:01:24.7589321Z [11:01:24 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
2019-03-05T11:01:24.7592401Z [11:01:24 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
2019-03-05T11:01:24.7594687Z [11:01:24 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
2019-03-05T11:01:25.9530902Z [11:01:25 AM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: git ls-remote --heads origin
2019-03-05T11:01:25.9531820Z fatal: Authentication failed for 'https://stelie@dev.azure.com/stelie/test-project/_git/test-project/'
2019-03-05T11:01:25.9532132Z 
2019-03-05T11:01:25.9532519Z 
2019-03-05T11:01:25.9533359Z     at makeError (/home/vsts/work/r1/a/_alpha-build/test-project-20190305.1/node_modules/execa/index.js:174:9)
2019-03-05T11:01:25.9533963Z     at Promise.all.then.arr (/home/vsts/work/r1/a/_alpha-build/test-project-20190305.1/node_modules/execa/index.js:278:16)
2019-03-05T11:01:25.9534366Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-03-05T11:01:25.9534958Z   code: 128,
2019-03-05T11:01:25.9537184Z   stdout: '',
2019-03-05T11:01:25.9537726Z   stderr:
2019-03-05T11:01:25.9538400Z    'fatal: Authentication failed for \'https://stelie@dev.azure.com/stelie/test-project/_git/test-project/\'\n',
2019-03-05T11:01:25.9538710Z   failed: true,
2019-03-05T11:01:25.9538924Z   signal: null,
2019-03-05T11:01:25.9539456Z   cmd: 'git ls-remote --heads origin',
2019-03-05T11:01:25.9539751Z   timedOut: false,
2019-03-05T11:01:25.9539985Z   killed: false }
2019-03-05T11:01:25.9540603Z { Error: Command failed: git ls-remote --heads origin
2019-03-05T11:01:25.9541208Z fatal: Authentication failed for 'https://stelie@dev.azure.com/stelie/test-project/_git/test-project/'
2019-03-05T11:01:25.9541473Z 
2019-03-05T11:01:25.9541667Z 
2019-03-05T11:01:25.9542245Z     at makeError (/home/vsts/work/r1/a/_alpha-build/test-project-20190305.1/node_modules/execa/index.js:174:9)
2019-03-05T11:01:25.9543689Z     at Promise.all.then.arr (/home/vsts/work/r1/a/_alpha-build/test-project-20190305.1/node_modules/execa/index.js:278:16)
2019-03-05T11:01:25.9544075Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-03-05T11:01:25.9544606Z   code: ‌128‌,‌
2019-03-05T11:01:25.9545130Z   stdout: ‌&#x27;&#x27;‌,‌
2019-03-05T11:01:25.9545410Z   stderr:
2019-03-05T11:01:25.9545943Z    ‌&#x27;fatal: Authentication failed for \&#x27;https:&#x2F;&#x2F;stelie@dev.azure.com&#x2F;stelie&#x2F;test-project&#x2F;_git&#x2F;test-project&#x2F;\&#x27;\n&#x27;‌,‌
2019-03-05T11:01:25.9546530Z   failed: ‌true‌,‌
2019-03-05T11:01:25.9548185Z   signal: ‌null‌,‌
2019-03-05T11:01:25.9548947Z   cmd: ‌&#x27;git ls-remote --heads origin&#x27;‌,‌
2019-03-05T11:01:25.9549570Z   timedOut: ‌false‌,‌
2019-03-05T11:01:25.9702482Z   killed: ‌false‌ }error Command failed with exit code 1.‌
2019-03-05T11:01:26.5664163Z info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
2019-03-05T11:01:26.5775461Z ##[error]Bash exited with code '1'.
2019-03-05T11:01:26.5788202Z ##[section]Finishing: yarn release
```

**Comment by pvdlg** [comment]
The command that fails is `git ls-remote --heads origin`. This command shouldn't require any authentication as it's just reading from your repo...
I don't understand how Azure was able to clone your repo at the beginning of the build process, but it's not able to read it later on....
That seems to be a problem specific to Azure. If you investigate a bit more and figure out why Azure loose read access to your repo, maybe we can find a workaround.

**Comment by steffeli** [comment]
Thanks for the reply. I will try to dig a bit deeper today to see if I can find more information about the issue. What I find strange is that it works flawlessly with the 15.x.x-version, and I haven't changed anything in particular in our CI pipeline, besides adding and pushing a new branch.

**Comment by steffeli** [comment]
So I fiddled around with moving the repo from Azure Repos to GitHub (which it's supposed to be located anyway) and adjusted the way we fetch Artifacts in our release pipeline. Clearly we tried to just copy the .git folder in order to make semantic-release work, but the credentials are not stored on the host agent if not checking out the specific repo by adding it as an Artifact. But the funny thing is now it works, but it still gives me an error about not having the correct username and password, even though it proceeds and releases a new package and version.
```
 2019-03-08T11:51:35.6029686Z [11:51:35 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
2019-03-08T11:51:35.6030191Z 2019-03-08T11:51:35.601Z semantic-release:plugins options for @semantic-release/github/fail: {}
2019-03-08T11:51:35.6030952Z [11:51:35 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
2019-03-08T11:51:37.4172583Z 2019-03-08T11:51:37.416Z semantic-release:get-tags found tags: [ { gitTag: 'v0.0.1', version: '0.0.1', channel: undefined }, { gitTag: 'v0.0.2', version: '0.0.2', channel: undefined }, { gitTag: 'v0.0.3', version: '0.0.3', channel: undefined }, { gitTag: 'v1.3.0', version: '1.3.0', channel: undefined }, { gitTag: 'v1.3.1', version: '1.3.1', channel: undefined }, { gitTag: 'v1.3.2', version: '1.3.2', channel: undefined }, { gitTag: 'v1.3.3', version: '1.3.3', channel: undefined }, { gitTag: 'v1.3.4', version: '1.3.4', channel: undefined }, { gitTag: 'v1.4.0-alpha.1@alpha', version: '1.4.0-alpha.1', channel: 'alpha' } ]
2019-03-08T11:51:37.5943331Z 2019-03-08T11:51:37.593Z semantic-release:get-tags found tags for branch master: [ { version: '0.0.1', channel: undefined, gitTag: 'v0.0.1', gitHead: 'acab0acbc84e6c1cf928f2f6b0d14bbc604198b9' }, { version: '0.0.2', channel: undefined, gitTag: 'v0.0.2', gitHead: 'e07f5b342746a03af811f7b981ded94d5a327631' }, { version: '0.0.3', channel: undefined, gitTag: 'v0.0.3', gitHead: 'ac09c10e9093db1298afa5e719a546d8793c2d4c' }, { version: '1.3.0', channel: undefined, gitTag: 'v1.3.0', gitHead: 'ac09c10e9093db1298afa5e719a546d8793c2d4c' }, { version: '1.3.1', channel: undefined, gitTag: 'v1.3.1', gitHead: '55766607dc1d842eb1759632dbb85cb8a6f0ad05' }, { version: '1.3.2', channel: undefined, gitTag: 'v1.3.2', gitHead: 'bcaa9e9cab2f48e4e79f23e60cd52a3f1d4951ae' }, { version: '1.3.3', channel: undefined, gitTag: 'v1.3.3', gitHead: '189b869b1fb8c4c20c8dd9132ea12df8173bb251' }, { version: '1.3.4', channel: undefined, gitTag: 'v1.3.4', gitHead: 'cd318e05b955608ea35929d8e4aae17ee2956820' } ]
2019-03-08T11:51:37.8007164Z 2019-03-08T11:51:37.799Z semantic-release:get-tags found tags for branch alpha: [ { version: '0.0.1', channel: undefined, gitTag: 'v0.0.1', gitHead: 'acab0acbc84e6c1cf928f2f6b0d14bbc604198b9' }, { version: '0.0.2', channel: undefined, gitTag: 'v0.0.2', gitHead: 'e07f5b342746a03af811f7b981ded94d5a327631' }, { version: '0.0.3', channel: undefined, gitTag: 'v0.0.3', gitHead: 'ac09c10e9093db1298afa5e719a546d8793c2d4c' }, { version: '1.3.0', channel: undefined, gitTag: 'v1.3.0', gitHead: 'ac09c10e9093db1298afa5e719a546d8793c2d4c' }, { version: '1.3.1', channel: undefined, gitTag: 'v1.3.1', gitHead: '55766607dc1d842eb1759632dbb85cb8a6f0ad05' }, { version: '1.3.2', channel: undefined, gitTag: 'v1.3.2', gitHead: 'bcaa9e9cab2f48e4e79f23e60cd52a3f1d4951ae' }, { version: '1.3.3', channel: undefined, gitTag: 'v1.3.3', gitHead: '189b869b1fb8c4c20c8dd9132ea12df8173bb251' }, { version: '1.4.0-alpha.1', channel: 'alpha', gitTag: 'v1.4.0-alpha.1@alpha', gitHead: 'e3ce1f8ba8424296b377e8747cdfa29fa67c1ebb' } ]
2019-03-08T11:51:37.8157704Z [11:51:37 AM] [semantic-release] › ✔  Run automated release from branch alpha
2019-03-08T11:51:38.5030329Z 2019-03-08T11:51:38.502Z semantic-release:git Error: Command failed: git push --dry-run https://github.com/Helsenorge/test-project HEAD:alpha
2019-03-08T11:51:38.5031618Z remote: Invalid username or password.
2019-03-08T11:51:38.5032296Z fatal: Authentication failed for 'https://github.com/Helsenorge/test-project/'
2019-03-08T11:51:38.5032685Z 
2019-03-08T11:51:38.5032935Z 
2019-03-08T11:51:38.5033496Z     at makeError (/home/vsts/work/r1/a/_Helsenorge_test-project/node_modules/execa/index.js:174:9)
2019-03-08T11:51:38.5034106Z     at Promise.all.then.arr (/home/vsts/work/r1/a/_Helsenorge_test-project/node_modules/execa/index.js:278:16)
2019-03-08T11:51:38.5035964Z     at process._tickCallback (internal/process/next_tick.js:68:7)
2019-03-08T11:51:39.1772033Z [11:51:39 AM] [semantic-release] › ✔  Allowed to push to the Git repository
2019-03-08T11:51:39.1778445Z [11:51:39 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
2019-03-08T11:51:39.1806595Z [11:51:39 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
2019-03-08T11:51:39.1808111Z [11:51:39 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
2019-03-08T11:51:39.2024305Z [11:51:39 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
2019-03-08T11:51:39.7512419Z [11:51:39 AM] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /home/vsts/work/r1/a/_Helsenorge_test-project/.npmrc
2019-03-08T11:51:40.1341020Z [11:51:40 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
2019-03-08T11:51:40.1343254Z [11:51:40 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github
```

**Comment by steffeli** [comment]
I'm closing this. I came to the conclusion that this most likely is issues with Azure Pipelines and the hosted agents rather than semantic-release.

**Comment by kirach** [comment]
I'm having exactly the same issue with semantic-release `16.0.0-beta.18` on jenkins (version 15 works just fine). I'm using argument `repositoryUrl` to pass an address of github url:
```groovy
withCredentials([usernamePassword(credentialsId: 'kirach_github_token', passwordVariable: 'GITHUB_TOKEN', usernameVariable: 'GITHUB_USERNAME')]) {
  sh "npx semantic-release@beta --branch=semantic-release --dry-run --repositoryUrl=https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/dv01-inc/explorer"
}
```
and it's faling with the same error: `Command failed: git ls-remote --heads origin`

It looks like the command is not using the passed argument `repositoryUrl`

**Comment by travi** [comment]
> I'm having exactly the same issue

since the original problem here was concluded to be related to azure pipelines, i don't think the cause of your issue is exactly similar as you suggest. i would recommend opening a new issue rather than adding to an issue that has already been closed. 

also be sure to sure previous issues to see if any others are helpful that are more specifically related to jenkins. similar problems have been reported in the past that might have solutions described that could be helpful. if not, a new issue would be the best bet

**Comment by krohrsb** [comment]
Having this issue on a Jenkins pipeline.

Had to do a few things as a workaround.

```
sh 'git config --local credential.helper "!p() { echo username=\\$GIT_USERNAME; echo password=\\$GIT_PASSWORD; }; p"'
withCredentials([usernamePassword(credentialsId: 'creds-id', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
  sh yarn semantic-release
}
```

Basically, tell git which variables to look in for auth. Use withCredentials to set them before running semantic-release.

I don't have this issue with CircleCI. Maybe because circle jobs are given auth context of the user that triggered the job. Jenkins (at least how mine is configured currently) only uses creds to clone, after that, nothing.

**Comment by percebus** [comment]
@steffeli came 6 years later to the party

Did you try adding explicitly the `checkout` with `persistCredentials: true` ?

```yaml
      - checkout: self
        displayName: checkout self
        persistCredentials: true
```
