### ISSUE TITLE
GitHub enterprise not supported due to EMISSINGREPO error

### ISSUE THREAD

**Issue by modean** [semantic-release/semantic-release#1116]
## Current behavior

Semantic release GitHub plug-in is configured to run against a GitHub enterprise instance (see semantic-release config below). With that config the github plug-in triggers a EMISSINGREPO error despite the fact that the repo exists.

Repository per the `package.json` file is set to:

```
  "repository": {
    "type": "git",
    "url": "ssh://git@github.xxx.com/NGP-TWC/wdpx-kube-npm-config.git"
  },
```

The URL format also has been set to `git@github.xxx.com:NGP-TWC/wdpx-kube-npm-config.git` which essentially as well did yield a EMISSINGREPO error. The repository exists. `NGP-TWC` denotes a GitHub org.

While using the `ssh://` URL format Travis has been configured to use `ssh-agent` to be able to access the SSH key of the GitHub repo. While setting up SSH support for Travis, the according semantic-release instructions were used to do so.

Because the behaviour essentially is the same independent from the URL format used, it looks like the root cause has to be elsewhere.

## Expected behavior

Repository is found.

## Environment

- **semantic-release** version: 15.13.3
- CI environment: Travis (hosted enterprise version)
- Plugins used: commit-analyzer, release-notes-generator, changelog, npm, github
- **semantic-release** configuration:

```
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/npm",
    ["@semantic-release/github", {
      "githubUrl": "https://github.xxx.com",
      "githubApiPathPrefix": "/api/v3/",
      "failComment": false
    }]
  ],
  "debug": true,
  "branch": "master"
}
```

- CI logs: 

```
[2:36:12 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.3

  semantic-release:config load config from: /home/travis/build/NGP-TWC/wdpx-kube-npm-config/.releaserc +0ms

  semantic-release:config options values: { branch: 'master',

  semantic-release:config   repositoryUrl: 'ssh://git@github.xxx.com/NGP-TWC/wdpx-kube-npm-config.git',

  semantic-release:config   tagFormat: 'v${version}',

  semantic-release:config   plugins:

  semantic-release:config    [ '@semantic-release/commit-analyzer',

  semantic-release:config      '@semantic-release/release-notes-generator',

  semantic-release:config      '@semantic-release/changelog',

  semantic-release:config      '@semantic-release/npm',

  semantic-release:config      [ '@semantic-release/github', [Object] ] ],

  semantic-release:config   debug: true,

  semantic-release:config   _: [],

  semantic-release:config   '$0': '../../../.npm/_npx/6510/bin/semantic-release' } +4ms

  semantic-release:plugins options for @semantic-release/changelog/verifyConditions: {} +0ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"

  semantic-release:plugins options for @semantic-release/npm/verifyConditions: {} +1ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"

  semantic-release:plugins options for @semantic-release/github/verifyConditions: { githubUrl: 'https://github.xxx.com',

  semantic-release:plugins   githubApiPathPrefix: '/api/v3/',

  semantic-release:plugins   failComment: false } +1ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"

  semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {} +0ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"

  semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {} +1ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"

  semantic-release:plugins options for @semantic-release/changelog/prepare: {} +0ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"

  semantic-release:plugins options for @semantic-release/npm/prepare: {} +0ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"

  semantic-release:plugins options for @semantic-release/npm/publish: {} +1ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"

  semantic-release:plugins options for @semantic-release/github/publish: { githubUrl: 'https://github.xxx.com',

  semantic-release:plugins   githubApiPathPrefix: '/api/v3/',

  semantic-release:plugins   failComment: false } +0ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"

  semantic-release:plugins options for @semantic-release/github/success: { githubUrl: 'https://github.xxx.com',

  semantic-release:plugins   githubApiPathPrefix: '/api/v3/',

  semantic-release:plugins   failComment: false } +1ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"

  semantic-release:plugins options for @semantic-release/github/fail: { githubUrl: 'https://github.xxx.com',

  semantic-release:plugins   githubApiPathPrefix: '/api/v3/',

  semantic-release:plugins   failComment: false } +0ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"

[2:36:13 PM] [semantic-release] › ✔  Run automated release from branch master

[2:36:14 PM] [semantic-release] › ✔  Allowed to push to the Git repository

[2:36:14 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"

[2:36:14 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"

[2:36:14 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"

[2:36:14 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://.artifactory.xxx.com/artifactory/api/npm/wcp-wdp-npm-virtual/

[2:36:14 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"

[2:36:14 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"

[2:36:14 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://github.xxx.com/api/v3/)

[2:36:23 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/github"

[2:36:23 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"

[2:36:23 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://github.xxx.com/api/v3/)

[2:36:32 PM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"

[2:36:32 PM] [semantic-release] › ✖  EMISSINGREPO The repository NGP-TWC/wdpx-kube-npm-config doesn't exist.

The semantic-release repositoryUrl option must refer to your GitHub repository. The repository must be accessible with the GitHub API (https://developer.github.com/v3).


By default the repositoryUrl option is retrieved from the repository property of your package.json or the git origin url (https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes) of the repository cloned by your CI environment.


If you are using GitHub Enterprise (https://enterprise.github.com) please make sure to configure the githubUrl and githubApiPathPrefix options (https://github.com/semantic-release/github/blob/master/README.md#options).


[2:36:32 PM] [semantic-release] › ✖  EMISSINGREPO The repository NGP-TWC/wdpx-kube-npm-config doesn't exist.

The semantic-release repositoryUrl option must refer to your GitHub repository. The repository must be accessible with the GitHub API (https://developer.github.com/v3).


By default the repositoryUrl option is retrieved from the repository property of your package.json or the git origin url (https://git-scm.com/book/en/v2/Git-Basics-Working-with-Remotes) of the repository cloned by your CI environment.


If you are using GitHub Enterprise (https://enterprise.github.com) please make sure to configure the githubUrl and githubApiPathPrefix options (https://github.com/semantic-release/github/blob/master/README.md#options).


{ AggregateError: 

    SemanticReleaseError: The repository NGP-TWC/wdpx-kube-npm-config doesn't exist.

        at module.exports (/home/travis/.npm/_npx/6510/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/get-error.js:6:10)

        at module.exports (/home/travis/.npm/_npx/6510/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/verify.js:68:21)

    at /home/travis/.npm/_npx/6510/lib/node_modules/semantic-release/lib/plugins/pipeline.js:53:11 name: 'AggregateError' }
```

**Comment by travi** [comment]
From the logs that you posted above: 

> If you are using GitHub Enterprise (https://enterprise.github.com) please make sure to configure the githubUrl and githubApiPathPrefix options (https://github.com/semantic-release/github/blob/master/README.md#options).

**Comment by modean** [comment]
@travi from the logs that I have posted above:

```
  semantic-release:plugins options for @semantic-release/npm/publish: {} +1ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"

  semantic-release:plugins options for @semantic-release/github/publish: { githubUrl: 'https://github.xxx.com',

  semantic-release:plugins   githubApiPathPrefix: '/api/v3/',

  semantic-release:plugins   failComment: false } +0ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"

  semantic-release:plugins options for @semantic-release/github/success: { githubUrl: 'https://github.xxx.com',

  semantic-release:plugins   githubApiPathPrefix: '/api/v3/',

  semantic-release:plugins   failComment: false } +1ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"

  semantic-release:plugins options for @semantic-release/github/fail: { githubUrl: 'https://github.xxx.com',

  semantic-release:plugins   githubApiPathPrefix: '/api/v3/',

  semantic-release:plugins   failComment: false } +0ms

[2:36:13 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
```

From the config that I have posted above:

```
    ["@semantic-release/github", {
      "githubUrl": "https://github.xxx.com",
      "githubApiPathPrefix": "/api/v3/",
      "failComment": false
    }]
```

**Comment by travi** [comment]
ah, sorry. your details about your semantic-release config file blended in with the log output when i thought i could be helpful quickly. i saw your package.json details, but not the other.

i'm not confident about this, but i think the trailing slash on the prefix needs to be removed. 

beyond that, my suspicion is that the problem is related to the use of the ssh url in the package.json repository field. while you may be pulling the code from your repo over ssh, semantic-release interacts with github through its api, so i believe it needs the https version, which is also the [recommended version by npm](https://docs.npmjs.com/files/package.json#repository).

**Comment by modean** [comment]
@travi wrt/ the trailing slash I'd like to make the remark that with earlier versions of semantic release that `githubUrl` and `githubApiPathPrefix` settings actually did work together with the GHE setup I am using.

wrt/ to using `https://` over `ssh://` I'd like to add that the GitHub enterprise instance I am using is configured to not allow `https://`. As mentioned before with earlier semantic release versions that GHE setting actually did not cause issues. I also spend some time researching and came across this article:

https://semantic-release.gitbook.io/semantic-release/recipes/recipes-1/git-auth-ssh-keys

In that article it is explicitly mentioned that SSH as well is supported.

The semantic release version that works with our GHE setting is `11.2.0` but I figured that this version does not really support features like sharable configs as explained here:

https://semantic-release.gitbook.io/semantic-release/usage/shareable-configurations

Also to gain advantage of newly introduced features like advanced workflows, I prefer to not stik with version `11.2.0`.

**Comment by travi** [comment]
> In that article it is explicitly mentioned that SSH as well is supported.

this is true for interactions with git, like pushing tags, but i do not believe the same is true for interactions with the github api, like publishing release notes. 

since i'm not a maintainer, i'm not fully familiar with the internals, but this part of the log suggests to me that the github plugin is attempting to ensure (over https) that it will be able to perform the interactions with the api that it is configured to perform:

```
[2:36:14 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://github.xxx.com/api/v3/)

[2:36:23 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/github"
```

if the server is not accessible over https, i would expect that is the reason it is failing to be found at that step.

**Comment by modean** [comment]
@travi hummm ok thanks. I suppose it would be good a maintainer could shed some light on why the errors do happen with the current version compared to older versions (here: 11.2.0) that did work together with the same GHE setup. That includes pushing releases to GHE and the like.

**Comment by pvdlg** [comment]
The `@semantic-release/github` interact with the GitHub via API. The GitHub API is a REST API accessible over https. The plugin uses the URL configured via `githubUrl` and `githubApiPathPrefix`.
If your server is not accessible via https then you can't use the API and therefore can't use `@semantic-release/github`. There is no way around that, you need to able to access the API to use it.

**Comment by modean** [comment]
@pvdlg I disagree for one reason. It is working with version 11.2.0. So what essentially changed in between version 11.2.0 and 15.13.3? All the settings at my end incl. the GHE setup did remain the same. I assume with version 11.2.0 the GitHub REST API is also used.
