### ISSUE TITLE
An error on CI install

### ISSUE THREAD

**Issue by mrself** [semantic-release/semantic-release#114]
I have such an error when setup cli:
```
semantic-release-cli setup
? Are you using GitHub Enterprise? No
? What is your npm registry? https://registry.npmjs.org/
? What is your npm username? mrself
? What is your npm email? yaruk.my@gmail.com
? What is your GitHub username? mrself
? What CI are you using? Travis CI
C:\Users\Lightman\AppData\Roaming\npm\node_modules\semantic-release-cli\dist\lib\travis.js:113
    travis.repos(info.ghrepo.slug[0], info.ghrepo.slug[1]).get(function (err,
                            ^
TypeError: Cannot read property 'slug' of undefined
    at C:\Users\Lightman\AppData\Roaming\npm\node_modules\semantic-release-cli\dist\lib\travis.js:113:29
    at C:\Users\Lightman\AppData\Roaming\npm\node_modules\semantic-release-cli\dist\lib\travis.js:50:5
    at C:\Users\Lightman\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\travis-ci\lib\travis-ci.js:51:21
    at Request._callback (C:\Users\Lightman\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\travis-ci\lib\travis-http.js:51:13)
    at Request.self.callback (C:\Users\Lightman\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\travis-ci\node_modules\request\index.js:148:22)
    at Request.emit (events.js:110:17)
    at Request.<anonymous> (C:\Users\Lightman\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\travis-ci\node_modules\request\index.js:886:14)
    at Request.emit (events.js:129:20)
    at IncomingMessage.<anonymous> (C:\Users\Lightman\AppData\Roaming\npm\node_modules\semantic-release-cli\node_modules\travis-ci\node_modules\request\index.js:837:12)

    at IncomingMessage.emit (events.js:129:20)
```

**Comment by mrself** [comment]
My github repo was `git+git@github.com:mrself/` instead of `git+https://github.com/mrself/`. I think I did not notice it when run `npm init`

**Comment by bahmutov** [comment]
Same problem, the repo in package.json
```
"repository": {
     "type": "git",
     "url": "git@github.com:bahmutov/obind.git"
}
```

**Comment by bahmutov** [comment]
checked the info - seems the ghrepo property is missing completely
```js
// in semantic-release-cli/dist/lib/travis.js
function setUpTravis(pkg, info, cb) {
  var log = info.log;
  var travis = info.travis;
  syncTravis(travis, function () {
    console.log('gh repo', info.ghrepo);
    console.log('info', info);
    travis.repos(info.ghrepo.slug[0], info.ghrepo.slug[1]).get(function (err, res) {
```
prints for info
```
giturl: "https:git@github.com:bahmutov/obind.git",
github: { valid object }
```

maybe it is not parsing the git repo url correctly?

**Comment by bahmutov** [comment]
Seems the git url parsing code is *really old* using https://www.npmjs.com/package/parse-github-repo-url
which does not handle most of the newer formats
