### ISSUE TITLE
beta: no tag found on gitlab CI

### ISSUE THREAD

**Issue by plup** [semantic-release/semantic-release#1148]
## Current behavior

Gitlab CI can't find existing tags in the beta version.

Here is the ouput of my gitlab CI job (4955):
```
$ git tag -l
v1.0.0
v1.0.0-alpha.1@alpha

$ npm install -g semantic-release@v16.0.0-beta.18 @semantic-release/gitlab
npm WARN @semantic-release/gitlab@3.1.2 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
+ semantic-release@16.0.0-beta.18
+ @semantic-release/gitlab@3.1.2
added 991 packages from 981 contributors in 39.09s

$ semantic-release
[4:17:53 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.18
[skip]
[4:17:59 PM] [semantic-release] › ℹ  No git tag version found on branch master
[4:17:59 PM] [semantic-release] › ℹ  No previous release found, retrieving all commits
[skip]
[4:17:59 PM] [semantic-release] › ℹ  There is no previous release, the next release version is 1.0.0
[skip]
[4:17:59 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: git tag v1.0.0 87ec8f5789baa5bb12ac795ded368f968d2660ed
fatal: tag 'v1.0.0' already exists


    at makeError (/usr/local/lib/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/usr/local/lib/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
  code: 128,
  stdout: '',
  stderr: "fatal: tag 'v1.0.0' already exists\n",
  failed: true,
  signal: null,
  cmd: 'git tag v1.0.0 87ec8f5789baa5bb12ac795ded368f968d2660ed',
  timedOut: false,
  killed: false }
{ Error: Command failed: git tag v1.0.0 87ec8f5789baa5bb12ac795ded368f968d2660ed
fatal: tag 'v1.0.0' already exists
```

## Expected behavior

If I downgrade to the stable release and triggers the CI again everything runs as expected (job 4956):
```
$ git tag -l
v1.0.0
v1.0.0-alpha.1@alpha

$ npm install -g semantic-release @semantic-release/gitlab
+ semantic-release@15.13.3
+ @semantic-release/gitlab@3.1.2
added 977 packages from 979 contributors in 38.721s

$ semantic-release
[4:25:07 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.3
[skip]
[4:25:10 PM] [semantic-release] › ℹ  Found git tag v1.0.0 associated with version 1.0.0
[4:25:10 PM] [semantic-release] › ℹ  Found 4 commits since last release
[skip]
[4:25:10 PM] [semantic-release] › ℹ  The next release version is 1.1.0
[skip]
[4:25:13 PM] [semantic-release] › ✔  Created tag v1.1.0
[skip]
[4:25:19 PM] [semantic-release] › ✔  Published release 1.1.0
Job succeeded
```

## Configuration

```
$ cat package.json 
{
  "name": "siblab",
  "version": "0.1.0",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "description": "",
  "release": {
    "branches": [
      "master",
      {"name": "alpha", "prerelease": true}
    ],
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/gitlab"
    ]
 ```

## Environment

- **semantic-release** version: 16.0.0-beta.18
- CI environment: Gitlab CI
- Plugins used: "@semantic-release/commit-analyzer", "@semantic-release/gitlab"
- **semantic-release** configuration: see above 
- CI logs: see above

**Comment by plup** [comment]
Just got through the code to understand how it works and ended up with an issue related to Gitlab CI. 

Long story short: 

The branch is not created as `semantic-release` expects it when Gitlab CI clones the project. The workaround is to force the branch creation before the release execution: 
```
script:
    - git checkout $CI_COMMIT_REF_NAME
    - semantic-release
```

It executes the following command `git merge-base --is-ancestor v1.0.0-alpha.1@alpha alpha` and it doesn't find where the tags belongs to if the branch doesn't exist. So it keeps saying that there is no release and try to publish the `v1.0.0` every time.
