### ISSUE TITLE
Error evaluating acceptable range of maintenance releases

### ISSUE THREAD

**Issue by AlexandreCassagne** [semantic-release/semantic-release#1183]
## Current behavior

- There are releases in 2.8.* but I need to make a patch for 2.7.0.
- I used `git checkout -b 2.7.x v2.7.0` to create my maintenance branch.
- I made two `fix` commits. I pushed them to origin (set-upstream...)

(this is a local run, but a similar message appears on CI, with a different range:
`Based on the releases published on other branches, only versions within the range >=2.7.0 <1.0.0 can be published from branch 2.7.x.`)

```
$ semantic-release                              

[11:05:55] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.19
[11:05:55] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[11:05:55] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[11:05:55] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[11:05:55] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[11:05:55] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[11:05:55] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[11:05:55] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[11:05:55] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[11:05:55] [semantic-release] › ⚠  This run was not triggered in a known CI environment, running in dry-run mode.
[11:06:01] [semantic-release] › ⚠  Run automated release from branch 2.7.x in dry-run mode
[11:06:09] [semantic-release] › ✔  Allowed to push to the Git repository
[11:06:09] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[11:06:09] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[11:06:09] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[11:06:09] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.com/api/v4)
[11:06:09] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[11:06:09] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[11:06:09] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[11:06:09] [semantic-release] › ℹ  Found git tag v2.7.0@2.7.x associated with version 2.7.0 on branch 2.7.x
[11:06:09] [semantic-release] › ℹ  Found 2 commits since last release
[11:06:09] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:06:09] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: .releaserc
[11:06:09] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[11:06:09] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(Image Upload): Fix an Issue, to Update 2.7.0 -> 2.7.1
[11:06:09] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[11:06:09] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
[11:06:09] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:06:09] [semantic-release] › ℹ  The next release version is 2.7.1
[11:06:09] [semantic-release] › ✖  EINVALIDNEXTVERSION The release `2.7.1` on branch `2.7.x` cannot be published as it is out of range.
Based on the releases published on other branches, only versions within the range >=2.7.0 <2.6.0 can be published from branch 2.7.x.

The following commits are responsible for the invalid release:

    * fix: .releaserc (2ecf5f2) # => another patch
    * fix(Image Upload): Fix an Issue, to Update 2.7.0 -> 2.7.1 (5f2616d)

Those commits should be moved to a valid branch with git merge (https://git-scm.com/docs/git-merge)
 or git cherry-pick (https://git-scm.com/docs/git-cherry-pick) and removed from
 branch 2.7.x with git revert (https://git-scm.com/docs/git-revert) or git reset
 (https://git-scm.com/docs/git-reset).

A valid branch could be master.

See the workflow configuration documentation (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/workflow-configuration.md) 
for more details.

{ SemanticReleaseError: The release `2.7.1` on branch `2.7.x` cannot be published as it is out of range.
    at module.exports (~/.nvm/versions/node/v8.16.0/lib/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (~/.nvm/versions/node/v8.16.0/lib/node_modules/semantic-release/index.js:160:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  name: 'SemanticReleaseError',
  code: 'EINVALIDNEXTVERSION',
  details: 'Based on the releases published on other branches, only versions within the range `>=2.7.0 <2.6.0` can be published from branch `2.7.x`.\n\nThe following commits are responsible for the invalid release:\n- fix: .releaserc (2ecf5f2)\n- fix(Image Upload): Remove Dangling `@GetMapping` fixing issue #135 (5f2616d)\n\nThose commits should be moved to a valid branch with [git merge](https://git-scm.com/docs/git-merge) or [git cherry-pick](https://git-scm.com/docs/git-cherry-pick) and removed from branch `2.7.x` with [git revert](https://git-scm.com/docs/git-revert) or [git reset](https://git-scm.com/docs/git-reset).\n\nA valid branch could be `master`.\n\nSee the [workflow configuration documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/workflow-configuration.md) for more details.',
  semanticRelease: true }%                                      

  ```

## Expected behavior
Either my setup is wrong, or semantic-release is making an error calculating the range of acceptable releases (instead of "Based on the releases published on other branches, only versions within the range >=2.7.0 <2.6.0 can be published from branch 2.7.x.")

## Environment

- **semantic-release** version: 16.0.0-beta.19
- CI environment: GitLab, but the issue occurs locally also.
- plugins
1. "verifyConditions" from "@semantic-release/changelog"
2.  "verifyConditions" from "@semantic-release/gitlab"
3. "verifyConditions" from "@semantic-release/git"
4.  "analyzeCommits" from "@semantic-release/commit-analyzer"
5. "generateNotes" from "@semantic-release/release-notes-generator"
6.  "prepare" from "@semantic-release/changelog"
7.  "prepare" from "@semantic-release/git"
8. "publish" from "@semantic-release/gitlab"

- **semantic-release** configuration:
```json
{
    "branches": [
        "+([1-9])?(.{+([1-9]),x}).x",
        "master",
        "next",
        "next-major",
        {
            "name": "beta",
            "prerelease": true
        },
        {
            "name": "alpha",
            "prerelease": true
        }
    ],
    "plugins": [
        "@semantic-release/commit-analyzer",
        "@semantic-release/release-notes-generator",
        "@semantic-release/changelog",
        [
            "@semantic-release/gitlab",
            {
                "gitlabUrl": "https://gitlab.com",
                "assets": [
                    {
                        "path": "build/asciidoc/index.html",
                        "label": "HTML Documentation"
                    },
                    {
                        "path": "CHANGELOG.md",
                        "label": "Changelog"
                    }
                ]
            }
        ],
        {
            "path": "@semantic-release/git",
            "assets": [
                "CHANGELOG.md"
            ],
            "message": "chore(release): ${nextRelease.version} \n\n${nextRelease.notes}"
        }
    ]
}
```

**Comment by scottsword** [comment]
I'm experiencing the exact same thing using `16.0.0-beta.17`. I have a v2 on master and a v3 on alpha. If I try and bump the major version on master from a non-alpha branch using semantic release it gives me a range failure. If I attempt to merge in alpha where the changes have been done I get the range error. Regardless of what I do I'm blocked from releasing a major version.

**Comment by scottsword** [comment]
Possible related thread - https://github.com/semantic-release/semantic-release/issues/1131

**Comment by AlexandreCassagne** [comment]
> I'm experiencing the exact same thing using `16.0.0-beta.17`. I have a v2 on master and a v3 on alpha. If I try and bump the major version on master from a non-alpha branch using semantic release it gives me a range failure. If I attempt to merge in alpha where the changes have been done I get the range error. Regardless of what I do I'm blocked from releasing a major version.

Let me know if you manage to get the configuration to work. I tried reverting some commits and downgrading back to the stable v15 but with no luck.

**Comment by pvdlg** [comment]
Can you provide for each maintenance branches (`2.7.x`, etc...) and release branches (`master`, etc...) the list of tags in their history?
You can use the command `git tag --merged <branch>`.

**Comment by AlexandreCassagne** [comment]
@pvdlg

<details> <summary>master</summary>

```v1.0.0
v1.0.1
v1.0.2
v1.1.0
v1.1.1
v1.2.0
v1.2.1
v1.3.0
v1.4.0
v1.4.1
v1.4.2
v2.0.0
v2.0.1
v2.1.0
v2.1.1
v2.10.0
v2.10.1
v2.2.0
v2.3.0
v2.4.0
v2.4.1
v2.4.2
v2.4.3
v2.4.4
v2.4.5
v2.4.6
v2.5.0
v2.6.0
v2.6.1
v2.7.0
v2.7.0@2.7.x
v2.8.0
v2.8.1
v2.8.2
v2.9.0
v2.9.1```

</details>

**Comment by pvdlg** [comment]
I can't reproduce... Can you run with `--debug` option and provide the logs.

**Comment by AlexandreCassagne** [comment]
@pvdlg Closing this for now. I tried to reproduce this but am unable to with beta 19. This may have been beta 17 after all. I'll reopen this if I can reproduce it again

**Comment by adrianschmidt** [comment]
I found this thread because I was getting "SemanticReleaseError: The release `36.1.1` on branch `36.1.x` cannot be published as it is out of range."

It turned out that I was trying to release v36.1.1 from the branch `36.1.x` while the latest release on `main` was v36.1.0. That made semantic-release react, because for all it knew, the next release on `main` could very well be v36.1.1.

I just wanted to post that, in case the next reader might be helped by it 😅
