### ISSUE TITLE
tag does already exists beta 20

### ISSUE THREAD

**Issue by alexan** [semantic-release/semantic-release#1199]
## Current behavior

I'm trying to update to semantic release beta. With beta 20 I successfully released a test package. Now I switched to a package which I have previously released with semantic-release@15. The updated semantic release now does not seem to detect my tags right:
I am fetching with: `git fetch --tags ...`

## Expected behavior

should detect that I already published two releases. (v1.0.0, v1.0.1). This does work with semantic-release@15 with the same build setup

## Environment

- **semantic-release** version: ^16.0.0-beta.20
- CI environment: Jenkins CI
- config
```
module.exports = {
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    [
      '@semantic-release/npm',
      {
        pkgRoot: '.',
        tarballDir: '.',
      },
    ],
    [
      '@semantic-release/gitlab',
      {
        gitlabUrl: '...',
        assets: [
          {
            path: '-*.tgz',
          },
        ],
      },
    ],
  ],
};

```
- CI logs: 
```
[10:08:49 AM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.20
[10:08:50 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[10:08:50 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[10:08:50 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[10:08:50 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[10:08:50 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[10:08:50 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[10:08:50 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[10:08:50 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[10:08:50 AM] [semantic-release] › ✔  Run automated release from branch master
[10:08:50 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[10:08:50 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[10:08:50 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry release/
[10:08:50 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[10:08:50 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[10:08:50 AM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (/api/v4)
[10:08:50 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[10:08:50 AM] [semantic-release] › ℹ  No git tag version found on branch master
[10:08:50 AM] [semantic-release] › ℹ  No previous release found, retrieving all commits
[10:08:50 AM] [semantic-release] › ℹ  Found 6 commits since last release
[10:08:50 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge branch 'feature/semantic-release-update' into 'master'

ci: update sematic release to 16

See merge request !3
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci: update semantic release to 16
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: build: add commit npm script
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge branch 'bugfix/add-schema' into 'master'

fix(fnx-component): correctly reference schema in collection

See merge request !1
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(fnx-component): correctly reference schema in collection
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: initial commit
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[10:08:50 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 6 commits complete: minor release
[10:08:50 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:08:50 AM] [semantic-release] › ℹ  There is no previous release, the next release version is 1.0.0
[10:08:50 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:08:51 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:08:51 AM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[10:08:51 AM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 1.0.0 to package.json in 
v1.0.0
[10:08:51 AM] [semantic-release] [@semantic-release/npm] › ℹ  Creating npm package version 1.0.0
npm notice 
npm notice package: @1.0.0
npm notice === Tarball Contents === 
npm notice 1.5kB package.json                                                  
npm notice 1.4kB Jenkinsfile                                                   
npm notice 67B   prettier.config.js                                            
npm notice 639B  README.md                                                     
npm notice 464B  release.config.js                                             
npm notice 604B  tsconfig.json                                                 
npm notice 182B  scripts/prerelease/commitId.js                                
npm notice 265B  scripts/prerelease/lastTag.js                                 
npm notice 915B  scripts/prerelease/prerelease.js                              
npm notice 333B  src/collection.json                                           
npm notice 0     src/fnx-component/files/__name@dasherize__.component.__style__
npm notice 41B   src/fnx-component/files/__name@dasherize__.component.html     
npm notice 525B  src/fnx-component/files/README.md                             
npm notice 11B   src/fnx-component/index_spec.d.ts                             
npm notice 625B  src/fnx-component/index_spec.js                               
npm notice 545B  src/fnx-component/index_spec.js.map                           
npm notice 109B  src/fnx-component/index.d.ts                                  
npm notice 5.4kB src/fnx-component/index.js                                    
npm notice 4.4kB src/fnx-component/index.js.map                                
npm notice 525B  src/fnx-component/schema.json                                 
npm notice === Tarball Details === 
npm notice name:              
npm notice version:       1.0.0                                   
npm notice filename:     -1.0.0.tgz        
npm notice package size:  6.5 kB                                  
npm notice unpacked size: 18.6 kB                                 
npm notice shasum:        91b17176827a6d17209a6a22a562b4925c52064b
npm notice integrity:     sha512-nivompmrfEPn3[...]4VdCsziLfQauA==
npm notice total files:   20                                      
npm notice 
-1.0.0.tgz
[10:08:52 AM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[10:08:52 AM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: git tag v1.0.0 e76d5c745c506d0a5c61ecdfde5a4bb44f9c37d4
fatal: tag 'v1.0.0' already exists


    at makeError (/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr /node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 128,
  stdout: '',
  stderr: 'fatal: tag \'v1.0.0\' already exists\n',
  failed: true,
  signal: null,
  cmd: 'git tag v1.0.0 e76d5c745c506d0a5c61ecdfde5a4bb44f9c37d4',
  timedOut: false,
  killed: false }
{ Error: Command failed: git tag v1.0.0 e76d5c745c506d0a5c61ecdfde5a4bb44f9c37d4
fatal: tag 'v1.0.0' already exists


    at makeError (/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr /node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: [33m128[39m,
  stdout: [32m''[39m,
  stderr: [32m'fatal: tag \'v1.0.0\' already exists\n'[39m,
  failed: [33mtrue[39m,
  signal: [1mnull[22m,
  cmd: [32m'git tag v1.0.0 e76d5c745c506d0a5c61ecdfde5a4bb44f9c37d4'[39m,
  timedOut: [33mfalse[39m,
  killed: [33mfalse[39m }npm ERR! code ELIFECYCLE
```

**Comment by BowlingX** [comment]
I experience the same issue with `beta-20`. I have over 200 releases and it seems not to detect one.

```
[11:18:18] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1282 commits complete: major release
[11:18:18] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[11:18:18] [semantic-release] › ℹ  There is no previous release, the next release version is 1.0.0
[
```
Relevant fields in `package.json`:

```json
{
"release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      "@semantic-release/npm",
      "@semantic-release/git"
    ],
    "repositoryUrl": "xxx"
  },
"devDependencies": {
    "@semantic-release/changelog": "^3.0.4",
    "@semantic-release/commit-analyzer": "^7.0.0-beta.2",
    "@semantic-release/git": "^7.1.0-beta.3",
    "@semantic-release/npm": "^5.2.0-beta.6",
    "@semantic-release/release-notes-generator": "^7.1.7",
    "semantic-release": "^16.0.0-beta.20"
  }
}
```

It seems to come from the `@semantic-release/commit-analyzer` module?

**Comment by BowlingX** [comment]
Running locally with yarn `semantic-release -d --no-ci` did work for me (showed the correct next version).

**Comment by jmodjeski75** [comment]
@BowlingX can you try with a stable version of @semantic-release/commit-analyzer?

**Comment by jmodjeski75** [comment]
@alexan what version of @semantic-release/commit-analyzer are you using?

**Comment by bryanlarsen** [comment]
We have the same problem.   Here's the log from the npm install:

```
+ npm install -g @semantic-release/changelog@^3.0.4 @semantic-release/git@^7.1.0-beta.3 @semantic-release/gitlab@^3.1.5 semantic-release@^16.0.0-beta.19
/usr/bin/semantic-release -> /usr/lib/node_modules/semantic-release/bin/semantic-release.js
npm WARN @semantic-release/release-notes-generator@7.1.4 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/commit-analyzer@7.0.0-beta-.2 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/github@5.4.0-beta.1 requires a peer of semantic-release@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/npm@5.2.0-beta.6 requires a peer of semantic-release@>=15.9.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/gitlab@3.1.5 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/changelog@3.0.4 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.

+ semantic-release@16.0.0-beta.20
+ @semantic-release/gitlab@3.1.5
+ @semantic-release/git@7.1.0-beta.3
+ @semantic-release/changelog@3.0.4
```

**Comment by alexan** [comment]
I have not specified a specific version in devDependencies. From my package-lock I see it resolved to:
`7.0.0-beta-.2` because: https://github.com/semantic-release/semantic-release/blob/beta/package.json#L22.

**Comment by bryanlarsen** [comment]
commit-analyzer@6.1.1 has the same problem:

```
+ npm install -g @semantic-release/changelog@^3.0.4 @semantic-release/git@^7.1.0-beta.3 @semantic-release/gitlab@^3.1.5 semantic-release@^16.0.0-beta.19 @semantic-release/commit-analyzer@^6.1.1
/usr/bin/semantic-release -> /usr/lib/node_modules/semantic-release/bin/semantic-release.js
npm WARN @semantic-release/commit-analyzer@7.0.0-beta-.2 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/github@5.4.0-beta.1 requires a peer of semantic-release@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/npm@5.2.0-beta.6 requires a peer of semantic-release@>=15.9.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/release-notes-generator@7.1.4 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/changelog@3.0.4 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/gitlab@3.1.5 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/commit-analyzer@6.1.1 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.

+ semantic-release@16.0.0-beta.20
+ @semantic-release/changelog@3.0.4
+ @semantic-release/git@7.1.0-beta.3
+ @semantic-release/gitlab@3.1.5
+ @semantic-release/commit-analyzer@6.1.1
added 1263 packages from 980 contributors in 35.542s
+ semantic-release
[3:17:12 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.0-beta.20
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[3:17:13 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[3:17:19 PM] [semantic-release] › ✔  Run automated release from branch pre-commit
[3:17:19 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[3:17:19 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[3:17:19 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[3:17:19 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[3:17:19 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[3:17:19 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[3:17:19 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[3:17:19 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[3:17:19 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (https://gitlab.com/api/v4)
[3:17:20 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[3:17:20 PM] [semantic-release] › ℹ  No git tag version found on branch pre-commit
[3:17:20 PM] [semantic-release] › ℹ  No previous release found, retrieving all commits
```

**Comment by bryanlarsen** [comment]
oops, I noticed that my attempts to use commit-analyzer@6.1.1 just resulted in two versions of commit-analyzer being installed.

**Comment by bryanlarsen** [comment]
commit-analyzer beta-.2 works with semantic-release beta.19:

```
+ npm install -g @semantic-release/changelog@^3.0.4 @semantic-release/git@^7.1.0-beta.3 @semantic-release/gitlab@^3.1.5 semantic-release@16.0.0-beta.19
/usr/bin/semantic-release -> /usr/lib/node_modules/semantic-release/bin/semantic-release.js
npm WARN @semantic-release/npm@5.2.0-beta.6 requires a peer of semantic-release@>=15.9.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/release-notes-generator@7.1.4 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/commit-analyzer@7.0.0-beta-.2 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/github@5.4.0-beta.1 requires a peer of semantic-release@>=16.8.0 <17.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/changelog@3.0.4 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @semantic-release/gitlab@3.1.5 requires a peer of semantic-release@>=15.8.0 <16.0.0 but none is installed. You must install peer dependencies yourself.

+ semantic-release@16.0.0-beta.19
+ @semantic-release/changelog@3.0.4
+ @semantic-release/git@7.1.0-beta.3
+ @semantic-release/gitlab@3.1.5
```

**Comment by pvdlg** [comment]
The problem come from the changes introduced in https://github.com/semantic-release/semantic-release/pull/1186.

Could you:
- Make a run with beta.20 with `--debug` and provide the full logs
- Try with beta.19 and confirm it works

**Comment by pvdlg** [comment]
I'm guessing it come from the changes in the `fetch` function here: https://github.com/semantic-release/semantic-release/pull/1186/files#diff-89fd8e8ef20565f129343f363cc8433cR135

Probably the tags are not fetched properly now.

**Comment by jmodjeski75** [comment]
@pvdlg I believe it to be the change in the refspec

**Comment by pvdlg** [comment]
I'm guessing it's because `+refs/heads/${branch}:refs/heads/${branch}` was replaced by `+refs/heads/${branch}:refs/remotes/upstream/${branch}`. @jmodjeski75 what is the reason for this change?

**Comment by jmodjeski75** [comment]
@pvdlg I not sure this was necessary, this should not need to track upstream changes

**Comment by pvdlg** [comment]
@alexan can you try again with beta.21?

**Comment by alexan** [comment]
@pvdlg beta.21 worked for me
