### ISSUE TITLE
generateNotes step fails when using angular-bitbucket preset

### ISSUE THREAD

**Issue by JoA-MoS** [semantic-release/semantic-release#1219]
## Current behavior

While running `npx semantic-release` or  `npx semantic-release --no-ci --debug --branch=feature/better-changelog --dry-run` during the generateNotes step an error is reported stating: 

```
An error occurred while running semantic-release: { TypeError: Cannot read property 'bugs' of undefined
    at transform (C:\mycomp\myproj\my-repo\node_modules\conventional-changelog-angular-bitbucket\src\index.js:61:42)
```
I am using the [angular-bitbucket](https://github.com/uglow/conventional-changelog-angular-bitbucket) preset and creating the changelog via `conventional-changelog` cli works as expected:

```
npx conventional-changelog -p angular-bitbucket -i CHANGELOG.md -s -r 0
```

It appears that the conventional-changelog cli and the corp-semantic-release package use a different entry point into the conventional-changelog than semantic-release/release-notes-generator. I believe this is causing the writer to not merge the config that is present in the package.json, and instead only pulling a few properties from the context to generate the changelogContext see `@semantic-release/release-notes-generator/index.js`

```javascript
  const changelogContext = {
    version: nextRelease.version,
    host: format({protocol, hostname, port}),
    owner,
    repository,
    previousTag,
    currentTag,
    linkCompare: currentTag && previousTag,
    issue,
    commit,
  };

return getStream(intoStream.obj(parsedCommits).pipe(writer(changelogContext, writerOpts)));
```

## Expected behavior

A changelog would be generated using the host and bugs url defined in either the package.json or the release.cofig.js

## Environment

- **semantic-release** version: 15.13.17
- CI environment: Jenkins or --no-ci
- Plugins used: 
```
 '@semantic-release/commit-analyzer',
'@semantic-release/release-notes-generator',
'@semantic-release/changelog',
'@semantic-release/exec',
'@semantic-release/npm',
'@semantic-release/git',
```

- **semantic-release** configuration: 

Excerpt from release.config.js
```
  [
      '@semantic-release/release-notes-generator',
      {
        preset: 'angular-bitbucket',
        host: 'https://my-bb-host.org/projects/myproj/repos/my-repo.git',
        bugs: {
          url: 'https://my-jira-host.org/jira/browse',
        },
      },
    ],
```

excerpt from package.json
```
  "host": "https://my-bb-host.org/projects/myproj/repos/my-repo.git",
  "bugs": {
    "url": "https://my-jira-host.org/jira/browse"
  },
```

- CI logs: 
```
[4:11:22 PM] [semantic-release] » i  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
  semantic-release:release-notes-generator version: '2.16.2' +0ms
  semantic-release:release-notes-generator host: 'my-host.org' +1ms
  semantic-release:release-notes-generator owner: 'scm' +0ms
  semantic-release:release-notes-generator repository: 'myproj/my-repo' +1ms
  semantic-release:release-notes-generator previousTag: 'v2.16.1' +0ms
  semantic-release:release-notes-generator currentTag: 'v2.16.2' +0ms
[4:11:22 PM] [semantic-release] » ×  Failed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[4:11:22 PM] [semantic-release] » ×  An error occurred while running semantic-release: { TypeError: Cannot read property 'bugs' of undefined
    at transform (C:\my-comp\myproj\my-repo\node_modules\conventional-changelog-angular-bitbucket\src\index.js:61:42)
    at Object.processCommit (C:\my-comp\myproj\my-repo\node_modules\conventional-changelog-writer\lib\util.js:120:14)
    at DestroyableTransform._transform (C:\my-comp\myproj\my-repo\node_modules\conventional-changelog-writer\index.js:88:25)
    at DestroyableTransform.Transform._read (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Class.ondata (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at Class.emit (events.js:189:13)
  bufferedData: '',
  pluginName: '@semantic-release/release-notes-generator' }
{ TypeError: Cannot read property 'bugs' of undefined
    at transform (C:\my-comp\myproj\my-repo\node_modules\conventional-changelog-angular-bitbucket\src\index.js:61:42)
    at Object.processCommit (C:\my-comp\myproj\my-repo\node_modules\conventional-changelog-writer\lib\util.js:120:14)
    at DestroyableTransform._transform (C:\my-comp\myproj\my-repo\node_modules\conventional-changelog-writer\index.js:88:25)
    at DestroyableTransform.Transform._read (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_transform.js:172:83)
    at doWrite (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_writable.js:428:64)
    at writeOrBuffer (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_writable.js:417:5)
    at DestroyableTransform.Writable.write (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_writable.js:334:11)
    at Class.ondata (C:\my-comp\myproj\my-repo\node_modules\readable-stream\lib\_stream_readable.js:619:20)
    at Class.emit (events.js:189:13)
  bufferedData: '',
  pluginName: '@semantic-release/release-notes-generator' }
```

**Comment by JoA-MoS** [comment]
I did just update to the 7.2.0 release or the release-notes-generator and it is still missing the bugs

https://github.com/semantic-release/release-notes-generator/commit/44abdf9

**Comment by JoA-MoS** [comment]
So, I think I see what needs to change but I am not sure if a change should also be made to the angular-bitbucket preset. 

```javascript
 const {
    host: hostConfig,
    linkCompare,
    linkReferences,
    commit: commitConfig,
    issue: issueConfig,
    bugs,
  } = pluginConfig;
  const changelogContext = merge(
    {
      version: nextRelease.version,
      host: format({ protocol, hostname, port }),
      owner,
      repository,
      previousTag,
      currentTag,
      linkCompare: currentTag && previousTag,
      issue,
      commit,
    },
    { host: hostConfig, linkCompare, linkReferences, commit: commitConfig, issue: issueConfig, packageData: { bugs } }
  );
```
Is this the correct change to make or is their a better approach to pull in all the [packageData](https://github.com/conventional-changelog/conventional-changelog/blob/8a6a44b98a7b0dddf3e034d6f7f3cf0c51171f0a/packages/conventional-changelog-core/README.md#packagedata)?

**Comment by pvdlg** [comment]
I could search for a `package.json` in the current directory, read it and pass it in `packageData`.

However I think it's incorrect for your preset to expect that to be set. There is cases were it won't be set: https://github.com/conventional-changelog/conventional-changelog/blob/dc8aedae0519045bfcb2e649167f0f6bfb2f4a30/packages/conventional-changelog-core/lib/merge-config.js#L156

Also not all projects have a `package.json` (such a non JS projects).

**Comment by JoA-MoS** [comment]
Thanks for the reply, A couple of questions

1. It seems like that in general semantic-release uses a logic (very simplified analysis) where it looks at the package.json if it exists get the properties from that then look at the release section of the package.json and overwrite any properties, then look at the release.config.js, and merge those on top. Is that correct?

2. Why did you choose the entry point at into the changelog using the `conventional-changelog-writer` rather than the default `conventional-changelog`?

Rather than searching for the package.json, the config could just expose packageData then leave it up to the user to populate as needed. 

I am looking at how `conventional-changelog-conventionalcommits` populates the issueUrlFormat to see how the angular-bitbucket preset could be changed.
