### ISSUE TITLE
cannot find the highest version tag

### ISSUE THREAD

**Issue by njzjz** [semantic-release/semantic-release#1229]
The highest version tag is v1.4.0, but semantic-release only found v1.3.25.
```
### STARTED yarn semantic-release 06:01:21Z

Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9: Pulling from gct-12-yfhoqvax2mb4fssy7fgtqd5/e0647a01f184a24378384b57bc7815798ce0c34b1468596198997c4c3c35030e/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1
Digest: sha256:aaa3619d44cf917097a2e651c00f9e70e42b6e8c263ea890f55930242aeab7e1
Status: Image is up to date for gcr.io/gct-12-yfhoqvax2mb4fssy7fgtqd5/e0647a01f184a24378384b57bc7815798ce0c34b1468596198997c4c3c35030e/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Step 1/12 : FROM node:10
 ---> e05cbde47b8f
Step 2/12 : LABEL version="1.1.0"
 ---> Using cache
 ---> a190f737c996
Step 3/12 : LABEL repository="https://github.com/Borales/actions-yarn"
 ---> Using cache
 ---> c15d419a6b1f
Step 4/12 : LABEL homepage="https://github.com/Borales/actions-yarn"
 ---> Using cache
 ---> 514f33c1674e
Step 5/12 : LABEL maintainer="Oleksandr Bordun <bordun.alexandr@gmail.com>"
 ---> Using cache
 ---> 01f80e0de3e9
Step 6/12 : LABEL com.github.actions.name="GitHub Action for Yarn"
 ---> Using cache
 ---> 62bc05f4378e
Step 7/12 : LABEL com.github.actions.description="Wraps the yarn CLI to enable common yarn commands."
 ---> Using cache
 ---> ba1e9ac5d13f
Step 8/12 : LABEL com.github.actions.icon="package"
 ---> Using cache
 ---> 1107b3649dfe
Step 9/12 : LABEL com.github.actions.color="blue"
 ---> Using cache
 ---> 6f49230897dc
Step 10/12 : COPY "entrypoint.sh" "/entrypoint.sh"
 ---> Using cache
 ---> 18ffa90f66af
Step 11/12 : ENTRYPOINT ["/entrypoint.sh"]
 ---> Using cache
 ---> 39260f8ac4ed
Step 12/12 : CMD ["help"]
 ---> Using cache
 ---> 8e59b31d4672
Successfully built 8e59b31d4672
Successfully tagged gcr.io/gct-12-yfhoqvax2mb4fssy7fgtqd5/e0647a01f184a24378384b57bc7815798ce0c34b1468596198997c4c3c35030e/8a5edab282632443219e051e4ade2d1d5bbc671c781051bf1437897cbdfea0f1:fc613b4dfd6736a7bd268c8a0e74ed0d1c04a959f59dd74ef2874983fd443fc9
Already have image (with digest): gcr.io/github-actions-images/action-runner:latest
yarn run v1.16.0
$ semantic-release
[6:01:18 AM] [semantic-release] › ℹ  Running semantic-release version 15.13.18
[6:01:19 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[6:01:19 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[6:01:19 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[6:01:19 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[6:01:19 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[6:01:19 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[6:01:19 AM] [semantic-release] › ✔  Run automated release from branch master
[6:01:21 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[6:01:21 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[6:01:21 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[6:01:21 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[6:01:22 AM] [semantic-release] › ℹ  Found git tag v1.3.25 associated with version 1.3.25
[6:01:22 AM] [semantic-release] › ℹ  Found 24 commits since last release
[6:01:22 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Deploying to gh-pages - 06:01:21
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #300 from njzjz/dependabot/npm_and_yarn/reacnetgenerator/static/webpack/url-loader-2.0.1
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #303 from njzjz/dependabot/npm_and_yarn/semantic-release-15.13.18
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): bump url-loader in /reacnetgenerator/static/webpack

Bumps [url-loader](https://github.com/webpack-contrib/url-loader) from 2.0.0 to 2.0.1.
- [Release notes](https://github.com/webpack-contrib/url-loader/releases)
- [Changelog](https://github.com/webpack-contrib/url-loader/blob/master/CHANGELOG.md)
- [Commits](https://github.com/webpack-contrib/url-loader/compare/v2.0.0...v2.0.1)

Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps-dev): bump semantic-release from 15.13.16 to 15.13.18

Bumps [semantic-release](https://github.com/semantic-release/semantic-release) from 15.13.16 to 15.13.18.
- [Release notes](https://github.com/semantic-release/semantic-release/releases)
- [Commits](https://github.com/semantic-release/semantic-release/compare/v15.13.16...v15.13.18)

Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore: remove .travis.yml (#304)
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #299 from njzjz/dependabot/npm_and_yarn/reacnetgenerator/static/webpack/webpack-cli-3.3.5
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): bump webpack-cli in /reacnetgenerator/static/webpack

Bumps [webpack-cli](https://github.com/webpack/webpack-cli) from 3.3.4 to 3.3.5.
- [Release notes](https://github.com/webpack/webpack-cli/releases)
- [Changelog](https://github.com/webpack/webpack-cli/blob/master/CHANGELOG.md)
- [Commits](https://github.com/webpack/webpack-cli/compare/v3.3.4...v3.3.5)

Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): update dependency vuepress to v1.0.2
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(deps): update dependency webpack to v4.35.0
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): lock file maintenance
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(deps): update dependency startbootstrap-creative to v5.1.7
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: bugfix (#289)
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(deps): update dependency webpack to v4.34.0
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): update dependency semantic-release to v15.13.16
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(deps): update dependency css-loader to v3 (#285)
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(deps): update dependency webpack-cli to v3.3.4
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: add reactant (#283)
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): lock file maintenance
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): update dependency vuepress to v1.0.1
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): lock file maintenance
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: add maxspecies option (resolves #245) (#279)
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: add progress bar for converting signals (#278)

* fix: add progress bar for converting signals

resolves #246

* Update reacnetgenerator/_path.py

* Update _hmmfilter.py
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: separate command line from main script (#276)

* fix: commandline

* fix: compile the script

* Update commandline.py

* Update reacnetgenerator/reacnetgen.py
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[6:01:22 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 24 commits complete: minor release
[6:01:22 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[6:01:22 AM] [semantic-release] › ℹ  The next release version is 1.4.0
[6:01:22 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:01:23 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:01:23 AM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: git tag v1.4.0
fatal: tag 'v1.4.0' already exists


    at makeError (/github/workspace/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/github/workspace/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 128,
  stdout: '',
  stderr: 'fatal: tag \'v1.4.0\' already exists\n',
  failed: true,
  signal: null,
  cmd: 'git tag v1.4.0',
  timedOut: false,
  killed: false }
{ Error: Command failed: git tag v1.4.0
fatal: tag 'v1.4.0' already exists


    at makeError (/github/workspace/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/github/workspace/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 128,
  stdout: '',
  stderr: 'fatal: tag \'v1.4.0\' already exists\n',
  failed: true,
  signal: null,
  cmd: 'git tag v1.4.0',
  timedOut: false,
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  killed: false }error Command failed with exit code 1.

### FAILED yarn semantic-release 06:01:52Z (31.062s)
```

**Comment by pvdlg** [comment]
Is the tag `v1.4.0` in the history of `master`?
You can check that with `git tag --merged master` which is going to look at all the tags in `master` history.

semantic-release will search only for tags pointing to a commit in the history of the branch on which it's running.

**Comment by link89** [comment]
It is a problem because we use following git flow:
https://datasift.github.io/gitflow/IntroducingGitFlow.html
As you can see, the develop branch never rebase to master but merge into it, and feature branch is always folked from master.
When we using prerelease rule on stage branch, which is folked from master, it would never read the latest release correctly and we have to using a workaround.

**Comment by njzjz** [comment]
@pvdlg No, it is not in the history of master.

**Comment by njzjz** [comment]
Pushing a tag to `master` resolves the problem.
