### ISSUE TITLE
Setup SSH, but still get ENOGHTOKEN error for github

### ISSUE THREAD

**Issue by karlyanelson** [semantic-release/semantic-release#1264]
## Current behavior

We are trying to use semantic-release with CircleCI. We were not able to do the setup through the semantic-release CLI, because for security reasons we need to authenticate through SSH, so we haven't setup the GH_TOKEN. We followed the SSH setup instructions for CircleCI from the documentation: https://semantic-release.gitbook.io/semantic-release/recipes/git-hosted-services/git-auth-ssh-keys, including adding everything we need to our environmental variables but our build is still failing in CircleCI with an error saying we don't have a GH_TOKEN even though we shouldn't need one.

Here's the error we're getting:
```
[10:06:47 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/github"
[10:06:47 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/github" in dry-run mode
[10:06:47 PM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository principlesos/design-system-tokens.

AggregateError: 
    SemanticReleaseError: No GitHub token specified.
        at module.exports (/home/circleci/project/node_modules/@semantic-release/github/lib/get-error.js:6:10)
        at module.exports (/home/circleci/project/node_modules/@semantic-release/github/lib/verify.js:85:17)
        at verifyConditions (/home/circleci/project/node_modules/@semantic-release/github/index.js:24:9)
        at validator (/home/circleci/project/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
        at /home/circleci/project/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
        at next (/home/circleci/project/node_modules/p-reduce/index.js:17:9)
    at /home/circleci/project/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at async Object.pluginsConf.<computed> [as verifyConditions] (/home/circleci/project/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/circleci/project/node_modules/semantic-release/index.js:82:3)
    at async module.exports (/home/circleci/project/node_modules/semantic-release/index.js:168:22)
    at async module.exports (/home/circleci/project/node_modules/semantic-release/cli.js:55:5) {
  name: 'AggregateError'
}Exited with code 1
```

## Expected behavior

Semantic-release is able to connect to github repo and push tags, releases, etc.

## Environment

- **semantic-release** version: ^15.13.19
- CI environment: CircleCI
- Plugins used: Github, NPM
- **semantic-release** configuration: This is all I have in my .releaserc, should I have more?
```
{
  "branch": "master"
}
```
- CircleCI config.yml:
```
      - run:
          name: authenticate github
          command: |
            # Decrypt the git_deploy_key.enc key into /tmp/git_deploy_key
            openssl aes-256-cbc -d -K $REPO_ENC_KEY -iv $REPO_ENC_IV -in git_deploy_key.enc -out /tmp/git_deploy_key
            # Make sure only the current user can read the private key
            chmod 600 /tmp/git_deploy_key
            # Create a script to return the passphrase environment variable to ssh-add
            echo 'echo ${SSL_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
            # Start the authentication agent
            eval "$(ssh-agent -s)"
            # Add the key to the authentication agent
            DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
      - run:
          name: semantically release
          command: npx semantic-release --dry-run
```
- CI logs:  our circle ci is private so I can't link to it, but here's the entire output from:

**the "authenticate github" step (which passed):**

```
#!/bin/bash -eo pipefail
# Decrypt the git_deploy_key.enc key into /tmp/git_deploy_key
openssl aes-256-cbc -d -K $REPO_ENC_KEY -iv $REPO_ENC_IV -in git_deploy_key.enc -out /tmp/git_deploy_key
# Make sure only the current user can read the private key
chmod 600 /tmp/git_deploy_key
# Create a script to return the passphrase environment variable to ssh-add
echo 'echo ${SSL_PASSPHRASE}' > /tmp/askpass && chmod +x /tmp/askpass
# Start the authentication agent
eval "$(ssh-agent -s)"
# Add the key to the authentication agent
DISPLAY=":0.0" SSH_ASKPASS="/tmp/askpass" setsid ssh-add /tmp/git_deploy_key </dev/null
Agent pid 115
Identity added: /tmp/git_deploy_key (/tmp/git_deploy_key)
```

 **the "semantically release" step (which failed):**
```
#!/bin/bash -eo pipefail
npx semantic-release --dry-run
[10:06:46 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.21
[10:06:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[10:06:46 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[10:06:46 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[10:06:46 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[10:06:46 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[10:06:46 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[10:06:46 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[10:06:46 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[10:06:46 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[10:06:46 PM] [semantic-release] › ⚠  Run automated release from branch semantic-release-config in dry-run mode
[10:06:47 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[10:06:47 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[10:06:47 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://principled.jfrog.io/principled/api/npm/npm-mpllc/
[10:06:47 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[10:06:47 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[10:06:47 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[10:06:47 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/github"
[10:06:47 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/github" in dry-run mode
[10:06:47 PM] [semantic-release] › ✖  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository principlesos/design-system-tokens.

AggregateError: 
    SemanticReleaseError: No GitHub token specified.
        at module.exports (/home/circleci/project/node_modules/@semantic-release/github/lib/get-error.js:6:10)
        at module.exports (/home/circleci/project/node_modules/@semantic-release/github/lib/verify.js:85:17)
        at verifyConditions (/home/circleci/project/node_modules/@semantic-release/github/index.js:24:9)
        at validator (/home/circleci/project/node_modules/semantic-release/lib/plugins/normalize.js:34:30)
        at /home/circleci/project/node_modules/semantic-release/lib/plugins/pipeline.js:37:40
        at next (/home/circleci/project/node_modules/p-reduce/index.js:17:9)
    at /home/circleci/project/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at async Object.pluginsConf.<computed> [as verifyConditions] (/home/circleci/project/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/circleci/project/node_modules/semantic-release/index.js:82:3)
    at async module.exports (/home/circleci/project/node_modules/semantic-release/index.js:168:22)
    at async module.exports (/home/circleci/project/node_modules/semantic-release/cli.js:55:5) {
  name: 'AggregateError'
}Exited with code 1
```

**Comment by gr2m** [comment]
The GitHub token is still necessary to create tags/releases, which is done using GitHub's API. It will not be used for git commands if you configure the ssh git URL

**Comment by karlyanelson** [comment]
Thank you for helping me.

I'm confused though because the [documentation](https://semantic-release.gitbook.io/semantic-release/recipes/git-hosted-services/git-auth-ssh-keys) says that:

> **Note**: SSH keys allow to push the Git release tag associated to the released version. Some plugins might also require an API token. See each plugin documentation for additional information.

Isn't that saying I can create tags/releases just with SSH?

**Comment by gr2m** [comment]
I think we do actually create tags with git. But releases are a GitHub-specific feature.

> If I can only do that with the tokens then what's the point of having an SSH option?

Only the github plugin needs the token, if you don't need the github plugin which creates the releases, you don't need the token

**Comment by karlyanelson** [comment]
Oh ok, thanks for your help! It would be nice if that was clearer in the documentation

**Comment by gr2m** [comment]
If you have an idea how the docs could be improved to make that more clear, we would appreciate a pull request :)

**Comment by karlyanelson** [comment]
Ok! I shall attempt :)

**Comment by pvdlg** [comment]
See https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md:
> **Note**: The environment variables `GH_TOKEN`, `GITHUB_TOKEN`, `GL_TOKEN` and `GITLAB_TOKEN` can be used for both the Git authentication and the API authentication required by [@semantic-release/github](https://github.com/semantic-release/github) and [@semantic-release/gitlab](https://github.com/semantic-release/gitlab).

Do you think it needs more clarification?

**Comment by karlyanelson** [comment]
@pvdlg thanks for commenting! Yeah, see for me that still is just saying you _can_ use a `GH_TOKEN`,etc. but you don't _have_ to if you use SSH. Really what originally tripped me up was:

> Note: SSH keys allow to push the Git release tag associated to the released version. Some plugins might also require an API token. See each plugin documentation for additional information.

Made it sound like SSH could do everything I wanted, though I know it does say "Some plugins might also require an API token". But I was assuming that because it lets you push a git release tag that the github plugin worked fine with just SSH.

I think I would like it to say something like: 

> Note: SSH keys allow to push the Git tag associated to the released version, **but they don't allow authentication to Git to create the release through the github plugin.** Some other plugins might also require an API token. See each plugin documentation for additional information.

I guess I don't know why you mention SSH at all. I don't see a situation where you wouldn't want to use the github plugin.

**Comment by pvdlg** [comment]
> Made it sound like SSH could do everything I wanted, though I know it does say "Some plugins might also require an API token". But I was assuming that because it lets you push a git release tag that the github plugin worked fine with just SSH.

I'm not a native english speaker but it felt that "also" in "Some plugins might also require an API token" means "in addition of ssh keys".
It seems you think a release tag and a GitHub release are the same but it's not the case. A tag is a Git object that can be read by any git client, a GitHub release does reference a Git tag but it is data specific to GitHub that a git client won't know about.

> I guess I don't know why you mention SSH at all. I don't see a situation where you wouldn't want to use the github plugin.

Because there is people who do not use GitHub. Some use GitLAb, Bitbucket or their own Git repo.

**Comment by pvdlg** [comment]
Closing as this was clarified in a recent doc update.
