### ISSUE TITLE
MODULE_NOT_FOUND with npm ci command

### ISSUE THREAD

**Issue by patoi** [semantic-release/semantic-release#1300]
## Current behavior

In package.json:
```
  "prerelease": "npm ci && npm test",
  "release": "semantic-release -d",
```

Running `npm run release`

I've got error in the first run:

```
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'validate-npm-package-name'
```

Second run result: success, there is no error.

Third run: I've got same error as in the first case.

Each successful run is followed by a faulty run.

## Expected behavior

No error.

## Environment

- **semantic-release** version: ^15.13.24
- CI environment: none (locally run)
- Plugins used: see plugins in config.
- **semantic-release** configuration:
```
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    ['@semantic-release/npm', {
      npmPublish: false
    }],
    '@semantic-release/git'
  ]
```
- CI logs: npm logs
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/xxx/.nvm/versions/node/v10.16.3/bin/node',
1 verbose cli   '/Users/xxx/work/projectname/node_modules/.bin/npm',
1 verbose cli   'ci' ]
2 info using npm@6.11.3
3 info using node@v10.16.3
4 info prepare initializing installer
5 verbose prepare starting workers
6 verbose prepare installation prefix: /Users/xxx/work/projectname
7 verbose prepare using package-lock.json
8 warn prepare removing existing node_modules/ before installation
9 verbose checkLock verifying package-lock data
10 verbose teardown shutting down workers.
11 info teardown Done in 0s
12 verbose stack Error: Cannot find module 'validate-npm-package-name'
12 verbose stack     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
12 verbose stack     at Function.Module._load (internal/modules/cjs/loader.js:562:25)
12 verbose stack     at Module.require (internal/modules/cjs/loader.js:692:17)
12 verbose stack     at require (internal/modules/cjs/helpers.js:25:18)
12 verbose stack     at Result.setName (/Users/xxx/work/projectname/node_modules/npm/node_modules/npm-package-arg/npa.js:118:51)
12 verbose stack     at new Result (/Users/xxx/work/projectname/node_modules/npm/node_modules/npm-package-arg/npa.js:111:23)
12 verbose stack     at Function.resolve (/Users/xxx/work/projectname/node_modules/npm/node_modules/npm-package-arg/npa.js:58:15)
12 verbose stack     at Object.keys.forEach.name (/Users/xxx/work/projectname/node_modules/npm/node_modules/lock-verify/index.js:26:26)
12 verbose stack     at Array.forEach (<anonymous>)
12 verbose stack     at Promise.all.then.result (/Users/xxx/work/projectname/node_modules/npm/node_modules/lock-verify/index.js:25:25)
13 verbose cwd /Users/xxx/work/projectname
14 verbose Darwin 18.7.0
15 verbose argv "/Users/xxx/.nvm/versions/node/v10.16.3/bin/node" "/Users/xxx/work/projectname/node_modules/.bin/npm" "ci"
16 verbose node v10.16.3
17 verbose npm  v6.11.3
18 error code MODULE_NOT_FOUND
19 error Cannot find module 'validate-npm-package-name'
20 verbose exit [ 1, true ]
```

**Comment by patoi** [comment]
With `npm install` there is no error. But `npm install` is not acceptable on CI server for autoreleasing.

**Comment by gr2m** [comment]
This is very odd, I've never run into that issue myself. Maybe open an issue on https://github.com/npm/validate-npm-package-name/issues? It's maintained by npm themselves, maybe they have an idea

**Comment by patoi** [comment]
Ok, thanks. I've created a reproduction code for it: https://github.com/patoi/reproduction-node-v10-module-not-found-error

It seems like there is a problem with Node.js v10.16.3 or npm and not with semantic-release.

**Comment by raray** [comment]
I am also seeing this with Node `10.20.1`
