### ISSUE TITLE
semantic-release misreports old builds as EGITNOPERMISSION

### ISSUE THREAD

**Issue by skeggse** [semantic-release/semantic-release#1342]
## Current behavior

We've got a fairly standard `semantic-release` setup, and started noticing that if we merge multiple PRs in quick succession or re-run an older build on our release branch that the build fails.

This isn't  a big problem as the latest commit will still succeed, and in some ways it's useful to have older builds fail (unless you want to release a fix and a feature, and still get the fix to publish under the previous minor version). It does, however, mean that our commit history looks somewhat poor and results in many issues being opened on the repo informing us that "The automated release is failing."

For example, if we have this commit sequence:

```
ce1b756 [tip]
561c792
fe34079
```

The `ce1b756` commit will not fail (and have nominal logs from `semantic-release`) no matter how many times we re-run it.

The `561c792` commit was pushed just moments before the `ce1b756` commit, and it initially failed with the `EGITNOPERMISSION` error. Attempts to re-run the build for this commit likewise fail, (have tried >3 times).

The `fe34079` commit initially succeeded (no push contention), but for diagnostic purposes we tried re-running it after the other two commits had initially failed/succeeded, and `fe34079` failed with the same `EGITNOPERMISSION`.

This would be less surprising if it were trying to do a dry-run push from `HEAD:master`, but instead the logs consistently show this:
```
[5:36:19 PM] [semantic-release] › ✖  The command "git ls-remote --heads origin master" failed with the error message remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/mixmaxhq/{redacted}.git/'
.
[5:36:19 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
```

## Expected behavior

Ideally we'd make a few things happen in response to this ticket:

- the `semantic-release` command would not fail in these circumstances, or would fail with a more informative error message
- if this is a limitation of `semantic-release`, we'd document the limitation somewhere
- if we need to fail in these circumstances, we wouldn't open issues on the repo

## Environment

- **semantic-release** version: 15.13.18
- CI environment: self-hosted Jenkins
- Plugins used: `@semantic-release/changelog`, `@semantic-release/git`
- **semantic-release** configuration:
```js
module.exports = {
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/github',
    '@semantic-release/npm',
    '@semantic-release/changelog',
    '@semantic-release/git',
  ],
};
```
- CI logs: see below

<details><summary>Sample of full `semantic-release` output</summary>

```
[5:36:17 PM] [semantic-release] › ℹ  Running semantic-release version 15.13.18
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[5:36:18 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[5:36:18 PM] [semantic-release] › ✔  Run automated release from branch master
[5:36:19 PM] [semantic-release] › ✖  The command "git ls-remote --heads origin master" failed with the error message remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/mixmaxhq/{redacted}.git/'
.
[5:36:19 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[5:36:19 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[5:36:21 PM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #148.
[5:36:22 PM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #148: https://github.com/mixmaxhq/{redacted}/issues/148#issuecomment-548487824.
[5:36:22 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[5:36:22 PM] [semantic-release] › ✖  EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch master on remote Git repository with URL https://[secure]:[secure]@github.com/mixmaxhq/{redacted}.git.

Please refer to the authentication configuration documentation (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) is configured with a valid Git URL (https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).

{ SemanticReleaseError: The push permission to the Git repository is required.
    at module.exports (/{redacted}/mixmaxhq_{redacted}_master/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/{redacted}/mixmaxhq_{redacted}_master/node_modules/semantic-release/index.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details:
   '**semantic-release** cannot push the version tag to the branch `master` on remote Git repository with URL `https://[secure]:[secure]@github.com/mixmaxhq/{redacted}.git`.\n\nPlease refer to the [authentication configuration documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) is configured with a [valid Git URL](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).',
  semanticRelease: true }npm ERR! code ELIFECYCLE
```
</details>

**Comment by gr2m** [comment]
Thanks for opening the issue @skeggse, I ran into this myself in the past when quickly merging multiple pull requests. I think the ideal outcome would be that semantic release realises that there are new commits since the CI build was triggered and just ends neutrally, with an explanation.

**Comment by skeggse** [comment]
Yeah, I think that'd be good behavior.

Any thoughts on the workflow where we merge a `fix` and then a `feature`, and would like the first to be included in a separate release - just in case folks are using the `~` version spec? I ran into this earlier, and would be rather bummed if I had to revert a PR in order to perform releases in the way I wanted. The behavior you're proposing is certainly better than the current behavior, to be fair!

**Comment by pvdlg** [comment]
> Thanks for opening the issue @skeggse, I ran into this myself in the past when quickly merging multiple pull requests. I think the ideal outcome would be that semantic release realises that there are new commits since the CI build was triggered and just ends neutrally, with an explanation.

So it's already supposed to work that way, see https://github.com/semantic-release/semantic-release/blob/9eaf9552c1f730caaa6eaffdc80c2d4b888bee2d/index.js#L68

Somehow in the situation described `isBranchUpToDate` returned `true` even though the local branch was not up to date with the remote one. I already tried to reproduce that but couldn't.
I'd appreciate any help in reproducing this issue so I could figure out a way to fix it.

**Comment by pvdlg** [comment]
What version of git are you using in your CI?

The only thing I can think of is that when [we get the remote](https://github.com/semantic-release/semantic-release/blob/9eaf9552c1f730caaa6eaffdc80c2d4b888bee2d/lib/git.js#L179) Git uses the value from `git/refs/remotes/origin/master` instead of making a call to the remote server.
However I tested with Git 2.23.0 and it ignores what's in `git/refs/remotes/origin/master` and retrieve the value of the remote head by making a network call to the remote repo...

**Comment by skeggse** [comment]
I am noticing that failures are only logged in debug (which I assume isn't default):

https://github.com/semantic-release/semantic-release/blob/9eaf9552c1f730caaa6eaffdc80c2d4b888bee2d/lib/git.js#L180-L184

Not sure what the consequence of that is, but I think the current CI setup may be checking out detached refs and only fetches a subset of refs from the remote - it's possible `git/refs/remotes/origin/master` doesn't exist.

I'll check the Git version tomorrow, and see if enabling the debug flag yields any further clues.

**Comment by pvdlg** [comment]
Yes it's only logged in debug. You can enable it with `--debug` option.
In order to get the head of the remote branch we use `git ls-remote` which (at least in the recent version of Git) ignore whatever you have in the local repo and makes a network call to the remote to get the head.
So you should always get the actual head of the remote no matter the state of the local clone.

**Comment by skeggse** [comment]
We're running Git `2.11.0` in CI.

More details from passing `--debug`:
```
[9:23:41 PM] [semantic-release] › ✔  Run automated release from branch master
2019-11-01T21:23:41.900Z semantic-release:git Error: Command failed: git push --dry-run git@github.com:mixmaxhq/{redacted}.git HEAD:master
error: cannot run ssh: No such file or directory
fatal: unable to fork


    at makeError (/{redacted}/mixmaxhq_{redacted}_master/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/{redacted}/mixmaxhq_{redacted}_master/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-11-01T21:23:42.329Z semantic-release:git Error: Command failed: git push --dry-run https://[secure]:[secure]@github.com/mixmaxhq/{redacted}.git HEAD:master
To https://github.com/mixmaxhq/{redacted}.git
 ! [rejected]        HEAD -> master (non-fast-forward)
error: failed to push some refs to 'https://[secure]:[secure]@github.com/mixmaxhq/{redacted}.git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.


    at makeError (/{redacted}/mixmaxhq_{redacted}_master/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/{redacted}/mixmaxhq_{redacted}_master/node_modules/execa/index.js:278:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[9:23:42 PM] [semantic-release] › ✖  The command "git ls-remote --heads origin master" failed with the error message remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/mixmaxhq/{redacted}.git/'
.
[9:23:42 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
```

So it mostly looks like we're reporting the wrong error.

Would it make sense to throw the caught error here?

https://github.com/semantic-release/semantic-release/blob/9eaf9552c1f730caaa6eaffdc80c2d4b888bee2d/lib/git.js#L180-L184

---

Separately - and I can open this as a separate issue - what would it take to remove this limitation? I maintain that re-running builds that are behind the tip of the release branch can be useful in some cases where you'd like to fix a bug and then add a feature.

**Comment by pvdlg** [comment]
So the problem is that in your particular setup running `git ls-remote` require authentication. It's usually not the case as the CI usually has read access to the repo. Not really how your CI manage to clone the repo....

It's fixed #1348 by using the authenticated URL to run `git ls-remote`

> Separately - and I can open this as a separate issue - what would it take to remove this limitation? I maintain that re-running builds that are behind the tip of the release branch can be useful in some cases where you'd like to fix a bug and then add a feature.

Again there is no issue to open as what you describe is the intended behavior

**Comment by skeggse** [comment]
Ah awesome, thank you!

**Comment by skeggse** [comment]
Can you clarify what you mean when you say this is intended behavior? Do you mean that the current behavior (if the checked out revision is behind the tip of the remote release branch, do nothing) is intended, or the behavior I described is the intended behavior?

**Comment by pvdlg** [comment]
The intended behavior is that when the head of the local branch is behind the remote one we just skip the release, log a message and don't error out. That should allow you to re-run builds that are behind the remote.

Maybe I misunderstood what you meant so I'm going to try to clarify.

We can't make releases if the local branch is behind as we want to give the opportunity to plugins (such `@semantic-release/git`) to make a commit associated with the release and push it (with an updated `package.json`, `CHANGELOG.md`, etc...). If we were to make a release when the local branch is behind the remote we wouldn't be able to push such commit.

semantic-release is opinionated and one of the main assumption we have is that every commit on a release branch can be released and should be released right away. As such, publishing a release that doesn't include all the commits currently on the remote is something that goes against this philosophy.

So if you end up in this local behind remote situation, then the release will be skipped, the build will not failed (anymore) and we expect a different CI job to be triggered by the commit currently at the tip of the remote and then the release will happen from there.
