### ISSUE TITLE
ENOPKG Missing `package.json` file.

### ISSUE THREAD

**Issue by paulpach** [semantic-release/semantic-release#1401]
## Current behavior

semantic-release calls npm plugin even if I remove it from plugins.

Per the [documentation](https://semantic-release.gitbook.io/semantic-release/usage/plugins#plugins), I override the plugins section in my config file and don't include semantic-release/npm

```yml
{
    "plugins": [
        ["@semantic-release/commit-analyzer", {
            "preset": "angular",
            "releaseRules": [
                {"type": "breaking", "release": "major"},
                {"type": "feature", "release": "minor"},
            ]
        }],
        '@semantic-release/release-notes-generator', 
        ["@semantic-release/github", {
            "assets": [
                {"path": "Mirror.unitypackage", "label": "Mirror.unitypackage"}
            ]
        }],
        ["@semantic-release/exec", {
            "prepareCmd": "echo ${nextRelease.version} > Assets/Mirror/version.txt",
        }],
    ]
}
```

I run semantic release and I get this:

```
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
...

[Semantic release]: ENOPKG Missing `package.json` file.
A package.json file (https://docs.npmjs.com/files/package.json) at the root of your project is required to release on npm.

Please follow the npm guideline (https://docs.npmjs.com/getting-started/creating-node-modules) to create a valid package.json file.


SemanticReleaseError: Missing `package.json` file.
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/get-pkg.js:17:19) {
  name: 'SemanticReleaseError',
  code: 'ENOPKG',
  details: 'A [package.json file](https://docs.npmjs.com/files/package.json) at the root of your project is required to release on npm.\n' +
    '\n' +
    'Please follow the [npm guideline](https://docs.npmjs.com/getting-started/creating-node-modules) to create a valid `package.json` file.',
  semanticRelease: true,
  pluginName: '@semantic-release/npm'
}
```

as you can see from the output,  it is ignoring my configuration and running verifyConditions, prepare and publish from @semantic-release/npm anyway,  which fails because this is not a node.js application

## Expected behavior

I expect my package to be released,  and not run any of the semantic-release/npm steps

Note this used to work about a month ago,  it stopped working in recent releases.

There does not appear to be a way to disable npm plugin anymore.
## Environment

- **semantic-release** version: 15.4.0
- CI environment: appveyor
- Plugins used: @semantic-release/commit-analyzer, '@semantic-release/release-notes-generator', @semantic-release/github, @semantic-release/exec
- **semantic-release** configuration: 
```yml
{
    "plugins": [
        ["@semantic-release/commit-analyzer", {
            "preset": "angular",
            "releaseRules": [
                {"type": "breaking", "release": "major"},
                {"type": "feature", "release": "minor"},
            ]
        }],
        '@semantic-release/release-notes-generator', 
        ["@semantic-release/github", {
            "assets": [
                {"path": "Mirror.unitypackage", "label": "Mirror.unitypackage"}
            ]
        }],
        ["@semantic-release/exec", {
            "prepareCmd": "echo ${nextRelease.version} > Assets/Mirror/version.txt",
        }],
    ]
}
```

- CI logs: 
```
semantic-release --no-ci --debug                                                             11:50:31
[Semantic release]: Running semantic-release version 15.4.0
  semantic-release:config options values: {
  semantic-release:config   branch: 'master',
  semantic-release:config   repositoryUrl: 'https://github.com/paulpach/Mirror.git',
  semantic-release:config   tagFormat: 'v${version}',
  semantic-release:config   plugins: [
  semantic-release:config     [ '@semantic-release/commit-analyzer', [Object] ],
  semantic-release:config     '@semantic-release/release-notes-generator',
  semantic-release:config     [ '@semantic-release/github', [Object] ],
  semantic-release:config     [ '@semantic-release/exec', [Object] ]
  semantic-release:config   ],
  semantic-release:config   _: [],
  semantic-release:config   ci: false,
  semantic-release:config   debug: true,
  semantic-release:config   '$0': '/usr/local/bin/semantic-release',
  semantic-release:config   noCi: true
  semantic-release:config } +0ms
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify GitHub authentication
[before-after-hook]: "Hook()" repurposing warning, use "Hook.Collection()". Read more: https://git.io/upgrade-before-after-hook-to-1.4
[Semantic release]: Found existing semantic-release issue #8.
  semantic-release:github create comment: {
  semantic-release:github   owner: 'paulpach',
  semantic-release:github   repo: 'Mirror',
  semantic-release:github   number: 8,
  semantic-release:github   body: '## :rotating_light: The automated release from the `master` branch failed. :rotating_light:\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'I recommend you give this issue a high priority, so other packages depending on you could benefit from your bug fixes and new features.\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'You can find below the list of errors reported by **semantic-release**. Each one of them has to be resolved in order to automatically publish your package. I’m sure you can resolve this 💪.\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'Errors are usually caused by a misconfiguration or an authentication problem. With each error reported below you will find explanation and guidance to help you to resolve it.\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'Once all the errors are resolved, **semantic-release** will release your package the next time you push a commit to the `master` branch. You can also manually restart the failed CI job that runs **semantic-release**.\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'If you are not sure how to resolve this, here is some links that can help you:\n' +
  semantic-release:github     '- [Usage documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/README.md)\n' +
  semantic-release:github     '- [Frequently Asked Questions](https://github.com/semantic-release/semantic-release/blob/caribou/docs/support/FAQ.md)\n' +
  semantic-release:github     '- [Support channels](https://github.com/semantic-release/semantic-release#get-help)\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'If those don’t help, or if this issue is reporting something you think isn’t right, you can always ask the humans behind **[semantic-release](https://github.com/semantic-release/semantic-release/issues/new)**.\n' +
  semantic-release:github     '\n' +
  semantic-release:github     '---\n' +
  semantic-release:github     '\n' +
  semantic-release:github     '### Missing `package.json` file.\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'A [package.json file](https://docs.npmjs.com/files/package.json) at the root of your project is required to release on npm.\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'Please follow the [npm guideline](https://docs.npmjs.com/getting-started/creating-node-modules) to create a valid `package.json` file.\n' +
  semantic-release:github     '\n' +
  semantic-release:github     '---\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'Good luck with your project ✨\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:'
  semantic-release:github } +0ms
[Semantic release]: Added comment to issue #8: https://github.com/paulpach/Mirror/issues/8#issuecomment-568919568.
[Semantic release]: ENOPKG Missing `package.json` file.
A package.json file (https://docs.npmjs.com/files/package.json) at the root of your project is required to release on npm.

Please follow the npm guideline (https://docs.npmjs.com/getting-started/creating-node-modules) to create a valid package.json file.


SemanticReleaseError: Missing `package.json` file.
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/get-pkg.js:17:19) {
  name: 'SemanticReleaseError',
  code: 'ENOPKG',
  details: 'A [package.json file](https://docs.npmjs.com/files/package.json) at the root of your project is required to release on npm.\n' +
    '\n' +
    'Please follow the [npm guideline](https://docs.npmjs.com/getting-started/creating-node-modules) to create a valid `package.json` file.',
  semanticRelease: true,
  pluginName: '@semantic-release/npm'
}
```

**Comment by pvdlg** [comment]
Please upgrade to version `15.14.0`. `15.4.0` doesn't support the `plugins` option.
