### ISSUE TITLE
[Question] Configuration for non NPM package with gitlab

### ISSUE THREAD

**Issue by emirot** [semantic-release/semantic-release#1402]
## New feature motivation

I would like to add a recipe for non node project.
Right now, it's only for node project : https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/gitlab-ci.md

## New feature description

Add in this page https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/gitlab-ci.md for non node projects.

I wanted to use https://dev.to/aesadde/automated-semantic-versions-for-all-projects-with-semantic-release-and-gitlab-ci-4045 but I'm getting :

```
[10:38:27 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 271 commits complete: patch release
[10:38:27 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:38:27 AM] [semantic-release] › ℹ  There is no previous release, the next release version is 1.0.0
[10:38:27 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:38:28 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:38:28 AM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[10:38:28 AM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/npm"
[10:38:28 AM] [semantic-release] › ✖  ENOPKG Missing `package.json` file.
A package.json file (https://docs.npmjs.com/files/package.json) at the root of your project is required to release on npm.

Please follow the npm guideline (https://docs.npmjs.com/getting-started/creating-node-modules) to create a valid package.json file.

AggregateError: 
    SemanticReleaseError: Missing `package.json` file.
        at module.exports (/usr/local/lib/node_modules/@semantic-release/gitlab-config/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/usr/local/lib/node_modules/@semantic-release/gitlab-config/node_modules/@semantic-release/npm/lib/get-pkg.js:17:33)
    at prepare (/usr/local/lib/node_modules/@semantic-release/gitlab-config/node_modules/@semantic-release/npm/index.js:64:11) {
  name: 'AggregateError'
}
ERROR: Job failed: exit code 1
```

**Comment by pvdlg** [comment]
See https://github.com/semantic-release/semantic-release/blob/master/docs/support/FAQ.md#can-i-use-semantic-release-to-publish-non-javascript-packages
In particular:
> In addition you will need to configure the semantic-release plugins to disable the @semantic-release/npm plugin which is used by default and use a plugin for your project type.
