### ISSUE TITLE
Repository URL forced to be HTTPS

### ISSUE THREAD

**Issue by AndrewLeedham** [semantic-release/semantic-release#1454]
## Current behavior

Running `semantic-release@17` inside Circle Ci with SSH GitHub authentication is failing with:
```
yarn run v1.21.1
$ /home/circleci/repo/node_modules/.bin/semantic-release
[1:57:47 AM] [semantic-release] › ℹ  Running semantic-release-plus version 17.0.2
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-slack-bot"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "success" from "semantic-release-slack-bot"
[1:57:47 AM] [semantic-release] › ✔  Loaded plugin "fail" from "semantic-release-slack-bot"
[1:57:48 AM] [semantic-release] › ✔  Run automated release from branch master
[1:57:48 AM] [semantic-release] › ✖  The command "git push --dry-run https://[secure]@github.com/xeroxinteractive/config.git HEAD:master" failed with the error message remote: Permission to xeroxinteractive/config.git denied to xeroxinteractive-builder.
fatal: unable to access 'https://[secure]@github.com/xeroxinteractive/config.git/': The requested URL returned error: 403.
[1:57:48 AM] [semantic-release] › ℹ  Start step "fail" of plugin "semantic-release-slack-bot"
[1:57:48 AM] [semantic-release] [semantic-release-slack-bot] › ℹ  Notifying on fail skipped
[1:57:48 AM] [semantic-release] › ✔  Completed step "fail" of plugin "semantic-release-slack-bot"
[1:57:48 AM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch master on the remote Git repository with URL https://[secure]@github.com/xeroxinteractive/config.git.

This can be caused by:

    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release-plus/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release-plus/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)

SemanticReleaseError: Cannot push to the Git repository.
    at module.exports (/home/circleci/repo/node_modules/semantic-release-plus/lib/get-error.js:6:10)
    at run (/home/circleci/repo/node_modules/semantic-release-plus/index.js:87:11)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
    at async module.exports (/home/circleci/repo/node_modules/semantic-release-plus/index.js:257:22)
    at async module.exports (/home/circleci/repo/node_modules/semantic-release-plus/cli.js:55:5) {
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master` on the remote Git repository with URL `https://[secure]@github.com/xeroxinteractive/config.git`.\n' +
    '\n' +
    'This can be caused by:\n' +
    ' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release-plus/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
    ' - the repository being unavailable\n' +
    ' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release-plus/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
```

It seems to be trying with HTTPS (`https://[secure]@github.com/xeroxinteractive/config.git`) when I would expect it to initially just directly try the repository field seen in my package.json (`git@github.com:xeroxinteractive/config.git`)

I tried SSH-ing into the CircleCI environment and found that running `git push --dry-run ssh://git@github.com/xeroxinteractive/config.git HEAD:master` or `git push --dry-run git@github.com:xeroxinteractive/config.git HEAD:master` works fine but `git push --dry-run https://git@github.com/xeroxinteractive/config.git HEAD:master` does not.

Looking at the source code https://github.com/semantic-release/semantic-release/blob/0785a844fa8ac1320383452ce531898be3b01f92/lib/get-git-auth-url.js#L35 seems to convert the URL to HTTPS, which I think is the root cause of the problem.

## Expected behavior

Push to work via SSH.

## Environment

- **semantic-release** version: 17.0.1
- CI environment: Circle CI
- Plugins used: semantic-release-slack-bot
- **semantic-release** configuration: https://github.com/xeroxinteractive/config/blob/master/release.config.js
- CI logs: https://circleci.com/gh/xeroxinteractive/config/399

**Comment by pvdlg** [comment]
semantic-release will try to use the URL you configure in your `package.json` first and if it fails it will try to use the HTTPS version with your credentials.

So it seems when semantic-release runs `git push --dry-run git@github.com:xeroxinteractive/config.git HEAD:master` it fails and therefore try with `git push --dry-run https://git@github.com/xeroxinteractive/config.git HEAD:master`.

Not sure why `git push --dry-run git@github.com:xeroxinteractive/config.git HEAD:master` works in your tests though. Probably when you ssh in your machine the environment is slightly different that when ssemantic-release runs.

You can get more info about what happens when semantic-release attempts  `git push --dry-run git@github.com:xeroxinteractive/config.git HEAD:master` by using the `--debug` option

**Comment by AndrewLeedham** [comment]
> semantic-release will try to use the URL you configure in your `package.json` first and if it fails it will try to use the HTTPS version with your credentials.
> 
> So it seems when semantic-release runs `git push --dry-run git@github.com:xeroxinteractive/config.git HEAD:master` it fails and therefore try with `git push --dry-run https://git@github.com/xeroxinteractive/config.git HEAD:master`.
> 
> Not sure why `git push --dry-run git@github.com:xeroxinteractive/config.git HEAD:master` works in your tests though. Probably when you ssh in your machine the environment is slightly different that when ssemantic-release runs.
> 
> You can get more info about what happens when semantic-release attempts `git push --dry-run git@github.com:xeroxinteractive/config.git HEAD:master` by using the `--debug` option

I ran it with `--debug` and it seems it is trying https first and failing straight away. See: https://circleci.com/gh/xeroxinteractive/config/405

**Comment by pvdlg** [comment]
That should be fixed, however it seems you are using a fork, so you'll have to get this merged to the fork.

**Comment by AndrewLeedham** [comment]
Thanks for the quick fix 🚀 . I will give it a test once the fork has been updated.

**Comment by AndrewLeedham** [comment]
> That should be fixed, however it seems you are using a fork, so you'll have to get this merged to the fork.

Fork was updated and everything is working, thanks! 🎉
