### ISSUE TITLE
error relating to `This test run was triggered on the branch` ... Even though I do have it set as a release branch?

### ISSUE THREAD

**Issue by chrissound** [semantic-release/semantic-release#1486]
## Environment

- **semantic-release** version: 
```
"semantic-release": "^15.14.0",
```
-
- CI environment: docker container
- Plugins used: 
```
    "@semantic-release/git": "^9.0.0",
    "@semantic-release/gitlab": "^6.0.2",
```
- **semantic-release** configuration: 
```
...
  "release": {
    "branches": ["master", "chris-dev-cicd"],
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/npm",
        {
          "npmPublish": true,
          "tarballDir": "dist"
        }
      ],
      "@semantic-release/gitlab"
    ]
  }
...
```
 CI logs: 
```
root@737ce5e924de:/build# npx semantic-release --branches chris-dev-cicd
[9:17:51 PM] [semantic-release] › ℹ  Running semantic-release version 15.14.0
[9:17:51 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[9:17:51 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[9:17:51 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:17:51 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[9:17:51 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[9:17:51 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[9:17:51 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[9:17:51 PM] [semantic-release] › ⚠  This run was not triggered in a known CI environment, running in dry-run mode.
[9:17:51 PM] [semantic-release] › ℹ  This test run was triggered on the branch chris-dev-cicd, while semantic-release is configured to only publish from master, therefore a new version won’t be published.
root@737ce5e924de:/build# echo $?
0
```

**Comment by malekjaroslav** [comment]
I experience the same issue

**Comment by chrissound** [comment]
@malekjaroslav are you running this on a branch that is *not* `master`? Just trying to narrow this error down.

**Comment by malekjaroslav** [comment]
Yes, I run it on branch "dev"

**Comment by chrissound** [comment]
Here it is with debug info (`--debug`):
```
104 2020-03-17T12:38:09.992Z semantic-release:config load config from: /builds/xxxxxxxxxxxxxxxpackage.json
105 2020-03-17T12:38:10.014Z semantic-release:config options values: {
106   branch: 'master',
107   repositoryUrl: 'https://gitlab-ci-token:[secure]@gitlab.xxxxxxxxxxxxxxxx.git',
108   tagFormat: 'v${version}',
109   plugins: [
110     '@semantic-release/commit-analyzer',
111     '@semantic-release/release-notes-generator',
112     [ '@semantic-release/npm', [Object] ],
113     '@semantic-release/gitlab'
114   ],
115   branches: [ 'master', 'chris-dev-cicd' ],
116   _: [],
117   debug: true,
118   '$0': 'node_modules/.bin/semantic-release'
119 }
120 [12:38:10 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
121 2020-03-17T12:38:10.426Z semantic-release:plugins options for @semantic-release/npm/verifyConditions: { npmPublish: true, tarballDir: 'dist' }
122 2020-03-17T12:38:10.429Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: {}
123 [12:38:10 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
124 [12:38:10 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
125 2020-03-17T12:38:10.433Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
126 2020-03-17T12:38:10.435Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
127 2020-03-17T12:38:10.438Z semantic-release:plugins options for @semantic-release/npm/prepare: { npmPublish: true, tarballDir: 'dist' }
128 [12:38:10 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
129 [12:38:10 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
130 [12:38:10 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
131 2020-03-17T12:38:10.440Z semantic-release:plugins options for @semantic-release/npm/publish: { npmPublish: true, tarballDir: 'dist' }
132 2020-03-17T12:38:10.442Z semantic-release:plugins options for @semantic-release/gitlab/publish: {}
133 [12:38:10 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
134 [12:38:10 PM] [semantic-release] › ℹ  This test run was triggered on the branch chris-dev-cicd, while semantic-release is configured to only publish from master, therefore a new version won’t be published.
```

**Comment by chrissound** [comment]
The configuration value `branches`  seems to only be a new addition after v15.14...

As it is not documented here: https://github.com/semantic-release/semantic-release/issues/1486

@malekjaroslav  maybe you're on a older version too?

**Comment by pvdlg** [comment]
The `--branches` option exist only on semantic-release version > 16.

The branches you configure in semantic-release need to exists on the remote repo.

**Comment by abhiamnyuMt** [comment]
I am facing a similar issue, I am running this on merge-request gitlab-pipeline
command: ` semantic-release --dry-run --no-ci --branches validate-pr --debug` 

Semantic release object:
```
{ branches: [ 'validate-pr' ],
   repositoryUrl: 'git@gitlab.com:call-ai/sample-service.git',
   tagFormat: 'v${version}',
   plugins:
    [ [ '@semantic-release/commit-analyzer', [Object] ],
      [ '@semantic-release/exec', [Object] ],
      [ '@semantic-release/exec', [Object] ] ],
   _: [],
   'dry-run': true,
   d: true,
   dryRun: true,
   ci: false,
   b: [ 'validate-pr' ],
   debug: true,
   '$0': 'semantic-release',
   noCi: true }
```

Error message: ` This test run was triggered on the branch master, while semantic-release is configured to only publish from validate-pr, therefore a new version won’t be published`

**Comment by MingboPeng** [comment]
It seems when using `no-ci`, it doesn't understand the current branch correctly:
I checked current branch to be 'master' before running `npx semantic-release --ci false --debug --branches 'master' `
```
git checkout master
Already on 'master'

git branch -a
master
  cvsimport
* master
  remotes/origin/cvsimport
  remotes/origin/master
  remotes/origin/master-mirror
```

I always get   **`This test run was triggered on the branch cvsimport, while semantic-release is configured to only publish from master,`**

```
2020-06-28T15:05:55.8106346Z [3:05:55 PM] [semantic-release] › ℹ  Running semantic-release version 17.1.1
2020-06-28T15:05:55.8305111Z 2020-06-28T15:05:55.829Z semantic-release:config load config from: undefined
2020-06-28T15:05:55.8427794Z 2020-06-28T15:05:55.842Z semantic-release:config options values: {
2020-06-28T15:05:55.8428947Z   branches: [ 'master' ],
2020-06-28T15:05:55.8429551Z   repositoryUrl: 'https://github.com/MingboPeng/Radiance',
2020-06-28T15:05:55.8430057Z   tagFormat: 'v${version}',
2020-06-28T15:05:55.8430496Z   plugins: [
2020-06-28T15:05:55.8431008Z     '@semantic-release/commit-analyzer',
2020-06-28T15:05:55.8431514Z     '@semantic-release/release-notes-generator',
2020-06-28T15:05:55.8431985Z     '@semantic-release/npm',
2020-06-28T15:05:55.8432446Z     '@semantic-release/github'
2020-06-28T15:05:55.8432766Z   ],
2020-06-28T15:05:55.8436749Z   _: [],
2020-06-28T15:05:55.8436881Z   ci: false,
2020-06-28T15:05:55.8437006Z   debug: true,
2020-06-28T15:05:55.8437316Z   b: [ 'master' ],
2020-06-28T15:05:55.8437613Z   '$0': '../../../.npm/_npx/3143/bin/semantic-release',
2020-06-28T15:05:55.8437752Z   noCi: true
2020-06-28T15:05:55.8437875Z }
2020-06-28T15:05:56.0377428Z 2020-06-28T15:05:56.037Z semantic-release:plugins options for @semantic-release/npm/verifyConditions: {}
2020-06-28T15:05:56.0383776Z [3:05:56 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
2020-06-28T15:05:56.0385918Z 2020-06-28T15:05:56.038Z semantic-release:plugins options for @semantic-release/github/verifyConditions: {}
2020-06-28T15:05:56.0388210Z [3:05:56 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
2020-06-28T15:05:56.0390111Z 2020-06-28T15:05:56.038Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
2020-06-28T15:05:56.0391432Z [3:05:56 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2020-06-28T15:05:56.0394047Z 2020-06-28T15:05:56.039Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
2020-06-28T15:05:56.0395884Z [3:05:56 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2020-06-28T15:05:56.0397524Z 2020-06-28T15:05:56.039Z semantic-release:plugins options for @semantic-release/npm/prepare: {}
2020-06-28T15:05:56.0398690Z [3:05:56 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
2020-06-28T15:05:56.0400458Z 2020-06-28T15:05:56.039Z semantic-release:plugins options for @semantic-release/npm/publish: {}
2020-06-28T15:05:56.0401541Z [3:05:56 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
2020-06-28T15:05:56.0403142Z 2020-06-28T15:05:56.040Z semantic-release:plugins options for @semantic-release/github/publish: {}
2020-06-28T15:05:56.0403841Z [3:05:56 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
2020-06-28T15:05:56.0404962Z 2020-06-28T15:05:56.040Z semantic-release:plugins options for @semantic-release/npm/addChannel: {}
2020-06-28T15:05:56.0406229Z [3:05:56 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
2020-06-28T15:05:56.0407214Z 2020-06-28T15:05:56.040Z semantic-release:plugins options for @semantic-release/github/addChannel: {}
2020-06-28T15:05:56.0408711Z [3:05:56 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
2020-06-28T15:05:56.0409739Z 2020-06-28T15:05:56.040Z semantic-release:plugins options for @semantic-release/github/success: {}
2020-06-28T15:05:56.0410823Z [3:05:56 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
2020-06-28T15:05:56.0412283Z 2020-06-28T15:05:56.041Z semantic-release:plugins options for @semantic-release/github/fail: {}
2020-06-28T15:05:56.0413144Z [3:05:56 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
2020-06-28T15:05:56.6217683Z 2020-06-28T15:05:56.438Z semantic-release:git Error: Command failed with exit code 1: git push --dry-run --no-verify https://github.com/MingboPeng/Radiance HEAD:cvsimport
2020-06-28T15:05:56.6230431Z To https://github.com/MingboPeng/Radiance
2020-06-28T15:05:56.6231682Z  ! [rejected]          HEAD -> cvsimport (non-fast-forward)
2020-06-28T15:05:56.6232581Z error: failed to push some refs to 'https://github.com/MingboPeng/Radiance'
2020-06-28T15:05:56.6233614Z hint: Updates were rejected because a pushed branch tip is behind its remote
2020-06-28T15:05:56.6234226Z hint: counterpart. Check out this branch and integrate the remote changes
2020-06-28T15:05:56.6235036Z hint: (e.g. 'git pull ...') before pushing again.
2020-06-28T15:05:56.6235839Z hint: See the 'Note about fast-forwards' in 'git push --help' for details.
2020-06-28T15:05:56.6236766Z     at makeError (/home/runner/.npm/_npx/3143/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:59:11)
2020-06-28T15:05:56.6237740Z     at handlePromise (/home/runner/.npm/_npx/3143/lib/node_modules/semantic-release/node_modules/execa/index.js:114:26)
2020-06-28T15:05:56.6238266Z     at processTicksAndRejections (internal/process/task_queues.js:97:5)
2020-06-28T15:05:56.6239138Z     at async verifyAuth (/home/runner/.npm/_npx/3143/lib/node_modules/semantic-release/lib/git.js:207:5)
2020-06-28T15:05:56.6240077Z     at async module.exports (/home/runner/.npm/_npx/3143/lib/node_modules/semantic-release/lib/get-git-auth-url.js:45:5)
2020-06-28T15:05:56.6241279Z     at async run (/home/runner/.npm/_npx/3143/lib/node_modules/semantic-release/index.js:56:27)
2020-06-28T15:05:56.6242252Z     at async module.exports (/home/runner/.npm/_npx/3143/lib/node_modules/semantic-release/index.js:260:22)
2020-06-28T15:05:56.6243144Z     at async module.exports (/home/runner/.npm/_npx/3143/lib/node_modules/semantic-release/cli.js:55:5)
2020-06-28T15:05:56.9482030Z 2020-06-28T15:05:56.947Z semantic-release:get-tags found tags for branch master: [ { gitTag: 'v5.2.4', version: '5.2.4', channels: [ null ] }, { gitTag: 'v5.3.0', version: '5.3.0', channels: [ null ] } ]
2020-06-28T15:05:56.9542521Z [3:05:56 PM] [semantic-release] › ℹ  This test run was triggered on the branch cvsimport, while semantic-release is configured to only publish from master, therefore a new version won’t be published.
```

**Comment by wojtek-krysiak** [comment]
had the same issue, but in my case, I had a wrong `repository` property set i `package.json`. Correcting it solved that.

**Comment by zioalex** [comment]
As documented here, https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches, the branch you want to push should be already there or you will get the error `ERELEASEBRANCHES `.

After this it works for me.

**Comment by flowck** [comment]
I am facing the same issue:

- semantic-release: 17.4.7
- Repository manually checked out to: main
- Running semantic-release locally works perfectly

```
Run git checkout main
Already on 'main'
M	package-lock.json
Your branch is up to date with 'origin/main'.

...

2021-09-20T15:47:39.977Z semantic-release:get-tags found tags for branch main: [ { gitTag: 'v1.0.0', version: '1.0.0', channels: [ null ] } ]
[3:47:39 PM] [semantic-release] › ℹ  This test run was triggered on the branch develop, while semantic-release is configured to only publish from main, therefore a new version won’t be published.
```

Does anybody have any idea on how to tackle this issue?

**Comment by zioalex** [comment]
> Does anybody have any idea on how to tackle this issue?
@flowck  it is not clear where you are running the tool. From what I can see it says `triggered on the branch develop`. This is the reason of the missed version.

**Comment by mlozanno** [comment]
I have the same issue, but my problem is the 'origin' prefix:
`This test run was triggered on the branch origin/beta, while semantic-release is configured to only publish from master, next, homolog, beta, therefore a new version won’t be published.`

**Comment by josephvano** [comment]
I ran into this myself but it was an issue with the name of my configuration file. Ensure that your configuration is being loaded properly. Look at the beginning of the logs during execution and see what config values are being loaded.

Seeing **undefined** is a sign of incorrect config filename or mis-configuration.

Run with `DEBUG=semantic-release*` to get debug output
>DEBUG=semantic-release* npx semantic-release
>[5:50:26 PM] [semantic-release] › ℹ  Running semantic-release version 18.0.0
>2021-11-18T17:50:26.401Z semantic-release:config load config from: undefined
>2021-11-18T17:50:26.415Z semantic-release:config options values: {


HTH

**Comment by damdafayton** [comment]
mine is fixed when i published the branch
