### ISSUE TITLE
Allow only generating the changelog

### ISSUE THREAD

**Issue by charlax** [semantic-release/semantic-release#1491]
## New feature motivation

Here's the use case: I'm on my feature branch, and I'd like to see how the changelog looks like. I've tried using `--dry-run`, but it fails because I'm not on one of my release-ready branches:

```bash
% ./node_modules/.bin/semantic-release --dry-run --no-verify
[output removed for brevity]
[9:18:20 AM] [semantic-release] › ℹ  This test run was triggered on the branch my-awesome-new-feature, while semantic-release is configured to only publish from master, alpha, therefore a new version won’t be published.
```

I guess I could use a `branch` argument, but I couldn't find the proper way to allow all branches:

```bash
% ./node_modules/.bin/semantic-release --dry-run --no-verify --branches '.*'
[9:23:40 AM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration.

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].

AggregateError:
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/code/node_modules/semantic-release/lib/get-error.js:6:10)
        at /code/node_modules/semantic-release/lib/branches/index.js:44:19
        at Array.reduce (<anonymous>)
        at module.exports (/code/node_modules/semantic-release/lib/branches/index.js:34:46)
        at async run (/code/node_modules/semantic-release/index.js:56:22)
        at async module.exports (/code/node_modules/semantic-release/index.js:257:22)
        at async module.exports (/code/node_modules/semantic-release/cli.js:55:5)
    at module.exports (/code/node_modules/semantic-release/lib/branches/index.js:66:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/code/node_modules/semantic-release/index.js:56:22)
    at async module.exports (/code/node_modules/semantic-release/index.js:257:22)
    at async module.exports (/code/node_modules/semantic-release/cli.js:55:5) {
  name: 'AggregateError'
}

% ./node_modules/.bin/semantic-release --dry-run --no-verify --branches '[".*"]'
# same error

% ./node_modules/.bin/semantic-release --dry-run --no-verify --branches '["master", ".*"]'
# same error

% ./node_modules/.bin/semantic-release --dry-run --no-verify --branches $(git rev-parse --abbrev-ref HEAD)
# same error

% ./node_modules/.bin/semantic-release --dry-run --no-verify --branches '.*, master'
ℹ  This test run was triggered on the branch my-awesome-new-feature, while semantic-release is configured to only publish from master, therefore a new version won’t be published.
```

`semantic-release` is quite opinionated so I'd like to see the generated changelog...

## New feature description

Either properly document the format the `--branches` option should take on the cli, or add some simple way to display the changelog...

**Comment by amejiarosario** [comment]
I'm having the same issue. I want to preview the changelog!

**Comment by sanghin** [comment]
You can do that (i'm using `^17.1.1`), 1st you have to push your branch on the remote repository and then you use this command

For readability i will replace `./node_modules/.bin/semantic-release` with `yarn release` if you don't mind :)

```yarn release --dry-run --no-ci --branches 'feat/my-branch'``` 

To add multiple branch use a comma `--branches 'master,branch,branch2'`
