### ISSUE TITLE
Cannot read property 'objectMode' of undefined

### ISSUE THREAD

**Issue by thebrodmann** [semantic-release/semantic-release#1495]
## Current behavior

During the publishing of a patch on a maintenance branch throws the following error:

```bash
npm ERR! Cannot read property 'objectMode' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-03-16T17_07_09_914Z-debug.log
[5:07:09 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[5:07:09 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[5:07:09 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[5:07:09 PM] [semantic-release] › ✖  EINVALIDNPMTOKEN Invalid npm token.
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry https://registry.npmjs.org/.

If you are using Two-Factor Authentication, make configure the auth-only level (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) is supported. semantic-release cannot publish with the default auth-and-writes level.

Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.
```

I double-checked `NPM_TOKEN` and it's valid.

## Expected behavior

Publish patch on the maintenance branch without any issue.

## Environment

- **semantic-release** version: 16.0.4
- CI environment: CircleCI 
- Plugins used: 
  - @semantic-release/commit-analyzer
  - @semantic-release/release-notes-generator
  - @semantic-release/changelog
  - @semantic-release/npm
  - @semantic-release/git
- **semantic-release** configuration: 
- CI logs: 

```bash
[5:07:07 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.4
[5:07:07 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[5:07:07 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[5:07:07 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[5:07:07 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[5:07:07 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[5:07:07 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[5:07:07 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[5:07:07 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[5:07:07 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[5:07:07 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[5:07:08 PM] [semantic-release] › ✔  Run automated release from branch 2.1.x
[5:07:09 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[5:07:09 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[5:07:09 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[5:07:09 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[5:07:09 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[5:07:09 PM] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /tmp/3f3331b3e402f8c48cad8ef5eb15fd4e/.npmrc
npm ERR! Cannot read property 'objectMode' of undefined

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/circleci/.npm/_logs/2020-03-16T17_07_09_914Z-debug.log
[5:07:09 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[5:07:09 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[5:07:09 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[5:07:09 PM] [semantic-release] › ✖  EINVALIDNPMTOKEN Invalid npm token.
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry https://registry.npmjs.org/.

If you are using Two-Factor Authentication, make configure the auth-only level (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) is supported. semantic-release cannot publish with the default auth-and-writes level.

Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.

{ AggregateError: 
    SemanticReleaseError: Invalid npm token.
        at module.exports (/home/circleci/repo/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/home/circleci/repo/node_modules/@semantic-release/npm/lib/verify-auth.js:26:33)
    at /home/circleci/repo/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at process.internalTickCallback (internal/process/next_tick.js:77:7) name: 'AggregateError' }

Exited with code exit status 1

CircleCI received exit code 1
```

**Comment by pvdlg** [comment]
Please verify the compatibility of the plugins you are using with the version of semantic-release.
You should have warning messages during `npm install` that tell which plugin is not compatible.

**Comment by thebrodmann** [comment]
I don't see any warning about semantic-release.

```bash
npm WARN deprecated rollup-plugin-node-resolve@5.2.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-node-resolve.
npm WARN deprecated rollup-plugin-commonjs@10.1.0: This package has been deprecated and is no longer maintained. Please use @rollup/plugin-commonjs.
npm WARN deprecated redux-starter-kit@0.5.1: Redux Starter Kit has been renamed to Redux Toolkit. Please switch from `redux-starter-kit` to `@reduxjs/toolkit` to migrate
npm WARN deprecated mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated core-js@1.2.7: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated @types/vfile-message@2.0.0: This is a stub types definition. vfile-message provides its own type definitions, so you do not need this installed.
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()

> fsevents@1.2.12 install /Users/thebrodmann/Projects/github/thebrodmann/deox/node_modules/fsevents
> node-gyp rebuild

No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:351:16)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/thebrodmann/Projects/github/thebrodmann/deox/node_modules/fsevents
gyp ERR! node -v v12.14.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 

> husky@2.7.0 install /Users/thebrodmann/Projects/github/thebrodmann/deox/node_modules/husky
> node husky install
```

**Comment by pvdlg** [comment]
Can you provide the version of semantic-release and each plugin you are using?

**Comment by thebrodmann** [comment]
```bash
├─┬ @semantic-release/changelog@3.0.6
│ ├── @semantic-release/error@2.2.0
├─┬ @semantic-release/commit-analyzer@7.0.0
├─┬ @semantic-release/git@7.1.0-beta.11
│ ├── @semantic-release/error@2.2.0 deduped
├─┬ @semantic-release/github@5.6.0-beta.7
│ ├── @semantic-release/error@2.2.0 deduped
├─┬ @semantic-release/npm@6.0.0
│ ├── @semantic-release/error@2.2.0 deduped
npm├─┬ @semantic-release/release-notes-generator@7.3.5
 ERR! peer dep missing: jest@>=25 <26, required by ts-jest@25.2.1
npm ERR! peer dep missing: @types/react@^15.0.0 || ^16.0.0, required by react-hot-loader@4.12.20
npm ERR! peer dep missing: marked@^0.4.0 || ^0.5.0 || ^0.6.0 || ^0.7.0, required by marked-terminal@3.3.0
├─┬ semantic-release@16.0.4
│ ├── @semantic-release/commit-analyzer@7.0.0 deduped
│ ├── @semantic-release/error@2.2.0 deduped
│ ├─┬ @semantic-release/github@6.0.2
│ │ ├── @semantic-release/error@2.2.0 deduped
│ ├── @semantic-release/npm@6.0.0 deduped
│ ├── @semantic-release/release-notes-generator@7.3.5 deduped
```

**Comment by evansiroky** [comment]
I'm having this issue too.

- **semantic-release** version: 17.0.8
- CI environment: Travis-CI.
- Plugins used: default
- **semantic-release** configuration: default
- CI logs: see failing build [here](https://travis-ci.org/github/conveyal/mastarm/jobs/697814352#L377)
