### ISSUE TITLE
semantic-release not incrementing versions

### ISSUE THREAD

**Issue by amclin** [semantic-release/semantic-release#1502]
## Current behavior
`semantic-release` keeps trying to to recreate the same version number over and over, which causes the release to fail. It is correctly identifying that a new version is necessary, but isn't incrementing the version number. `v1.1.2` exists as a [git tag](https://github.com/amclin/aem-packager/tags), and as a [github release](https://github.com/amclin/aem-packager/releases/tag/v1.1.2), and is specified in the [package.json](https://github.com/amclin/aem-packager/blob/master/package.json#L3)

But every time semantic-release runs,  it tries to create the new version as `v1.1.2`, which fails because that tag already exists.

## Expected behavior
`semantic-release` increments version number and tries to tag `v1.1.3` or `v1.2.0`

## Environment

- **semantic-release** version: `^17.0.2`
- CI environment: Travis 
- Plugins used:
  * `@semantic-release/changelog`: `^5.0.0`,
  * `@semantic-release/git`: `^9.0.0`,
  * `@semantic-release/github`: `^7.0.0`,
  * `@semantic-release/npm`: `^7.0.0`,
- **semantic-release** configuration: https://github.com/amclin/aem-packager/blob/master/.releaserc
- CI logs: https://travis-ci.com/github/amclin/aem-packager/jobs/301903734

### Error from log:
```
[4:37:18 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 276 commits complete: patch release
[4:37:18 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[4:37:18 PM] [semantic-release] › ℹ  The next release version is 1.1.2
[4:37:18 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[4:37:19 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[4:37:19 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[4:37:19 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Update /home/travis/build/amclin/aem-packager/CHANGELOG.md
[4:37:19 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[4:37:19 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[4:37:19 PM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 1.1.2 to package.json in /home/travis/build/amclin/aem-packager
v1.1.2
[4:37:20 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[4:37:20 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[4:37:21 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 1 file(s) to commit
[4:37:24 PM] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: v1.1.2
[4:37:24 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
[4:37:24 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[4:37:24 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[4:37:25 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git tag v1.1.2 17359392872f08aa50c277552250c48b63a66b02
fatal: tag 'v1.1.2' already exists
    at makeError (/home/travis/build/amclin/aem-packager/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/home/travis/build/amclin/aem-packager/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async tag (/home/travis/build/amclin/aem-packager/node_modules/semantic-release/lib/git.js:224:3)
    at async run (/home/travis/build/amclin/aem-packager/node_modules/semantic-release/index.js:190:5)
    at async module.exports (/home/travis/build/amclin/aem-packager/node_modules/semantic-release/index.js:259:22)
    at async module.exports (/home/travis/build/amclin/aem-packager/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 128: git tag v1.1.2 17359392872f08aa50c277552250c48b63a66b02',
  command: 'git tag v1.1.2 17359392872f08aa50c277552250c48b63a66b02',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "fatal: tag 'v1.1.2' already exists",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 128: git tag v1.1.2 17359392872f08aa50c277552250c48b63a66b02
fatal: tag 'v1.1.2' already exists
    at makeError (/home/travis/build/amclin/aem-packager/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/home/travis/build/amclin/aem-packager/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async tag (/home/travis/build/amclin/aem-packager/node_modules/semantic-release/lib/git.js:224:3)
    at async run (/home/travis/build/amclin/aem-packager/node_modules/semantic-release/index.js:190:5)
    at async module.exports (/home/travis/build/amclin/aem-packager/node_modules/semantic-release/index.js:259:22)
    at async module.exports (/home/travis/build/amclin/aem-packager/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 128: git tag v1.1.2 17359392872f08aa50c277552250c48b63a66b02',
  command: 'git tag v1.1.2 17359392872f08aa50c277552250c48b63a66b02',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "fatal: tag 'v1.1.2' already exists",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}Script failed with status 1
```

**Comment by gr2m** [comment]
The problem is that the tag `v1.1.2` does not appear in your commit history. Did you maybe do a `git push --force` at some point? Try to delete the `v1.1.2` tag, re-create it attached to a commit in the `master` branch, then re-run semantic-release

**Comment by amclin** [comment]
The `v1.1.2` tag was on a commit that branches off of master. I don't remember the specifics of what I was doing 4 months ago that caused that to happen:
<img width="613" alt="Screen Shot 2020-03-24 at 10 23 21 AM" src="https://user-images.githubusercontent.com/105728/77457216-9d150800-6db9-11ea-80d6-63a942e49ed1.png">

Deleting that tag and tagging a commit on master would mean the tags no longer match the commit that was released or what was in the changelog.

Shouldn't  `semantic-release` be looking authoritatively at the tags themselves instead of commit history to determine the latest tag? Especially if releasing from branches other than master are supported?

**Comment by gr2m** [comment]
It's very complicated to track releases over multiple branches. `semantic-release` is using git notes for that purpose. 

I do not see how semantic release should look for release tags in other branches than the current one, but what we could do is log a more helpful error message in case of a tag conflict, with information on how to resolve it.

**Comment by amclin** [comment]
Making the recommended change fixed my specific issue, but only because I was able to identify a suitable commit on the master branch that was equivalent - I could see that being a non-option on complex branch/release projects.

When a repo is cloned, all the tags on all branches are present. Couldn't the git tag API be used to identify existing tags instead of (what I presume is happening now) stepping back through the history to find a tag?

**Comment by gr2m** [comment]
Maybe, but it would add a lot of complexity, for an edge case that is usually was usually not intended to happen.

Another way to resolve it is to do the release once manually. After that semantic-release will also continue to work as it should

**Comment by zyrepo** [comment]
The problem has not been solved yet,

**Comment by brunohbrito** [comment]
I got stucked at same point. It solved for me after merge my branch (eg: bug/old_bug) with master after a new release.

**Comment by tflambre-fairville** [comment]
You could (if possible for you) remove the current existing tag 1.1.2

See
https://devconnected.com/how-to-delete-local-and-remote-tags-on-git/
