### ISSUE TITLE
`branch` is undefined causing a TypeError.

### ISSUE THREAD

**Issue by BeyondEvil** [semantic-release/semantic-release#1508]
## Current behavior

semantic release fails due to TypeError.

## Expected behavior

semantic release passes without any TypeErrors.

## Environment

- **semantic-release** version: 15.14.0 (node: v10.16.0)
- CI environment: Circle CI
- Plugins used: See config below
<details>

<summary> - <b>semantic-release</b> config (<i>.releaserc.js</i>) </summary>

```javascript
module.exports = {
  "branch": "master",
  "preset": "eslint",
  "plugins": [
    "@semantic-release/commit-analyzer",
    [
      "@semantic-release/release-notes-generator",
      {
        "writerOpts": {
          "transform": (commit) => {
            if (!commit.tag || typeof commit.tag !== `string`) { 
              return 
            }
            commit.message = commit.message.replace(/CP-\d+/g, '[$&](https://proxyco.atlassian.net/browse/$&)');
            commit.shortHash = commit.hash.substring(0, 7); 
            return commit
          }
        }
      }
    ],
    "@semantic-release/changelog",
    [
      "@semantic-release/git",
      {
        "message": "Release ${nextRelease.gitTag} [skip ci]"
      }
    ],
    "@semantic-release/github"
  ]
}
```

</details>

<details>

<summary> - CI logs </summary>

```bash
#!/bin/bash -eo pipefail
semantic-release

[12:54:04 PM] [semantic-release] › ℹ  Running semantic-release version 15.14.0
[12:54:04 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[12:54:04 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[12:54:04 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[12:54:04 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:54:04 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:54:04 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[12:54:04 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[12:54:04 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[12:54:04 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[12:54:04 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[12:54:04 PM] [semantic-release] › ✔  Run automated release from branch master
[12:54:04 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[12:54:04 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[12:54:04 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[12:54:04 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[12:54:04 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[12:54:04 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[12:54:04 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[@octokit/rest] `const Octokit = require("@octokit/rest")` is deprecated. Use `const { Octokit } = require("@octokit/rest")` instead
[12:54:05 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[12:54:05 PM] [semantic-release] › ℹ  Found git tag v1.2.1 associated with version 1.2.1
[12:54:05 PM] [semantic-release] › ℹ  Found 7 commits since last release
[12:54:05 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #7 from proxyco/CP-749/remove-hack

Fix: remove committer hack (CP-749)
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Fix: remove committer hack (CP-749)
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #6 from proxyco/CP-749/fix-release-flow

Fix: Correct release flow (CP-749)
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Fix: Correct release flow (CP-749)
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Chore: don't override constants (CP-749)
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #5 from proxyco/CP-749/proxytron-as-committer

Fix: Use Proxytron as SR committer (CP-749)
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Fix: Use Proxytron as SR committer (CP-749)
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[12:54:05 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 7 commits complete: patch release
[12:54:05 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:54:05 PM] [semantic-release] › ℹ  The next release version is 1.2.2
[12:54:05 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:54:05 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:54:05 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[12:54:05 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Update /root/project/CHANGELOG.md
[12:54:05 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[12:54:05 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[12:54:05 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 1 file(s) to commit
[12:54:05 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/git"
[12:54:05 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Cannot read property 'name' of undefined
    at module.exports (/usr/local/lib/node_modules/@semantic-release/git/lib/prepare.js:65:45)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '@semantic-release/git' }
{ TypeError: Cannot read property 'name' of undefined
    at module.exports (/usr/local/lib/node_modules/@semantic-release/git/lib/prepare.js:65:45)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '@semantic-release/git' }
Exited with code exit status 1
```

</details>

**Comment by gr2m** [comment]
can you please fill out all the questions from our issue template? https://github.com/semantic-release/semantic-release/issues/new?template=01_bug_report.md

**Comment by BeyondEvil** [comment]
Done! Please let me know if there's anything else I can provide. 🙏

**Comment by gr2m** [comment]
Did you try updating to the latest version of semantic-release? Current version is 17, your version is quite outdated. See migration guids at https://github.com/semantic-release/semantic-release/releases/v16.0.0 and https://github.com/semantic-release/semantic-release/releases/v17.0.0

**Comment by BeyondEvil** [comment]
Updating to latest (17.0.4) worked. 🤷‍♂

**Comment by gr2m** [comment]
Awesome, thanks for letting us know 👍 Glad it resolved your problem
