### ISSUE TITLE
Unable to do a prerelease in drone CI - exit code 128

### ISSUE THREAD

**Issue by avalkowsky** [semantic-release/semantic-release#1513]
## Current behavior

Hi,

I'm running the semantic-release on Drone CI with a configuration to make a prerelease on branches beta and develop. Issue and logs are related to beta branch, because I did not check in on the develop but I expect it's the same. 

Problem seems to be related to the "@semantic-release/github" as I see the error 
`Command failed with exit code 128: git tag --merged beta
fatal: malformed object name beta`

## Expected behavior
When I run the `semantic-release` on beta branch, with the configuration below, it should:
- push tags to github
- publish npm package with @beta tag

## Environment

- **semantic-release** version:  "^16.0.4" (the same happened on 17 though)
- CI environment: DroneCi v0.8
- Plugins used: 
"@semantic-release/changelog": "^3.0.2",
    "@semantic-release/commit-analyzer": "^6.1.0",
    "@semantic-release/git": "^7.0.8",
    "@semantic-release/github": "^7.0.5",
    "@semantic-release/npm": "^5.1.7",
    "@semantic-release/release-notes-generator": "^7.1.4",

- **semantic-release** configuration: 
.releaserc:
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/npm",
    "@semantic-release/git",
    "@semantic-release/github"
  ],
  "branches": ["master", { "name": "develop", "prerelease": "rc" }, { "name": "beta", "prerelease": "beta" }]
}

- CI logs:

```npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
+ export GH_TOKEN=$GITHUB_TOKEN
+ npm whoami --registry https://registry.npmjs.org
automation-drone
+ npm run release -- --debug

> @tyui/tyui-common@1.5.0 release /drone/src/github.com/tyui/tyui-common
> semantic-release "--debug"

[3:39:03 PM] [semantic-release] › ℹ  Running semantic-release version 16.0.4
2020-04-01T15:39:03.361Z semantic-release:config load config from: /drone/src/github.com/tyui/tyui-common/.releaserc
2020-04-01T15:39:03.367Z semantic-release:config options values: {
  branches: [
    'master',
    { name: 'develop', prerelease: 'rc' },
    { name: 'beta', prerelease: 'beta' }
  ],
  repositoryUrl: 'git+https://github.com/tyui/tyui-common.git',
  tagFormat: 'v${version}',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    '@semantic-release/npm',
    '@semantic-release/git',
    '@semantic-release/github'
  ],
  _: [],
  debug: true,
  '$0': 'node_modules/.bin/semantic-release'
}
2020-04-01T15:39:03.619Z semantic-release:plugins options for @semantic-release/changelog/verifyConditions: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
2020-04-01T15:39:03.620Z semantic-release:plugins options for @semantic-release/npm/verifyConditions: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
2020-04-01T15:39:03.621Z semantic-release:plugins options for @semantic-release/git/verifyConditions: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
2020-04-01T15:39:03.621Z semantic-release:plugins options for @semantic-release/github/verifyConditions: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
2020-04-01T15:39:03.622Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2020-04-01T15:39:03.622Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2020-04-01T15:39:03.622Z semantic-release:plugins options for @semantic-release/changelog/prepare: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
2020-04-01T15:39:03.623Z semantic-release:plugins options for @semantic-release/npm/prepare: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
2020-04-01T15:39:03.623Z semantic-release:plugins options for @semantic-release/git/prepare: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
2020-04-01T15:39:03.623Z semantic-release:plugins options for @semantic-release/npm/publish: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
2020-04-01T15:39:03.624Z semantic-release:plugins options for @semantic-release/github/publish: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
2020-04-01T15:39:03.624Z semantic-release:plugins options for @semantic-release/npm/addChannel: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
2020-04-01T15:39:03.624Z semantic-release:plugins options for @semantic-release/github/addChannel: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
2020-04-01T15:39:03.625Z semantic-release:plugins options for @semantic-release/github/success: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
2020-04-01T15:39:03.625Z semantic-release:plugins options for @semantic-release/github/fail: {}
[3:39:03 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
2020-04-01T15:39:07.986Z semantic-release:get-tags found tags for branch master: [ { gitTag: 'v1.0.0', version: '1.0.0', channels: [ null ] }, { gitTag: 'v1.0.1', version: '1.0.1', channels: [ null ] }, { gitTag: 'v1.1.0', version: '1.1.0', channels: [ null ] }, { gitTag: 'v1.1.1', version: '1.1.1', channels: [ null ] }, { gitTag: 'v1.2.0', version: '1.2.0', channels: [ null ] }, { gitTag: 'v1.3.0', version: '1.3.0', channels: [ null ] }, { gitTag: 'v1.3.1', version: '1.3.1', channels: [ null ] }, { gitTag: 'v1.4.0', version: '1.4.0', channels: [ null ] }, { gitTag: 'v1.4.1', version: '1.4.1', channels: [ null ] }, { gitTag: 'v1.4.2', version: '1.4.2', channels: [ null ] }, { gitTag: 'v1.5.0', version: '1.5.0', channels: [ null ] } ]
2020-04-01T15:39:08.082Z semantic-release:get-tags found tags for branch develop: [ { gitTag: 'v1.0.0', version: '1.0.0', channels: [ null ] }, { gitTag: 'v1.0.1', version: '1.0.1', channels: [ null ] }, { gitTag: 'v1.1.0', version: '1.1.0', channels: [ null ] }, { gitTag: 'v1.1.1', version: '1.1.1', channels: [ null ] }, { gitTag: 'v1.2.0', version: '1.2.0', channels: [ null ] }, { gitTag: 'v1.3.0', version: '1.3.0', channels: [ null ] }, { gitTag: 'v1.3.1', version: '1.3.1', channels: [ null ] }, { gitTag: 'v1.4.0', version: '1.4.0', channels: [ null ] }, { gitTag: 'v1.4.1', version: '1.4.1', channels: [ null ] }, { gitTag: 'v1.4.2', version: '1.4.2', channels: [ null ] }, { gitTag: 'v1.5.0', version: '1.5.0', channels: [ null ] } ]
[3:39:08 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git tag --merged beta
fatal: malformed object name beta
    at makeError (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getTags (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/lib/git.js:31:11)
    at async /drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/lib/branches/get-tags.js:18:9
    at async module.exports (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/lib/branches/index.js:26:20)
    at async run (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/index.js:56:22)
    at async module.exports (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/index.js:257:22)
    at async module.exports (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 128: git tag --merged beta',
  command: 'git tag --merged beta',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'fatal: malformed object name beta',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 128: git tag --merged beta
fatal: malformed object name beta
    at makeError (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/node_modules/execa/lib/error.js:58:11)
    at handlePromise (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getTags (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/lib/git.js:31:11)
    at async /drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/lib/branches/get-tags.js:18:9
    at async module.exports (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/lib/branches/index.js:26:20)
    at async run (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/index.js:56:22)
    at async module.exports (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/index.js:257:22)
    at async module.exports (/drone/src/github.com/tyui/tyui-common/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 128: git tag --merged beta',
  command: 'git tag --merged beta',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'fatal: malformed object name beta',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @tyui/tyui-common@1.5.0 release: `semantic-release "--debug"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @tyui/tyui-common@1.5.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-01T15_39_08_102Z-debug.log
```

Thanks for any help!

**Comment by avalkowsky** [comment]
OK, I got it.
CI tricked me, and the branch I tried to make it work was actually master instead of beta.
It's a little strange, cause the files are actually from beta branch, but probably I just don't get some git magic here. Anyway `git rev-parse --abbrev-ref HEAD` gave me `master`.
Checkout beta did enabled making the prerelease.

However I think it should be able to make a full release then or at least give me a good message what was wrong, like helping me notice the CI messed with git stuff.

**Comment by pvdlg** [comment]
semantic-release uses environment variable set by the CI to figure out what is the current branch.
If your CI clone a different branch than the one it advertise via environment variable there is nothing we can do unfortunatly.

With Drone we use the variable `DRONE_BRANCH`.
