### ISSUE TITLE
EINVALIDGHTOKEN Invalid GitHub token. Github Enterprise

### ISSUE THREAD

**Issue by KristoferKwan** [semantic-release/semantic-release#1517]
## Current behavior

Ran (travis-cli):
```
travis login -I -t $TRAVIS_TOKEN --github-token=$GH_TOKEN
```
Response:
```
Successfully logged in as <User>!
```
Ran:
```
GH_TOKEN=$GH_TOKEN npx semantic-release
 --no-ci --debug
```
Response:
```
[9:43:18 AM] [semantic-release] › ℹ  Running semantic-release version 17.0.4
  semantic-release:config load config from: /Users/kwank/Documents/insightsFactoryPersonal/package.json +0ms
  semantic-release:config options values: {
  semantic-release:config   branches: [ 'master', 'next' ],
  semantic-release:config   repositoryUrl: 'https://github.company.com/Kristofer-Kwan/InsightsFactory.git',
  semantic-release:config   tagFormat: 'v${version}',
  semantic-release:config   plugins: [
  semantic-release:config     '@semantic-release/commit-analyzer',
  semantic-release:config     '@semantic-release/release-notes-generator',
  semantic-release:config     '@semantic-release/npm',
  semantic-release:config     '@semantic-release/github'
  semantic-release:config   ],
  semantic-release:config   _: [],
  semantic-release:config   ci: false,
  semantic-release:config   debug: true,
  semantic-release:config   '$0': 'node_modules/.bin/semantic-release',
  semantic-release:config   noCi: true
  semantic-release:config } +2ms
  semantic-release:plugins options for @semantic-release/npm/verifyConditions: {} +0ms
[9:43:19 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/github/verifyConditions: {} +0ms
[9:43:19 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {} +1ms
[9:43:19 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
  semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {} +0ms
[9:43:19 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
  semantic-release:plugins options for @semantic-release/npm/prepare: {} +0ms
[9:43:19 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/npm/publish: {} +0ms
[9:43:19 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/github/publish: {} +1ms
[9:43:19 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/npm/addChannel: {} +0ms
[9:43:19 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/github/addChannel: {} +0ms
[9:43:19 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/github/success: {} +0ms
[9:43:19 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/github/fail: {} +5ms
[9:43:19 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
  semantic-release:get-tags found tags for branch master: [] +0ms
[9:43:20 AM] [semantic-release] › ✔  Run automated release from branch master on repository https://github.<compant>.com/Kristofer-Kwan/InsightsFactory.git
[9:43:20 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:43:20 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[9:43:20 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[9:43:20 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[9:43:20 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[9:43:20 AM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/github"
[9:43:20 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[9:43:20 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[9:43:21 AM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
[9:43:21 AM] [semantic-release] › ✖  EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository Kristofer-Kwan/InsightsFactory.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personal token.

[9:43:21 AM] [semantic-release] › ✖  EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository Kristofer-Kwan/InsightsFactory.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personal token.

AggregateError: 
    SemanticReleaseError: Invalid GitHub token.
        at module.exports (/Users/kwank/Documents/insightsFactoryPersonal/node_modules/@semantic-release/github/lib/get-error.js:6:10)
        at module.exports (/Users/kwank/Documents/insightsFactoryPersonal/node_modules/@semantic-release/github/lib/verify.js:74:21)
    at /Users/kwank/Documents/insightsFactoryPersonal/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at async Object.pluginsConf.<computed> [as verifyConditions] (/Users/kwank/Documents/insightsFactoryPersonal/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/Users/kwank/Documents/insightsFactoryPersonal/node_modules/semantic-release/index.js:93:3)
    at async module.exports (/Users/kwank/Documents/insightsFactoryPersonal/node_modules/semantic-release/index.js:258:22)
    at async module.exports (/Users/kwank/Documents/insightsFactoryPersonal/node_modules/semantic-release/cli.js:55:5) {
  name: 'AggregateError'
}
```
> NOTE: I have also tested it with travis, although it gives a similar issue. Additionally, the link to my repo does work in browser. The token was generated on my github enterprise account. The tokens that I used had superuser permission access. 

## Expected behavior

- My Github token validates (I've created multiple personal access tokens with superuser access for testing)
- Release should work (if Github token validates) 

## Environment

- **semantic-release** version:  "^17.0.4"
- CI environment: Travis Enterprise 
- Plugins used: Default plugins
- **semantic-release** configuration:   
```
{
  "name": "insights-semantic-release",
  "version": "0.0.0-development",
  "private": true,
  "scripts": {
    "commit": "git-cz",
    "semantic-release": "semantic-release"
  },
  "dependencies": {},
  "devDependencies": {
    "commitizen": "^4.0.3",
    "cz-conventional-changelog": "^3.1.0",
    "semantic-release": "^17.0.4"
  },
  "repository": {
    "type": "git",
    "url": "https://github.company.com/Kristofer-Kwan/InsightsFactory.git"
  },
  "release": {
    "branches": [
      "master",
      "next"
    ],
    "repositoryUrl": "https://github.company.com/Kristofer-Kwan/InsightsFactory.git"
  },
  "config": {
    "commitizen": {
      "path": "node_modules/cz-conventional-changelog"
    }
  }
}
```
 
- CI logs: (see above^)

**Comment by KristoferKwan** [comment]
Figured it out.. forgot to add the GH_URL and GH_PREFIX specifications to my release configs for github enterprise
