### ISSUE TITLE
Version calculation is creating duplicate version

### ISSUE THREAD

**Issue by ianschmitz** [semantic-release/semantic-release#1531]
First of all, thank you for this awesome project. I'm really digging the release flow :+1:

## Current behavior

We recently adopted semantic-release, and use a `master < beta < alpha` strategy with the default configuration. After recently merging `alpha` into `beta`, and subsequently creating a new `alpha` branch from the tip of `beta` and creating a new commit on `alpha`, semantic-release is incorrectly calculating the next version for the `alpha` branch. 

It is calculating `v1.0.0-alpha.18` which is an already released version, as can be seen in the log below.

Here's the top few log entires from `git log`

```
* d6d8723 (HEAD -> alpha, origin/alpha) feat: updates to support Web 5.7+ (#10)
* 8082e0e (origin/beta, beta) chore: fix git tags fetch during release (#11)
* 0d7818d chore: update package.json metadata (#8)
* d40abf4 (tag: v1.0.0-beta.2) feat: forward locale url param to Web (#9)
* b08aaa8 (tag: v1.0.0-beta.1, tag: v1.0.0-alpha.18) fix: Add debug url param to webviewer loading url (#7)
* 9746c10 (tag: v1.0.0-alpha.17) feat: update SDK sample (#5)
* 7a4fccb chore: upgrade dependencies (#6)
* 1a603f5 (tag: v1.0.0-alpha.16) feat: add link to developer center in create CLI (#4)
* ff50acb (tag: v1.0.0-alpha.15) feat: generate random namespace id on project creation (#3)
* 3b8415a (tag: v1.0.0-alpha.14) fix: skip linking during install
* 2af6605 (tag: v1.0.0-alpha.13) fix: disable strict null checks (#2)
* 91c7837 (tag: v1.0.0-alpha.12) fix: .gitignore being renamed to .npmignore by npm
```

What's interesting is the log output during release. It seems to think the last released version on the `alpha` branch is `v1.0.0-alpha.17`. Here's the output from a `semantic-release -d --no-ci --debug`:

```
[8:31:59 AM] [semantic-release] › ℹ  Running semantic-release version 17.0.4
  semantic-release:config load config from: undefined +0ms
  semantic-release:config options values: {
  semantic-release:config   branches: [
  semantic-release:config     '+([0-9])?(.{+([0-9]),x}).x',
  semantic-release:config     'master',
  semantic-release:config     'next',
  semantic-release:config     'next-major',
  semantic-release:config     { name: 'beta', prerelease: true },
  semantic-release:config     { name: 'alpha', prerelease: true }
  semantic-release:config   ],
  semantic-release:config   repositoryUrl: 'git+https://github.com/geocortex/vertigis-web-sdk.git',
  semantic-release:config   tagFormat: 'v${version}',
  semantic-release:config   plugins: [
  semantic-release:config     '@semantic-release/commit-analyzer',
  semantic-release:config     '@semantic-release/release-notes-generator',
  semantic-release:config     '@semantic-release/npm',
  semantic-release:config     '@semantic-release/github'
  semantic-release:config   ],
  semantic-release:config   _: [],
  semantic-release:config   d: true,
  semantic-release:config   'dry-run': true,
  semantic-release:config   dryRun: true,
  semantic-release:config   ci: false,
  semantic-release:config   debug: true,
  semantic-release:config   '$0': 'node_modules/.bin/semantic-release',
  semantic-release:config   noCi: true
  semantic-release:config } +1ms
  semantic-release:plugins options for @semantic-release/npm/verifyConditions: {} +0ms
[8:31:59 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/github/verifyConditions: {} +0ms
[8:31:59 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {} +1ms
[8:31:59 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
  semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {} +0ms
[8:31:59 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
  semantic-release:plugins options for @semantic-release/npm/prepare: {} +1ms
[8:31:59 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/npm/publish: {} +0ms
[8:31:59 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/github/publish: {} +0ms
[8:31:59 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/npm/addChannel: {} +1ms
[8:31:59 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/github/addChannel: {} +0ms
[8:31:59 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/github/success: {} +0ms
[8:31:59 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/github/fail: {} +1ms
[8:31:59 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
  semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://github.com/geocortex/vertigis-web-sdk.git HEAD:alpha
  semantic-release:git remote: Invalid username or password.
  semantic-release:git fatal: Authentication failed for 'https://github.com/geocortex/vertigis-web-sdk.git/'
  semantic-release:git     at makeError (/home/ian/Code/vertigis-web-sdk/node_modules/semantic-release/node_modules/execa/lib/error.js:58:11)
  semantic-release:git     at handlePromise (/home/ian/Code/vertigis-web-sdk/node_modules/semantic-release/node_modules/execa/index.js:114:26)
  semantic-release:git     at processTicksAndRejections (internal/process/task_queues.js:97:5)
  semantic-release:git     at async verifyAuth (/home/ian/Code/vertigis-web-sdk/node_modules/semantic-release/lib/git.js:207:5)
  semantic-release:git     at async module.exports (/home/ian/Code/vertigis-web-sdk/node_modules/semantic-release/lib/get-git-auth-url.js:43:5)
  semantic-release:git     at async run (/home/ian/Code/vertigis-web-sdk/node_modules/semantic-release/index.js:55:27)
  semantic-release:git     at async module.exports (/home/ian/Code/vertigis-web-sdk/node_modules/semantic-release/index.js:259:22)
  semantic-release:git     at async module.exports (/home/ian/Code/vertigis-web-sdk/node_modules/semantic-release/cli.js:55:5) +0ms
  semantic-release:get-tags found tags for branch master: [] +0ms
  semantic-release:get-tags found tags for branch beta: [ { gitTag: 'v1.0.0-alpha.1', version: '1.0.0-alpha.1', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.10', version: '1.0.0-alpha.10', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.11', version: '1.0.0-alpha.11', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.12', version: '1.0.0-alpha.12', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.13', version: '1.0.0-alpha.13', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.14', version: '1.0.0-alpha.14', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.15', version: '1.0.0-alpha.15', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.16', version: '1.0.0-alpha.16', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.17', version: '1.0.0-alpha.17', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.18', version: '1.0.0-alpha.18', channels: [ 'beta' ] }, { gitTag: 'v1.0.0-alpha.2', version: '1.0.0-alpha.2', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.3', version: '1.0.0-alpha.3', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.4', version: '1.0.0-alpha.4', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.5', version: '1.0.0-alpha.5', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.6', version: '1.0.0-alpha.6', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.7', version: '1.0.0-alpha.7', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.8', version: '1.0.0-alpha.8', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.9', version: '1.0.0-alpha.9', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-beta.1', version: '1.0.0-beta.1', channels: [ 'beta' ] }, { gitTag: 'v1.0.0-beta.2', version: '1.0.0-beta.2', channels: [ 'beta' ] } ] +100ms
  semantic-release:get-tags found tags for branch alpha: [ { gitTag: 'v1.0.0-alpha.1', version: '1.0.0-alpha.1', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.10', version: '1.0.0-alpha.10', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.11', version: '1.0.0-alpha.11', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.12', version: '1.0.0-alpha.12', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.13', version: '1.0.0-alpha.13', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.14', version: '1.0.0-alpha.14', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.15', version: '1.0.0-alpha.15', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.16', version: '1.0.0-alpha.16', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.17', version: '1.0.0-alpha.17', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.18', version: '1.0.0-alpha.18', channels: [ 'beta' ] }, { gitTag: 'v1.0.0-alpha.2', version: '1.0.0-alpha.2', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.3', version: '1.0.0-alpha.3', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.4', version: '1.0.0-alpha.4', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.5', version: '1.0.0-alpha.5', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.6', version: '1.0.0-alpha.6', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.7', version: '1.0.0-alpha.7', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.8', version: '1.0.0-alpha.8', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-alpha.9', version: '1.0.0-alpha.9', channels: [ 'alpha' ] }, { gitTag: 'v1.0.0-beta.1', version: '1.0.0-beta.1', channels: [ 'beta' ] }, { gitTag: 'v1.0.0-beta.2', version: '1.0.0-beta.2', channels: [ 'beta' ] } ] +106ms
[8:32:01 AM] [semantic-release] › ⚠  Run automated release from branch alpha on repository https://[secure]@github.com/geocortex/vertigis-web-sdk.git in dry-run mode
[8:32:02 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[8:32:02 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[8:32:02 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[8:32:02 AM] [semantic-release] [@semantic-release/npm] › ℹ  Reading npm config from /home/ian/.npmrc, /home/ian/Code/vertigis-web-sdk/.npmrc
ianschmitz
[8:32:02 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[8:32:02 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[8:32:02 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[8:32:02 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[8:32:02 AM] [semantic-release] › ℹ  Found git tag v1.0.0-alpha.17 associated with version 1.0.0-alpha.17 on branch alpha
  semantic-release:get-commits Use from: 9746c10cd0b009fcb1bada7ad63e266a63658c6d +0ms
[8:32:02 AM] [semantic-release] › ℹ  Found 5 commits since last release
  semantic-release:get-commits Parsed commits: [ { commit: { long: 'd6d8723d04ac003d3573075466362b8aeb0dc92c', short: 'd6d8723' }, tree: { long: 'ec613a4b4c323e26a08ce4aa1155c579de3ce802', short: 'ec613a4' }, author: { name: 'eric-parsons', email: 'eric.d.parsons@gmail.com', date: 2020-04-16T19:24:28.000Z }, committer: { name: 'Ian Schmitz', email: 'ianschmitz@gmail.com', date: 2020-04-16T23:53:49.000Z }, subject: 'feat: updates to support Web 5.7+ (#10)', body: '* Updating SDK and sample to work with Web 5.7.\n' + '\n' + '* Temporarily removing dependency on @vertigis/web.\n' + '\n' + 'It will be restored once this package is available in public npm.\n', hash: 'd6d8723d04ac003d3573075466362b8aeb0dc92c', committerDate: 2020-04-16T23:53:49.000Z, message: 'feat: updates to support Web 5.7+ (#10)\n' + '\n' + '* Updating SDK and sample to work with Web 5.7.\n' + '\n' + '* Temporarily removing dependency on @vertigis/web.\n' + '\n' + 'It will be restored once this package is available in public npm.', gitTags: '(HEAD -> alpha, origin/alpha)' }, { commit: { long: '8082e0e2587b1356a0e775bfeaef0c99391d91e9', short: '8082e0e' }, tree: { long: 'cd8c16d2ad2133a31c7c89ee03c01c0edf7ccc63', short: 'cd8c16d' }, author: { name: 'Ian Schmitz', email: 'ianschmitz@gmail.com', date: 2020-04-16T20:56:09.000Z }, committer: { name: 'GitHub', email: 'noreply@github.com', date: 2020-04-16T20:56:09.000Z }, subject: 'chore: fix git tags fetch during release (#11)', body: '', hash: '8082e0e2587b1356a0e775bfeaef0c99391d91e9', committerDate: 2020-04-16T20:56:09.000Z, message: 'chore: fix git tags fetch during release (#11)', gitTags: '(origin/beta, beta)' }, { commit: { long: '0d7818dedefa252a6d6325bd63eeb5f8a71b52c6', short: '0d7818d' }, tree: { long: '7fbd884be1a4d678a23d44246e8d7c510377193b', short: '7fbd884' }, author: { name: 'Ian Schmitz', email: 'ianschmitz@gmail.com', date: 2020-04-16T18:18:57.000Z }, committer: { name: 'GitHub', email: 'noreply@github.com', date: 2020-04-16T18:18:57.000Z }, subject: 'chore: update package.json metadata (#8)', body: '', hash: '0d7818dedefa252a6d6325bd63eeb5f8a71b52c6', committerDate: 2020-04-16T18:18:57.000Z, message: 'chore: update package.json metadata (#8)', gitTags: '' }, { commit: { long: 'd40abf4efa2aaeca7ca319f69f58d4d7bacaec9a', short: 'd40abf4' }, tree: { long: '7e7ca333896ae6761e3b0aced0e89ad9a36c3b45', short: '7e7ca33' }, author: { name: 'Ian Schmitz', email: 'ianschmitz@gmail.com', date: 2020-04-16T18:10:34.000Z }, committer: { name: 'GitHub', email: 'noreply@github.com', date: 2020-04-16T18:10:34.000Z }, subject: 'feat: forward locale url param to Web (#9)', body: '', hash: 'd40abf4efa2aaeca7ca319f69f58d4d7bacaec9a', committerDate: 2020-04-16T18:10:34.000Z, message: 'feat: forward locale url param to Web (#9)', gitTags: '(tag: v1.0.0-beta.2)' }, { commit: { long: 'b08aaa81d886298e0031e3fe630938ff3d78d4ea', short: 'b08aaa8' }, tree: { long: 'e800e97f58d000e6ebb0c8e515f2ad06cc4a6ea1', short: 'e800e97' }, author: { name: 'Noah Silvera', email: 'noah.a.silvera@gmail.com', date: 2020-04-07T22:13:57.000Z }, committer: { name: 'GitHub', email: 'noreply@github.com', date: 2020-04-07T22:13:57.000Z }, subject: 'fix: Add debug url param to webviewer loading url (#7)', body: '', hash: 'b08aaa81d886298e0031e3fe630938ff3d78d4ea', committerDate: 2020-04-07T22:13:57.000Z, message: 'fix: Add debug url param to webviewer loading url (#7)', gitTags: '(tag: v1.0.0-beta.1, tag: v1.0.0-alpha.18)' } ] +10ms
[8:32:02 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[8:32:02 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: updates to support Web 5.7+ (#10)

* Updating SDK and sample to work with Web 5.7.

* Temporarily removing dependency on @vertigis/web.

It will be restored once this package is available in public npm.
  semantic-release:commit-analyzer Analyzing with default rules +0ms
  semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor' +0ms
[8:32:02 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[8:32:02 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore: fix git tags fetch during release (#11)
  semantic-release:commit-analyzer Analyzing with default rules +1ms
[8:32:02 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[8:32:02 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore: update package.json metadata (#8)
  semantic-release:commit-analyzer Analyzing with default rules +0ms
[8:32:02 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[8:32:02 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: forward locale url param to Web (#9)
  semantic-release:commit-analyzer Analyzing with default rules +0ms
  semantic-release:commit-analyzer The rule { type: 'feat', release: 'minor' } match commit with release type 'minor' +1ms
[8:32:02 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[8:32:02 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: Add debug url param to webviewer loading url (#7)
  semantic-release:commit-analyzer Analyzing with default rules +0ms
  semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch' +0ms
[8:32:02 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[8:32:02 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 5 commits complete: minor release
[8:32:02 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[8:32:02 AM] [semantic-release] › ℹ  The next release version is 1.0.0-alpha.18
[8:32:02 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
  semantic-release:release-notes-generator version: '1.0.0-alpha.18' +0ms
  semantic-release:release-notes-generator host: undefined +0ms
  semantic-release:release-notes-generator owner: 'geocortex' +0ms
  semantic-release:release-notes-generator repository: 'vertigis-web-sdk' +0ms
  semantic-release:release-notes-generator previousTag: 'v1.0.0-alpha.17' +0ms
  semantic-release:release-notes-generator currentTag: 'v1.0.0-alpha.18' +0ms
  semantic-release:release-notes-generator host: 'https://github.com' +0ms
  semantic-release:release-notes-generator linkReferences: undefined +0ms
  semantic-release:release-notes-generator issue: 'issues' +0ms
  semantic-release:release-notes-generator commit: 'commit' +0ms
[8:32:02 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[8:32:02 AM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/npm" in dry-run mode
[8:32:02 AM] [semantic-release] › ⚠  Skip v1.0.0-alpha.18 tag creation in dry-run mode
[8:32:02 AM] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/npm" in dry-run mode
[8:32:02 AM] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/github" in dry-run mode
[8:32:02 AM] [semantic-release] › ⚠  Skip step "success" of plugin "@semantic-release/github" in dry-run mode
[8:32:02 AM] [semantic-release] › ✔  Published release 1.0.0-alpha.18 on alpha channel
[8:32:02 AM] [semantic-release] › ℹ  Release note for version 1.0.0-alpha.18:
# 1.0.0-alpha.18 (https://github.com/geocortex/vertigis-web-sdk/compare/v1.0.0-alpha.17...v1.0.0-alpha.18) (2020-04-17)

### Bug Fixes

    * Add debug url param to webviewer loading url (#7 (https://github.com/geocortex/vertigis-web-sdk/issues/7)) (b08aaa8 (https://github.com/geocortex/vertigis-web-sdk/commit/b08aaa81d886298e0031e3fe630938ff3d78d4ea))

### Features

    * forward locale url param to Web (#9 (https://github.com/geocortex/vertigis-web-sdk/issues/9)) (d40abf4 (https://github.com/geocortex/vertigis-web-sdk/commit/d40abf4efa2aaeca7ca319f69f58d4d7bacaec9a))
    * updates to support Web 5.7+ (#10 (https://github.com/geocortex/vertigis-web-sdk/issues/10)) (d6d8723 (https://github.com/geocortex/vertigis-web-sdk/commit/d6d8723d04ac003d3573075466362b8aeb0dc92c))
```

You'll notice in the `semantic-release:get-tags found tags for branch alpha:` line, this interesting tidbit:

```
{ gitTag: 'v1.0.0-alpha.17', version: '1.0.0-alpha.17', channels: [ 'alpha' ] },
{ gitTag: 'v1.0.0-alpha.18', version: '1.0.0-alpha.18', channels: [ 'beta' ] }
```

I had thought the issue was possibly caused by us merging the alpha branch into beta, continuing work on beta, and then creating a new commit on alpha which was out of date from beta. However i re-created the alpha branch (which is what you see in the `git log` above), and cherry picked the new commit on top, but got the same result from semantic-release.

## Expected behavior

Version is calculated as `v1.0.0-alpha.19`.

## Environment

- **semantic-release** version: 17.0.6
- CI environment: GitHub Actions - same result locally
- Plugins used: Default
- **semantic-release** configuration: Default
- CI logs: https://github.com/geocortex/vertigis-web-sdk/runs/593867678?check_suite_focus=true

**Comment by ianschmitz** [comment]
Following the code path for https://github.com/semantic-release/semantic-release/blob/0785a844fa8ac1320383452ce531898be3b01f92/lib/branches/get-tags.js#L22 `git notes --ref semantic-release show b08aaa8` returns:

```
{"channels":["beta"]}
```

**Comment by aperdomob** [comment]
I have a similar issue

The problem is related to the `lastRelease` always take the first filter result and it doesn't verify with pre-release is launched 

https://github.com/semantic-release/semantic-release/blob/master/lib/get-last-release.js#L30

**Comment by aperdomob** [comment]
Hi @ianschmitz 

I checked your comment and I think that you are right, I propose some changes for that. But I have bad news, you will need to update the notes manually

**Comment by ianschmitz** [comment]
> Hi @ianschmitz 
> 
> I checked your comment and I think that you are right, I propose some changes for that. But I have bad news, you will need to update the notes manually

I figured as much. That's no problem at all as I was having to do that to debug the behavior. Thanks for fixing!

**Comment by pvdlg** [comment]
@ianschmitz @aperdomob I couldn't reproduce what you are describing. I'm probably missing something.

Can you provide an minimal reproducible example, with the list of git command to run to end up in that situation?

**Comment by aperdomob** [comment]
Hi @pvdlg thank you for your attention

Hi created this test you should use into index.test.js

```js
test.only('Publish a pre-release version - example', async (t) => {
  const {cwd, repositoryUrl} = await gitRepo(true);
  await gitCommits(['feat: initial commit'], {cwd});
  await gitTagVersion('v1.0.0', undefined, {cwd});
  await gitPush(repositoryUrl, 'master', {cwd});
  await gitCheckout('beta', true, {cwd});
  await gitCommits(['feat: a feature'], {cwd});
  await gitPush(repositoryUrl, 'beta', {cwd});

  const config = {branches: ['master', {name: 'beta', prerelease: true}, {name: 'alpha', prerelease: true}], repositoryUrl};
  const options = {
    ...config,
    verifyConditions: stub().resolves(),
    verifyRelease: stub().resolves(),
    generateNotes: stub().resolves(''),
    addChannel: false,
    prepare: stub().resolves(),
    publish: stub().resolves(),
    success: stub().resolves(),
    fail: stub().resolves(),
  };

  const semanticReleaseBeta = requireNoCache('..', {
    './lib/get-logger': () => t.context.logger,
    'env-ci': () => ({isCi: true, branch: 'beta', isPr: false}),
  });
  let {releases} = await semanticReleaseBeta(options, {cwd, env: {}, stdout: {write: () => {}}, stderr: {write: () => {}}});

  t.is(releases.length, 1);
  t.is(releases[0].version, '1.1.0-beta.1');
  t.is(releases[0].gitTag, 'v1.1.0-beta.1');
  t.is(await gitGetNote('v1.1.0-beta.1', {cwd}), '{"channels":["beta"]}');

  await gitCheckout('alpha', true, {cwd});
  await gitPush(repositoryUrl, 'alpha', {cwd});

  const semanticReleaseAlpha = requireNoCache('..', {
    './lib/get-logger': () => t.context.logger,
    'env-ci': () => ({isCi: true, branch: 'alpha', isPr: false}),
  });

  let alpha = await semanticReleaseAlpha(options, {cwd, env: {}, stdout: {write: () => {}}, stderr: {write: () => {}}});

  t.is(alpha.releases.length, 1);
  t.is(alpha.releases[0].version, '1.1.0-alpha.1');
  t.is(alpha.releases[0].gitTag, 'v1.1.0-alpha.1');
  t.is(await gitGetNote('v1.1.0-alpha.1', {cwd}), '{"channels":["alpha"]}');
  t.is(await gitGetNote('v1.1.0-beta.1', {cwd}), '{"channels":["alpha"]}'); // the expected behavior should  \\ {"channels":["beta"]} or {"channels":["beta", "alpha"]}

  await gitCheckout('beta', {cwd});
  await gitCommits(['fix: a fix'], {cwd});
  ({releases} = await semanticReleaseBeta(options, {
    cwd,
    env: {},
    stdout: {write: () => {}},
    stderr: {write: () => {}},
  })); // fail because there is no branch with beta channel

  // t.is(releases.length, 1);
  // t.is(releases[0].version, '1.1.0-beta.2');
  // t.is(releases[0].gitTag, 'v1.1.0-beta.2');
  // t.is(await gitGetNote('v1.1.0-beta.2', {cwd}), '{"channels":["beta"]}');
});
```

**Comment by aperdomob** [comment]
Hi @pvdlg could you check the test?

**Comment by aperdomob** [comment]
Hi, is there any progress on this issue?
