### ISSUE TITLE
RequestError [HttpError]: Cookies must be enabled to use GitHub.

### ISSUE THREAD

**Issue by kleinfreund** [semantic-release/semantic-release#1548]
## Current behavior

I setup a semantic-release workflow via GitHub actions for the repository https://github.com/kleinfreund/vue-accessible-color-picker. On push, the workflow was run and the first version of my package was published (yay!). However, immediately afterwards, the following step failed (full error below):

```
[semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/github"
[semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Cookies must be enabled to use GitHub.
```

I’m not sure what to make of this error. I don’t recall reading anything in the Getting started documents and articles I followed about some Cookie settings I needed to be aware of.

Note that I have both `NPM_TOKEN` and `GH_TOKEN` configured via the secrets settings of the repository in question. The `GH_TOKEN` is a public access token which was created with the `public_repo` permission.

What am I missing from my setup and how can I recover from this botched release?

<details>
<summary>full trace</summary>

[semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/github"
[semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Cookies must be enabled to use GitHub.
    at /home/runner/work/vue-accessible-color-picker/vue-accessible-color-picker/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 403,
  headers: {
    'cache-control': 'no-cache',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://live.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com",
    'content-type': 'text/plain; charset=utf-8',
    date: 'Thu, 14 May 2020 17:40:28 GMT',
    'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'set-cookie': '_gh_sess=[REDACTED]; path=/; secure; HttpOnly',
    status: '403 Forbidden',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'X-PJAX, Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-request-id': '0400:0851:57C564:924595:5EBD828C',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://github.com/repos/kleinfreund/vue-accessible-color-picker/releases',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/17.9.0 octokit-core.js/2.5.0 Node.js/12.16.3 (Linux 5.3; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"tag_name":"v1.0.0","name":"v1.0.0","body":"# 1.0.0 (2020-05-14)\\n\\n\\n### Features\\n\\n* implement initial version of vue-accessible-color-picker ([eba7d30](https://github.com/kleinfreund/vue-accessible-color-picker/commit/eba7d3055364c2bcbeaa1a0067df6521050d2d3b))\\n\\n\\n\\n","prerelease":false}',
    request: { agent: undefined, hook: [Function: bound bound register] }
  },
  pluginName: '@semantic-release/github'
}
RequestError [HttpError]: Cookies must be enabled to use GitHub.
    at /home/runner/work/vue-accessible-color-picker/vue-accessible-color-picker/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 403,
  headers: {
    'cache-control': 'no-cache',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com cdn.optimizely.com logx.optimizely.com/v1/events wss://live.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com",
    'content-type': 'text/plain; charset=utf-8',
    date: 'Thu, 14 May 2020 17:40:28 GMT',
    'expect-ct': 'max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    'set-cookie': '_gh_sess=[REDACTED]; path=/; secure; HttpOnly',
    status: '403 Forbidden',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'X-PJAX, Accept-Encoding, Accept, X-Requested-With',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-request-id': '0400:0851:57C564:924595:5EBD828C',
    'x-xss-protection': '1; mode=block'
  },
  request: {
    method: 'POST',
    url: 'https://github.com/repos/kleinfreund/vue-accessible-color-picker/releases',
    headers: {
      accept: 'application/vnd.github.v3+json',
      'user-agent': 'octokit-rest.js/17.9.0 octokit-core.js/2.5.0 Node.js/12.16.3 (Linux 5.3; x64)',
      authorization: 'token [REDACTED]',
      'content-type': 'application/json; charset=utf-8'
    },
    body: '{"tag_name":"v1.0.0","name":"v1.0.0","body":"# 1.0.0 (2020-05-14)\\n\\n\\n### Features\\n\\n* implement initial version of vue-accessible-color-picker ([eba7d30](https://github.com/kleinfreund/vue-accessible-color-picker/commit/eba7d3055364c2bcbeaa1a0067df6521050d2d3b))\\n\\n\\n\\n","prerelease":false}',
    request: { agent: undefined, hook: [Function: bound bound register] }
  },
  pluginName: '@semantic-release/github'
}
##[error]Process completed with exit code 1.
</details>

## Expected behavior

For this error to not happened

or

for this error to actually tell me something useful (I know this is in particular not a problem with semantic-release).

## Environment

- **semantic-release** version: 17.0.7
- CI environment: GitHub actions
- Plugins used: *none*
- **semantic-release** configuration: https://github.com/kleinfreund/vue-accessible-color-picker/blob/main/release.config.js
- CI logs: https://github.com/kleinfreund/vue-accessible-color-picker/runs/675427677

**Comment by gr2m** [comment]
What is very odd is that the request is sent to `https://github.com/repos/kleinfreund/vue-accessible-color-picker/releases`, but it should have been `https://api.github.com/repos/kleinfreund/vue-accessible-color-picker/releases`. The baseUrl is incorrect. Do you have any idea how that might have happened?

**Comment by kleinfreund** [comment]
Oh, that is odd indeed. I didn’t even notice that. That would explain some sort of authentication failure. I have no idea how that might have happened. I really tried my best not to shoot to far over the finish line and tried the most basic setup and workflow configuration I could think that I was still okay with releasing a package. I’ll do some text-search, but so far, I’m empty-handed. :/

**Comment by gr2m** [comment]
Can you try to change `repository.url` in your `package.json` to

```json
  "url": "https://github.com/kleinfreund/vue-accessible-color-picker.git"
```

The `.git` suffix is missing. It's really just a guess, but worth a try

You will also have to manually create the release for `v1.0.0`, semantic-release won't be able to fix that for you

**Comment by gr2m** [comment]
I'm fairly sure the problem occurs around here: https://github.com/semantic-release/github/blob/8027e9120afb2110be40d9e224bea627f0b6361c/lib/get-client.js#L30 🤔

**Comment by kleinfreund** [comment]
Can I test this by temporarily setting `dryRun: true` in my `release.config.js` to avoid needlessly releasing a version v1.0.1 on NPM?

As for the cause of the error, it could maybe just be a certain incompatibility with the object format for the repository field? I think I will try using just a string value rather than the object syntax in my next try.

Also, with “manually create the release for `v1.0.0`”, do you mean manually performing the steps the `@semantic-release/github` was about to do but failed at? I’ll see if I can find some documents for what exactly happens there because I don’t know.

**Comment by gr2m** [comment]
With "manually create the release for v1.0.0" I mean create it using the UI on github.com. The tag already exists, that's all semantic-release cares about moving forward. But if you want to add release notes, then you have to create a release manually.

Let me try to reproduce the problem you experienced with a test repository, hold on

**Comment by gr2m** [comment]
So this is curious:
https://github.com/gr2m/vue-accessible-color-picker/runs/675583625?check_suite_focus=true#step:5:33

Because of this line:
https://github.com/semantic-release/github/blob/8027e9120afb2110be40d9e224bea627f0b6361c/lib/resolve-config.js#L19

I wonder if the `GITHUB_URL` is new, introduced today via https://github.blog/changelog/2020-05-14-github-actions-new-runner-release-v2-262-1/. I'll investigate

**Comment by gr2m** [comment]
I was able to reproduce your error:
https://github.com/gr2m/vue-accessible-color-picker/runs/675591678?check_suite_focus=true#step:6:137

**Comment by kleinfreund** [comment]
Following your recommendation to fix the `repository` field in my package.json (adding the missing `.git` extension), I pushed a new commit (including the `dryRun: true` setting in `release.config.js`). The release workflow ran successfully now: https://github.com/kleinfreund/vue-accessible-color-picker/runs/675623615

**Comment by gr2m** [comment]
I've added the `.git` suffix and got the same error: https://github.com/gr2m/vue-accessible-color-picker/runs/675618003?check_suite_focus=true#step:6:140

When run in dry mode, semantic-release is not attempting to create a release, so you don't get the error
