### ISSUE TITLE
Error in semantic-release/github: Cookies must be enabled to use GitHub.

### ISSUE THREAD

**Issue by koljakutschera** [semantic-release/semantic-release#1557]
## Current behavior

Action always errors with:

Failed step "publish" of plugin "@semantic-release/github"
✖  An error occurred while running semantic-release: RequestError [HttpError]: Cookies must be enabled to use GitHub.

## Expected behavior

GitHub publish should work

## Notes

Seems to be related to: https://github.com/semantic-release/github/issues/271

## Environment

- **semantic-release** version: "semantic-release": "^17.0.7"
- CI environment: GitHub actions
- Plugins used: /
- **semantic-release** configuration: 

Using: semantic-release-action (https://github.com/codfish/semantic-release-action) with no additional config.

- CI logs:

```[10:49:42 AM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/npm"
[10:49:42 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
[10:49:42 AM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/github"
[10:49:42 AM] [semantic-release] › ✖  An error occurred while running semantic-release: RequestError [HttpError]: Cookies must be enabled to use GitHub.
    at /action/node_modules/@octokit/request/dist-node/index.js:66:23
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  status: 403,```

**Comment by gr2m** [comment]
update your lockfile, this has been fixed via https://github.com/semantic-release/github/pull/269
