### ISSUE TITLE
Application error (6): <chrome-web-store-extension-id> pending review so can't be edited

### ISSUE THREAD

**Issue by adrienjoly** [semantic-release/semantic-release#1564]
## Current behavior

While `semantic-release` is trying to publish the new version of my extension to Chrome Web Store:

```
[3:47:37 PM] [semantic-release] › ✔  Created tag v1.20.0
[3:47:37 PM] [semantic-release] › ℹ  Start step "publish" of plugin "semantic-release-chrome"
[3:47:38 PM] [semantic-release] › ✖  Failed step "publish" of plugin "semantic-release-chrome"
[3:47:38 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[3:47:39 PM] [semantic-release] [@semantic-release/github] › ℹ  Created issue #98: https://github.com/adrienjoly/chrome-next-step-for-trello/issues/98.
[3:47:39 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[3:47:39 PM] [semantic-release] › ✖  CLIENT_ERROR Application error (6): iajhmklhilkjgabejjemfbhmclgnmamf pending review so can't be edited
{ AggregateError: 
    SemanticReleaseError: Application error (6): iajhmklhilkjgabejjemfbhmclgnmamf pending review so can't be edited
        at uploadRes.itemError.forEach.err (/home/travis/build/adrienjoly/chrome-next-step-for-trello/node_modules/semantic-release-chrome/dist/publish.js:48:29)
        at Array.forEach (<anonymous>)
        at publish (/home/travis/build/adrienjoly/chrome-next-step-for-trello/node_modules/semantic-release-chrome/dist/publish.js:47:25)
    at publish (/home/travis/build/adrienjoly/chrome-next-step-for-trello/node_modules/semantic-release-chrome/dist/publish.js:51:11)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'AggregateError' }
Done. Your build exited with 0.
```

(initial ticket: https://github.com/adrienjoly/chrome-next-step-for-trello/issues/98, for reference and details)

## Expected behavior

I would like the latest version of my extension to be published to Chrome Web Store, like it did for the previous version, published just a few minutes before (v1.19.2, cf [list of commits on `master`](https://github.com/adrienjoly/chrome-next-step-for-trello/commits/master))

I don't remember having submitted any request for changes on my Chrome Web Store page lately => I don't understand what's under review, and how I to publish that update.

## Environment

- **semantic-release** version: 15.14.0
- CI environment: Travis
- Plugins used: `"semantic-release-chrome": "^1.1.1"`
- **semantic-release** configuration: https://github.com/adrienjoly/chrome-next-step-for-trello/blob/master/release.config.js
- CI logs: https://travis-ci.org/github/adrienjoly/chrome-next-step-for-trello/builds/690397467#L330

Thanks in advance for your consideration!

**Comment by adrienjoly** [comment]
Here's how I tried to re-publish it:

1. `$ git push --delete origin v1.20.0` (to delete the tag that semantic-release created on GitHub, before failing to publish)
2. Restart the build on Travis CI

Unfortunately, the publication was skipped for the following reason:

`ℹ  The local branch master is behind the remote one, therefore a new version won't be published.` (https://travis-ci.org/github/adrienjoly/chrome-next-step-for-trello/builds/690397467#L286)

=> I guess that I have to create a new version?

**Comment by adrienjoly** [comment]
Update: creating another version (with minor/patch changes) solved the issue.

Learnings: It's better to not delete tags created by semantic-release, even if the publication failed. 😅 (I had to recreate the `v1.20.0` tag manually, after the consequence explained above)

Proposed change: in the Pull Request created by semantic-release upon failure to publish to Chrome Web Store, invite the developer to submit another change, a little bit later, to trigger the publication of another version.

**Comment by gr2m** [comment]
Glad you got it worked out 👍
