### ISSUE TITLE
Log error about promise rejection

### ISSUE THREAD

**Issue by hmendezm** [semantic-release/semantic-release#1572]
## Current behavior

 The Azure pipeline finished without error but when I checked the task semantic-release, I see the error below. I am not sure If it is working or not. if something did not finish. I do not see a new tag

## Expected behavior

Not error at all.

## Environment

- **semantic-release** version: 17.0.8
- CI environment:  azure
- Plugins used: 
 "release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/npm",
        {
          "npmPublish": false
        }
      ],
      "@semantic-release/changelog",
      "@semantic-release/git"
    ],
    "branch":  ["master", "develop"]
  }
- CI logs: 
2020-06-04T17:24:00.5581559Z ##[section]Starting: Semantic Release
2020-06-04T17:24:01.3404679Z ==============================================================================
2020-06-04T17:24:01.3405040Z Task         : Semantic Release Freestyle
2020-06-04T17:24:01.3405376Z Description  : Task for simplifying Semantic Release (0.0.53)
2020-06-04T17:24:01.3405637Z Version      : 0.0.53
2020-06-04T17:24:01.3405868Z Author       : Daniel Habenicht
2020-06-04T17:24:01.3406224Z Help         : https://github.com/DanielHabenicht/AzurePipelines-SemanticRelease/issues
2020-06-04T17:24:01.3406617Z ==============================================================================
2020-06-04T17:24:02.3406982Z (node:1720) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
2020-06-04T17:24:02.3407897Z     at Object.readSync (fs.js:498:3)
2020-06-04T17:24:02.3408363Z     at tryReadSync (fs.js:332:20)
2020-06-04T17:24:02.3408856Z     at Object.readFileSync (fs.js:369:19)
2020-06-04T17:24:02.3409633Z     at Function.getConfig (D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\utility\utility.js:134:38)
2020-06-04T17:24:02.3410689Z     at D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\index.js:26:42
2020-06-04T17:24:02.3411318Z     at Generator.next (<anonymous>)
2020-06-04T17:24:02.3411927Z     at D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\index.js:8:71
2020-06-04T17:24:02.3412548Z     at new Promise (<anonymous>)
2020-06-04T17:24:02.3413208Z     at __awaiter (D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\index.js:4:12)
2020-06-04T17:24:02.3413985Z     at run (D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\index.js:24:12)
2020-06-04T17:24:02.3414820Z (node:1720) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
2020-06-04T17:24:02.3415790Z (node:1720) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
2020-06-04T17:24:02.3419916Z ##[section]Finishing: Semantic Release

**Comment by gr2m** [comment]
what is the `getConfig` function at `D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\utility\utility.js:134:38`? Is it part of semantic-release?

**Comment by hmendezm** [comment]
it has to be. I am just using the semantic task.  if you see the whole log, this function is inside the task. Please find more info
### Full log
Starting: Semantic Release
Task         : Semantic Release Freestyle
Description  : Task for simplifying Semantic Release (0.0.53)
Version      : 0.0.53
Author       : Daniel Habenicht
Help         : https://github.com/DanielHabenicht/AzurePipelines-SemanticRelease/issues

(node:1352) UnhandledPromiseRejectionWarning: Error: EISDIR: illegal operation on a directory, read
    at Object.readSync (fs.js:498:3)
    at tryReadSync (fs.js:332:20)
    at Object.readFileSync (fs.js:369:19)
    at Function.getConfig (D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\utility\utility.js:134:38)
    at D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\index.js:26:42
    at Generator.next (<anonymous>)
    at D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\index.js:4:12)
    at run (D:\a\_tasks\freestyle_87a45e6c-a243-455c-861d-37404e26212d\0.0.53\index.js:24:12)
(node:1352) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1352) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Finishing: Semantic Release

### PIpeline setup below

![image](https://user-images.githubusercontent.com/1881431/83882922-c5ea3f80-a710-11ea-9a20-103674a631a6.png)
![image](https://user-images.githubusercontent.com/1881431/83882581-54aa8c80-a710-11ea-84bc-fa0a90ee4440.png)
![image](https://user-images.githubusercontent.com/1881431/83882651-6d1aa700-a710-11ea-988c-80103c218953.png)

**Comment by hmendezm** [comment]
Hey Gregor, did I post this error in the wrong place? this is about semantic azure pipeline Task created by Daniel Habenicht

**Comment by gr2m** [comment]
ah yes, maybe create an issue with the the plugin, or update the issue title & ping Daniel here
