### ISSUE TITLE
Support custom location of the configuration file (`package.json`/`.releaserc`)

### ISSUE THREAD

**Issue by jcornaz** [semantic-release/semantic-release#1592]
## New feature motivation

When I have a complex release process with many scripts being invoked by `@semantic-release/exec`, then I'd like to put everything related to the release process into a `.release` folder of my repository. That way, I can keep everything neat and organized, rather that having everything on the root of the repository.

Yes I know, I can put my script anywhere I want. But, it turns out the `package.json` and `package.lock` (or `.releaserc`) are *also* release-related (in non-javascript project). So it would make sense, and improve organization to put these configuration files `.release` folder too. Otherwise, I am just confusing my teammates, who'd see a `.release` folder not containing the release process config...

## New feature description

It is already possible to use different [file name and format](https://semantic-release.gitbook.io/semantic-release/usage/configuration#configuration-file).

It would be nice to be also able to chose the location of the file.

Example: 

```
semantic-release --config .release/package.json
```

or 

```
semantic-release --config .release/.releaserc.yml
```

**Comment by abbottdev** [comment]
Can you use the `--extends` parameter? You can pass it a filepath 😄

**Comment by jcornaz** [comment]
> Can you use the --extends parameter? You can pass it a filepath 😄

Can you show a complete example? Sorry but it isn't clear to me.

I looked at https://semantic-release.gitbook.io/semantic-release/usage/configuration#options and thought `--extends` was for *shared configurations*. (which is not what I want)

Nevertheless from https://semantic-release.gitbook.io/semantic-release/usage/shareable-configurations I understood that a shared configurations is: 

> is an npm package that exports a semantic-release configuration object

But I don't want to create a npm package that and export an object.


Maybe what I'm asking for, is indeed already available, but only need to be clarified in the documentation.

**Comment by dominykas** [comment]
> But I don't want to create a npm package.

The docs say:

> List of modules or file paths

It can be a simple module (i.e. a js file), if you give it a full path.

**Comment by jcornaz** [comment]
>The docs say:
>
>> List of modules or file paths
>
> It can be a simple module (i.e. a js file), if you give it a full path.

The docs actually say:

> List of modules or file paths containing a shareable configuration.

(It seems like you missed the *containing a shareable configuration* part of the sentence).

Reading about [shareable configuration](https://semantic-release.gitbook.io/semantic-release/usage/shareable-configurations), it doesn't look like what I'm after.

Maybe I'm not clear. Are you saying that `semantic-release --extends .release/config.yaml` would consider the yaml config file, and not require a `package.json` on the root of my repository?

**Comment by waynevanson** [comment]
> Maybe I'm not clear. Are you saying that semantic-release --extends ./.release/config.yaml would consider the yaml config file, and not require a package.json on the root of my repository?

@jcornaz yes. `--extends` is analogous to `--config`

> Reading about shareable configuration, it doesn't look like what I'm after.

Shareable configuration is just a configuration file, which you load in with `--extends`.

I just tried this with `semantic-release --extends ./.config/semantic-release.json` and it worked.

This might be worth mentioning in the docs for clarity. I feel this issue has been answered and could be closed.

**Comment by jcornaz** [comment]
> I just tried this with semantic-release --extends ./.config/semantic-release.json and it worked.

Would it work if the config is a `yaml` file?

> This might be worth mentioning in the docs for clarity.

Definitely.

> I feel this issue has been answered and could be closed.

If documentation must be updated, then this issue is not yet solved.

**Comment by zioalex** [comment]
It doesn't work for me:
```
semantic-release --extends ~/.releaserc
[8:34:18 AM] [semantic-release] › ℹ  Running semantic-release version 17.4.2
[8:34:18 AM] [semantic-release] › ✖  An error occurred while running semantic-release: /home/AzDevOps/.releaserc:2
"branches": ["master", "next", "development"],
          ^

SyntaxError: Unexpected token ':'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /home/AzDevOps/node_modules/semantic-release/lib/get-config.js:29:32
    at Array.reduce (<anonymous>)
    at module.exports (/home/AzDevOps/node_modules/semantic-release/lib/get-config.js:28:33)
/home/AzDevOps/.releaserc:2
"branches": ["master", "next", "development"],
```
Where the .releaserc is a standard config file:
```
{
"branches": ["master", "next", "development"],
"plugins": [
        ["@semantic-release/commit-analyzer", {
                "preset": "eslint"
        }],
        "@semantic-release/release-notes-generator",
        ["@semantic-release/exec", {
                "publishCmd": "~/publish.sh ${nextRelease.version}"
                }],
# '@semantic-release/changelog', # Doesn't work out of the box with ADO
        ],
ci: false # Needed because ADO is not recognized as a CI system
}
```
Any other ideas?

**Comment by brianpham** [comment]
Doesn't work for me as well when I am pointing to <dir>/.releaserc file. I am getting the same error as @zioalex. Anyone found a solution for this?

**Comment by Tommyf** [comment]
How timely, I was just looking for a way to do this.

In my case, I would like a different `@semantic-release/changelog` configuration for different branches. This is because I dislike all the duplication in the `CHANGELOG.md` when promoting a pre-release branch. This was [discussed](https://github.com/semantic-release/changelog/issues/51) [many](https://github.com/semantic-release/changelog/issues/62) [times](https://github.com/semantic-release/changelog/pull/157) but there seems to be no current solution.

So I decided a separate config would make sense, but I just found I cannot specify the config as a parameter.

So now i'm just going to copy the appropriate config to `.releaserc.yml` before running `semver-release`. Hacky :/

**Comment by Intregrisist** [comment]
Confirmed, it does exactly what I expected. I agree with @jcornaz, if there is still confusion the documentation needs to be updated for this issue to be resolved.

**Comment by BinToss** [comment]
```
Error: Cannot find module './node/.releaserc.yml'
Require stack:
- C:\Repos\HaloSPV3\HCE.Shared\file:\C:\Repos\HaloSPV3\HCE.Shared\node\dist\node\noop.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at resolveFileName (C:\Repos\HaloSPV3\HCE.Shared\node_modules\resolve-from\index.js:29:39)
    at resolveFrom (C:\Repos\HaloSPV3\HCE.Shared\node_modules\resolve-from\index.js:43:9)
    at module.exports (C:\Repos\HaloSPV3\HCE.Shared\node_modules\resolve-from\index.js:46:47)
>   at file:///C:/Repos/HaloSPV3/HCE.Shared/node_modules/semantic-release/lib/get-config.js:38:85
    at async default (file:///C:/Repos/HaloSPV3/HCE.Shared/node_modules/semantic-release/lib/get-config.js:36:11)
    at async optionB (file:///C:/Repos/HaloSPV3/HCE.Shared/node/dist/index.mjs:63:21)
    at async main (file:///C:/Repos/HaloSPV3/HCE.Shared/node/dist/index.mjs:68:12)
```
https://github.com/semantic-release/semantic-release/blob/9e10e44fed366434d2f5de7f10398edb025b2101/lib/get-config.js#L38

I've traced the issue to an `OR` operation that calls two functions. The first function call (`resolveFrom.silent(__dirname, extendP`) throws the exception—it's trying to find a CJS/ES module and is treating the supplied path as module name. That function doesn't seem as silent as its name implies. The second one works as expected and is what allows us to use many different files and paths for our config file/object.

# Semantic Release inherently supports many config variations e.g. ".releaserc.yaml"
It leverages [cosmiconfig](https://github.com/cosmiconfig/cosmiconfig) to load your config file/object. Semantic-release calls cosmiconfig and passes "release" for the moduleName parameter and allows API users to specify the directory to look under (if unspecified, defaults to the process's current working directory). Cosmiconfig 8.20.0 searches a named entry in package.json and/or a file by name at the following paths:
```js
searchPlaces: [
  'package.json',
  `.${moduleName}rc`,
  `.${moduleName}rc.json`,
  `.${moduleName}rc.yaml`,
  `.${moduleName}rc.yml`,
  `.${moduleName}rc.js`,
  `.${moduleName}rc.cjs`,
  `.${moduleName}rc.mjs`,
  `.config/${moduleName}rc`,
  `.config/${moduleName}rc.json`,
  `.config/${moduleName}rc.yaml`,
  `.config/${moduleName}rc.yml`,
  `.config/${moduleName}rc.js`,
  `.config/${moduleName}rc.cjs`,
  `.config/${moduleName}rc.mjs`,
  `${moduleName}.config.js`,
  `${moduleName}.config.cjs`,
  `${moduleName}.config.mjs`
].filter(Boolean),
```

**Comment by easingthemes** [comment]
I'm using https://www.npmjs.com/package/semantic-release-monorepo, for monorepo / npm workspaces.
```
|packages
  |--a
  |--b
```
Each package has it's own npm script `semantic-release`. Configuration is exactly the same.
```
{
extends: 'semantic-release-monorepo',
}
```
`extends` can not be used here since it will override existing on in shared config.
Via CI command is executed as
``` npm run release --workspaces```
which will run npm script in each package.
Currently I have a step before the release to copy common config to all packages.
For this situation custom location of a config file would be very useful.

**Comment by BinToss** [comment]
@easingthemes `extends` can be an array. You can also extend from a (non-YAML, non-TS) config file which extends from another and so on.
In array form, the first config file or module is copied to a variable. All properties of subsequent configs _overwrite_ the value already present in the variable's correpsonding property.

If you need to merge array-type or object-type properties, or insert plugins or plugin configs into the plugins array, you'll need to use CJS or MJS to do so.

**Comment by alwaystom** [comment]
by using release.config.js, --extends is useless, and it will throw  Error: Cannot find module '@semantic-release/commit-analyzer

**Comment by jebeaudet** [comment]
In our case, we want to build a golden CI path where we control and enforce the configuration of semantic-release. We currently use a `release.config.mjs` to workaround the limitation of not supporting maintenance branches with a prefix ([reference](https://github.com/semantic-release/semantic-release/issues/1623#issuecomment-871700509). Unfortunately, `mjs` file have a lower precedance in `cosmiconfig` which means that if the repo has a `.releaserc.json` file, it'll get picked up instead of ours.

Having a simple `--config-file-location` switch would be perfect for us since it would guarantee us that semantic-release is using the file we want to use and trust.

**Comment by BinToss** [comment]
> Having a simple `--config-file-location` switch would be perfect for us since it would guarantee us that semantic-release is using the file we want to use and trust.

A `--config <file-path>` option may be more intuitive because that convention is common in the JavaScript ecosystem.

**Comment by jonapich** [comment]
A `--config` switch has been implemented, now waiting for code review and merge.
