### ISSUE TITLE
git ls-remote --heads uses http url instead of ssh

### ISSUE THREAD

**Issue by gempain** [semantic-release/semantic-release#1632]
## Current behavior

I'm trying to release a private Github repo configured to use SSH. semantic-release fails with the following error:
```
Command failed with exit code 128: git ls-remote --heads https://github.com/my/repo
```

## Expected behavior

My repo is configured with an SSH URL:

```
$ git remote get-url origin
git@github.com:my/repo.git
```

and I've configured a deploy key in the Github repo and the private key is properly configured using `ssh-add`. I don't understand where `--heads https://github.com/my/repo` is coming from and why it's not `--heads git@github.com:my/repo.git`.

## Environment

- **semantic-release** version: 17.1.1
- CI environment: n/a
- Plugins used: 
- **semantic-release** configuration: 
```js
module.exports = {
  branches: ["master"],
  plugins: [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    ["@semantic-release/git", {
      "assets": ['CHANGELOG.md', 'package.json'],
    }],
    // "@semantic-release/npm",
  ],
};
```
- CI logs:
```
$ npm run release

> my-package@1.0.0 release /repo
> semantic-release

[12:53:18 PM] [semantic-release] › ℹ Running semantic-release version 17.1.1
[12:53:18 PM] [semantic-release] › ✔ Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[12:53:18 PM] [semantic-release] › ✔ Loaded plugin "verifyConditions" from "@semantic-release/git"
[12:53:18 PM] [semantic-release] › ✔ Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:53:18 PM] [semantic-release] › ✔ Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:53:18 PM] [semantic-release] › ✔ Loaded plugin "prepare" from "@semantic-release/changelog"
[12:53:18 PM] [semantic-release] › ✔ Loaded plugin "prepare" from "@semantic-release/git"
[12:53:18 PM] [semantic-release] › ⚠ This run was not triggered in a known CI environment, running in dry-run mode.
[12:53:19 PM] [semantic-release] › ✖ An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://github.com/my/repo
fatal: could not read Username for 'https://github.com': No such device or address
at makeError (/repo/node_modules/execa/lib/error.js:59:11)
at handlePromise (/repo/node_modules/execa/index.js:114:26)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async getBranches (/repo/node_modules/semantic-release/lib/git.js:66:11)
at async module.exports (/repo/node_modules/semantic-release/lib/branches/expand.js:6:23)
at async module.exports (/repo/node_modules/semantic-release/lib/branches/index.js:14:26)
at async run (/repo/node_modules/semantic-release/index.js:57:22)
at async module.exports (/repo/node_modules/semantic-release/index.js:260:22)
at async module.exports (/repo/node_modules/semantic-release/cli.js:55:5) {
shortMessage: 'Command failed with exit code 128: git ls-remote --heads https://github.com/my/repo',
command: 'git ls-remote --heads https://github.com/my/repo',
exitCode: 128,
signal: undefined,
signalDescription: undefined,
stdout: '',
stderr: "fatal: could not read Username for 'https://github.com': No such device or address",
failed: true,
timedOut: false,
isCanceled: false,
killed: false
}
Error: Command failed with exit code 128: git ls-remote --heads https://github.com/my/repo
fatal: could not read Username for 'https://github.com': No such device or address
at makeError (/repo/node_modules/execa/lib/error.js:59:11)
at handlePromise (/repo/node_modules/execa/index.js:114:26)
at processTicksAndRejections (internal/process/task_queues.js:97:5)
at async getBranches (/repo/node_modules/semantic-release/lib/git.js:66:11)
at async module.exports (/repo/node_modules/semantic-release/lib/branches/expand.js:6:23)
at async module.exports (/repo/node_modules/semantic-release/lib/branches/index.js:14:26)
at async run (/repo/node_modules/semantic-release/index.js:57:22)
at async module.exports (/repo/node_modules/semantic-release/index.js:260:22)
at async module.exports (/repo/node_modules/semantic-release/cli.js:55:5) {
shortMessage: 'Command failed with exit code 128: git ls-remote --heads https://github.com/my/repo',
command: 'git ls-remote --heads https://github.com/my/repo',
exitCode: 128,
signal: undefined,
signalDescription: undefined,
stdout: '',
stderr: "fatal: could not read Username for 'https://github.com': No such device or address",
failed: true,
timedOut: false,
isCanceled: false,
killed: false
}npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-package@1.0.0 release: `semantic-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-package@1.0.0 release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2020-09-07T12_53_19_326Z-debug.log
command exited with code 1
```

**Comment by gempain** [comment]
Okay, found it... semantic-release is using `repository.url` from my `package.json`. I had to force it to use the SSH url via the CLI:
```
npm run release -- --dry-run --repositoryUrl "$(git remote get-url origin | tr -d '\n')"
```

I wasn't expecting this behavior. I would expect semantic-release to use the repository URL set for remote `origin` and be able to change the default remote in the CLI with `--remote`.

**Comment by ch264** [comment]
@gempain I have the same issue and found this response in another comment:

https://github.com/semantic-release/semantic-release/issues/951#issuecomment-430690908

If the repositoryUrl is configured as a git or ssh URL, the git command line tries to use ssh. If you have some ssh keys in your environment and those doesn't give you permission to access your repo, then the error occurs. This could be what is happening in my place

**Comment by fang-hd** [comment]
how to solve this problem
