### ISSUE TITLE
npm: semantic release does not increase the version

### ISSUE THREAD

**Issue by aminya** [semantic-release/semantic-release#1636]
## Current behavior

I used to use semantic-release without any issues, but lately it always fails saying that the tag already exists.

https://github.com/atom-ide-community/babel-preset-atomic/runs/1104804194#step:6:52

## Expected behavior

Increase the version based on the commit message

## Environment
https://github.com/atom-ide-community/babel-preset-atomic

- **semantic-release** version: 17.1.1 
- CI environment: GitHub actions
- Plugins used: npm
- **semantic-release** configuration: 
https://github.com/atom-ide-community/babel-preset-atomic/blob/15a4d431426f5e2fcf89a51ff7a94b9836b85f71/.github/workflows/CI.yml#L48
```
        uses: cycjimmy/semantic-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
```

- CI logs: 
```
2020-09-12T03:13:13.1365987Z ##[group]Run cycjimmy/semantic-release-action@v2
2020-09-12T03:13:13.1366513Z with:
2020-09-12T03:13:13.1366752Z env:
2020-09-12T03:13:13.1367000Z   DISPLAY: :99
2020-09-12T03:13:13.1368401Z   GITHUB_TOKEN: ***
2020-09-12T03:13:13.1368814Z   NPM_TOKEN: ***
2020-09-12T03:13:13.1369087Z ##[endgroup]
2020-09-12T03:13:14.4624689Z added 2 packages in 0.724s
2020-09-12T03:13:14.4635879Z 
2020-09-12T03:13:33.1077740Z [3:13:32 AM] [semantic-release] › ℹ  Running semantic-release version 17.1.1
2020-09-12T03:13:33.3103368Z [3:13:33 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
2020-09-12T03:13:33.3114685Z [3:13:33 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
2020-09-12T03:13:33.3116788Z [3:13:33 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2020-09-12T03:13:33.3118863Z [3:13:33 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2020-09-12T03:13:33.3120767Z [3:13:33 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
2020-09-12T03:13:33.3122258Z [3:13:33 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
2020-09-12T03:13:33.3123751Z [3:13:33 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
2020-09-12T03:13:33.3125347Z [3:13:33 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
2020-09-12T03:13:33.3157185Z [3:13:33 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
2020-09-12T03:13:33.3163411Z [3:13:33 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
2020-09-12T03:13:33.3166544Z [3:13:33 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
2020-09-12T03:13:34.7107909Z [3:13:34 AM] [semantic-release] › ✔  Run automated release from branch master on repository https://github.com/atom-ide-community/babel
2020-09-12T03:13:35.0106156Z [3:13:35 AM] [semantic-release] › ✔  Allowed to push to the Git repository
2020-09-12T03:13:35.0114887Z [3:13:35 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
2020-09-12T03:13:35.0381518Z [3:13:35 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
2020-09-12T03:13:35.0426783Z [3:13:35 AM] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /tmp/b00db7179785d14f25e93f70d53de7cc/.npmrc
2020-09-12T03:13:35.7903211Z atom-ide-community
2020-09-12T03:13:35.7965728Z [3:13:35 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
2020-09-12T03:13:35.7968060Z [3:13:35 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
2020-09-12T03:13:35.7990716Z [3:13:35 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
2020-09-12T03:13:35.8088683Z [3:13:35 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
2020-09-12T03:13:35.8161775Z [3:13:35 AM] [semantic-release] › ℹ  Found git tag v2.2.0 associated with version 2.2.0 on branch master
2020-09-12T03:13:35.8276125Z [3:13:35 AM] [semantic-release] › ℹ  Found 4 commits since last release
2020-09-12T03:13:35.8278258Z [3:13:35 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
2020-09-12T03:13:35.8356053Z [3:13:35 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: add babel-plugin-transform-not-strict
2020-09-12T03:13:35.8363983Z [3:13:35 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
2020-09-12T03:13:35.8366261Z [3:13:35 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: [skip ci]
2020-09-12T03:13:35.8368648Z [3:13:35 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
2020-09-12T03:13:35.8370664Z [3:13:35 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: react and flow options
2020-09-12T03:13:35.8372666Z [3:13:35 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
2020-09-12T03:13:35.8374407Z [3:13:35 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: v 2.2.0
2020-09-12T03:13:35.8377092Z [3:13:35 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
2020-09-12T03:13:35.8378729Z [3:13:35 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 4 commits complete: minor release
2020-09-12T03:13:35.8380460Z [3:13:35 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
2020-09-12T03:13:35.8452087Z [3:13:35 AM] [semantic-release] › ℹ  The next release version is 2.3.0
2020-09-12T03:13:35.8488306Z [3:13:35 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2020-09-12T03:13:35.9405436Z [3:13:35 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2020-09-12T03:13:35.9408568Z [3:13:35 AM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
2020-09-12T03:13:35.9491299Z [3:13:35 AM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 2.3.0 to package.json in /home/runner/work/babel-preset-atomic/babel-preset-atomic
2020-09-12T03:13:36.2300492Z v2.3.0
2020-09-12T03:13:36.2713809Z [3:13:36 AM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
2020-09-12T03:13:36.2850549Z [3:13:36 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git tag v2.3.0 15a4d431426f5e2fcf89a51ff7a94b9836b85f71
2020-09-12T03:13:36.2852040Z fatal: tag 'v2.3.0' already exists
2020-09-12T03:13:36.2853164Z     at makeError (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/execa/lib/error.js:59:11)
2020-09-12T03:13:36.2854605Z     at handlePromise (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/execa/index.js:114:26)
2020-09-12T03:13:36.2855684Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-09-12T03:13:36.2857062Z     at async tag (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/lib/git.js:224:3)
2020-09-12T03:13:36.2858573Z     at async run (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js:191:5)
2020-09-12T03:13:36.2860218Z     at async module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js:260:22)
2020-09-12T03:13:36.2861673Z     at async release (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/src/index.js:25:18) {
2020-09-12T03:13:36.2862991Z   shortMessage: 'Command failed with exit code 128: git tag v2.3.0 15a4d431426f5e2fcf89a51ff7a94b9836b85f71',
2020-09-12T03:13:36.2864126Z   command: 'git tag v2.3.0 15a4d431426f5e2fcf89a51ff7a94b9836b85f71',
2020-09-12T03:13:36.2864672Z   exitCode: 128,
2020-09-12T03:13:36.2865095Z   signal: undefined,
2020-09-12T03:13:36.2865556Z   signalDescription: undefined,
2020-09-12T03:13:36.2866097Z   stdout: '',
2020-09-12T03:13:36.2866657Z   stderr: "fatal: tag 'v2.3.0' already exists",
2020-09-12T03:13:36.2867038Z   failed: true,
2020-09-12T03:13:36.2867342Z   timedOut: false,
2020-09-12T03:13:36.2867699Z   isCanceled: false,
2020-09-12T03:13:36.2868036Z   killed: false
2020-09-12T03:13:36.2868311Z }
2020-09-12T03:13:36.2874607Z ##[error]Error: Command failed with exit code 128: git tag v2.3.0 15a4d431426f5e2fcf89a51ff7a94b9836b85f71
fatal: tag 'v2.3.0' already exists
2020-09-12T03:13:36.3041023Z Post job cleanup.
2020-09-12T03:13:36.4283612Z [command]/usr/bin/git version
2020-09-12T03:13:36.4357177Z git version 2.28.0
2020-09-12T03:13:36.4403849Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2020-09-12T03:13:36.4458310Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 
```

**Comment by travi** [comment]
this is because the tag `v2.3.0` exists in the repository, but is not on the branch that you are releasing from. from https://github.com/atom-ide-community/babel-preset-atomic/commit/73c476d0a9e8be8a26b81d1c8ca0757a4d09cb8d, i can see that the commit that the tag is associated with "does not belong to any branch on this repository."

**Comment by aminya** [comment]
How is that possible? semantic bot created the tag itself. I didn't tell it what to do.

https://github.com/atom-ide-community/babel-preset-atomic/releases

**Comment by travi** [comment]
is it possible that history was rewritten in some way after the tag was created? thats the most common was situations like this come up

**Comment by aminya** [comment]
Hmm, 🤔 Maybe I have forced pushed by mistake. Yes, that could be it. 

So, what is the solution? Can't you detect this?

**Comment by travi** [comment]
semantic-release needs to look for the version tag in the current branch. rewriting history removes the tagged commit from the linear history of the branch, so semantic-release isn't able to find it in the branch. this is the nature of git and outside the scope of semantic-release. 

we recommend using the branch protection provided by github to prevent accidentally rewriting history on any release branches, such as `master`, `alpha`, `beta`

**Comment by manuviswam** [comment]
How to solve the issue once the history is rewritten?

**Comment by travi** [comment]
https://semantic-release.gitbook.io/semantic-release/support/troubleshooting#release-not-found-release-branch-after-git-push-force
