### ISSUE TITLE
branches config not used by the CLI / can't use 'release' as a branch name

### ISSUE THREAD

**Issue by khaledosman** [semantic-release/semantic-release#1643]
## Current behavior
My release branch config is not seen by the cli.

## Expected behavior

expected my branch to be seen and the command to proceed successfully

## Environment

- **semantic-release** version: 17.1.1 
- CI environment: No-CI / Dry run mode locally 
- Plugins used: 
    "@semantic-release/changelog": "^5.0.1",
    "@semantic-release/commit-analyzer": "^8.0.1",
    "@semantic-release/exec": "^5.0.0",
    "@semantic-release/git": "^9.0.0",
    "@semantic-release/npm": "^7.0.5",
    "@semantic-release/release-notes-generator": "^9.0.1",
- **semantic-release** configuration: 
```json
"release": {
    "branches": [
      "release"
    ],
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      [
        "@semantic-release/npm",
        {
          "npmPublish": false
        }
      ],
      "@semantic-release/git",
      [
        "@semantic-release/exec",
        {
          "publishCmd": "npm run bump-versions"
        }
      ],
      [
        "semantic-release-slack-bot",
        {
          "notifyOnSuccess": true,
          "notifyOnFail": false,
          "onSuccessTemplate": {
            "text": "A new version of $package_name with version $npm_package_version has been released at $repo_url ! \n $release_notes"
          },
          "markdownReleaseNotes": true
        }
      ]
    ]
  },
```
- CI logs: 
```sh
yarn run v1.22.10
$ npx semantic-release
[1:55:40 PM] [semantic-release] › ℹ  Running semantic-release version 17.1.2
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-slack-bot"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/exec"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "success" from "semantic-release-slack-bot"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
[1:55:41 PM] [semantic-release] › ✔  Loaded plugin "fail" from "semantic-release-slack-bot"
[1:55:41 PM] [semantic-release] › ⚠  This run was not triggered in a known CI environment, running in dry-run mode.
[1:55:44 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/exec" in dry-run mode
[1:55:44 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "semantic-release-slack-bot" in dry-run mode
[1:55:44 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration.

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].

AggregateError:
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/lib/get-error.js:6:10)
        at /Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/lib/branches/index.js:44:19
        at Array.reduce (<anonymous>)
        at module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/lib/branches/index.js:34:46)
        at async run (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/index.js:57:22)
        at async module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/index.js:260:22)
        at async module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/cli.js:55:5)
    at module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/lib/branches/index.js:66:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/index.js:57:22)
    at async module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/index.js:260:22)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by gr2m** [comment]
could you run `npx semantic-release --debug`? It might log more clues to help identify the cause of the problem

**Comment by khaledosman** [comment]
```
$ npx semantic-release --debug
[9:19:45 PM] [semantic-release] › ℹ  Running semantic-release version 17.1.2
  semantic-release:config load config from: /Users/khaledosman/Documents/github/webapp/package.json +0ms
  semantic-release:config options values: {
  semantic-release:config   branches: [ 'release' ],
  semantic-release:config   repositoryUrl: 'https://github.com/vantik/webapp.git',
  semantic-release:config   tagFormat: 'v${version}',
  semantic-release:config   plugins: [
  semantic-release:config     '@semantic-release/commit-analyzer',
  semantic-release:config     '@semantic-release/release-notes-generator',
  semantic-release:config     '@semantic-release/changelog',
  semantic-release:config     [ '@semantic-release/npm', [Object] ],
  semantic-release:config     '@semantic-release/git',
  semantic-release:config     [ '@semantic-release/exec', [Object] ],
  semantic-release:config     [ 'semantic-release-slack-bot', [Object] ]
  semantic-release:config   ],
  semantic-release:config   _: [],
  semantic-release:config   debug: true,
  semantic-release:config   '$0': 'node_modules/.bin/semantic-release'
  semantic-release:config } +4ms
  semantic-release:plugins options for @semantic-release/changelog/verifyConditions: {} +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
  semantic-release:plugins options for @semantic-release/npm/verifyConditions: { npmPublish: false } +2ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/git/verifyConditions: {} +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
  semantic-release:plugins options for @semantic-release/exec/verifyConditions: { publishCmd: 'npm run bump-versions' } +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
  semantic-release:plugins options for semantic-release-slack-bot/verifyConditions: {
  semantic-release:plugins   notifyOnSuccess: true,
  semantic-release:plugins   notifyOnFail: false,
  semantic-release:plugins   onSuccessTemplate: {
  semantic-release:plugins     text: 'A new version of $package_name with version $npm_package_version has been released at $repo_url ! \n' +
  semantic-release:plugins       ' $release_notes'
  semantic-release:plugins   },
  semantic-release:plugins   markdownReleaseNotes: true
  semantic-release:plugins } +1ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "semantic-release-slack-bot"
  semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {} +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
  semantic-release:plugins options for @semantic-release/exec/analyzeCommits: { publishCmd: 'npm run bump-versions' } +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
  semantic-release:plugins options for @semantic-release/exec/verifyRelease: { publishCmd: 'npm run bump-versions' } +1ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
  semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {} +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
  semantic-release:plugins options for @semantic-release/exec/generateNotes: { publishCmd: 'npm run bump-versions' } +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
  semantic-release:plugins options for @semantic-release/changelog/prepare: {} +1ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
  semantic-release:plugins options for @semantic-release/npm/prepare: { npmPublish: false } +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/git/prepare: {} +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
  semantic-release:plugins options for @semantic-release/exec/prepare: { publishCmd: 'npm run bump-versions' } +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
  semantic-release:plugins options for @semantic-release/npm/publish: { npmPublish: false } +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/exec/publish: { publishCmd: 'npm run bump-versions' } +1ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
  semantic-release:plugins options for @semantic-release/npm/addChannel: { npmPublish: false } +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
  semantic-release:plugins options for @semantic-release/exec/addChannel: { publishCmd: 'npm run bump-versions' } +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/exec"
  semantic-release:plugins options for @semantic-release/exec/success: { publishCmd: 'npm run bump-versions' } +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
  semantic-release:plugins options for semantic-release-slack-bot/success: {
  semantic-release:plugins   notifyOnSuccess: true,
  semantic-release:plugins   notifyOnFail: false,
  semantic-release:plugins   onSuccessTemplate: {
  semantic-release:plugins     text: 'A new version of $package_name with version $npm_package_version has been released at $repo_url ! \n' +
  semantic-release:plugins       ' $release_notes'
  semantic-release:plugins   },
  semantic-release:plugins   markdownReleaseNotes: true
  semantic-release:plugins } +1ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "success" from "semantic-release-slack-bot"
  semantic-release:plugins options for @semantic-release/exec/fail: { publishCmd: 'npm run bump-versions' } +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
  semantic-release:plugins options for semantic-release-slack-bot/fail: {
  semantic-release:plugins   notifyOnSuccess: true,
  semantic-release:plugins   notifyOnFail: false,
  semantic-release:plugins   onSuccessTemplate: {
  semantic-release:plugins     text: 'A new version of $package_name with version $npm_package_version has been released at $repo_url ! \n' +
  semantic-release:plugins       ' $release_notes'
  semantic-release:plugins   },
  semantic-release:plugins   markdownReleaseNotes: true
  semantic-release:plugins } +0ms
[9:19:45 PM] [semantic-release] › ✔  Loaded plugin "fail" from "semantic-release-slack-bot"
[9:19:45 PM] [semantic-release] › ⚠  This run was not triggered in a known CI environment, running in dry-run mode.
  semantic-release:get-git-auth-url Verifying ssh auth by attempting to push to  https://github.com/vantik/webapp.git +0ms
[9:19:49 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/exec" in dry-run mode
[9:19:49 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "semantic-release-slack-bot" in dry-run mode
[9:19:49 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration.

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].

AggregateError:
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/lib/get-error.js:6:10)
        at /Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/lib/branches/index.js:44:19
        at Array.reduce (<anonymous>)
        at module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/lib/branches/index.js:34:46)
        at async run (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/index.js:57:22)
        at async module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/index.js:260:22)
        at async module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/cli.js:55:5)
    at module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/lib/branches/index.js:66:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async run (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/index.js:57:22)
    at async module.exports (/Users/khaledosman/Documents/github/webapp/node_modules/semantic-release/index.js:260:22)
```

**Comment by gr2m** [comment]
Do you have a `release` branch in your repository?

**Comment by khaledosman** [comment]
not sure, how do I set that up? does that have to be the `default` branch in the repository settings?

**Comment by khaledosman** [comment]
only locally, but its not pushed in the repository yet, perhaps thats the problem

**Comment by khaledosman** [comment]
yup, that was indeed the case, creating/pushing the actual branch fixed the issue

**Comment by gr2m** [comment]
I think there is an opportunity here to improve the error message, I'm sure you won't be the last person to run into this. I will create a follow up issue. Thanks Khaled!

**Comment by gr2m** [comment]
here you go: https://github.com/semantic-release/semantic-release/issues/1645
