### ISSUE TITLE
remove tag from GitHub if a subsequent release step fails

### ISSUE THREAD

**Issue by jedwards1211** [semantic-release/semantic-release#1654]
## Current behavior

I'm really not sure if I'm misinterpreting something, because I would think an issue like this would have been fixed long ago, but `semantic-release` seems to be creating a tag on GitHub and leaving that tag in place even if `npm publish` fails.  Meaning that if I push `chore: fix build` next, `semantic-release` thinks it doesn't need to release, since the only commit after the erroneous git tag is a `chore`.

```
[5:27:27 AM] [semantic-release] › ✔  Created tag v1.3.1
[5:27:27 AM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/npm"
[5:27:27 AM] [semantic-release] [@semantic-release/npm] › ℹ  Publishing version 1.3.1 to npm registry on dist-tag latest
npm WARN lifecycle The node binary used for scripts is /tmp/yarn--1602307639683-0.9226842724428059/node but npm is using /usr/local/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> @jedwards1211/js-toolchain@1.3.1 prepublishOnly /home/circleci/project
...

/home/circleci/project/bin/toolchain.js build exited with code 127
    1) works on test project


  0 passing (5s)
  1 failing

  1) toolchain
       works on test project:
     Error: Process exited with code 127
      at ChildProcess.done (node_modules/promisify-child-process/index.cjs:70:19)
      at maybeClose (internal/child_process.js:1021:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
...

  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/npm'
}error Command failed with exit code 1.
```

## Expected behavior

`semantic-release` deletes the tag from GitHub if a subsequent release step fails.

## Environment

- **semantic-release** version: 17.1.2
- CI environment: CircleCI
- Plugins used: default
- **semantic-release** configuration: `{ "publishConfig": { "access": "public" } }`
- CI logs: https://app.circleci.com/pipelines/github/jedwards1211/js-toolchain/36/workflows/b6369a7f-9c26-4ce0-b3ab-1a13cb0113f5/jobs/22

**Comment by jedwards1211** [comment]
I think CircleCI may now be automatically pushing tags created during the build to GitHub if the build succeeds?  (Node that I'm running `semantic-release || true`...)
This image makes it look like it but so far I haven't been able to google for explicit confirmation that this is what CircleCI does.
![image](https://user-images.githubusercontent.com/1448194/95647183-f4976e80-0a92-11eb-8b37-500bf669199e.png)
If this is the case, then we need to figure out how to disable this behavior and add that to the docs for working with CircleCI.

**Comment by gr2m** [comment]
> I'm really not sure if I'm misinterpreting something, because I would think an issue like this would have been fixed long ago, but `semantic-release` seems to be creating a tag on GitHub and leaving that tag in place even if the subsequent `npm publish` fails

That is correct. The NPM and GitHub specific features are plugins, they work independently. `semantic-release` core only checks commit messages and creates tags. There is no "recovery" life cycle hook at this point. And even if there were, some cases are not recoverable. For example, once an npm version was published, it cannot be re-published. 

The lifecycle hooks are documented here: https://semantic-release.gitbook.io/semantic-release/usage/plugins. We could think about adding a "recover" or "reset" lifecycle hook. Independent of how we would call it, it would be called in case one of the other plugins failed. We could also log a warning about the order of plugins, and recommend to run the plugins without a recovery hook at the end, if possible. This would all be a bigger undertaking

> maybe it's long since unnecessary to add the `|| true`?

Correct, it's no longer necessary

**Comment by jedwards1211** [comment]
A recovery hook is an interesting idea.

Since creating and pushing the tag is [done in core](https://github.com/semantic-release/semantic-release/blob/0f0c650b41764d1a3deb33631147c7ca0e39fe59/index.js#L193), rather than a plugin, would a pluggable "recovery" hook even be necesssary?  Seems to me that core could just delete the remote tag ([using a push](https://stackoverflow.com/questions/5480258/how-to-delete-a-remote-tag)) if something failed.

**Comment by jedwards1211** [comment]
If nothing else, semantic-release should warn the user if something fails after the tag is created, with a message something like

> Warning: the new tag v1.2.3 was left in your remote repository even though the release failed.  This will prevent commits since the previous release from being included in the next successful release.  If it's possible to delete all artifacts that got published before failure (if any), then you should delete this tag from your remote repository.

**Comment by jedwards1211** [comment]
@gr2m I probably didn't fully realize this or explain it clearly, but this is a pretty serious issue because unless we manually delete the dangling git tag, *commits between the previous release and the failed release will never get added to GitHub release notes* (or whatever changelog other plugins manage).  In the worst case where the release fails in the middle of a commit with breaking changes, although the major version bump will fortunately remain for the next release, the breaking changes will never get added to the GitHub releases.

I'm changing the title to reflect this...

**Comment by jedwards1211** [comment]
I only became aware of this issue recently because I stopped doing redundant build and test steps before calling `semantic-release` in an effort to speed up my builds.  I assume most people run their build and test steps before release, which can guard against this.  But if people are using a `prepublishOnly` script that could intermittently fail due to race conditions in the tests etc., they're still in danger of this issue.

**Comment by jedwards1211** [comment]
@travi seems like you've been active lately, could I get your opinion about this?

> Since creating and pushing the tag is [done in core](https://github.com/semantic-release/semantic-release/blob/0f0c650b41764d1a3deb33631147c7ca0e39fe59/index.js#L193), rather than a plugin, would a pluggable "recovery" hook even be necessary for this? Seems to me that core could just delete the remote tag ([using a push](https://stackoverflow.com/questions/5480258/how-to-delete-a-remote-tag)) if something failed.

**Comment by jedwards1211** [comment]
> could you help us understand why removing the tag and re-running is not accomplishing what you need?

Two reasons:
- It's just annoying having to go to the trouble to do so.  I started using semantic-release in the first place to do as little manual work as possible...
- It's easy to forget that sometimes a tag has been pushed if a previous build failed.  I only realize when a later build confusingly reports that there are no changes to publish.
 
I haven't ever had a case where I didn't need to remove the tag if something failed after semantic-release pushed it.

> unofficial plugins could still leave core uninformed

I wish there were at least an *option* to delete the tag when something goes wrong

**Comment by travi** [comment]
> I haven't ever had a case where I didn't need to remove the tag if something failed after semantic-release pushed it. What's an example of why you decided not to remove a tag?

also consider the case when semantic-release is configured to commit changes to `package.json` and/or `CHANGELOG.md`. if the release fails after pushing the commit for those updates, the commit would need to be reverted in addition to removal of the tag.

**Comment by jedwards1211** [comment]
Those are interesting points...it makes me think that deciding what's published based on a tag alone isn't necessarily the ideal behavior.  For example, it could look at if the version has actually been published to npm.  I'm bummed that you're happy with the status quo, because I get annoyed by this fairly often.  Maybe because I have a lot more semantic-release packages than most people and the tokens go out of date periodically.

**Comment by travi** [comment]
> I'm bummed that you're happy with the status quo

i have not stated that i am happy with the status quo. your feature request is noted. i'm simply explaining that solving this well would be complex and semantic-release is already complex enough that it is difficult to maintain with a small maintenance team. additional complexity has to be considered in our decisions around what features we are able to prioritize. 

> Maybe because I have a lot more semantic-release packages than most people and the tokens go out of date periodically.

i maintain hundreds of packages across organizations, all with semantic-release. i understand the pain of updating tokens across projects and even wrote a [tool for doing so in travis-ci](https://github.com/travi/travis-token-updater) at one point. 

even with knowing the pain of running into this situation occasionally, the complexity of handling this well in semantic-release is high enough that i'm not able to promise a solution to this any time soon.

**Comment by travi** [comment]
> I guess part of the problem in this case was that the `semantic-release-vsce` plugin doesn't seem to verify the VSCode Marketplace personal access token in its `verifyConditions` step, so if the token expires, it only fails at the `publish` step. I filed an issue in `semantic-release-vsce` about that.

that is a great point to call out. the more that plugins do to avoid this situation the better. obviously, there are cases where the check will still miss some cases, but attempting to verify can avoid many of the failure situations. it would be great if you would link to your issue from here.

**Comment by jedwards1211** [comment]
I'm on an old version of that plugin so as far as I know the newest version works correctly.

What do you think about the idea of plugins like `@semantic-release/npm` being able to check if a version has actually been published?

**Comment by jedwards1211** [comment]
I'm thinking about new solutions.  Let me think about it a bit longer though.  If the version wasn't published to npm but there have been commits since the build that attempted to publish that version, it wouldn't be so simple.
