### ISSUE TITLE
"TypeError: Cannot read property 'name' of undefined" in @semantic-release/github/lib/get-fail-comment.js

### ISSUE THREAD

**Issue by kentcdodds** [semantic-release/semantic-release#1655]
## Current behavior

All my libraries use `kcd-scripts` to do automated releases on Travis. [Here's the relevant travis config](https://github.com/kentcdodds/react-workshop-app/blob/494dd6d218d87f7d73c535cd7e2344231351385d/.travis.yml#L18-L23):

```
jobs:
  include:
    - stage: release
      node_js: 14
      script: kcd-scripts travis-release
      if: fork = false
```

Here's [the relevant code](https://github.com/kentcdodds/kcd-scripts/blob/4961e9741460825131f5de47d93d41b0a9ffe99d/src/scripts/travis-release.js#L42) that runs when running `kcd-scripts travis-release`:

```
npx semantic-release@17
```

This has been working fine for all my projects for quite some time. But for [@kentcdodds/react-workshop-app](https://travis-ci.com/github/kentcdodds/react-workshop-app/builds) it suddenly started erroring out for me with this error. Here's the first build when this started happening: https://travis-ci.com/github/kentcdodds/react-workshop-app/jobs/397488322

```
[3:17:07 PM] [semantic-release] › ℹ  Running semantic-release version 17.1.2
2020-10-11T15:17:07.410Z semantic-release:config load config from: /home/travis/build/kentcdodds/react-workshop-app/package.json
2020-10-11T15:17:07.417Z semantic-release:config options values: {
  branches: [ 'master', 'next', 'beta' ],
  repositoryUrl: 'git+https://github.com/kentcdodds/react-fundamentals.git',
  tagFormat: 'v${version}',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/npm',
    '@semantic-release/github'
  ],
  _: [],
  '$0': '../../../.npm/_npx/5251/bin/semantic-release'
}
2020-10-11T15:17:07.591Z semantic-release:plugins options for @semantic-release/npm/verifyConditions: {}
[3:17:07 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
2020-10-11T15:17:07.595Z semantic-release:plugins options for @semantic-release/github/verifyConditions: {}
[3:17:07 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
2020-10-11T15:17:07.599Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[3:17:07 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2020-10-11T15:17:07.601Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
[3:17:07 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
2020-10-11T15:17:07.601Z semantic-release:plugins options for @semantic-release/npm/prepare: {}
[3:17:07 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
2020-10-11T15:17:07.602Z semantic-release:plugins options for @semantic-release/npm/publish: {}
[3:17:07 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
2020-10-11T15:17:07.602Z semantic-release:plugins options for @semantic-release/github/publish: {}
[3:17:07 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
2020-10-11T15:17:07.602Z semantic-release:plugins options for @semantic-release/npm/addChannel: {}
[3:17:07 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
2020-10-11T15:17:07.603Z semantic-release:plugins options for @semantic-release/github/addChannel: {}
[3:17:07 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
2020-10-11T15:17:07.603Z semantic-release:plugins options for @semantic-release/github/success: {}
[3:17:07 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
2020-10-11T15:17:07.603Z semantic-release:plugins options for @semantic-release/github/fail: {}
[3:17:07 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
2020-10-11T15:17:07.659Z semantic-release:get-git-auth-url Verifying ssh auth by attempting to push to  https://github.com/kentcdodds/react-fundamentals.git
2020-10-11T15:17:07.968Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://github.com/kentcdodds/react-fundamentals.git HEAD:master
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/kentcdodds/react-fundamentals.git/'
    at makeError (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async verifyAuth (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/lib/git.js:207:5)
    at async module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/lib/get-git-auth-url.js:47:5)
    at async run (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/index.js:56:27)
    at async module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/cli.js:55:5)
2020-10-11T15:17:07.969Z semantic-release:get-git-auth-url SSH key auth failed, falling back to https.
[3:17:09 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[3:17:09 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[3:17:10 PM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
[3:17:10 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Cannot read property 'name' of undefined
    at module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/get-fail-comment.js:19:10)
    at module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/fail.js:28:74)
    at async fail (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/node_modules/@semantic-release/github/index.js:64:3)
    at async validator (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as fail] (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async callFail (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/index.js:235:7)
    at async module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/index.js:264:7)
    at async module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/cli.js:55:5) {
  pluginName: '@semantic-release/github'
}
[3:17:10 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).
This may occur if your repository does not have a release branch, such as master.
Your configuration for the problematic branches is [].
AggregateError: 
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/lib/get-error.js:6:10)
        at /home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/lib/branches/index.js:44:19
        at Array.reduce (<anonymous>)
        at module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/lib/branches/index.js:34:46)
        at async run (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/index.js:57:22)
        at async module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/index.js:260:22)
        at async module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/cli.js:55:5)
    at module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/lib/branches/index.js:66:11)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async run (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/index.js:57:22)
    at async module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/travis/.npm/_npx/5251/lib/node_modules/semantic-release/cli.js:55:5)The command "kcd-scripts travis-release" exited with 1.
```

I believe that's [this line in `@semantic-release/github/lib/get-fail-comment.js`](https://github.com/semantic-release/github/blob/24344df17ad715f1d7fafcd3ced1283b9e1f4d8f/lib/get-fail-comment.js#L19).

I'm guessing it's an issue with the github plugin. Not sure what though.

## Expected behavior

Release should go out as usual.

## Environment

- **semantic-release** version: `@17`
- CI environment: Travis
- Plugins used: Unconfigured
- **semantic-release** configuration: Unconfigured.
- CI logs: Pasted above.

**Comment by kentcdodds** [comment]
Oh, and I did try to add configuration for the branches but that changed nothing.

**Comment by kentcdodds** [comment]
I updated the output with `DEBUG=semantic-release:*` output.

**Comment by gr2m** [comment]
Hey Kent, sorry for the trouble! That is some odd error message you got there!

Did the problem occur after you added the configuration?

```json
  "release": {
    "branches": [
      "master",
      "next",
      "beta"
    ]
  },
```

If so, can you remove it? The default configruation should work just fine. If you want to keep the configuration, try changing `"beta"` to `"{name: 'beta', prerelease: true}"`

**Comment by travi** [comment]
I notice that the first failure commit sets the repository url in the package json. The format of that url is a common source for problems. That is likely causing that auth failure that shows as the first error in the output. I'm guessing that the `name` error is simply a failure to parse the error message.

**Comment by travi** [comment]
Upon further inspection, it looks like it is now set twice in that file

**Comment by gr2m** [comment]
Yeah, the double "repository" entry is likely the problem.

I think we should check for that case, I've seen it happening before. I wound this package that we could use for checking: https://www.npmjs.com/package/find-duplicated-property-keys. It does a recursive deep check, which might be helpful for the `"release": { ... }` configuration anyway.

**Comment by kentcdodds** [comment]
![Facepalm GIF-downsized_large](https://user-images.githubusercontent.com/1500684/95690023-19463000-0bd2-11eb-91dc-9d79c9be616d.gif)

Thanks! That fixed it for me. Feel free to close this issue if you'd like.

**Comment by gr2m** [comment]
Thanks for letting us know! I'm working on throwing a helpful error which will save humanity some facepalms in future, I hope :)

**Comment by kentcdodds** [comment]
Thank you!

![thank you](https://i.giphy.com/hV7Vz9VwUaedWJZIxp.gif)
