### ISSUE TITLE
npm latest tag not update to next tage version on branch merges

### ISSUE THREAD

**Issue by jerradpatch** [semantic-release/semantic-release#1672]
## Current behavior

I have two branched master and next. The configuration looks like this (below)

The next branch is ahead of master. In npm master is at 1.0.0 and next is at 2.0.0. After merging next into master, the latest tag is not updated to version 2.0.0. From the docs this is how it should work, what am I doing wrong?

https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/distribution-channels.md#adding-a-version-to-latest

## Expected behavior

I would like the latest tag to be updated to the version of the next tag in npm when master is merged with next in github

## Environment

- **semantic-release** version: 
    "@commitlint/cli": "^11.0.0",
    "@commitlint/config-conventional": "^11.0.0",
    "@semantic-release/git": "^9.0.0",
    "cz-conventional-changelog": "^3.3.0",
    "husky": "^4.3.0",
    "semantic-release": "^17.2.1"

- CI environment: Jenkins
- Plugins used:
- **semantic-release**
{
  "branches": [
    "master",
    {"name": "next", "channel": "next"}
  ],
  "ci": false,
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/npm"
  ]
}

- CI logs:

after the merge these are the logs

02:36:16 + npx semantic-release
02:36:17 [6:36:16 AM] [semantic-release] › ℹ  Running semantic-release version 17.2.1
02:36:17 [6:36:16 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
02:36:17 [6:36:16 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
02:36:17 [6:36:16 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
02:36:17 [6:36:16 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
02:36:17 [6:36:16 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
02:36:17 [6:36:16 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
02:36:21 [6:36:20 AM] [semantic-release] › ✔  Run automated release from branch master on repository https://gecgithub01.XXX.com/j0p035x/test-semverpackage.git
02:36:21 [6:36:21 AM] [semantic-release] › ✔  Allowed to push to the Git repository
02:36:21 [6:36:21 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
02:36:21 [6:36:21 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://npme.XXX.com
02:36:21 [6:36:21 AM] [semantic-release] [@semantic-release/npm] › ℹ  Reading npm config from /mnt/jenkinspan/.npmrc, /mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/ws/.npmrc
02:36:21 [6:36:21 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
02:36:21 [6:36:21 AM] [semantic-release] › ℹ  Found git tag v2.13.0 associated with version 2.13.0 on branch master
02:36:21 [6:36:21 AM] [semantic-release] › ℹ  Found 0 commits since last release
02:36:21 [6:36:21 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
02:36:21 [6:36:21 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 0 commits complete: no release
02:36:21 [6:36:21 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
02:36:21 [6:36:21 AM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.

**Comment by jerradpatch** [comment]
nvm, I think this is due to a corporate registry not implementing /dist-tags for npm packages. Here is the error that I get after the registry fails to return /dist-tags.

```
command: 'npm dist-tag add test-semverpackage@2.14.0 latest --userconfig /tmp/59e79d295ddee8cdf12a51a71b111f95/.npmrc --registry https://npme.XXX.com',
16:38:14   exitCode: 1,
16:38:14   signal: undefined,
16:38:14   signalDescription: undefined,
16:38:14   stdout: '',
16:38:14   stderr: 'npm ERR! code E404\n' +
16:38:14     'npm ERR! 404 Not Found - GET [secure]-/package/test-semverpackage/dist-tags\n' +
16:38:14     'npm ERR! 404 \n' +
16:38:14     "npm ERR! 404  'test-semverpackage@2.14.0' is not in the npm registry.\n" +
16:38:14     'npm ERR! 404 You should bug the author to publish it (or use the name yourself!)\n' +
16:38:14     'npm ERR! 404 \n' +
16:38:14     'npm ERR! 404 Note that you can also install from a\n' +
16:38:14     'npm ERR! 404 tarball, folder, http url, or git url.\n' +
16:38:14     '\n' +
16:38:14     'npm ERR! A complete log of this run can be found in:\n' +
16:38:14     'npm ERR!     /mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/.npm/_logs/2020-10-29T20_38_13_885Z-debug.log',
16:38:14   failed: true,
16:38:14   timedOut: false,
16:38:14   isCanceled: false,
16:38:14   killed: false,
16:38:14   pluginName: '@semantic-release/npm'
16:38:14 }
16:38:14 Error: Command failed with exit code 1: npm dist-tag add test-semverpackage@2.14.0 latest --userconfig /tmp/59e79d295ddee8cdf12a51a71b111f95/.npmrc --registry https://npme.XXX.com
16:38:14 npm ERR! code E404
16:38:14 npm ERR! 404 Not Found - GET [secure]-/package/test-semverpackage/dist-tags
16:38:14 npm ERR! 404 
16:38:14 npm ERR! 404  'test-semverpackage@2.14.0' is not in the npm registry.
16:38:14 npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
16:38:14 npm ERR! 404 
16:38:14 npm ERR! 404 Note that you can also install from a
16:38:14 npm ERR! 404 tarball, folder, http url, or git url.
16:38:14 
16:38:14 npm ERR! A complete log of this run can be found in:
16:38:14 npm ERR!     /mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/.npm/_logs/2020-10-29T20_38_13_885Z-debug.log
16:38:14     at makeError (/mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/ws/node_modules/execa/lib/error.js:59:11)
16:38:14     at handlePromise (/mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/ws/node_modules/execa/index.js:114:26)
16:38:14     at processTicksAndRejections (internal/process/task_queues.js:93:5)
16:38:14     at async module.exports (/mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/ws/node_modules/@semantic-release/npm/lib/add-channel.js:31:5)
16:38:14     at async validator (/mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/ws/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
16:38:14     at async /mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/ws/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
16:38:14     at async /mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/ws/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
16:38:14     at async Object.pluginsConf.<computed> [as addChannel] (/mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/ws/node_modules/semantic-release/lib/plugins/index.js:80:11)
16:38:14     at async run (/mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/ws/node_modules/semantic-release/index.js:132:24)
16:38:14     at async module.exports (/mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/ws/node_modules/semantic-release/index.js:260:22) {
16:38:14   shortMessage: 'Command failed with exit code 1: npm dist-tag add test-semverpackage@2.14.0 latest --userconfig /tmp/59e79d295ddee8cdf12a51a71b111f95/.npmrc --registry https://npme.XXX.com',
16:38:14   command: 'npm dist-tag add test-semverpackage@2.14.0 latest --userconfig /tmp/59e79d295ddee8cdf12a51a71b111f95/.npmrc --registry https://npme.XXX.com',
16:38:14   exitCode: 1,
16:38:14   signal: undefined,
16:38:14   signalDescription: undefined,
16:38:14   stdout: '',
16:38:14   stderr: 'npm ERR! code E404\n' +
16:38:14     'npm ERR! 404 Not Found - GET [secure]-/package/test-semverpackage/dist-tags\n' +
16:38:14     'npm ERR! 404 \n' +
16:38:14     "npm ERR! 404  'test-semverpackage@2.14.0' is not in the npm registry.\n" +
16:38:14     'npm ERR! 404 You should bug the author to publish it (or use the name yourself!)\n' +
16:38:14     'npm ERR! 404 \n' +
16:38:14     'npm ERR! 404 Note that you can also install from a\n' +
16:38:14     'npm ERR! 404 tarball, folder, http url, or git url.\n' +
16:38:14     '\n' +
16:38:14     'npm ERR! A complete log of this run can be found in:\n' +
16:38:14     'npm ERR!     /mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/.npm/_logs/2020-10-29T20_38_13_885Z-debug.log',
16:38:14   failed: true,
16:38:14   timedOut: false,
16:38:14   isCanceled: false,
16:38:14   killed: false,
16:38:14   pluginName: '@semantic-release/npm'
```

However, from this error, I notice that the job to update the latest tag to the next tag only kicks off after then merge from latest to master. In my case that job failed. Now when I restart the job, I would expect it to detect that npm tags latest and next are not what was expected, and restart the job that failed before. However, this is the logs after I restart the failed job.

```
17:08:18 + npx semantic-release
17:08:19 [9:08:18 PM] [semantic-release] › ℹ  Running semantic-release version 17.2.1
17:08:19 [9:08:18 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
17:08:19 [9:08:18 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
17:08:19 [9:08:18 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
17:08:19 [9:08:18 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
17:08:19 [9:08:18 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
17:08:19 [9:08:18 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
17:08:24 [9:08:23 PM] [semantic-release] › ✔  Run automated release from branch master on repository https://gecgithub01.XXX.com/j0p035x/test-semverpackage.git
17:08:24 [9:08:24 PM] [semantic-release] › ✔  Allowed to push to the Git repository
17:08:24 [9:08:24 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
17:08:24 [9:08:24 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://npme.XXX.com
17:08:24 [9:08:24 PM] [semantic-release] [@semantic-release/npm] › ℹ  Reading npm config from /mnt/jenkinspan/.npmrc, /mnt/jenkinspan/workspace/CustomerTransaction/test-semverpackage-multibranch/master/ws/.npmrc
17:08:24 [9:08:24 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
17:08:24 [9:08:24 PM] [semantic-release] › ℹ  Found git tag v2.14.0 associated with version 2.14.0 on branch master
17:08:24 [9:08:24 PM] [semantic-release] › ℹ  Found 0 commits since last release
17:08:24 [9:08:24 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
17:08:24 [9:08:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 0 commits complete: no release
17:08:24 [9:08:24 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
17:08:24 [9:08:24 PM] [semantic-release] › ℹ  There are no relevant changes, so no new version is released.
```

You can see from above that the difference in npm tags is not detected and the failed job is not rerun as expected.

**Comment by philipp-rudloff-sendcloud** [comment]
I’m also seeing this issue with the default npm registry. After merging `next` into the project’s default branch, the common "There are no relevant changes, so no new version is released." message is logged at the end of the semantic release workflow and the npm dist tag is not updated.

The documentation on https://semantic-release.gitbook.io/semantic-release/recipes/release-workflow/distribution-channels#adding-a-version-to-latest says this should happen.

After checking the documentation for https://github.com/semantic-release/npm I think I’m missing the following from my release.config.js file:

```
  addChannel: ['@semantic-release/npm'],
```
