### ISSUE TITLE
Error when integrating with husky?

### ISSUE THREAD

**Issue by bestickley** [semantic-release/semantic-release#1674]
## Current behavior

I ran `semantic-release` locally on my machine and I got an error. I think the issue may have something to do with husky being installed? I have @commitlint/cli, @commitlint/config-conventional, and husky installed as well. The error looks like it's trying to run the command `dirname` but I'm on a windows machine. This may not necessarily be a semantic-release issue, but can anyone help me?

## Expected behavior

No error

## Environment

- **semantic-release** version: 17.2.2
- CI environment: N/A
- Plugins used: changelog, git
- **semantic-release** configuration:
"release": {
    "ci": false,
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      ["@semantic-release/github", {
        "githubUrl": "https://github.boozallencsn.com",
        "githubApiPathPrefix": "api/v3"
      }],
      "@semantic-release/git",
      "@semantic-release/changelog"
    ]
  },
- CI logs:
[5:08:05 PM] [semantic-release] [@semantic-release/commit-analyzer] » i  Analysis of 150 commits complete: minor release
[5:08:05 PM] [semantic-release] » √  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[5:08:06 PM] [semantic-release] » i  The next release version is 0.13.0
[5:08:06 PM] [semantic-release] » i  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:08:06 PM] [semantic-release] » √  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:08:06 PM] [semantic-release] » i  Start step "prepare" of plugin "@semantic-release/git"
[5:08:21 PM] [semantic-release] » √  Completed step "prepare" of plugin "@semantic-release/git"
[5:08:21 PM] [semantic-release] » i  Start step "prepare" of plugin "@semantic-release/changelog"
[5:08:21 PM] [semantic-release] [@semantic-release/changelog] » i  Create C:\Users\583327\Code\ForceAnalytics\the-bridge\CHANGELOG.md
[5:08:21 PM] [semantic-release] » √  Completed step "prepare" of plugin "@semantic-release/changelog"
[5:08:23 PM] [semantic-release] » ×  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push --tags git@github.boozallencsn.com:NRFA/the-bridge.git
.git/hooks/pre-push: line 8: dirname: command not found
.git/hooks/pre-push: line 8: /husky.sh: No such file or directory
error: failed to push some refs to 'github.boozallencsn.com:NRFA/the-bridge.git'
    at makeError (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\execa\index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async push (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\semantic-release\lib\git.js:236:3)
    at async run (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\semantic-release\index.js:193:5)
    at async module.exports (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\semantic-release\index.js:260:22)
    at async module.exports (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\semantic-release\cli.js:55:5) {
  shortMessage: 'Command failed with exit code 1: git push --tags git@github.boozallencsn.com:NRFA/the-bridge.git',
  command: 'git push --tags git@github.boozallencsn.com:NRFA/the-bridge.git',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '.git/hooks/pre-push: line 8: dirname: command not found\n' +
    '.git/hooks/pre-push: line 8: /husky.sh: No such file or directory\n' +
    "error: failed to push some refs to 'github.boozallencsn.com:NRFA/the-bridge.git'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 1: git push --tags git@github.boozallencsn.com:NRFA/the-bridge.git
.git/hooks/pre-push: line 8: dirname: command not found
.git/hooks/pre-push: line 8: /husky.sh: No such file or directory
error: failed to push some refs to 'github.boozallencsn.com:NRFA/the-bridge.git'
    at makeError (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\execa\lib\error.js:59:11)
    at handlePromise (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\execa\index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async push (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\semantic-release\lib\git.js:236:3)
    at async run (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\semantic-release\index.js:193:5)
    at async module.exports (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\semantic-release\index.js:260:22)
    at async module.exports (C:\Users\583327\Code\ForceAnalytics\the-bridge\node_modules\semantic-release\cli.js:55:5) {
  shortMessage: 'Command failed with exit code 1: git push --tags git@github.boozallencsn.com:NRFA/the-bridge.git',
  command: 'git push --tags git@github.boozallencsn.com:NRFA/the-bridge.git',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: '.git/hooks/pre-push: line 8: dirname: command not found\n' +
    '.git/hooks/pre-push: line 8: /husky.sh: No such file or directory\n' +
    "error: failed to push some refs to 'github.boozallencsn.com:NRFA/the-bridge.git'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! the-bridge@0.13.0 semantic-release: `semantic-release`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the the-bridge@0.13.0 semantic-release script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\583327\AppData\Roaming\npm-cache\_logs\2020-10-30T21_08_24_020Z-debug.log
PS C:\Users\583327\Code\ForceAnalytics\the-bridge> git push --tags git@github.boozallencsn.com:NRFA/the-bridge.git
Total 0 (delta 0), reused 0 (delta 0), pack-reused 0
To github.boozallencsn.com:NRFA/the-bridge.git
 * [new tag]         v0.13.0 -> v0.13.0

**Comment by ManojBahuguna** [comment]
On windows, git bash is used to execute sh script  
ensure that git bin location (e.g: C:\Program Files\Git\bin) is set in PATH
