### ISSUE TITLE
git ls-remote command fails in v17.2.2 - Error: Invalid username or password

### ISSUE THREAD

**Issue by msneller** [semantic-release/semantic-release#1676]
## Current behavior
When running I get the following error.
```
Error: Command failed with exit code 128: git ls-remote --heads https://github.com/myrepo.git
```
This started happening about 4 days ago on one of our builds. Strangely, all other builds still work. I then reverted to semantic-release@17.2.1 and it fixed the issue.

## Expected behavior

```
[2:11:36 PM] [semantic-release] › ℹ  Running semantic-release version 17.2.1
[2:11:36 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[2:11:36 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[2:11:36 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[2:11:36 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[2:11:36 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[2:11:37 PM] [semantic-release] › ℹ  This test run was triggered on the branch origin/master, while semantic-release is configured to only publish from master, therefore a new version won’t be published.
```

## Environment

- **semantic-release** version: 
"@semantic-release/changelog": "^3.0.6",
"@semantic-release/commit-analyzer": "^7.0.0",
"@semantic-release/git": "^9.0.0",
"@semantic-release/npm": "^6.0.0",
"@semantic-release/release-notes-generator": "^7.3.5",
"semantic-release": "^17.0.0"
- CI environment: Jenkins
- Plugins used: 
npm
- **semantic-release** configuration: 
```
{
  "branch": "master",
  "plugins": [
    ["@semantic-release/npm",{"npmPublish":false}]
    ]
}
```
- CI logs: 
```
[2:00:39 PM] [semantic-release] › ℹ  Running semantic-release version 17.2.2
[2:00:39 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[2:00:39 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[2:00:39 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[2:00:39 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[2:00:39 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[2:00:39 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed with exit code 128: git ls-remote --heads https://github.com/myrepo.git
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/myrepo.git/'
    at makeError (/usr/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/lib/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  shortMessage:
   'Command failed with exit code 128: git ls-remote --heads https://github.com/myrepo.git',
  command:
   'git ls-remote --heads https://github.com/myrepo.git',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr:
   'remote: Invalid username or password.\nfatal: Authentication failed for \'https://github.com/myrepo.git/\'',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
{ Error: Command failed with exit code 128: git ls-remote --heads https://github.com/myrepo.git
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/myrepo.git/'
    at makeError (/usr/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/usr/lib/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  shortMessage:
   'Command failed with exit code 128: git ls-remote --heads https://github.com/myrepo.git',
  command:
   'git ls-remote --heads https://github.com/myrepo.git',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr:
   'remote: Invalid username or password.\nfatal: Authentication failed for \'https://github.com/myrepo.git/\'',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false }
script returned exit code 1
```

**Comment by gr2m** [comment]
> Authentication failed for 'https://github.com/myrepo.git/'


That does not look right, can you make sure the repository url is correct in your package.json? There should be a repository owner, and there should be no trailing `/`

**Comment by kugashia** [comment]
For someone who might refer this in future,

We had this issue; Apparently, our git credentials were updated and we were passing in the wrong ones for the semantic-release. it could be something else as well but we got it fixed by syncing the correct credentials. Worth double-checking.

**Comment by gr2m** [comment]
It does not need to be an object, any format of the `repository` key supported by npm is supported by semantic-release.

I usually set it to

```js
  "repository": "github:owner/repo"
```

**Comment by villelahdenvuo** [comment]
I'm getting a similar error even though I set the repository in many different ways:

```
Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@github.com/granodigital/repo.git
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/granodigital/repo/'
```

The GH_TOKEN is defined on the CI and SSH keys should also work, so I don't understand why it's saying that it's using password auth.

**Comment by MinaroShikuchi** [comment]
Same issue, but it came from a typo in the package name in package.json

**Comment by gr2m** [comment]
What I recommend these days is not to use personal access tokens at all, but instead utilize single-purpose GitHub apps in combination with https://github.com/actions/create-github-app-token to create an access token as needed. The GitHub App credentials don't expire, the access token are valid for 1h which should be more than enough for a release process.
