### ISSUE TITLE
Create option to disable verifyAuth or allow plugins to overwrite verifyAuth

### ISSUE THREAD

**Issue by secustor** [semantic-release/semantic-release#1729]
## New feature motivation

GitlabCI tokens have no permissions to push code, therefore semnatic-release users have to use personal tokens which is not ideal from a security and maintenance standpoint.      
https://github.com/semantic-release/gitlab/issues/156

## New feature description

To enable the usage of CI tokens we need a possibility to prevent semnatic-release to fail on the `verifyAuth` stage, an alternative could be to allow plugins to overwrite the `verifyAuth` stage. 

## New feature implementation

If the first idea is implemented it could be in form of flags such as `--skip-verifyAuth` or better `--skip-stage=verifyAuth` .  

The second concept needs new implementation in the core and the Gitlab plugin, but seems for me to be the cleaner variant. 
Basically core will provide a default implementation for `verifyAuth` and allows plugins to overwrite this default. 

I'm willing give this a shot to implement this myself.

**Comment by travi** [comment]
as mentioned in https://github.com/semantic-release/gitlab/issues/156#issuecomment-746562629, semantic-release needs the ability to push tags back to the repository. without authorization to do this, the core of semantic-release cannot determine the proper commit that is associated with the previous version. since auth is necessary, i don't understand how skipping verification would be helpful here.

**Comment by secustor** [comment]
Thanks for the fast response!

I have looked a little bit deeper into the code base and see now the problem, but I'm not sure what do you mean that sematic needs to push to get the next release. From what I have seen it pushes only tags and their notes after sematic has decided to what the next release is. 

To better clarify my use beforehand, basically I want to use the `CI_JOB_TOKEN` from Gitlab which has no right to push code but can create Releases. This releases can be created on existing tags or implicitly generate one using a git reference.      
So basically I want to create the tags with this implicit method instead of pushing the tag using git.     

The solution could be to move the push logic into a plugin phase and provide a default as I have described in the first post for `verifyAuth`. Finally the logic can be then overwritten by the Gitlab plugin to create a release using the [Release API](https://docs.gitlab.com/ee/api/releases/#create-a-release)

**Comment by travi** [comment]
> From what I have seen it pushes only tags and their notes after sematic has decided to what the next release is.

Correct, but the tag that is pushed by semantic-release is used for the _next_ release for determining the previous version to apply the next determined version bump to. The intention of semantic-release is to handle the whole release process and there are several discussions about why this behavior exists in core. It is very unlikely that we would change this behavior.

I think there is some confusion around this request beyond this, though. A token with more privileges would not improve this situation. semantic-release uses git to push the tags, not the GitLab (or other host) API. The API is only used for enhancing the tag with release details, etc. API tokens would not enable git push access, unless there is a detail about GitLab that I do not understand. The services that I am familiar with enable pushing tags back to the VCS host that they cloned from by default. I would recommend looking into why the git credentials are not allowing tag pushes.

**Comment by walkafwalka** [comment]
@travi To further clarify, there are two methods to create a tag in GitLab:

1. Push the tag via git. This is the method you are referring to, and it requires git push access. GitLab's `CI_JOB_TOKEN` **DOES NOT** have git push access. Thus, users are generating a personal access token which is less secure.
2. Create a GitLab Release via the API. This method allows you to either specify an existing tag or a nonexistent tag. If a nonexistent tag is specified, the tag is automatically created by the API (no git push access required). GitLab's `CI_JOB_TOKEN` **DOES** have API access to the GitLab Release API. Thus, the `CI_JOB_TOKEN` does not need git push access to create a tag if it is done through a release.

> semantic-release uses git to push the tags, not the GitLab (or other host) API.

Yes, by default. The ask is to allow this to allow plugins to override the tag creation. Other providers may have alternative, more secure, methods than git, such as an API. GitLab's API method is more secure because the token is dynamically generated on every run, and it does not require push access to the repository.

**Comment by travi** [comment]
> GitLab's `CI_JOB_TOKEN` **DOES NOT** have git push access.

It shouldnt matter if the API token has push access since it is the git credentials that need to have this access instead.

> Thus, users are generating a personal access token which is less secure.

Less secure in what way? The benefit of using tokens is that you can limit the access that they have. I'm not very familiar with GitLab, but I don't understand why the tokens are being considered insecure

> Yes, by default. The ask is to allow this to allow plugins to override this tag creation method.

tag creation used to be available in plugins, but was later moved to core. you can browse the issue history for the reasoning behind this decision, but it is very unlikely that we will reverse this decision. 

> GitLab's API method is more secure because the token is dynamically generated on every run, and it does not require push access to the repository.

OK, I agree with the limited token life being more secure than a longer lived token, like a PAC. This is similar to the `GITHUB_TOKEN` available with GitHub Actions. However, I don't believe that it is necessarily less secure than git credentials that should also be provided by a CI service that enabled cloning. Again, I'm not familiar with GitLab, but the services that I have used and am familiar with provide git push capability by default. If this is not the case with GitLab, I think the request should be for them to provide this rather than for semantic-release to provide an ability to work around this lack of functionality.

@nfriend could you help fill in any gaps or misstatements i may have made regarding GitLab?

**Comment by walkafwalka** [comment]
I think the root of our disagreement is regarding the option for alternative authentication to git, which I do not have much more to add.

There is a popular GitLab issue to provide even more control and flexibility to CI job tokens. See https://gitlab.com/groups/gitlab-org/-/epics/3559.

**Comment by nfriend** [comment]
@travi Sorry for the slow reply!

> could you help fill in any gaps or misstatements i may have made regarding GitLab?

Everything looks accurate to me 👍 Thanks for the ping!

**Comment by nfriend** [comment]
Just as an aside, one option that might be slightly better than a Personal Access Token is a [Project Access Token](https://docs.gitlab.com/ee/user/project/settings/project_access_tokens.html), which is scoped to a specific project.

_(Caveat: Project Access Tokens aren't available to free users of the SAAS version of GitLab.)_

**Comment by EvanCarroll** [comment]
I can't recreate this issue.. Re,

> GitlabCI tokens have no permissions to push code, therefore semnatic-release users have to use personal tokens which is not ideal from a security and maintenance standpoint.

For my GitLab 14 SaaS, they do. For example this will work fine where `foo` is the name of a group, and `bar` is the name of a repo and `STUPID_TOKEN` is the any **project or user** token generated with `api` access.

    git push --dry-run --no-verify "https://whatever:STUPID_TOKEN@gitlab.acme.net/foo/bar.git"

**Comment by secustor** [comment]
@EvanCarroll That's correct Personal Access Tokens as well Group and Project Tokens can be created with 'repository_write' permissions, but this is a manual task.   

What I wanted to achieve with the issue is to remove the management overhead of creating this tokens. Gitlab injects for this an temporary token which is only valid for the duration of the job is running.  This token is saved in the environment variable `CI_JOB_TOKEN`, which is the token I refer to when I mention the Gitlab CI Token.       
This token does not have write permissions to the repository, but it has access to the Tag and Release API.    
My idea has been to allow plugin to overwrite the tag creation method, which would solve that.

**Comment by EvanCarroll** [comment]
@secustor just to be clear, you can do the above with just `api` you don't need `repo_write`.

If you can pull that off with just the token auto-provided to the CI, that sounds like the way to go. I agree, it's insane to have _any_ GitLab functionality in the core and to still have a plugin available for GitLab. That stinks of bad design. That said, if @travi prefers that approach and he's the head dev, sounds like you're not going to get away from it. Perhaps then you could just add `CI_JOB_TOKEN` to the end of the list of the tokens `GITLAB_TOKEN` sources from in core.

**Comment by secustor** [comment]
I agree that the fetching credentials should be placed in the plugin too, but the mapping of the tokens is not problem as this can be solved outside of semantic.       

The problem is that semantic uses `git tag <a version>` and  `git push origin --tags` to create tags on the remote and this needs `repo_write` permissions in the case of Gitlab.     
I think this a good solution to use Git here as default as it is the common denominator for most platforms out there, but I think there should the possibility for plugins to overwrite this tag creation process. Especially if it leads to lower entry burdens, higher security trough short lived access tokens  and a general better UX. 

Therefore I proposed the solution above to allow plugins to overwrite this step too, as semantic allows for the release generation.

**Comment by rene84** [comment]
Hi @secustor did you by any chance end up forking semantic-release for this issue?

If so, I would like to get in touch.

We are in the same situation with a large number of gitlab projects and project access tokens are really something I don't want to do if not necessary

**Comment by rene84** [comment]
> I think the root of our disagreement is regarding the option for alternative authentication to git, which I do not have much more to add.

I think the root of the request is to be able to disable (with a flag) semantic-versioning core from setting the git tag and deferring that responsibility to a plugin (gitlab plugin in this case). If that flag were to be on, then it also logically makes sense that the core does not need repository write permissions (I could be wrong here) only read permissions to fetch the latest tag to determine what the next tag needs to be.

So if core doesn't set the tag, then the verifyAuth stage also needs to do something different because core shouldn't care about how the plugin eventually manages to set the tag.

The short lived job token CI_JOB_TOKEN has permission to read the repository but not write. So that should be sufficient.

The issue with Project Access Tokens is:
* management overhead
* long lived tokens unbound to a user representing a security risk even with protection and masking on the cicd variable
* protected cicd variables are only available on protected branches, so things like dry-running semantic-release in a merge request isn't even possible

**Comment by secustor** [comment]
@rene84 We decided to add the project token generation to our project creation pipeline in Terraform, which also adds the token to the CI variables.

**Comment by fgblomqvist** [comment]
So the logical argument here is that people want to use an auto-generated token that has narrower permissions than the one that has to be manually created. What is it that does not make sense of that @nfriend @travi? I don't think you need any Gitlab knowledge to understand that it's always better to be able to give less permissions to something if possible, no? Otherwise why don't we just give root access to everything?

Don't get me wrong, this project is fantastic in a lot of ways, but it sounds like this thread died on a misunderstanding of security best-practices rather than a disagreement of how something should be solved.

**Comment by EvanCarroll** [comment]
@rene84 I had this working in my by fork, fyi.

**Comment by flickerfly** [comment]
@rene84 I'm very interested in seeing your work. I noticed comments in @EvanCarroll's diff that tags aren't working in how he's doing it and having that capability is certainly an interesting piece. I agree that the security and maintenance improvements of this method are HUGE.

**Comment by maheshglm** [comment]
Hi @rene84 , I followed your changes in **semantic-release** and **semantic-release/gitlab** plugin to work with CI_JOB_TOKEN. Besides that, we are using `@semantic-release/git` plugin to commit `chore` message and push changelog.md. So now git plugin is throwing error as it cannot push changes to repo with `CI_JOB_TOKEN`. Can you suggest how did you achieve this requirement. Thanks in advance.

**Comment by flickerfly** [comment]
In the latest versions of GitLab, they've opened up what the CI tokens can do in relation to releases. I wonder if there is less need for adjustment and more "just works" as a result.

**Comment by EvanCarroll** [comment]
@flickerfly That comment would be more useful with a link and some research. ;)

**Comment by travi** [comment]
@PhilThurston i appreciate the additional explanation, but i think this follow up highlights that this thread has diverged from what i think the true situation is. I fully admit that i have not successfully guided the conversation to keep that clear, so i will try to gather the facts again.

> The use of PAT is a significant security risk compared to the CI_JOB_TOKEN.
>
> ...
>
> I would urge the maintainers to consider this for not only Gitlab but for other platforms that have such tools available for safer use.

this seems to frame things as if we as maintainers are unaware of or disagree that the situation could be better for mitigating security risks in the context of GitLab. i want to clarify that this is not the case. also, there are many potential security risks and various ways to mitigate such risks. there is no perfect level of security that still enables desired outcomes, so i urge everyone to avoid suggesting absolutes.

> > Less secure in what way? The benefit of using tokens is that you can limit the access that they have. I'm not very familiar with GitLab, but I don't understand why the tokens are being considered insecure
> 
> This question by @travi hasn't been directly addressed since this issue was opened.

again, i appreciate the further detail added to the thread, but i want to bring the response that did come up back into the picture: 

> GitLab's API method is more secure because the token is dynamically generated on every run, and it does not require push access to the repository.

and my response:

> I agree with the limited token life being more secure than a longer lived token, like a PAT. This is similar to the `GITHUB_TOKEN` available with GitHub Actions. However, I don't believe that it is necessarily less secure than git credentials that should also be provided by a CI service that enabled cloning.

as a reminder, i am not a gitlab user, but as a github user, when the GITHUB_TOKEN (which is a temp token provided by the action run) is used to push tags through git, am i not accomplishing the goal being asked for here? 

we need tags to be added to the repository. the most natural way, and most universal way, to do that is to add tags _using git_. in order to get those tags back to the hosted repo, we need the ability to push those tags back to the remote. keep in mind that we discourage the use of the git plugin to make actual commits during release, so in the base use case, we only even need the ability to push _tags_, not _commits_.

this is where the problem with the CI_JOB_TOKEN comes in. if the CI_JOB_TOKEN enabled pushing tags, the request that resulted in this entire thread would be nullified, would it not? a GITHUB_TOKEN, provided by a github actions workflow does enable this.  

which brings me back to:

> I would urge the maintainers to consider this for not only Gitlab but for other platforms that have such tools available for safer use.

what other platforms do you mean? gitlab is the only platform we have gotten this request for. 

what is being asked for in this issue is for semantic-release to _work around_ gitlab's lack of enabling pushing of git tags _through git_ with the desirable token. i still consider this a shortcoming of the gitlab implementation and find it very limiting that the only way to add a tag to the _git repository_ with that token is to make an api call that is completely independent from git itself. 

> There is a popular GitLab issue to provide even more control and flexibility to CI job tokens. See [gitlab.com/groups/gitlab-org/-/epics/3559](https://gitlab.com/groups/gitlab-org/-/epics/3559).

i think the best course of action is still to urge gitlab to make the token more capable of functionality that it currently lacks. gitlab is backed by a company of employees. we are a small handful of volunteer engineers, none of which are working on the project full time. most of us are not even gitlab users. 

we do not have a desire to leave gitlab users in a bad spot, but there is a capacity and long term maintenance piece to this. even if enabling this were our top priority, or we had a fully working contribution provided by the community, we need to consider the impact to the project long term. since gitlab is the only platform this has been raised for, all of the proposed work arounds would add significant complexity to the project and handling of other platforms.

> There was also a recent discussion internally with a client where this tool was rejected because of this large security flaw.

again, i ask that we are careful with our wording. suggesting that the current situation is a flaw implies that tokens are being made available in the clear. it is reasonable to determine that the mitigation options for the risk are not acceptable for your situation, but please avoid suggesting that there is a true vulnerability that our team is ignoring. (if there ever is a true vulnerability suspected, please refer to [our security policy](https://github.com/semantic-release/.github/blob/main/.github/SECURITY.md) rather than posting in a public issue).

also, please consider the complete system. semantic-release is not the only part of this puzzle. by choosing to use pipelines within gitlab, the context for this situation arises in a way that is not present on github actions, for example. there are other variables that can be changed other than semantic-release. i'm not suggesting that other variables are trivial to change, but i am suggesting that addressing this in semantic-release is less trivial to address than it might seem.

**Comment by travi** [comment]
@PhilThurston not trying to suggest that accusations are being made. i'm just trying to recenter the thread around facts and bring some perspective related to the project.

* we have not closed this issue, so that means we are not saying that this will never happen
* we have also not accepted it as a priority, so we are not promising that it will happen or with any timeline
* we would prefer to continue only creating tags using raw git. other options complicate the project in ways we would prefer to avoid
* gitlab's `CI_JOB_TOKEN` does not enable making tags _through raw git_, so the only way to use that token to create a tag  is to avoid tagging with raw git and instead use a custom process that is unique to gitlab
* we would prefer short lived tokens be used any time that is possible
* gitlab _could_ make it possible to make tags through raw git, making the need for a custom work around go away
* gitlab has a staff of employees
* semantic-release is a small project with no one working on it full time

however, the other thing that i was trying to ask was for us to be more careful about how we choose our words so that others can interpret implications appropriately. not using a time-limited token is not a _security flaw_. it is a choice that has implications. each project can decide for themselves whether those implications are within their tolerance or not. just because the available options may not be within a certain project's risk tolerance does not mean that it is outside of the risk tolerance of every project. i am asking again to be careful with terminology that is overly suggestive. to clarify, i am not trying to minimize that there are potential improvements available, but that does not mean that we need to communicate the situation as if there is an absolute choice that is the only option.

we are aware that gitlab has plenty of use. we agree that time-limited tokens are preferable to PATs. the part that still seems to be getting missed from what i am trying to communicate is that we see the best path forward as enabling the use of the time-limited token to create tags through raw git and push them through git rather than requiring a custom api call to create a release that results in the tags being created. if the many customers of gitlab would request this of gitlab, it is more likely that this could be resolved without a change to gitlab. we know this isnt the current state of things, but we are not eager to work around the situation that could be resolved with added flexibility from the gitlab side.

**Comment by KarstenSiemer** [comment]
Hi! Thanks for the efforts!
Any progress so far?

**Comment by Kenneth-Sills** [comment]
For what it's worth, Gitlab 17.2 will add the [`allow_push_repository_for_job_token` feature flag](https://docs.gitlab.com/ee/ci/jobs/ci_job_token.html#push-to-a-project-repository-using-a-job-token). When that's stable, this will be a non-issue, as @travi commented in bullet (6) above.

**Comment by amimas** [comment]
I understand this feature might not be needed anymore based on the GitLab feature mentioned above. I just wanted to share my experience because I find it very strange or at least don't understand how things are working right now.

I have been using semantic-release for awhile now in several of my projects. I create "Project Access Token" for each repos because it's only valid for the relevant project only, but it does increase the overhead of maintaining tokens across many projects. Initially these tokens were created with `api`, and `write_repository` scope and the token is given "Developer" role. My project release process worked fine.

Around last month or so, I found out that the `write_repository` access is not needed. Keep in mind that I also have other process running for automatically updating dependencies to newer versions, which would've updated semantic-release versions over time. But the main point is that as of right now, Project Access Token with only `api` scope and "Developer" role (in my setup) is sufficient for `semantic-release` to be able to successfully perform release creation.

This made me curious about the `CI_JOB_TOKEN` since that also has `api` scope (but not all API endpoints). So, I tried the `CI_JOB_TOKEN` and that didn't work. Also, keep in mind that the `CI_JOB_TOKEN` uses the job triggerer's access and since I own the project it would use my role. The error I was getting was still complaining about not being able to push a git tag...

```
[1:49:50 PM] [semantic-release] › ✘  Failed step "fail" of plugin "@semantic-release/gitlab"
[1:49:50 PM] [semantic-release] › ✘  EINVALIDGLTOKEN Invalid GitLab token.
The GitLab token (https://github.com/semantic-release/gitlab/blob/master/README.md#gitlab-authentication) configured in the GL_TOKEN or GITLAB_TOKEN environment variable must be a valid personal access token (https://docs.gitlab.com/ce/user/profile/personal_access_tokens.html) allowing to push to the repository amimas/glab-project1.
Please make sure to set the GL_TOKEN or GITLAB_TOKEN environment variable in your CI with the exact value of the GitLab personal token.
[1:49:50 PM] [semantic-release] › ✘  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch main on the remote Git repository with URL https://gitlab-ci-token:[secure]@gitlab.example.com/amimas/glab-project1.git.
This can be caused by:
    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)
SemanticReleaseError: Cannot push to the Git repository.
    at default (file:///builds/amimas/glab-project1/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (file:///builds/amimas/glab-project1/node_modules/semantic-release/index.js:101:11)
    at async Module.default (file:///builds/amimas/glab-project1/node_modules/semantic-release/index.js:278:22)
    at async default (file:///builds/amimas/glab-project1/node_modules/semantic-release/cli.js:55:5) {
```

I guess what I find strange is that the "Project Access Token" with just the `api` access seems to work; don't need `write_repository` access, which I believe is needed for any git based operation. My environment is:

```
GitLab version: 17.1.2
Semantic-release packages:
    "devDependencies": {
      "@commitlint/cli": "19.4.0",
      "@commitlint/config-conventional": "19.2.2",
      "@semantic-release/gitlab": "13.2.1",
      "conventional-changelog-conventionalcommits": "8.0.0",
      "semantic-release": "24.0.0"
    },
```

**Comment by MRigal** [comment]
> https://gitlab.com/gitlab-org/gitlab/-/issues/468320 This might be possible soon in Gitlab 17.3 or 17.4

Only planned in 17.6 for Gitlab.com hosted envs. [This issue](https://gitlab.com/gitlab-org/gitlab/-/issues/475705) is blocking the rollout of the feature on gitlab.com (but the feature flag can be activated on self-hosted envs)
