### ISSUE TITLE
`verifyAuth` does not properly verify, whether `refs/notes/semantic-release` is "writeable"

### ISSUE THREAD

**Issue by ChristianUlbrich** [semantic-release/semantic-release#1762]
## Current behavior

Currently, `verifyAuth` only verifies "proper" git access, by running `git push --dry-run HEAD:${branch}` and while this makes sure, that _pushing_ to a particular branch is possible, it does not automatically mean, that using _git notes_ (and thus pushing to `refs/notes/semantic-release` is possible as well.

On some Git environments (such as Azure DevOps), you need additional permissions for being able to generate git notes.

So, while [verifyAuth()](https://github.com/semantic-release/semantic-release/blob/ece72757431984612b89f1298e21eaa04f12cd79/lib/git.js#L205) will succeed, later on [pushNotes()](https://github.com/semantic-release/semantic-release/blob/ece72757431984612b89f1298e21eaa04f12cd79/index.js#L117) will fail and thus you are left in a somewhat inconsistent state (tag has been pushed, whereas release meta data has not).

## Expected behavior
_semantic-release_ should behave in a **consistent** way; if (as currently implemented) _git notes_ are a **hard** requirement on the remote repository, it should be checked for in `verifyAuth()`. When this fails, no git operation will be done.

_Bonus:_ As an additional safe guard, it could be checked, whether **both** pushing the actual release branch **and** the git notes can be made [atomic](https://github.blog/2015-04-30-git-2-4-atomic-pushes-push-to-deploy-and-more/).

## Environment

- **semantic-release** version: 17.3.7
- CI environment: Azure DevOps using a [job access token](https://docs.microsoft.com/en-us/azure/devops/pipelines/process/access-tokens?view=azure-devops&tabs=yaml)
- Plugins used:
  * @semantic-release/changelog
  * @semantic-release/git
  * @semantic-release/npm
- **semantic-release**
```
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    [
      "@semantic-release/changelog",
      {
        "changelogFile": "CHANGELOG.md"
      }
    ],
    ["@semantic-release/npm", {
      "npmPublish": false
    }],
    ["@semantic-release/git", {
      "assets": ["package.json", "CHANGELOG.md"],
      "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
    }]
  ],
  "tagFormat": "@test/test-examples@${version}",
  "branches": [
    "+([0-9])?(.{+([0-9]),x}).x",
    "master",
    "next",
    {
      "name": "beta",
      "prerelease": true
    },
    {
      "name": "alpha",
      "prerelease": true
    }
  ]
}

``` 
- CI logs:
```
[12:17:15 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: git push https://XXX@dev.azure.com/XXXX/DI_ZUi-Web/_git/DI_ZUi-Web refs/notes/semantic-release
To https://dev.azure.com/XXXX/DI_ZUi-Web/_git/DI_ZUi-Web
 ! [remote rejected]   refs/notes/semantic-release -> refs/notes/semantic-release (TF401027: You need the Git 'ManageNote' permission to perform this action. Details: identity 'Build\8d7ef86b-17dd-4022-bf5a-493577abaf30', scope 'repository'.)
error: failed to push some refs to 'https://dev.azure.com/XXXXX/DI_ZUi-Web/_git/DI_ZUi-Web'
    at makeError (/home/vsts/work/1/s/node_modules/.pnpm/execa@5.0.0/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/vsts/work/1/s/node_modules/.pnpm/execa@5.0.0/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async pushNotes (/home/vsts/work/1/s/node_modules/.pnpm/semantic-release@17.3.7/node_modules/semantic-release/lib/git.js:248:3)
    at async run (/home/vsts/work/1/s/node_modules/.pnpm/semantic-release@17.3.7/node_modules/semantic-release/index.js:194:5)
    at async module.exports (/home/vsts/work/1/s/node_modules/.pnpm/semantic-release@17.3.7/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/vsts/work/1/s/node_modules/.pnpm/semantic-release@17.3.7/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 1: git push https://XXXXX@dev.azure.com/XXXX/DI_ZUi-Web/_git/DI_ZUi-Web refs/notes/semantic-release',
  command: 'git push https://XXXXX@dev.azure.com/XXXXX/DI_ZUi-Web/_git/DI_ZUi-Web refs/notes/semantic-release',

```

I know, that as a work around, I could use a _personal access token_ or try to configure Azure DevOps properly, but as I've stated, `verifyAccess` should really mean: "I can safely access the remote git repo".

**Comment by gr2m** [comment]
that all sounds good, can you send a pull request to implement the verification for git notes?

**Comment by ChristianUlbrich** [comment]
Hm... while we are at it, I think the same problem is also relevant for _creating tags_. This could also be prohibited by some branch policies, although I presume initial push would fail then anyhow. Furthermore I don't think this is a feature, right now it is a bug in semantic-release...

I try to find some time... I encountered another problem right now. :) (Am I the only using it with ADO :D )?

**Comment by gr2m** [comment]
Danke Christian :)
