### ISSUE TITLE
Error Invalid GitHub token even though token has push permissions on the repo

### ISSUE THREAD

**Issue by roimor** [semantic-release/semantic-release#1776]
## Current behavior

while trying to set up semantic release within our Jenkins pipeline for npm publish, the pipeline is failing on the   
"SemanticReleaseError: Invalid GitHub token." error, the personal access token is 100% valid and has the right perms to push to the repo. 

## Expected behavior

setting up the environment variables (GH_TOKEN + NPM_TOKEN ) in jenkins pipeline will be enough for semantic-release to be able to push changes to the github repo. (as the jenkins CI recipe suggests)  

## Environment

- **semantic-release** version: "^17.3.7"
- CI environment: Jenkins
- Plugins used: npm, github
- **semantic-release** configuration: 

*package.json:*

{
  "name": "architecture-tests",
  "version": "0.0.0-development",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "jest",
    "build": "npm -v",
    "semantic-release": "semantic-release"
  },
  "repository": {
    "type": "git",
    "url": "https://git.******.com/*****/****tests.git"
  },
  "publishConfig": {
    "registry": "https://*******.jfrog.io/artifactory/api/npm/*****-npm/"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@nestjs/common": "^7.6.4",
    "@nestjs/config": "^0.6.1",
    "@nestjs/core": "^7.5.1",
    "@zoominfo/nest-logger": "^0.3.0",
    "semantic-release": "^17.3.7"
  },
  "devDependencies": {
    "@commitlint/cli": "^11.0.0",
    "@commitlint/config-conventional": "^11.0.0",
    "husky": "^4.3.8",
    "jest": "^26.6.3",
    "semantic-release": "^17.3.7"
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS"
    }
  }
}

jenkins code:

  pipeline {

    agent any

    environment {
        GH_TOKEN  = credentials('semantic')
        NPM_TOKEN = credentials('artifactory')
    }

    stages {
      stage ('Check branch condition') {
        when { // Only go ahead for certain branches
          beforeAgent true
          anyOf {
            branch "master";
            branch "hotfix-*";
          } //end anyOf
        } //end when
        stages {
          stage('Configure') {
            steps {
              hook 'configure'

              configuration {
                source "jenkins.yaml"
                select defaultSettings.config_select
                setenv true
                defaults defaultSettings
              }

              define npmPackage: parse('package.json')
            } // End steps
          } // End stage Configure

          stage('Install') {
            steps {
              script {
                nodejs(nodeJSInstallationName: "node10.18", configId: "${artifactory_install_npmrc}") {
                  sh "npm_install"
                } //End nodejs
              } // End script
            } // end steps
          } // end stage Publish

          stage('Build') {
            when { expression { npmPackage.scripts?.build } }
              steps {
                script {
                  nodejs(nodeJSInstallationName: nodeJS_version, configId: "${artifactory_install_npmrc}") {
                    sh "npm run build"
                  } //End nodejs
                } // End script
              } // End steps
          } // End stage Build

          stage('Publish') {
            steps {
              echo "####################"
              echo "Publishing to Artifactory"
              echo "####################"
              script {
                nodejs(nodeJSInstallationName: "node10.18", configId: "${artifactory_publish_npmrc}") {
                  sh "npx semantic-release"
                } //End nodejs
              } // End script
            } // end steps
          } // end stage Publish

          stage('Cleanup') {
            steps {
              sh "${npm_prune}"
              sh "${npm_rm_node_modules}"
            } // End steps
          } // End stage Cleanup
        } // End stages

      } // End "Do all things"
    } // End all stages

- CI logs: 

Pipeline] sh 
+ npx semantic-release
[11:59:53 AM] [semantic-release] ��� ���  Running semantic-release version 17.3.7
[11:59:54 AM] [semantic-release] ��� ���  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[11:59:54 AM] [semantic-release] ��� ���  Loaded plugin "verifyConditions" from "@semantic-release/github"
[11:59:54 AM] [semantic-release] ��� ���  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[11:59:54 AM] [semantic-release] ��� ���  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[11:59:54 AM] [semantic-release] ��� ���  Loaded plugin "prepare" from "@semantic-release/npm"
[11:59:54 AM] [semantic-release] ��� ���  Loaded plugin "publish" from "@semantic-release/npm"
[11:59:54 AM] [semantic-release] ��� ���  Loaded plugin "publish" from "@semantic-release/github"
[11:59:54 AM] [semantic-release] ��� ���  Loaded plugin "addChannel" from "@semantic-release/npm"
[11:59:54 AM] [semantic-release] ��� ���  Loaded plugin "addChannel" from "@semantic-release/github"
[11:59:54 AM] [semantic-release] ��� ���  Loaded plugin "success" from "@semantic-release/github"
[11:59:54 AM] [semantic-release] ��� ���  Loaded plugin "fail" from "@semantic-release/github"
[11:59:56 AM] [semantic-release] ��� ���  Run automated release from branch master on repository https://[secure]@git.zoominfo.com/dozi/dozi-architecture-tests.git
[11:59:56 AM] [semantic-release] ��� ���  Allowed to push to the Git repository
[11:59:56 AM] [semantic-release] ��� ���  Start step "verifyConditions" of plugin "@semantic-release/npm"
[11:59:56 AM] [semantic-release] [@semantic-release/npm] ��� ���  Verify authentication for registry https://zoominfo.jfrog.io/artifactory/api/npm/zoom-npm/
[11:59:56 AM] [semantic-release] [@semantic-release/npm] ��� ���  Wrote NPM_TOKEN to /tmp/90bda8f5857141007a475b9450d092e1/.npmrc
[11:59:56 AM] [semantic-release] ��� ���  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[11:59:56 AM] [semantic-release] ��� ���  Start step "verifyConditions" of plugin "@semantic-release/github"
[11:59:56 AM] [semantic-release] [@semantic-release/github] ��� ���  Verify GitHub authentication
[11:59:56 AM] [semantic-release] ��� ���  Failed step "verifyConditions" of plugin "@semantic-release/github"
[11:59:56 AM] [semantic-release] ��� ���  Start step "fail" of plugin "@semantic-release/github"
[11:59:56 AM] [semantic-release] [@semantic-release/github] ��� ���  Verify GitHub authentication
[11:59:57 AM] [semantic-release] ��� ���  Failed step "fail" of plugin "@semantic-release/github"
[11:59:57 AM] [semantic-release] ��� ���  EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository ****/****-architecture-tests.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personal token.

[11:59:57 AM] [semantic-release] ��� ���  EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository ****/****-architecture-tests.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personal token.

{ AggregateError: 
    SemanticReleaseError: Invalid GitHub token.
        at module.exports (/var/lib/[secure]/workspace/b_*****-architecture-tests_master/node_modules/@semantic-release/github/lib/get-error.js:6:10)
        at module.exports (/var/lib/[secure]/workspace/b_*****-architecture-tests_master/node_modules/@semantic-release/github/lib/verify.js:86:21)
    at /var/lib/[secure]/workspace/b_*****-architecture-tests_master/node_modules/semantic-release/lib/plugins/pipeline.js:54:11 name: [32m'AggregateError'[39m }

**Comment by smt9020** [comment]
I seem to be getting a similar issue
