### ISSUE TITLE
Synchronous extends for shareable configuration

### ISSUE THREAD

**Issue by isuftin** [semantic-release/semantic-release#1830]
I am hitting up against an issue with how extends works in semantic release. It seems to be a problem (feature?) of when and how semrel combines shareable config with the actual config.

Here's my inital `release.config.js` without using extends...

```javascript
const config = {
    branches: [
        'master',
        {
            name: 'development',
            prerelease: true
        }
    ]
}

if (config.branches.some(it => it === branch || (it.name === branch && !it.prerelease))) {
  // Do stuff here if it's not a pre-release branch, like create a CHANGELOG
}

module.exports = config
```

This works as expected.

Shareable config, published as `my-shareable-config`:

```javascript
let config = {
    branches: [
        'master',
        {
            name: 'something_else',
            prerelease: true
        }
    ],
module.exports = config
```

My `release.config.js` using shared config:

```javascript
const config = {
    extends: [
        'my-shareable-config'
    ]
}

if (config.branches.some(it => it === branch || (it.name === branch && !it.prerelease))) {
  // Do stuff here if it's not a pre-release branch, like create a CHANGELOG
}

module.exports = config
```

The result: ` [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Cannot read property 'some' of undefined`

If I remove the javascript, everything works as expected and the branches I define in my shareable config are what are used.

If I add a `console.out(config)` right before the javascript in the scenario where I use the extends, I get...

`{ extends: [ 'my-shareable-config' ] }`

I would expect that by this point my config object would contain the data I have in `my-shareable-config` but it seems to not happen until later in the process.

So my question: Is there anything I can do here to include js in my `release.config.js` that works on content coming in from an `extends`?

I am using semantic-release 17.4.0

**Comment by isuftin** [comment]
In case more info is needed... debug output...

```
[2:20:50 PM] [semantic-release] › ℹ  Running semantic-release version 17.4.0
[2:20:50 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Cannot read property 'some' of undefined
    at Object.<anonymous> (/Users/isuftin/Development/downstream_project/release.config.js:66:21)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/import-fresh/index.js:32:59)
    at loadJs (/usr/local/lib/node_modules/semantic-release/node_modules/cosmiconfig/dist/loaders.js:16:18)
    at Explorer.loadFileContent (/usr/local/lib/node_modules/semantic-release/node_modules/cosmiconfig/dist/Explorer.js:84:32)
    at Explorer.createCosmiconfigResult (/usr/local/lib/node_modules/semantic-release/node_modules/cosmiconfig/dist/Explorer.js:89:36)
TypeError: Cannot read property 'some' of undefined
    at Object.<anonymous> (/Users/isuftin/Development/downstream_project/release.config.js:66:21)
    at Module._compile (node:internal/modules/cjs/loader:1091:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
    at Module.load (node:internal/modules/cjs/loader:971:32)
    at Function.Module._load (node:internal/modules/cjs/loader:812:14)
    at Module.require (node:internal/modules/cjs/loader:995:19)
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/import-fresh/index.js:32:59)
    at loadJs (/usr/local/lib/node_modules/semantic-release/node_modules/cosmiconfig/dist/loaders.js:16:18)
    at Explorer.loadFileContent (/usr/local/lib/node_modules/semantic-release/node_modules/cosmiconfig/dist/Explorer.js:84:32)
    at Explorer.createCosmiconfigResult (/usr/local/lib/node_modules/semantic-release/node_modules/cosmiconfig/dist/Explorer.js:89:36)npm ERR! code 1
npm ERR! path /Users/isuftin/Development/downstream_project
npm ERR! command failed
npm ERR! command sh -c semantic-release "--dry-run" "--debug"

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/isuftin/.npm/_logs/2021-03-03T20_20_50_857Z-debug.log
```

And the debug log...

```
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.10.0_1/bin/node',
0 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'semantic-release',
0 verbose cli   '--dry-run',
0 verbose cli   '--debug'
0 verbose cli ]
1 info using npm@7.5.3
2 info using node@v15.10.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 2ms
5 timing config:load:builtin Completed in 2ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/isuftin/Development/downstream_project/.npmrc Completed in 0ms
9 timing config:load:project Completed in 0ms
10 timing config:load:file:/Users/isuftin/.npmrc Completed in 1ms
11 timing config:load:user Completed in 1ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 8ms
19 verbose npm-session 8bf79c677fe8bfd5
20 timing npm:load Completed in 18ms
21 timing command:exec Completed in 466ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:378:20)
22 verbose stack     at maybeClose (node:internal/child_process:1067:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:301:5)
23 verbose cwd /Users/isuftin/Development/downstream_project
24 verbose Darwin 18.7.0
25 verbose argv "/usr/local/Cellar/node/15.10.0_1/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "semantic-release" "--dry-run" "--debug"
26 verbose node v15.10.0
27 verbose npm  v7.5.3
28 error code 1
29 error path /Users/isuftin/Development/downstream_project
30 error command failed
31 error command sh -c semantic-release "--dry-run" "--debug"
32 verbose exit 1
```

**Comment by isuftin** [comment]
Unless someone provides a better answer, not using `extends` and instead doing something like this seems to work but feels hacky:

```javascript
let shared_config = require('my-shareable-config')
let config = {...shared_config, ...{
    branches: [
        'master',
        {
            name: 'development',
            prerelease: true
        }
    ],
  // more config stuff here
}}

if (config.branches.some(it => it === branch || (it.name === branch && !it.prerelease))) {
  // Do stuff here if it's not a pre-release branch, like create a CHANGELOG
}

module.exports = config
```
