### ISSUE TITLE
Error: Cannot find module '@semantic-release/changelog'

### ISSUE THREAD

**Issue by W3-Anjan** [semantic-release/semantic-release#1898]
## Current behavior

On my java based android project, I am trying to implement automated semantic versioning. I am taking step by step reference from [this reference]( https://dev.to/migu3l/commit-standard-and-semantic-versioning-for-any-project-1ihc). Unfortunately I am getting this error below.

`npx: installed 572 in 16.141s
[10:19:27 AM] [semantic-release] › ℹ  Running semantic-release version 17.4.2
[10:19:28 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[10:19:28 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[10:19:28 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[10:19:28 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[10:19:28 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Cannot find module '@semantic-release/changelog'
Require stack:
- /home/runner/work/RxJavaTutorial/RxJavaTutorial/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at resolveFileName (/home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:47)
    at loadPlugin (/home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/lib/plugins/utils.js:51:82)
    at module.exports (/home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/lib/plugins/normalize.js:16:18)
    at /home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/lib/plugins/index.js:70:9
    at Array.map (<anonymous>)
    at /home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/lib/plugins/index.js:69:46
    at Array.reduce (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/RxJavaTutorial/RxJavaTutorial/noop.js' ]
}
Error: Cannot find module '@semantic-release/changelog'
Require stack:
- /home/runner/work/RxJavaTutorial/RxJavaTutorial/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at resolveFileName (/home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:47)
    at loadPlugin (/home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/lib/plugins/utils.js:51:82)
    at module.exports (/home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/lib/plugins/normalize.js:16:18)
    at /home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/lib/plugins/index.js:70:9
    at Array.map (<anonymous>)
    at /home/runner/.npm/_npx/1971/lib/node_modules/semantic-release/lib/plugins/index.js:69:46
    at Array.reduce (<anonymous>) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/RxJavaTutorial/RxJavaTutorial/noop.js' ]
}
Error: Process completed with exit code 1.`

## Environment

- **semantic-release** version: 
- CI environment: 
- Plugins used: 
- **semantic-release** configuration: 
- CI logs:

**Comment by boraoren** [comment]
npm install @semantic-release/changelog  -D
