### ISSUE TITLE
CLI crashes during setup

### ISSUE THREAD

**Issue by satya164** [semantic-release/semantic-release#191]
Whenever I try to run `semantic-release-cli setup`, after selecting the CI, it crashes.

Here is the stack trace.

```
/usr/local/lib/node_modules/semantic-release-cli/dist/lib/travis.js:113
    travis.repos(info.ghrepo.slug[0], info.ghrepo.slug[1]).get(function (err, res) {
                            ^

TypeError: Cannot read property 'slug' of undefined
    at /usr/local/lib/node_modules/semantic-release-cli/dist/lib/travis.js:113:29
    at /usr/local/lib/node_modules/semantic-release-cli/dist/lib/travis.js:50:5
    at /usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21
    at Request._callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:51:13)
    at Request.self.callback (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:148:22)
    at emitTwo (events.js:100:13)
    at Request.emit (events.js:185:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:886:14)
    at emitOne (events.js:95:20)
    at Request.emit (events.js:182:7)
```

**Comment by remy** [comment]
Do you get the same result on different repos or on the same single repo? I don't know the inners of semantic-release well enough to tell you off hand, but I could probably debug it...

**Comment by satya164** [comment]
@remy Tried several repos, and same result. I've 2 factor authentication enabled, if that helps.

**Comment by satya164** [comment]
@boennemann Any idea? I'll really love to use this.

**Comment by tusharmath** [comment]
Try logging in on travis and sync your repos and try again?

**Comment by satya164** [comment]
@tusharmath I'm stuck at initial set up in any repo. Travis doesn't come into picture.

**Comment by satya164** [comment]
I've not been able to repro this for quite some time. Closing.
