### ISSUE TITLE
Variables in cli arg tag-format are being evaluated even when single quoted or escaped

### ISSUE THREAD

**Issue by RoamingKiwi** [semantic-release/semantic-release#1933]
## Current behavior

Running semantic-release while providing the tag format via cli options evaluates the placeholder `${version}` as a variable and evaluates it. E.g. for `--tag-format  'v${version}'` tagFormat evaluates to `v`

```
npx semantic-release --tag-format 'v${version}'
[12:31:08 PM] [semantic-release] › ℹ  Running semantic-release version 17.4.2
[12:31:08 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[12:31:08 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:31:08 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:31:08 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[12:31:08 PM] [semantic-release] › ✖  ETAGNOVERSION Invalid `tagFormat` option.
The tagFormat (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#tagformat) option must contain the variable version exactly once.
Your configuration for the tagFormat option is v.
AggregateError: 
    SemanticReleaseError: Invalid `tagFormat` option.
        at module.exports (/app/node_modules/semantic-release/lib/get-error.js:6:10)
        at module.exports (/app/node_modules/semantic-release/lib/verify.js:29:17)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async run (/app/node_modules/semantic-release/index.js:54:3)
        at async module.exports (/app/node_modules/semantic-release/index.js:260:22)
        at async module.exports (/app/node_modules/semantic-release/cli.js:55:5)
    at module.exports (/app/node_modules/semantic-release/lib/verify.js:41:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/app/node_modules/semantic-release/index.js:54:3)
    at async module.exports (/app/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/app/node_modules/semantic-release/cli.js:55:5)

```

## Expected behavior

`--tag-format  'v${version}'` evaluates as `v${version}`

## Environment

- **semantic-release** version: 17.4.2
- CI environment: self hosted gitlab
- Plugins used: see log
- **semantic-release** configuration: N/A
- CI logs: copied above

**Comment by RoamingKiwi** [comment]
A workaround if anyone else is facing the same issue is to run `export version='${version}'` before semantic-release
