### ISSUE TITLE
"fatal: Authentication failed for 'https://[secure]@github.com/user/repo/'" - Error 128 - remote: Invalid username or password.

### ISSUE THREAD

**Issue by tonydehnke** [semantic-release/semantic-release#1947]
## Current behavior

When running on CircleCI - the semantic release fails,  but there have been no changes to the process

I checked on Github and it shows connection/auth to CircleCI is still valid.

## Expected behavior

Should work

## Environment

- **semantic-release** version:  "semantic-release": "^17.4.3",
- CI environment: CircleCI
- Plugins used: (Unsure what this is)
- **semantic-release** configuration: 

semantic_release:
    docker:
      - image: circleci/ruby:2.6.6-stretch-node-browsers # ...with this image as the primary container; this is where all `steps` will run
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Yarn Install
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run: npx semantic-release@17

workflows:
  version: 2
  build_test_and_release:
    jobs:
      - build_and_test

      - semantic_release:
          filters:
            branches:
              only:
                - master
                - staging
          requires:
            - build_and_test

- CI logs:

#!/bin/bash -eo pipefail
npx semantic-release@17
npx: installed 573 in 13.195s
[3:24:45 AM] [semantic-release] › ℹ  Running semantic-release version 17.4.3
[3:24:45 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[3:24:45 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[3:24:45 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[3:24:45 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[3:24:45 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[3:24:45 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[3:24:45 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[3:24:45 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@github.com/tonydehnke/12vBiz
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/tonydehnke/12vBiz/'
    at makeError (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getBranches (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/lib/git.js:66:11)
    at async module.exports (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/lib/branches/expand.js:6:23)
    at async module.exports (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/lib/branches/index.js:14:26)
    at async run (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/index.js:57:22)
    at async module.exports (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 128: git ls-remote --heads https://[secure]@github.com/tonydehnke/12vBiz',
  command: 'git ls-remote --heads https://[secure]@github.com/tonydehnke/12vBiz',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: Invalid username or password.\n' +
    "fatal: Authentication failed for 'https://[secure]@github.com/tonydehnke/12vBiz/'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
Error: Command failed with exit code 128: git ls-remote --heads https://[secure]@github.com/tonydehnke/12vBiz
remote: Invalid username or password.
fatal: Authentication failed for 'https://[secure]@github.com/tonydehnke/12vBiz/'
    at makeError (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/node_modules/execa/index.js:114:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getBranches (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/lib/git.js:66:11)
    at async module.exports (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/lib/branches/expand.js:6:23)
    at async module.exports (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/lib/branches/index.js:14:26)
    at async run (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/index.js:57:22)
    at async module.exports (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/circleci/.npm/_npx/263/lib/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 128: git ls-remote --heads https://[secure]@github.com/tonydehnke/12vBiz',
  command: 'git ls-remote --heads https://[secure]@github.com/tonydehnke/12vBiz',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: Invalid username or password.\n' +
    "fatal: Authentication failed for 'https://[secure]@github.com/tonydehnke/12vBiz/'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Exited with code exit status 1
CircleCI received exit code 1

**Comment by tonydehnke** [comment]
So was able to resolve this by regenerating the Auth Token in Github 
  1. Github:(Settings -> Developer settings -> Personal Access Tokens -> Regenate Token (kept all the settings the same).  
  2. Then in Circle CI:  Project -> Project Settings (top right of screen)  -> Environment Variables -> Delete old token (mine was called GH_TOKEN), and re-add GH_TOKEN with new value created in Github.  
  3. Re-run failed Semantic Release and it worked. 

I have no idea why the token stopped working.  I had not changed it in Github or CircleCI from what it had been for months.

Perhaps the error message could be improved to say that the Token failed?   Saying it's remote: Invalid username or password.\n is not really clear when it's a bad token.

**Comment by MrSwitch** [comment]
I wasn't able to resolve this by creating new tokens, it still gave me the prompt to sign in. Instead i downgraded to `semantic-release@17.0.1` which i knew worked.

Here's my triage 

❌ 

```
% npm -v
7.18.1
% node -v
v14.17.0
% npx semantic-release -v

17.4.4
% GITHUB_TOKEN=ghp_**REDACTED** npm run semantic-release

> 5appdashboard@7.9.0 semantic-release
> semantic-release

[12:13:43] [semantic-release] › ℹ  Running semantic-release version 17.4.4
[12:13:43] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[12:13:43] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[12:13:43] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:13:43] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:13:43] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[12:13:43] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[12:13:43] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[12:13:43] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[12:13:43] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[12:13:43] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[12:13:43] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[12:13:43] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[12:13:43] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[12:13:43] [semantic-release] › ⚠  This run was not triggered in a known CI environment, running in dry-run mode.
Username for 'https://github.com': ^C
```


Then after downgrading to `semantic-release@17.0.1`, you see it works 🎉 

✅ 
```
% npm i semantic-release@17.0.1      
...**TRUNCATED**
Run `npm audit` for details.
% GITHUB_TOKEN=ghp_**REDACTED** npm run semantic-release

> 5appdashboard@7.9.0 semantic-release
> semantic-release

[12:14:07] [semantic-release] › ℹ  Running semantic-release version 17.0.1
[12:14:08] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[12:14:08] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[12:14:08] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:14:08] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:14:08] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[12:14:08] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[12:14:08] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[12:14:08] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[12:14:08] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[12:14:08] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[12:14:08] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[12:14:08] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[12:14:08] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[12:14:08] [semantic-release] › ⚠  This run was not triggered in a known CI environment, running in dry-run mode.
[12:14:13] [semantic-release] › ⚠  Run automated release from branch master in dry-run mode
[12:14:14] [semantic-release] › ✔  Allowed to push to the Git repository
[12:14:14] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[12:14:14] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[12:14:14] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[12:14:14] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[12:14:14] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[12:14:14] [semantic-release] › ℹ  Found git tag v7.9.0 associated with version 7.9.0 on branch master
[12:14:14] [semantic-release] › ℹ  Found 8 commits since last release
[12:14:14] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #10269 from 5app/ci-patch-hub-rename

fix(ci): hub git path
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(ci): hub git path
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #10257 from 5app/staging

chore(release): Patch scorm bug in chrome
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #10261 from 5app/fix-ci-npm7

chore(ci): fix semantic-release commiting version 1 of package-lock
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(deps): re-update package-lock version 2, noissue
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore(ci): fix semantic-release commiting version 1 of package-lock, noissue
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #10252 from 5app/10241-api-support-gzip-encoded-body

fix(scorm): allow gzip payload to resolve chrome bug, #10241
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(scorm): add middleware to body parse gzip payloads, #10241
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[12:14:14] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 8 commits complete: patch release
[12:14:14] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:14:14] [semantic-release] › ℹ  The next release version is 7.9.1
[12:14:14] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:14:14] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:14:14] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/changelog" in dry-run mode
[12:14:14] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/npm" in dry-run mode
[12:14:14] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/git" in dry-run mode
[12:14:14] [semantic-release] › ⚠  Skip v7.9.1 tag creation in dry-run mode
[12:14:14] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/npm" in dry-run mode
[12:14:14] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/github" in dry-run mode
[12:14:14] [semantic-release] › ⚠  Skip step "success" of plugin "@semantic-release/github" in dry-run mode
[12:14:14] [semantic-release] › ✔  Published release 7.9.1 on default channel
[12:14:14] [semantic-release] › ℹ  Release note for version 7.9.1:
## 7.9.1 (https://github.com/5app/hub/compare/v7.9.0...v7.9.1) (2021-06-19)
...
```
