### ISSUE TITLE
17.4.4 tag is broken  - extensions.renderers?.[ext.name]

### ISSUE THREAD

**Issue by pzhuk** [semantic-release/semantic-release#1982]
17.4.4 seems to be broken, not sure if this is dependency 

## Current behavior

$ semantic-release
/usr/local/lib/node_modules/semantic-release/node_modules/marked/src/marked.js:158
          const prevRenderer = extensions.renderers?.[ext.name];
                                                    ^
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/semantic-release/index.js:2:16)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)

## Expected behavior

Successful run

## Environment

- **semantic-release** version:  17.4.4

**Comment by SergiiPietinov** [comment]
+1

**Comment by pzhuk** [comment]
duplicate https://github.com/semantic-release/semantic-release/issues/1981 I guess
also reported in dependency repo https://github.com/markedjs/marked/issues/2110

**Comment by smyrglsy** [comment]
+1

**Comment by elektracodes** [comment]
+1

**Comment by rafiek** [comment]
The fix for this is to create a new package-lock.json with the latest version of `marked`. I think?

**Comment by travi** [comment]
since this has been resolved on the `marked` side, updating your lockfile to the latest version of `marked` should resolve any issues you may have seen from this. closing this issue since there is no problem to resolve on the `semantic-release` side
