### ISSUE TITLE
Github Action Fails with @semantic-release/git

### ISSUE THREAD

**Issue by devGW** [semantic-release/semantic-release#2025]
## Current behavior
When I try to deploy on my github actions the new version of my application, I have the following error:
```
Run codfish/semantic-release-action@master
  with:
  env:
    GITHUB_TOKEN: 
    NPM_TOKEN: 
/usr/bin/docker run --name a33c1d8c6222bc45647feaaea993a70ebb649_b5d6a2 --label 8a33c1 --workdir /github/workspace --rm -e GITHUB_TOKEN -e NPM_TOKEN -e INPUT_BRANCHES -e INPUT_PLUGINS -e INPUT_EXTENDS -e INPUT_DRY_RUN -e INPUT_REPOSITORY_URL -e INPUT_TAG_FORMAT -e INPUT_BRANCH -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/lubycon-react/lubycon-react":"/github/workspace" 8a33c1:d8c6222bc45647feaaea993a70ebb649
[3:50:55 PM] [semantic-release] › ℹ  Running semantic-release version 17.4.0
[3:50:55 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Cannot find module '@semantic-release/git'
Require stack:
- /github/workspace/noop.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at resolveFileName (/action/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/action/node_modules/resolve-from/index.js:43:9)
    at module.exports (/action/node_modules/resolve-from/index.js:46:47)
    at loadPlugin (/action/node_modules/semantic-release/lib/plugins/utils.js:51:82)
    at /action/node_modules/semantic-release/lib/plugins/index.js:17:37
    at Array.reduce (<anonymous>)
    at module.exports (/action/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/action/node_modules/semantic-release/lib/get-config.js:84:35)
    at async module.exports (/action/node_modules/semantic-release/index.js:257:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/github/workspace/noop.js' ]
}
Error: Error: Cannot find module '@semantic-release/git'
Require stack:
- /github/workspace/noop.js
```

That is my package.json
```
{
  "name": "@lubycon/react",
  "description": "React utils which uses in Lubycon",
  "sideEffects": false,
  "version": "1.1.0",
  "keywords": [
    "react"
  ],
  "main": "dist/index.js",
  "module": "dist",
  "typings": "dist/types/index.d.ts",
  "publishConfig": {
    "access": "public"
  },
  "files": [
    "dist"
  ],
  "author": "Lubycon <lubycon@gmail.com>",
  "repository": {
    "type": "git",
    "url": "https://github.com/Lubycon/lubycon-react"
  },
  "license": "MIT",
  "engines": {
    "node": ">=10.15"
  },
  "scripts": {
    "lint": "tslint  --project tsconfig.json -t codeFrame 'src/**/*.ts' 'test/**/*.ts'",
    "prebuild": "rimraf dist",
    "build": "tsc --module commonjs && rollup -c rollup.config.ts",
    "start": "rollup -c rollup.config.ts -w",
    "test": "jest --coverage",
    "test:watch": "jest --coverage --watch",
    "test:prod": "npm run lint && npm run test -- --no-cache",
    "report-coverage": "cat ./coverage/lcov.info | coveralls",
    "commit": "git-cz",
    "precommit": "lint-staged",
    "copy-version": "ncp dist/package.json package.json",
    "typecheck": "tsc --noEmit"
  },
  "lint-staged": {
    "{src,test}/**/*.ts": [
      "prettier --write",
      "git add"
    ]
  },
  "config": {
    "commitizen": {
      "path": "node_modules/cz-conventional-changelog"
    }
  },
  "jest": {
    "transform": {
      ".(ts|tsx)": "ts-jest"
    },
    "testEnvironment": "node",
    "testRegex": "(/__tests__/.*|\\.(test|spec))\\.(ts|tsx|js)$",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js"
    ],
    "coveragePathIgnorePatterns": [
      "/node_modules/",
      "/test/"
    ],
    "coverageThreshold": {
      "global": {
        "branches": 90,
        "functions": 95,
        "lines": 95,
        "statements": 95
      }
    },
    "collectCoverageFrom": [
      "src/*.{js,ts}"
    ]
  },
  "commitlint": {
    "extends": [
      "@commitlint/config-conventional"
    ]
  },
  "devDependencies": {
    "@commitlint/cli": "^7.1.2",
    "@commitlint/config-conventional": "^7.1.2",
    "@semantic-release/commit-analyzer": "^8.0.1",
    "@semantic-release/git": "^9.0.0",
    "@semantic-release/github": "^7.2.3",
    "@semantic-release/npm": "^7.1.3",
    "@semantic-release/release-notes-generator": "^9.0.2",
    "@types/jest": "^23.3.2",
    "@types/node": "^10.11.0",
    "@types/react": "^17.0.13",
    "@typescript-eslint/eslint-plugin": "^4.25.0",
    "@typescript-eslint/parser": "^4.25.0",
    "@yarnpkg/pnpify": "^3.0.0-rc.10",
    "colors": "^1.3.2",
    "commitizen": "^3.0.0",
    "coveralls": "^3.0.2",
    "cross-env": "^5.2.0",
    "cz-conventional-changelog": "^2.1.0",
    "eslint": "^7.27.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-prettier": "^3.4.0",
    "husky": "^1.0.1",
    "jest": "^23.6.0",
    "jest-config": "^23.6.0",
    "lint-staged": "^8.0.0",
    "ncp": "^2.0.0",
    "prettier": "^2.1.2",
    "prompt": "^1.0.0",
    "replace-in-file": "^3.4.2",
    "rimraf": "^2.6.2",
    "rollup": "^2.38.5",
    "rollup-plugin-commonjs": "^10.1.0",
    "rollup-plugin-json": "^3.1.0",
    "rollup-plugin-node-resolve": "^3.4.0",
    "rollup-plugin-sourcemaps": "^0.4.2",
    "rollup-plugin-typescript2": "^0.30.0",
    "semantic-release": "^15.9.16",
    "shelljs": "^0.8.3",
    "ts-jest": "^23.10.2",
    "ts-node": "^7.0.1",
    "typescript": "^3.0.3"
  },
  "peerDependencies": {
    "react": "^17.0.2"
  }
}
```

## Expected behavior
Deploy with Github Actions and update package.json with the new version

## Environment
yarn: 2.4.2
semantic-release version: 15.9.16
CI environment: Github Actions
Plugins used:
"@semantic-release/npm",
"@semantic-release/github",
"@semantic-release/commit-analyzer",
"@semantic-release/release-notes-generator"
"@semantic-release/git"
semantic-release configuration: My full package.json is attached to this
CI logs: The semantic log is on this ticket also

**Comment by travi** [comment]
please refrain from posting support requests in multiple places. closing in favor of https://github.com/semantic-release/semantic-release/discussions/2024
