### ISSUE TITLE
Tag escaping not working properly.

### ISSUE THREAD

**Issue by ankurshaswat** [semantic-release/semantic-release#2030]
I am trying to use semantic release in a CI pipeline. The current workflow is 

```yml
  
name: Release
on: [push]

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install -g semantic-release @semantic-release/changelog @semantic-release/commit-analyzer @semantic-release/exec @semantic-release/git @semantic-release/release-notes-generator
      - run: npx semantic-release -t "v\${version}"
```

The error encountered -
```
[4:27:15 AM] [semantic-release] › ℹ  Running semantic-release version 17.4.4
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/exec"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
[4:27:15 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
[4:27:15 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/exec"
[4:27:15 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/exec"
[4:27:15 AM] [semantic-release] › ✖  ETAGNOVERSION Invalid `tagFormat` option.
The tagFormat (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#tagformat) option must contain the variable version exactly once.

Your configuration for the tagFormat option is v.

[4:27:15 AM] [semantic-release] › ✖  EINVALIDTAGFORMAT Invalid `tagFormat` option.
The tagFormat (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#tagformat) must compile to a valid Git reference (https://git-scm.com/docs/git-check-ref-format#_description).

Your configuration for the tagFormat option is v.

AggregateError: 
    SemanticReleaseError: Invalid `tagFormat` option.
        at module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/lib/get-error.js:6:10)
        at module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/lib/verify.js:22:17)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async run (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/index.js:54:3)
        at async module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/index.js:260:22)
        at async module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/cli.js:55:5)
    SemanticReleaseError: Invalid `tagFormat` option.
        at module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/lib/get-error.js:6:10)
        at module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/lib/verify.js:29:17)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async run (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/index.js:54:3)
        at async module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/index.js:260:22)
        at async module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/cli.js:55:5)
    at module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/lib/verify.js:41:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/index.js:54:3)
    at async module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/opt/hostedtoolcache/node/16.5.0/x64/lib/node_modules/semantic-release/cli.js:55:5)
Error: Process completed with exit code 1.
```

I have also tried double escaping version field ("v\\\${version}") and also using single quotes ('v${version}') for the tagformat parameter but in all cases the ${version} field is just being replaced by empty string and then leading to the same error. I am trying to specify manual tagformat to add branches but am not able to give any manual parameter.

I am using node 16 with github actions as seen from the workflow.

**Comment by toiroakr** [comment]
I faced with the same issue on updating npm from v6 to v7.

**Comment by kh-sonrai** [comment]
I am seeing similar issues in one of my pipelines. Has anyone found any solutions for this problem?

**Comment by LakshmiRavali** [comment]
I am also facing the same issue recently and blocked. Any update on the solution?

**Comment by tungnguyen2021** [comment]
A workaround is that you can put it in `.releaserc` like this
```
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/github"
  ],
  tagFormat: "v${version}"
}
```

See documentation here https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#configuration

**Comment by alko89** [comment]
I'm having the same issue. I tried different node versions, with, without escape for version var but no luck. I want to have different release tags (like release and dev) so I don't want to put it in the `releaserc` file.

I have a min repo where I'm trying different options:

https://gitlab.com/alko89/test

**Comment by mcfloyd** [comment]
Also running into this, and determined through many CI runs that it is not a CI issue.

**Comment by Blackclaws** [comment]
I've only found a single solution to this. Its putting the part in question into the package.json script section like this:
```
  "scripts": {
	"semantic-release": "semantic-release -e semantic-release-monorepo --no-ci --tag-format='test-service-v${version}'"
  },
```
Then you can just run
```
npm run semantic-release
```

**Comment by qcloutier-sonrai** [comment]
This hopefully won't be an issue for much longer now that this has been fixed in npm 8.13.0, but for those of us trying to run this in a pipeline with an older version, I've found the following to work:
```
VERSION='v${version}' npx semantic-release -t '$VERSION' 
```

Note the single quotes around both 'v${version}' and  '$VERSION' -- thankfully variables aren't getting expanded recursively so this one layer of indirection is good enough to get it the correct string.

Of course, once you upgrade npm to 8.13+, this will break! So be mindful that you'll have to change it.

**Comment by tomavic** [comment]
Should tag name be `v${VERSION}` or `test-v${VERSION}` but not `v${VERSION} test`?
