### ISSUE TITLE
Tags.Channels.Some is not a function

### ISSUE THREAD

**Issue by McRegt** [semantic-release/semantic-release#2186]
## Current behavior

Calculating a new pre-release version for one of our repositories fails with the below error message:

Previous commit:
`build: update something` -> Generated tag: `v2.0.14` with note `{"channels":["beta"]}`

New commit on feature branch `feature-12345`:
`revert: undo something` -> None, error message is thrown instead:

`An error occurred while running semantic-release: TypeError: tag.channels.some is not a function`

## Expected behavior

New commit on feature branch `feature-12345`:
`revert: undo something` -> Generated tag: `v2.1.0-feature-12345.1` with note `{"channels":["alpha"]}`

## Environment

Other repositories in the environment are working correctly, it's just this repository that runs into this error.
However, based on the information above, I don't see anything wrong with the tags and notes present.

- **semantic-release** version: 18.0.0
- CI environment: Azure DevOps
- Plugins used: See configuration below.
- **semantic-release** configuration: 

```
{
	"branches": [
		{
			"name": "release-v*",
			"channel": "release"
		},
		{
			"name": "master",
			"channel": "beta"
		},
		{
			"name": "feature-*",
			"prerelease": true,
			"channel": "alpha"
		}
	],
	"plugins": [
		[
			"@semantic-release/commit-analyzer",
			{
				"preset": "conventionalcommits",
				"releaseRules": [
					{
						"breaking": true,
						"release": "major"
					},
					{
						"type": "feat",
						"release": "minor"
					},
					{
						"type": "fix",
						"release": "patch"
					},
					{
						"type": "chore",
						"release": "patch"
					},
					{
						"type": "docs",
						"release": "patch"
					},
					{
						"type": "style",
						"release": "patch"
					},
					{
						"type": "refactor",
						"release": "patch"
					},
					{
						"type": "perf",
						"release": "patch"
					},
					{
						"type": "test",
						"release": "patch"
					},
					{
						"type": "ci",
						"release": "patch"
					},
					{
						"type": "build",
						"release": "patch"
					},
					{
						"type": "revert",
						"release": "minor"
					},
					{
						"scope": "no-release",
						"release": false
					}
				],
				"parserOpts": {
					"noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES"]
				},
				"presetConfig": {
					"types": [
						{
							"type": "feat",
							"section": "Features"
						},
						{
							"type": "fix",
							"section": "Bug Fixes"
						},
						{
							"type": "chore",
							"hidden": true
						},
						{
							"type": "docs",
							"hidden": true
						},
						{
							"type": "style",
							"hidden": true
						},
						{
							"type": "refactor",
							"hidden": true
						},
						{
							"type": "perf",
							"hidden": true
						},
						{
							"type": "test",
							"hidden": true
						},
						{
							"type": "ci",
							"hidden": true
						},
						{
							"type": "build",
							"hidden": true
						},
						{
							"type": "revert",
							"hidden":  true
						}
					]
				}
			}
		],
		"@semantic-release/release-notes-generator"
	]
}
```

- CI logs: 

```
[9:04:36 AM] [semantic-release] › ℹ  Running semantic-release version 18.0.0
[9:04:37 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:04:37 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[9:04:39 AM] [semantic-release] › ✔  Run automated release from branch feature-12345 on repository [REMOVED]
[9:04:39 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:04:39 AM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: tag.channels.some is not a function
    at /home/vsts/.yarn/berry/cache/semantic-release-npm-18.0.0-26bef7164f-8.zip/node_modules/semantic-release/lib/get-last-release.js:33:56
    at Array.filter (<anonymous>)
    at module.exports (/home/vsts/.yarn/berry/cache/semantic-release-npm-18.0.0-26bef7164f-8.zip/node_modules/semantic-release/lib/get-last-release.js:31:6)
    at run (/home/vsts/.yarn/berry/cache/semantic-release-npm-18.0.0-26bef7164f-8.zip/node_modules/semantic-release/index.js:142:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/home/vsts/.yarn/berry/cache/semantic-release-npm-18.0.0-26bef7164f-8.zip/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/vsts/.yarn/berry/cache/semantic-release-npm-18.0.0-26bef7164f-8.zip/node_modules/semantic-release/cli.js:55:5)
TypeError: tag.channels.some is not a function
    at /home/vsts/.yarn/berry/cache/semantic-release-npm-18.0.0-26bef7164f-8.zip/node_modules/semantic-release/lib/get-last-release.js:33:56
    at Array.filter (<anonymous>)
    at module.exports (/home/vsts/.yarn/berry/cache/semantic-release-npm-18.0.0-26bef7164f-8.zip/node_modules/semantic-release/lib/get-last-release.js:31:6)
    at run (/home/vsts/.yarn/berry/cache/semantic-release-npm-18.0.0-26bef7164f-8.zip/node_modules/semantic-release/index.js:142:25)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async module.exports (/home/vsts/.yarn/berry/cache/semantic-release-npm-18.0.0-26bef7164f-8.zip/node_modules/semantic-release/index.js:260:22)
```

**Comment by McRegt** [comment]
In the end it appears this was not caused by semantic release, but instead caused by the migration in relation to git notes that was needed for support for semantic release version 18.0.0. One (seemingly) random tag had a corresponding git note that was not compliant with the necessary format:

`{"channels":"alpha"}`

After updating it to the required format (using an array) the builds started working again.

`{"channels":["alpha"]}`
