### ISSUE TITLE
For every new version, Changelog.md file generated via CircleCI workflow deletes previous version logs and adds new  version logs only 

### ISSUE THREAD

**Issue by Eseoghene** [semantic-release/semantic-release#2209]
## Current behavior

For every new version, Changelog.md file generated deletes previous values. and creates the file afresh 
Please see image below file history
![image](https://user-images.githubusercontent.com/8102030/139114906-f34e81f8-fadb-44fd-9452-56906f068166.png)

## Expected behavior
Previous values from previous releases should be in the changelog.md file

## Environment

- **semantic-release** : `"^18.0.0"`
- CI environment: `CircleCI`
- Plugins used: 
  `  "@semantic-release/changelog": "^6.0.0"`
   ` "@semantic-release/git": "^10.0.0"`

- **semantic-release** configuration: 
 `{
    "branches": ["production"],
    "plugins": [
        "@semantic-release/commit-analyzer", 
        "@semantic-release/release-notes-generator",
        "@semantic-release/changelog",
        "@semantic-release/github",
        "@semantic-release/git" ]
    }`
- CI logs: 
`#!/bin/bash -eo pipefail
yarn semantic-release --debug
yarn run v1.22.5
$ /home/circleci/project/node_modules/.bin/semantic-release --debug
[5:12:56 PM] [semantic-release] › ℹ  Running semantic-release version 18.0.0
  semantic-release:config load config from: /home/circleci/project/.releaserc +0ms
  semantic-release:config options values: {
  semantic-release:config   branches: [ 'production' ],
  semantic-release:config   repositoryUrl: 'https://github.com/SertoID/Test-Release-flow.git',
  semantic-release:config   tagFormat: 'v${version}',
  semantic-release:config   plugins: [
  semantic-release:config     '@semantic-release/commit-analyzer',
  semantic-release:config     '@semantic-release/release-notes-generator',
  semantic-release:config     '@semantic-release/changelog',
  semantic-release:config     '@semantic-release/github',
  semantic-release:config     '@semantic-release/git'
  semantic-release:config   ],
  semantic-release:config   _: [],
  semantic-release:config   debug: true,
  semantic-release:config   '$0': 'node_modules/.bin/semantic-release'
  semantic-release:config } +2ms
  semantic-release:plugins options for @semantic-release/changelog/verifyConditions: {} +0ms
[5:12:57 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
  semantic-release:plugins options for @semantic-release/github/verifyConditions: {} +1ms
[5:12:57 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/git/verifyConditions: {} +0ms
[5:12:57 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
  semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {} +0ms
[5:12:57 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
  semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {} +1ms
[5:12:57 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
  semantic-release:plugins options for @semantic-release/changelog/prepare: {} +0ms
[5:12:57 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
  semantic-release:plugins options for @semantic-release/git/prepare: {} +0ms
[5:12:57 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
  semantic-release:plugins options for @semantic-release/github/publish: {} +0ms
[5:12:57 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/github/addChannel: {} +1ms
[5:12:57 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/github/success: {} +0ms
[5:12:57 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
  semantic-release:plugins options for @semantic-release/github/fail: {} +0ms
[5:12:57 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
  semantic-release:get-git-auth-url Verifying ssh auth by attempting to push to  https://github.com/SertoID/Test-Release-flow.git +0ms
  semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://github.com/SertoID/Test-Release-flow.git HEAD:production
  semantic-release:git remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
  semantic-release:git remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
  semantic-release:git fatal: Authentication failed for 'https://github.com/SertoID/Test-Release-flow.git/'
  semantic-release:git     at makeError (/home/circleci/project/node_modules/execa/lib/error.js:60:11)
  semantic-release:git     at handlePromise (/home/circleci/project/node_modules/execa/index.js:118:26)
  semantic-release:git     at processTicksAndRejections (node:internal/process/task_queues:93:5)
  semantic-release:git     at async verifyAuth (/home/circleci/project/node_modules/semantic-release/lib/git.js:207:5)
  semantic-release:git     at async module.exports (/home/circleci/project/node_modules/semantic-release/lib/get-git-auth-url.js:91:5)
  semantic-release:git     at async run (/home/circleci/project/node_modules/semantic-release/index.js:56:27)
  semantic-release:git     at async module.exports (/home/circleci/project/node_modules/semantic-release/index.js:260:22)
  semantic-release:git     at async module.exports (/home/circleci/project/node_modules/semantic-release/cli.js:55:5) +0ms
  semantic-release:get-git-auth-url SSH key auth failed, falling back to https. +984ms
  semantic-release:get-tags found tags for branch production: [ { gitTag: 'v1.0.0', version: '1.0.0', channels: [ null ] }, { gitTag: 'v1.0.0-main.1', version: '1.0.0-main.1', channels: [ 'main' ] }, { gitTag: 'v1.0.0-main.2', version: '1.0.0-main.2', channels: [ 'main' ] }, { gitTag: 'v1.0.0-main.3', version: '1.0.0-main.3', channels: [ 'main' ] }, { gitTag: 'v1.0.0-main.4', version: '1.0.0-main.4', channels: [ 'main' ] }, { gitTag: 'v1.0.1', version: '1.0.1', channels: [ null ] }, { gitTag: 'v1.1.0', version: '1.1.0', channels: [ 'production' ] }, { gitTag: 'v1.1.0-main.1', version: '1.1.0-main.1', channels: [ 'main' ] }, { gitTag: 'v1.1.0-main.2', version: '1.1.0-main.2', channels: [ 'main' ] }, { gitTag: 'v1.1.0-main.3', version: '1.1.0-main.3', channels: [ 'main' ] }, { gitTag: 'v1.10.0', version: '1.10.0', channels: [ null ] }, { gitTag: 'v1.11.0', version: '1.11.0', channels: [ null ] }, { gitTag: 'v1.12.0', version: '1.12.0', channels: [ null ] }, { gitTag: 'v1.13.0', version: '1.13.0', channels: [ null ] }, { gitTag: 'v1.14.0', version: '1.14.0', channels: [ null ] }, { gitTag: 'v1.15.0', version: '1.15.0', channels: [ null ] }, { gitTag: 'v1.16.0', version: '1.16.0', channels: [ null ] }, { gitTag: 'v1.16.1', version: '1.16.1', channels: [ null ] }, { gitTag: 'v1.16.2', version: '1.16.2', channels: [ null ] }, { gitTag: 'v1.16.3', version: '1.16.3', channels: [ null ] }, { gitTag: 'v1.16.4', version: '1.16.4', channels: [ null ] }, { gitTag: 'v1.16.5', version: '1.16.5', channels: [ null ] }, { gitTag: 'v1.2.0', version: '1.2.0', channels: [ 'production' ] }, { gitTag: 'v1.3.0', version: '1.3.0', channels: [ 'production' ] }, { gitTag: 'v1.4.0', version: '1.4.0', channels: [ null ] }, { gitTag: 'v1.5.0', version: '1.5.0', channels: [ null ] }, { gitTag: 'v1.5.1', version: '1.5.1', channels: [ null ] }, { gitTag: 'v1.6.0', version: '1.6.0', channels: [ null ] }, { gitTag: 'v1.6.1', version: '1.6.1', channels: [ null ] }, { gitTag: 'v1.7.0', version: '1.7.0', channels: [ null ] }, { gitTag: 'v1.7.1', version: '1.7.1', channels: [ null ] }, { gitTag: 'v1.8.0', version: '1.8.0', channels: [ null ] }, { gitTag: 'v1.9.0', version: '1.9.0', channels: [ null ] }, { gitTag: 'v2.0.0', version: '2.0.0', channels: [ null ] }, { gitTag: 'v2.0.1', version: '2.0.1', channels: [ null ] }, { gitTag: 'v2.0.2', version: '2.0.2', channels: [ null ] }, { gitTag: 'v2.0.3', version: '2.0.3', channels: [ null ] } ] +0ms
[5:12:59 PM] [semantic-release] › ✔  Run automated release from branch production on repository https://[secure]@github.com/SertoID/Test-Release-flow.git
[5:12:59 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[5:12:59 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[5:12:59 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[5:12:59 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[5:12:59 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[5:12:59 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[5:12:59 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[5:12:59 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[5:12:59 PM] [semantic-release] › ℹ  Found git tag v2.0.3 associated with version 2.0.3 on branch production
  semantic-release:get-commits Use from: acad5ba6bfaa3d34c3da1e079140ce89db822c2c +0ms
[5:12:59 PM] [semantic-release] › ℹ  Found 2 commits since last release
  semantic-release:get-commits Parsed commits: [ { commit: { long: 'c5b66e76e3794a7732f0fb6629f066f4c43c2a48', short: 'c5b66e7' }, tree: { long: '2dd66eea9e857cb838f9c07ea6df4a858ca5a558', short: '2dd66ee' }, author: { name: 'Eseoghene Mentie', email: 'ese.mentie@gmail.com', date: 2021-10-27T17:11:59.000Z }, committer: { name: 'GitHub', email: 'noreply@github.com', date: 2021-10-27T17:11:59.000Z }, subject: 'Merge pull request #43 from SertoID/Beautifynotes', body: 'fix: Add git plugin', hash: 'c5b66e76e3794a7732f0fb6629f066f4c43c2a48', committerDate: 2021-10-27T17:11:59.000Z, message: 'Merge pull request #43 from SertoID/Beautifynotes\n\nfix: Add git plugin', gitTags: '(HEAD -> production, origin/production, origin/HEAD)' }, { commit: { long: '70f256e29032544c7d89a4bd7d1c58ebdea4fd0e', short: '70f256e' }, tree: { long: '407577bac9877fe7f44bdff56e58c54bfce0a41d', short: '407577b' }, author: { name: 'Eseoghene Mentie', email: 'ese.mentie@gmail.com', date: 2021-10-27T17:06:46.000Z }, committer: { name: 'Eseoghene Mentie', email: 'ese.mentie@gmail.com', date: 2021-10-27T17:06:46.000Z }, subject: 'fix: Add git plugin', body: '', hash: '70f256e29032544c7d89a4bd7d1c58ebdea4fd0e', committerDate: 2021-10-27T17:06:46.000Z, message: 'fix: Add git plugin', gitTags: '(origin/Beautifynotes)' } ] +13ms
[5:12:59 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[5:12:59 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: Merge pull request #43 from SertoID/Beautifynotes

fix: Add git plugin
  semantic-release:commit-analyzer Analyzing with default rules +0ms
[5:12:59 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[5:12:59 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix: Add git plugin
  semantic-release:commit-analyzer Analyzing with default rules +1ms
  semantic-release:commit-analyzer The rule { type: 'fix', release: 'patch' } match commit with release type 'patch' +0ms
[5:12:59 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[5:12:59 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
[5:12:59 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[5:12:59 PM] [semantic-release] › ℹ  The next release version is 2.0.4
[5:12:59 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
  semantic-release:release-notes-generator version: '2.0.4' +0ms
  semantic-release:release-notes-generator host: undefined +0ms
  semantic-release:release-notes-generator owner: 'SertoID' +0ms
  semantic-release:release-notes-generator repository: 'Test-Release-flow' +0ms
  semantic-release:release-notes-generator previousTag: 'v2.0.3' +0ms
  semantic-release:release-notes-generator currentTag: 'v2.0.4' +0ms
  semantic-release:release-notes-generator host: 'https://github.com' +0ms
  semantic-release:release-notes-generator linkReferences: undefined +0ms
  semantic-release:release-notes-generator issue: 'issues' +0ms
  semantic-release:release-notes-generator commit: 'commit' +0ms
[5:12:59 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:12:59 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[5:12:59 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Create /home/circleci/project/CHANGELOG.md
[5:12:59 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[5:12:59 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[5:13:00 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 1 file(s) to commit
  semantic-release:git add file to git index {
  command: 'git add --force --ignore-errors CHANGELOG.md',
  escapedCommand: 'git add --force --ignore-errors CHANGELOG.md',
  exitCode: 0,
  stdout: '',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
} +0ms
  semantic-release:git commited files: [ 'CHANGELOG.md' ] +0ms
[5:13:00 PM] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: v2.0.4
[5:13:00 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
[5:13:00 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
  semantic-release:release-notes-generator version: '2.0.4' +1s
  semantic-release:release-notes-generator host: undefined +1ms
  semantic-release:release-notes-generator owner: 'SertoID' +0ms
  semantic-release:release-notes-generator repository: 'Test-Release-flow' +0ms
  semantic-release:release-notes-generator previousTag: 'v2.0.3' +0ms
  semantic-release:release-notes-generator currentTag: 'v2.0.4' +0ms
  semantic-release:release-notes-generator host: 'https://github.com' +0ms
  semantic-release:release-notes-generator linkReferences: undefined +0ms
  semantic-release:release-notes-generator issue: 'issues' +0ms
  semantic-release:release-notes-generator commit: 'commit' +0ms
[5:13:00 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[5:13:03 PM] [semantic-release] › ✔  Created tag v2.0.4
[5:13:03 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
  semantic-release:github release object: {
  semantic-release:github   owner: 'SertoID',
  semantic-release:github   repo: 'Test-Release-flow',
  semantic-release:github   tag_name: 'v2.0.4',
  semantic-release:github   target_commitish: 'production',
  semantic-release:github   name: 'v2.0.4',
  semantic-release:github   body: '## [2.0.4](https://github.com/SertoID/Test-Release-flow/compare/v2.0.3...v2.0.4) (2021-10-27)\n' +
  semantic-release:github     '\n' +
  semantic-release:github     '\n' +
  semantic-release:github     '### Bug Fixes\n' +
  semantic-release:github     '\n' +
  semantic-release:github     '* Add git plugin ([70f256e](https://github.com/SertoID/Test-Release-flow/commit/70f256e29032544c7d89a4bd7d1c58ebdea4fd0e))\n' +
  semantic-release:github     '\n' +
  semantic-release:github     '\n' +
  semantic-release:github     '\n',
  semantic-release:github   prerelease: false
  semantic-release:github } +0ms
[5:13:03 PM] [semantic-release] [@semantic-release/github] › ℹ  Published GitHub release: https://github.com/SertoID/Test-Release-flow/releases/tag/v2.0.4
[5:13:03 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[5:13:03 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
  semantic-release:github found pull requests: [ 43 ] +0ms
  semantic-release:github found issues via comments: [] +4ms
  semantic-release:github create comment: {
  semantic-release:github   owner: 'SertoID',
  semantic-release:github   repo: 'Test-Release-flow',
  semantic-release:github   issue_number: 43,
  semantic-release:github   body: ':tada: This PR is included in version 2.0.4 :tada:\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'The release is available on [GitHub release](https://github.com/SertoID/Test-Release-flow/releases/tag/v2.0.4)\n' +
  semantic-release:github     '\n' +
  semantic-release:github     'Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:'
  semantic-release:github } +0ms
[5:13:06 PM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #43: https://github.com/SertoID/Test-Release-flow/pull/43#issuecomment-953136660
[5:13:09 PM] [semantic-release] [@semantic-release/github] › ℹ  Added labels [ 'released' ] to issue #43
  semantic-release:github found semantic-release issues: [] +5s
[5:13:09 PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/github"
[5:13:09 PM] [semantic-release] › ✔  Published release 2.0.4 on default channel
Done in 13.38s.
CircleCI received exit`

**Comment by Eseoghene** [comment]
Figured out what was wrong the path in the config was in lowercase and the changelog.md should be "Uppercase" since YAML is case sensitive.
![image](https://user-images.githubusercontent.com/8102030/139704771-510ff66e-da27-495e-9eda-1f202d4f1c90.png)

Changed `changelog.md` to `CHANGELOG.md` and its working as expected now.
closing this
