### ISSUE TITLE
@semantic-release/npm silently failing in Github actions therefore not publishing package

### ISSUE THREAD

**Issue by tommaton** [semantic-release/semantic-release#2323]
## Current behavior

When running through the Github actions every action passes and the tags and release are made but the package.json version isn't updated and the package isn't published.

I've got the same setup in another project and everything is working as expected

## Expected behavior

I'm expecting to have all the tags and releases working (which they are) and the version number in the package.json updated to latest tag and to be published

## Environment

- **semantic-release** version: 18.0.0
- CI environment: Github actions
- Plugins used: 
-- "@semantic-release/commit-analyzer",
-- "@semantic-release/release-notes-generator",
-- "@semantic-release/changelog",
-- "@semantic-release/npm",
-- "@semantic-release/github"
- **semantic-release** configuration: 
```
{
  "branches": [
    "+([0-9])?(.{+([0-9]),x}).x",
    "main",
    "next",
    "next-major",
    {
      "name": "beta",
      "prerelease": true
    },
    {
      "name": "alpha",
      "prerelease": true
    }
  ],
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    "@semantic-release/npm",
    "@semantic-release/github"
  ]
}
```
- CI logs: 
```
[5:36:10 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[5:36:10 PM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 1.1.0-alpha.4 to package.json in /home/runner/work/my-package/my-package
(node:2296) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/work/my-package/my-package/node_modules/npm/node_modules/chalk/source/index.js
require() of ES modules is not supported.
require() of /home/runner/work/my-package/my-package/node_modules/npm/node_modules/chalk/source/index.js from /home/runner/work/my-package/my-package/node_modules/npm/lib/utils/explain-dep.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/work/my-package/my-package/node_modules/npm/node_modules/chalk/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/runner/work/my-package/my-package/node_modules/npm/lib/utils/explain-dep.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2296) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2296) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[5:36:10 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[5:36:12 PM] [semantic-release] › ✔  Created tag v1.1.0-alpha.4
[5:36:12 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/npm"
[5:36:12 PM] [semantic-release] [@semantic-release/npm] › ℹ  Publishing version 1.1.0-alpha.4 to npm registry on dist-tag alpha
(node:2322) UnhandledPromiseRejectionWarning: Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/runner/work/my-package/my-package/node_modules/npm/node_modules/chalk/source/index.js
require() of ES modules is not supported.
require() of /home/runner/work/my-package/my-package/node_modules/npm/node_modules/chalk/source/index.js from /home/runner/work/my-package/my-package/node_modules/npm/lib/utils/explain-dep.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/work/my-package/my-package/node_modules/npm/node_modules/chalk/package.json.

    at new NodeError (internal/errors.js:322:7)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1102:13)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/runner/work/my-package/my-package/node_modules/npm/lib/utils/explain-dep.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2322) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2322) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[5:36:12 PM] [semantic-release] [@semantic-release/npm] › ℹ  Published @MyOrg/my-package@1.1.0-alpha.4 to dist-tag @alpha on https://npm.pkg.github.com
[5:36:12 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/npm"
[5:36:12 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
[5:36:12 PM] [semantic-release] [@semantic-release/github] › ℹ  Published GitHub release: https://github.com/MyOrg/my-package/releases/tag/v1.1.0-alpha.4
[5:36:12 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[5:36:12 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
[5:36:16 PM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #5: https://github.com/MyOrg/my-package/pull/5#issuecomment-1010200825
[5:36:18 PM] [semantic-release] [@semantic-release/github] › ℹ  Added labels [ 'released on @alpha' ] to issue #5
[5:36:19 PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/githu
[5:36:19 PM] [semantic-release] › ✔  Published release 1.1.0-alpha.4 on alpha channel
```
This is a screen shot of the releases but no the packages been published
![Screenshot 2022-01-12 at 11 10 33](https://user-images.githubusercontent.com/3616123/149129719-6c4a2b57-eb46-4a26-ab08-424eb04e7794.png)
b"

**Comment by gr2m** [comment]
Looks like we don't handle the `UnhandledPromiseRejectionWarning` event. I think in the newer Node versions errors are thrown by default. What node version are you using in your CI?

**Comment by tommaton** [comment]
> Looks like we don't handle the `UnhandledPromiseRejectionWarning` event. I think in the newer Node versions errors are thrown by default. What node version are you using in your CI?

We're using v14 of node

**Comment by gr2m** [comment]
what version of `chalk` do you have in your dependency try? If you have a lock file, can you tell me what version of chalk you had when the error occurred? If not, can you run `npm ls chalk` before `semantic-release`?

I haven't seen that problem myself yet, and I run semantic-release in a lot of projects on Node 14, maybe it was a temporary glitch with chalk that was meanwhile resolved?

**Comment by tommaton** [comment]
@gr2m this is the result from the `npm i chalk`

```
@zegocover/zego-icons@1.0.0 /Users/thomas.maton/Projects/icons
├─┬ @babel/core@7.16.7
│ └─┬ @babel/code-frame@7.16.7
│   └─┬ @babel/highlight@7.16.7
│     └── chalk@2.4.2
├─┬ commitizen@4.2.4
│ ├─┬ cz-conventional-changelog@3.2.0
│ │ └── chalk@2.4.2
│ └─┬ inquirer@6.5.2
│   └── chalk@2.4.2
├─┬ cz-conventional-changelog@3.3.0
│ ├─┬ @commitlint/load@16.0.0
│ │ ├─┬ @commitlint/types@16.0.0
│ │ │ └── chalk@4.1.2 deduped
│ │ └── chalk@4.1.2 deduped
│ └── chalk@2.4.2
├─┬ eslint@7.32.0
│ └── chalk@4.1.2
└─┬ semantic-release@18.0.1
  ├─┬ @semantic-release/npm@8.0.3
  │ └─┬ npm@7.24.2
  │   ├── chalk@5.0.0 invalid: "^4.1.2" from node_modules/npm
  │   ├─┬ libnpmexec@3.0.2 invalid: "^2.0.1" from node_modules/npm
  │   │ └── chalk@4.1.2 deduped
  │   └─┬ npm-audit-report@2.1.5
  │     └── chalk@4.1.2 deduped
  ├─┬ marked-terminal@4.2.0
  │ └── chalk@4.1.2 deduped
  └─┬ signale@1.4.0
    └── chalk@2.4.2
```
> I haven't seen that problem myself yet, and I run semantic-release in a lot of projects on Node 14, maybe it was a temporary glitch with chalk that was meanwhile resolved?

Same here which is why I'm finding the issue weird which is still happening.

**Comment by gr2m** [comment]
Hmmm I still can't tell what the problem might be ... could you setup a minimal repository to replicate the issue? Does it only happen in this single repository for you?

**Comment by mario-jerkovic** [comment]
@gr2m got the same error after updating @semantic-release/npm to v9 and semantic-release to v19.0.2
NodeJS version is v16.13.2

```
+ yarn release
[12:30:48 PM] [semantic-release] › ℹ  Running semantic-release version 19.0.2
[12:30:48 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[12:30:48 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[12:30:48 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[12:30:48 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:30:48 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:30:48 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[12:30:48 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[12:30:48 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[12:30:48 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[12:30:48 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[12:31:00 PM] [semantic-release] › ✔  Run automated release from branch master on repository git@bitbucket.org:rimacautomobili/oem-dashboard-ui-kit.git
[12:31:01 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[12:31:01 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[12:31:01 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[12:31:01 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[12:31:01 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[12:31:01 PM] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /tmp/1f104be6c96f97b243225876c66e5e30/.npmrc
/opt/atlassian/pipelines/agent/build/node_modules/npm/lib/utils/explain-dep.js:1
const chalk = require('chalk')
              ^
Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/atlassian/pipelines/agent/build/node_modules/npm/node_modules/chalk/source/index.js from /opt/atlassian/pipelines/agent/build/node_modules/npm/lib/utils/explain-dep.js not supported.
Instead change the require of index.js in /opt/atlassian/pipelines/agent/build/node_modules/npm/lib/utils/explain-dep.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/npm/lib/utils/explain-dep.js:1:15)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/npm/lib/utils/explain-eresolve.js:5:49)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/npm/lib/utils/error-message.js:5:20)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/npm/lib/utils/exit-handler.js:4:22)
    at module.exports (/opt/atlassian/pipelines/agent/build/node_modules/npm/lib/cli.js:18:23)
    at Object.<anonymous> (/opt/atlassian/pipelines/agent/build/node_modules/npm/bin/npm-cli.js:2:25) {
  code: 'ERR_REQUIRE_ESM'
}
```

**Comment by mario-jerkovic** [comment]
@gr2m 
Here is the repro repository: https://github.com/mario-jerkovic/semantic-release-repro
You just have to run `yarn release` script which will call **semantic-release** with **dry run** options and you will be able to reproduce **ERR_REQUIRE_ESM**

**Comment by gr2m** [comment]
I was not able to reproduce the problem with Node 16.3.2 and yarn 3.1.1

```
➜  semantic-release-repro git:(master) ✗ NPM_TOKEN=npm_[TOKEN] yarn release                  
[8:43:48 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.2
[8:43:48 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[8:43:48 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[8:43:48 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[8:43:48 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[8:43:48 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[8:43:48 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[8:43:48 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[8:43:48 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[8:43:49 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[8:43:49 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[8:44:00 AM] [semantic-release] › ⚠  Run automated release from branch master on repository https://github.com/mario-jerkovic/semantic-release-repro.git in dry-run mode
[8:44:03 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[8:44:03 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[8:44:03 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[8:44:03 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[8:44:03 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[8:44:03 AM] [semantic-release] [@semantic-release/npm] › ℹ  Reading npm config from /Users/gregor/.npmrc
[8:44:03 AM] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /private/var/folders/54/y8s7nz313xb2363zjdz215940000gn/T/7d78a82feb87569a997ba3ea7ad1b298/.npmrc
gr2m
[8:44:03 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[8:44:03 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[8:44:03 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[8:44:03 AM] [semantic-release] › ℹ  No git tag version found on branch master
[8:44:03 AM] [semantic-release] › ℹ  No previous release found, retrieving all commits
[8:44:03 AM] [semantic-release] › ℹ  Found 4 commits since last release
[8:44:03 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[8:44:03 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore: typo
[8:44:03 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[8:44:03 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore: typo
[8:44:03 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[8:44:03 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore: typo
[8:44:03 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[8:44:03 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: init repro
[8:44:03 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[8:44:03 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 4 commits complete: minor release
[8:44:03 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[8:44:03 AM] [semantic-release] › ℹ  There is no previous release, the next release version is 1.0.0
[8:44:03 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[8:44:03 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[8:44:03 AM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/changelog" in dry-run mode
[8:44:03 AM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/npm" in dry-run mode
[8:44:04 AM] [semantic-release] › ⚠  Skip step "prepare" of plugin "@semantic-release/git" in dry-run mode
[8:44:04 AM] [semantic-release] › ⚠  Skip v1.0.0 tag creation in dry-run mode
[8:44:04 AM] [semantic-release] › ⚠  Skip step "publish" of plugin "@semantic-release/npm" in dry-run mode
[8:44:04 AM] [semantic-release] › ✔  Published release 1.0.0 on default channel
[8:44:04 AM] [semantic-release] › ℹ  Release note for version 1.0.0:
## 1.0.0 (2022-01-21)

### Features

    * init repro (1f37d59 (https://bitbucket.org/rimacautomobili/semantic-release-repro/commits/1f37d594ff90c873a8874979a713ff8d9cb37492))

### Other

    * typo (4a205fc (https://bitbucket.org/rimacautomobili/semantic-release-repro/commits/4a205fcd1759ea306fbf7055752fef00dffae511))
    * typo (24558ab (https://bitbucket.org/rimacautomobili/semantic-release-repro/commits/24558ab840e161b1b56579ba663f960839a9beb4))
    * typo (22541e3 (https://bitbucket.org/rimacautomobili/semantic-release-repro/commits/22541e3339097e975f3940c21232728b347099d9))
```

**Comment by hoonoh** [comment]
I had a same problem today and managed to get it working by patching `yarn.lock`. The problem comes from `chalk` v5 being pure ESM package and `npm` is trying to `require` it.

In my case, `yarn.lock` before:
```yaml
"chalk@npm:*, chalk@npm:5.0.0, chalk@npm:^5.0.0":
  version: 5.0.0

...

"npm@npm:^8.3.0":
  version: 8.3.2
  resolution: "npm@npm:8.3.2"
  dependencies:
	...
    chalk: "*"
	...
```
after patching:
```yaml

"chalk@npm:5.0.0, chalk@npm:^5.0.0":

...

"npm@npm:^8.3.0":
  version: 8.3.2
  resolution: "npm@npm:8.3.2"
  dependencies:
	...
    chalk: ^4.0.0
	...
```

**Comment by gr2m** [comment]
npm v8.3.2 defines `^4.1.2` as range for chalk:

https://unpkg.com/browse/npm@8.3.2/package.json#L69

Not sure where the `*` is coming from for you

**Comment by hoonoh** [comment]
I have no idea why but by looking at my commit logs this happened when I had yarn version updated via `yarn set version stable`.

**Comment by gaetanmaisse** [comment]
@gr2m you're right about npm v8.3.2 defining `^4.1.2` as the range for `chalk` in the `package.json`: https://unpkg.com/browse/npm@8.3.2/package.json#L69

But the registry is saying something else (`"chalk":"*"`) 🙃   You can check on https://registry.npmjs.org/npm/8.3.2

Not sure what's the reason behind that but it definitely is causing some troubles

**Comment by gr2m** [comment]
fascinating, let me reach out to the npm team

**Comment by darcyclarke** [comment]
Does `yarn@3` not respect bundled dependencies? 🤔 `npm` bundles all of our dependencies so references in `package.json` should not be then used to fetch remote versions of those deps. This seems like a bug with `yarn` if you happen to be using it to manage/install `npm` (something I would never recommend tbqh)

**Comment by 121593** [comment]
You can also work around by adding
```
"resolutions": {
    "npm/chalk": "^4.1.2"
},
```
to your package.json

**Comment by exKAZUu** [comment]
c.f. https://yarnpkg.com/getting-started/migration#dont-use-bundledependencies

**Comment by timhysniutd** [comment]
> "resolutions": {
>     "npm/chalk": "^4.1.2"
> },

Is there a solution like this for `npm`?

**Comment by rburgst** [comment]
> If using Yarn, a workaround is adding
> 
> ```
> "resolutions": {
>     "npm/chalk": "^4.1.2"
> },
> ```
> 
> to your package.json

note that this fails now if you update `npm` past 9.7.0. Then your releases fail in the semantic-release/npm prepare step without any output. Took me hours to figure this out.
