### ISSUE TITLE
Cannot publish release 1.0 from master

### ISSUE THREAD

**Issue by minimit** [semantic-release/semantic-release#2325]
## Current behavior

I've released successfully on the branch `beta` already, I merged into master to do the `1.0.0`. On master the last tag released was `v0.16.12`.

When running semantic release from github action I get a strange error (the same as #1513) see logs below. I've tried also to change the "main" repository branch to `master` and `beta`.

When I run locally with `"semantic-release": "^18.0.1",` i don't have errors but it **doesn't publish the release** also if the changelogs are full of all the commits from before beta.

## Expected behavior

Publish of `1.0.0`.

## Environment

- **semantic-release** version: cycjimmy/semantic-release-action@v2, and local 18.0.1
- CI environment: github actio, and local
- Plugins used: 
            @semantic-release/commit-analyzer
            @semantic-release/git
            @semantic-release/github
            @semantic-release/release-notes-generator
- **semantic-release** configuration: [link](https://github.com/xtendui/xtendui/blob/master/release.config.js)
- CI logs: 
```
Run cycjimmy/semantic-release-action@v2
  with:
    extra_plugins: @semantic-release/commit-analyzer
  @semantic-release/git
  @semantic-release/github
  @semantic-release/release-notes-generator
  
  env:
    NODE: 14.x
    GITHUB_TOKEN: ***
    NPM_TOKEN: ***
added 4 packages in 0.761s


[2:28:13 PM] [semantic-release] › ℹ  Running semantic-release version 18.0.1
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[2:28:14 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[2:28:28 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 128: git tag --merged beta
fatal: malformed object name beta
    at makeError (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/execa/lib/error.js:60:11)
Error: Error: Command failed with exit code 128: git tag --merged beta
fatal: malformed object name beta
    at handlePromise (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getTags (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/lib/git.js:31:11)
    at async /home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/lib/branches/get-tags.js:18:9
    at async module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/lib/branches/index.js:26:20)
    at async run (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js:57:22)
    at async module.exports (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/node_modules/semantic-release/index.js:260:22)
    at async release (/home/runner/work/_actions/cycjimmy/semantic-release-action/v2/src/index.js:28:18) {
  shortMessage: 'Command failed with exit code 128: git tag --merged beta',
  command: 'git tag --merged beta',
  escapedCommand: 'git tag --merged beta',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'fatal: malformed object name beta',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

**Comment by minimit** [comment]
I've managed to successfully publish from local adding the `--no-ci` flag. But I'll see if with CI github action will give the error on updates.

**Comment by travi** [comment]
the action that you are using is not supported by this team. please reduce your complexity to ensure that you are having a problem with semantic-release itself. if you still see errors when running directly, like `npx semantic-release`, it would help us understand if the problem is with semantic-release or the action wrapping it

**Comment by minimit** [comment]
Thanks @travi anyway after the local manual release of 1.0.0 the 1.0.1 went smoothly with the github action.
