### ISSUE TITLE
Cannot run in non-javascript project

### ISSUE THREAD

**Issue by jcornaz** [semantic-release/semantic-release#2341]
## Current behavior

Any call of `semantic-release-cli` in a non-javascript project crashes with:

```
node:internal/fs/utils:344
    throw err;
    ^

Error: ENOENT: no such file or directory, open './package.json'
    at Object.openSync (node:fs:585:3)
    at readFileSync (node:fs:453:35)
    at Object.<anonymous> (/home/jonathan/.nvm/versions/node/v16.13.1/lib/node_modules/semantic-release-cli/src/index.js:12:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at loader (/home/jonathan/.nvm/versions/node/v16.13.1/lib/node_modules/semantic-release-cli/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (/home/jonathan/.nvm/versions/node/v16.13.1/lib/node_modules/semantic-release-cli/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/jonathan/.nvm/versions/node/v16.13.1/lib/node_modules/semantic-release-cli/bin/semantic-release.js:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: './package.json'
}
```

## Expected behavior

No crash.

## Environment

- **semantic-release** version: a fresh *global installation*. (I cannot even get the version number, because `semantic-release-cli --version` crashes too)
- CI environment: running locally, on an archlinux
- Plugins used: commit-analyzer, release-notes-generator, github and exec
- **semantic-release** configuration: (in a `.releaserc.json`)
```json
{
  "plugins": [
    "@semantic-release/commit-analyzer",
    "@semantic-release/release-notes-generator",
    "@semantic-release/github",
    ["@semantic-release/exec", {
      "prepareCmd" : "echo set version ${nextRelease.version}",
      "publishCmd" : "echo publish"
    }]
  ]
}

```
- CI logs: The stack-trace I shared is all I have.

**Comment by gr2m** [comment]
`semantic-release-cli` is only to setup a new project. To run the actual `semantic-release` script for releases, run `npx semantic-release` instead.

**Comment by jcornaz** [comment]
Ah... thanks. That's a quite surprising behavior to me. Why create two CLI and name only one of them "-cli"?

Could this fact be documented? The [getting-started](https://semantic-release.gitbook.io/semantic-release/usage/getting-started) simply doesn't work on non-javascropt project, but doesn't mention it. And the [faq about non-javascript projects](https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-use-semantic-release-to-publish-non-javascript-packages) could probably also mention that the "CLI" to use is *not* semantic-release-cli.

**Comment by jcornaz** [comment]
After trying more with `semantic-release` I see it simply doesn't work with non-javascript project. 

```
[1:51:52 PM] [semantic-release] › ℹ  Running semantic-release version 19.0.2
[1:51:52 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Cannot find module '@semantic-release/exec'
Require stack:
- /home/jonathan/Desktop/bvh-arena/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolveFileName (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:46:47)
    at loadPlugin (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/utils.js:51:82)
    at /home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:17:37
    at Array.reduce (<anonymous>)
    at module.exports (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/get-config.js:84:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/jonathan/Desktop/bvh-arena/noop.js' ]
}
Error: Cannot find module '@semantic-release/exec'
Require stack:
- /home/jonathan/Desktop/bvh-arena/noop.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at resolveFileName (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:46:47)
    at loadPlugin (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/utils.js:51:82)
    at /home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:17:37
    at Array.reduce (<anonymous>)
    at module.exports (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:14:34)
    at module.exports (/home/jonathan/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/get-config.js:84:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/jonathan/Desktop/bvh-arena/noop.js' ]
}
```

@gr2m can you re-open this issue?

**Comment by gr2m** [comment]
`@semantic-release/exec` is a separate module that you need to have installed, it's not built into `semantic-release`.

Try

```
npm install --save-dev @semantic-release/exec
npx semantic-release
```

**Comment by jcornaz** [comment]
@gr2m, as I said it is **not** a javascript project. If you tell me the solution is to create a javascript project and add dev-depdencies to it, then you'd better update the [faq](https://semantic-release.gitbook.io/semantic-release/support/faq#can-i-use-semantic-release-to-publish-non-javascript-packages) and be honest about the fact that it only supports javascript projects.

**Comment by gr2m** [comment]
> @gr2m, as I said it is **not** a javascript project

It doesn't matter. You would run the commands above only in the release environment. You don't need to add `@semantic-release/exec` as dependency. You can also run

```
npm install --no-save @semantic-release/exec
npx semantic-release
```

that will probably be faster
