### ISSUE TITLE
JS API does not work correctly since v19.0.0

### ISSUE THREAD

**Issue by sebbo2002** [semantic-release/semantic-release#2342]
## Current behavior

I use semantic-release in a GitHub action that creates pull requests for me when I should do a release. This has worked wonderfully:

```js
const release = await semanticRelease({
    branches: [...this.branches, 'release-bot'],
    plugins: ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator'],
    dryRun: true
});
```

([Source](https://github.com/sebbo2002/release-bot/blob/develop/src/release-bot.js#L81-85))

 Since version 19.0.0, however, this place in semantic-release gives me trouble, because semantic-release simply breaks. An example for this:

```
2022-01-26T08:36:48.1875156Z [8:36:48 AM] [semantic-release] › ℹ  The next release version is 3.2.1
2022-01-26T08:36:48.1902920Z [8:36:48 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2022-01-26T08:36:48.2460850Z [8:36:48 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2022-01-26T08:36:48.2545769Z [8:36:48 AM] [semantic-release] › ⚠  Skip v3.2.1 tag creation in dry-run mode
2022-01-26T08:36:48.2551394Z [8:36:48 AM] [semantic-release] › ✔  Published release 3.2.1 on default channel
2022-01-26T08:36:48.2566146Z [8:36:48 AM] [semantic-release] › ℹ  Release note for version 3.2.1:
2022-01-26T08:36:48.2567623Z [8:36:48 AM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Not supported
2022-01-26T08:36:48.2568402Z     at terminalOutput (/home/runner/work/ical-generator/ical-generator/.actions/release-bot/node_modules/semantic-release/index.js:26:41)
2022-01-26T08:36:48.2569181Z     at run (/home/runner/work/ical-generator/ical-generator/.actions/release-bot/node_modules/semantic-release/index.js:218:34)
2022-01-26T08:36:48.2569821Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2022-01-26T08:36:48.2573362Z     at async module.exports (/home/runner/work/ical-generator/ical-generator/.actions/release-bot/node_modules/semantic-release/index.js:268:22)
2022-01-26T08:36:48.2594609Z ##[error]Not supported
2022-01-26T08:36:48.2605074Z     at async ReleaseBot.run (/home/runner/work/ical-generator/ical-generator/.actions/release-bot/src/release-bot.js:81:25)
2022-01-26T08:36:48.2729114Z Post job cleanup.
```

I suspect that it is due to the code introduced in commit d9e5bc06. However, I'm not familiar with the module used, so unfortunately I can't say much more about it at the moment. I tried it with node.js 14.18.3 and 16.13.2.

## Expected behavior

The JavaScript API of semantic-release works again as before.

## Environment

- **semantic-release** version: 19.0.2
- CI environment: GitHub Actions
- Plugins used: @semantic-release/commit-analyzer, @semantic-release/release-notes-generator
- **semantic-release** configuration: [here](https://github.com/sebbo2002/ical-generator/blob/develop/release.config.js)
- CI logs: [here](https://d.sebbo.net/release-bot-prqAgTsxZoQAT5bduV6m7onROOyMmJUR1jysY9AQlilgxcMYawMQRodWB6Ub2EXZZuv8sYTfYd7iD0Zy3RUVWLCzb0sl3ann4C3n.log)

**Comment by gr2m** [comment]
Could you start a pull request with a failing test that replicates the error?

**Comment by sebbo2002** [comment]
Okay, that was a stupid action. Much further debugging and building individual testates revealed that I had overlooked a version number in the action and the action was still running on node.js 12 (😫). Sorry for bugging you.
