### ISSUE TITLE
Using regex in "prerelease" causes SyntaxError: Unexpected token '}'

### ISSUE THREAD

**Issue by odtcviktorlivakivskyi** [semantic-release/semantic-release#2376]
## Current behavior

Following is configured for the preview/ branches in .releaserc:
`{
    "name": "preview/*",
    "prerelease": "${name.replace(/\//g, '-')}"
}`
So basically all slashes are converted to dashes.

Pipeline is triggered at preview/feature-a branch.
Following error appears in a pipeline:

```
SyntaxError: Unexpected token '}'
    at Function (<anonymous>)
    at /builds/com.trumpf.ux/com.trumpf.ux.ui-core/node_modules/lodash/lodash.js:14942:16
    at apply (/builds/com.trumpf.ux/com.trumpf.ux.ui-core/node_modules/lodash/lodash.js:4[87](https://gitlab.com/com.trumpf.ux/com.trumpf.ux.ui-core/-/jobs/2112742932#L87):27)
    at /builds/com.trumpf.ux/com.trumpf.ux.ui-core/node_modules/lodash/lodash.js:15326:16
    at apply (/builds/com.trumpf.ux/com.trumpf.ux.ui-core/node_modules/lodash/lodash.js:4[89](https://gitlab.com/com.trumpf.ux/com.trumpf.ux.ui-core/-/jobs/2112742932#L89):27)
    at /builds/com.trumpf.ux/com.trumpf.ux.ui-core/node_modules/lodash/lodash.js:6627:16
    at template (/builds/com.trumpf.ux/com.trumpf.ux.ui-core/node_modules/lodash/lodash.js:14[94](https://gitlab.com/com.trumpf.ux/com.trumpf.ux.ui-core/-/jobs/2112742932#L94)1:20)
    at /builds/com.trumpf.ux/com.trumpf.ux.ui-core/node_modules/semantic-release/lib/branches/expand.js:13:74
    at /builds/com.trumpf.ux/com.trumpf.ux.ui-core/node_modules/lodash/lodash.js:13469:38
    at /builds/com.trumpf.ux/com.trumpf.ux.ui-core/node_modules/lodash/lodash.js:4[96](https://gitlab.com/com.trumpf.ux/com.trumpf.ux.ui-core/-/jobs/2112742932#L96)7:15 {
  source: 'function(obj) {\n' +
    'obj || (obj = {});\n' +
    "var __t, __p = '';\n" +
    'with (obj) {\n' +
    '__p +=\n' +
    "((__t = (name.replace(///g, '-'))) == null ? '' : __t);\n" +
    '\n' +
    '}\n' +
    'return __p\n' +
    '}'
```

## Expected behavior

Pipeline runs without an error and a version with a suffix **preview-feature-a** is created.

## Environment

- **semantic-release** version: 19.0.2
- CI environment: Gitlab.com
- Plugins used: changelog, git
- **semantic-release** configuration: see above
- CI logs: see above

**Comment by odtcviktorlivakivskyi** [comment]
After playing a bit around I've found out, that the escaping backslash in a regexp needs to be escaped itself. Probably there is some double-conversion is happening in place.

Wrong:
`{ "name": "preview/*", "prerelease": "${name.replace(/\//g, '-')}" }`

Correct:
`{ "name": "preview/*", "prerelease": "${name.replace(/\\//g, '-')}" }`
