### ISSUE TITLE
cannot push to private github repo from CI github actions

### ISSUE THREAD

**Issue by george43g** [semantic-release/semantic-release#2464]
## Current behavior

When running `npx semantic-release` on CI, it gets a 403 error when trying to access the private repo using generated GH_TOKEN

```[4:03:37 PM] [semantic-release] › ✔  Run automated release from branch staging on repository https://[secure]@github.com/lothub/migdev.git
[4:03:38 PM] [semantic-release] › ✖  The command "git push --dry-run --no-verify https://[secure]@github.com/lothub/migdev.git HEAD:staging" failed with the error message remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/lothub/migdev.git/': The requested URL returned error: 403.
[4:03:38 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[4:03:38 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[4:03:39 PM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #51.
[4:03:40 PM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #51: https://github.com/lothub/migdev/issues/51#issuecomment-1152956289.
[4:03:40 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
[4:03:40 PM] [semantic-release] › ✖  EGITNOPERMISSION Cannot push to the Git repository.
semantic-release cannot push the version tag to the branch staging on the remote Git repository with URL https://[secure]@github.com/lothub/migdev.git.
This can be caused by:
    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)
SemanticReleaseError: Cannot push to the Git repository.
    at module.exports (/home/runner/work/migdev/migdev/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/runner/work/migdev/migdev/node_modules/semantic-release/index.js:98:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/runner/work/migdev/migdev/node_modules/semantic-release/index.js:268:[22](https://github.com/lothub/migdev/runs/6844234843?check_suite_focus=true#step:7:23))
    at async module.exports (/home/runner/work/migdev/migdev/node_modules/semantic-release/cli.js:55:5) {
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `staging` on the remote Git repository with URL `https://[secure]@github.com/lothub/migdev.git`.\n' +
'\n' +
'This can be caused by:\n' +
' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
' - the repository being unavailable\n' +
' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
}
```

## Expected behavior

When using the exact same token, `npx semantic-release` works when run from local machine (--dry-run). It should also work on CI given the exact same setup (the API key has the right privileges 

## Environment

- **semantic-release** version:     "@semantic-release/changelog": "^6.0.1",
- CI environment: github actions
- Plugins used: git, github, commit analyser, changelog, release notes generator
- CI logs: pasted above

- **semantic-release** configuration: 
```  "release": {
    "branches": [
      {
        "name": "production",
        "prerelease": false
      },
      {
        "name": "staging",
        "prerelease": true
      }
    ],
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      [
        "@semantic-release/changelog",
        {
          "changelogFile": "CHANGELOG.md"
        }
      ],
      [
        "@semantic-release/git",
        {
          "assets": [
            "CHANGELOG.md"
          ]
        }
      ],
      "@semantic-release/github"
    ]
  }
```

**Comment by george43g** [comment]
Also, when running locally with --no-ci flag, it hangs on this line:
```
Start step "success" of plugin "@semantic-release/github"
```
No error, it just never progresses past this.

**Comment by rzhosan** [comment]
Make sure that you gave the `write` level access to `permissions.contents` in your job configuration:
```
 permissions:
      contents: write
```

**Comment by danguilherme** [comment]
I was having the exact same issue as the OP and the solution above (adding the permission) worked.

If that's an expected behaviour, it should definitely be in the docs! Mainly in the [GitHub Actions](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/ci-configurations/github-actions.md) configuration recipe.

**Comment by hongfaqiu** [comment]
> Make sure that you gave the `write` level access to `permissions.contents` in your job configuration:
> 
> ```
>  permissions:
>       contents: write
> ```
Thank you, I solved my problem

**Comment by BustamanteMelkia** [comment]
> 

Tanks, it works.
