### ISSUE TITLE
"Cannot push the version tag to the branch

### ISSUE THREAD

**Issue by benthevining** [semantic-release/semantic-release#2481]
### Current behavior

Semantic-release had been working for a while, but suddenly started failing for me. The error message I get is:
```
SemanticReleaseError: Cannot push to the Git repository.
    at module.exports (/home/runner/work/Oranges/Oranges/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/runner/work/Oranges/Oranges/node_modules/semantic-release/index.js:98:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/runner/work/Oranges/Oranges/node_modules/semantic-release/index.js:269:22)
    at async module.exports (/home/runner/work/Oranges/Oranges/node_modules/semantic-release/cli.js:55:5) {
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `main` on the remote Git repository with URL `http://x-access-token:[secure]@github.com/benthevining/Oranges.git`.\n' +
'\n' +
'This can be caused by:\n' +
' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
' - the repository being unavailable\n' +
' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
}
```

The GitHub access token being used for this workflow has every single permission enabled, so I'm not sure what the problem is.

### Expected behavior

Semantic-release should be able to push to my repository.

### `semantic-release` version

19.0.3

### CI environment

GitHub actions

### `semantic-release` configuration

https://github.com/benthevining/Oranges/blob/411228effca09cd1cc826ed6f2fd5098375150a9/package.json#L22

### CI logs

https://github.com/benthevining/Oranges/runs/6989956263?check_suite_focus=true

**Comment by dimitriosdev** [comment]
I am facing the same issue

**Comment by kamrannabi** [comment]
Hi Ben,

Running into this same issue at the moment did you ever get around it?

**Comment by rienheuver** [comment]
I just ran into this as well. I'm configuring semantic-release but can't get it to work yet. I'm on semantic-release version 20.1.0

**Comment by rienheuver** [comment]
I've done some more testing but can't find the source of this. I have just tried to create a tag using my token in a simple request following: https://docs.github.com/en/rest/git/tags?apiVersion=2022-11-28 and that succeeded.

**Comment by rienheuver** [comment]
I now also tested running this locally with `npx semantic-release --no-ci` and the same `NPM_TOKEN` and `GH_TOKEN` as configured on my repo, and that succeeds as well :raised_eyebrow:

**Comment by rienheuver** [comment]
I figured the problem perhaps existed since the last major version (20), but I also ran into this with 19.0.5 like the OP

**Comment by rienheuver** [comment]
Finally found it! My workflow had a `permissions` block at the root of the `.yml` file like this:
```
permissions:
      contents: read
      pages: write
      id-token: write
```
Apparently this did an override on the `GH_TOKEN` I provided to semantic-release. I moved this permissions block to the specific job that needed it and now it works :smile:

**Comment by benthevining** [comment]
Oh nice! Do we know what permissions are required for semantic-release? Or should there be none specified in the workflow?

**Comment by rienheuver** [comment]
I think it needs at least `write` permission on `contents`, but haven't tried that

**Comment by benthevining** [comment]
I see. Thanks for your help so far, I'll try some things out!

**Comment by privatenumber** [comment]
I'm experiencing this as well on semantic-release v20.1.0 using default configuration.

#### CI logs

```
[5:08:00 AM] [semantic-release] › ℹ  Running semantic-release version 20.1.0
[5:08:00 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[5:08:00 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[5:08:00 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[5:08:00 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[5:08:00 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[5:08:00 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[5:08:00 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[5:08:00 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[5:08:00 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[5:08:00 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[5:08:00 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[5:08:02 AM] [semantic-release] › ✔  Run automated release from branch master on repository privatenumber/git-squash-branch
[5:08:02 AM] [semantic-release] › ✘  The command "git push --dry-run --no-verify https://[secure]@github.com/privatenumber/git-squash-branch.git HEAD:master" failed with the error message remote: Write access to repository not granted.
fatal: unable to access 'https://github.com/privatenumber/git-squash-branch.git/': The requested URL returned error: 403.
[5:08:02 AM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[5:08:02 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[5:08:05 AM] [semantic-release] [@semantic-release/github] › ℹ  Created issue #1: https://github.com/privatenumber/git-squash-branch/issues/1.
[5:08:05 AM] [semantic-release] › ✘  EGITNOPERMISSION Cannot push to the Git repository.
[5:08:05 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
semantic-release cannot push the version tag to the branch master on the remote Git repository with URL https://[secure]@github.com/privatenumber/git-squash-branch.git.

This can be caused by:

    * a misconfiguration of the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option
    * the repository being unavailable
    * or missing push permission for the user configured via the Git credentials on your CI environment (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)

SemanticReleaseError: Cannot push to the Git repository.
    at default (file:///home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/dlx-1777/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (file:///home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/dlx-1777/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/index.js:101:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.default (file:///home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/dlx-1777/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/index.js:275:22)
    at async default (file:///home/runner/setup-pnpm/node_modules/.bin/store/v3/tmp/dlx-1777/node_modules/.pnpm/semantic-release@20.1.0/node_modules/semantic-release/cli.js:55:5) {
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master` on the remote Git repository with URL `https://[secure]@github.com/privatenumber/git-squash-branch.git`.\n' +
    '\n' +
    'This can be caused by:\n' +
    ' - a misconfiguration of the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#repositoryurl) option\n' +
    ' - the repository being unavailable\n' +
    ' - or missing push permission for the user configured via the [Git credentials on your CI environment](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/ci-configuration.md#authentication)',
  semanticRelease: true
} ERROR  Command failed with exit code 1: semantic-release
```

#### Workflow

```yml
name: Release

on:
  push:
    branches: master

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'

    - name: Setup pnpm
      uses: pnpm/action-setup@v2.2.2
      with:
        version: 7
        run_install: true

    - name: Release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      run: pnpm dlx semantic-release
```


I have yet to try setting `permissions` in the workflow, because I'm providing my own via `GH_TOKEN` instead of `GITHUB_TOKEN`, so it shouldn't affect it.

I confirmed the token is fine because when semantic-release fails, it creates the issue with my user:
<img width="434" alt="Screenshot 2023-01-31 at 2 24 15 PM" src="https://user-images.githubusercontent.com/1075694/215673042-8548ba00-a19b-464a-a188-3b4f1765553f.png">

I wonder if i's possible there's a bug merged into semantic-release that uses `GITHUB_TOKEN` instead of `GH_TOKEN`.

**Comment by benthevining** [comment]
That would explain it!

**Comment by theurgi** [comment]
I ran into this issue using semantic-release v20.1.0 as well.

I did not explicitly generate a GITHUB_TOKEN for my repository, but rather, depend on [Automatic token authentication](https://docs.github.com/en/actions/security-guides/automatic-token-authentication):

> At the start of each workflow run, GitHub automatically creates a unique GITHUB_TOKEN secret to use in your workflow. You can use the GITHUB_TOKEN to authenticate in a workflow run.

The default permissions for an auto generated token are **read only**.

Therefore, what worked to resolve this in my case was to grant the token **Read and write permissions** in my repository settings as described here: [Configuring the default GITHUB_TOKEN permissions](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/enabling-features-for-your-repository/managing-github-actions-settings-for-a-repository#configuring-the-default-github_token-permissions).

With this, I did not need to add ...

```yml
  permissions:
    contents: write
```
... to my workflow.

Perhaps either approach results in the same internal process.

**Comment by codedbypaul** [comment]
Wondering if this is related to an issue i'm having. I'm trying to do a dry-run after using the cli to setup with a GH Personal Access Token, but i'm finding it's asking for my github username and password. I don't have a workflow set up for it as yet.

**Comment by timonmasberg** [comment]
For us, we cannot get the semantic-release command running, even though we provide the appropriate permissions,

  ```
  permissions:
      packages: write
      pull-requests: write
      contents: write
      issues: write
      id-token: write
```

we receive the following error

```
error: failed to push some refs to 'https://github.com/kordis-leitstelle/kordis'
    at makeError (file:///home/runner/work/kordis/kordis/node_modules/semantic-release/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///home/runner/work/kordis/kordis/node_modules/semantic-release/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async push (file:///home/runner/work/kordis/kordis/node_modules/semantic-release/lib/git.js:235:3)
    at async run (file:///home/runner/work/kordis/kordis/node_modules/semantic-release/index.js:210:5)
    at async Module.default (file:///home/runner/work/kordis/kordis/node_modules/semantic-release/index.js:278:22)
    at async default (file:///home/runner/work/kordis/kordis/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 1: git push --tags https://github.com/kordis-leitstelle/kordis',
  command: 'git push --tags https://github.com/kordis-leitstelle/kordis',
  escapedCommand: 'git push --tags "https://github.com/kordis-leitstelle/kordis"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'remote: error: GH006: Protected tag update failed for refs/tags/v1.0.0.        \n' +
    "remote: error: You're not authorized to create a tag        \n" +
    'To [https://github.com/kordis-leitstelle/kordis\n](https://github.com/kordis-leitstelle/kordis/n)' +
    ' ! [remote rejected] v1.0.0 -> v1.0.0 (protected tag hook declined)\n' +
    "error: failed to push some refs to 'https://github.com/kordis-leitstelle/kordis'",
  cwd: '/home/runner/work/kordis/kordis',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

```

**Comment by plumthedev** [comment]
@timonmasberg 
You should use `env` section to provide your GitHub token.

```
uses: cycjimmy/semantic-release-action@v4
env:
    GITHUB_TOKEN: ${{ github.token }}
```

**Comment by AllanOricil** [comment]
I created a PAT with all write permissions and got this error


````bash
✘  EGITNOPERMISSION Cannot push to the Git repository.
````

I also tried adding permissions to the auto generated token and got the same error


````yaml
permissions:
    packages: write
    pull-requests: write
    contents: write
    issues: write
    id-token: write
````

**Comment by Piwero** [comment]
@AllanOricil Check your Workflow permissions on settings/actions have the following permissions 

<img width="866" alt="Screenshot 2024-05-03 at 08 01 49" src="https://github.com/semantic-release/semantic-release/assets/72553098/68f102fa-1639-4ada-bb27-1b5739fec5ec">

**Comment by connormcwood** [comment]
@Piwero this was the issue, thank you

**Comment by 14790897** [comment]
thanks

**Comment by abed-daloopa** [comment]
>@AllanOricil Check your Workflow permissions on settings/actions have the following permissions

@Piwero Where is this setting exactly?
