### ISSUE TITLE
Incompatible with pnpm (occasionally)

### ISSUE THREAD

**Issue by NullVoxPopuli** [semantic-release/semantic-release#2530]
### Current behavior

```
[7:01:58 PM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 2.0.0 to package.json in /home/runner/work/ember-deep-tracked/ember-deep-tracked/ember-deep-tracked
ember-deep-tracked
v2.0.0
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-08-21T19_01_59_152Z-debug-0.log
[7:02:21 PM] [semantic-release] › ✖  Failed step "prepare" of plugin "@semantic-release/npm"
[7:02:21 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: npm version 2.0.0 --userconfig /tmp/5600fb90b2ba77a0de6001859b2fc798/.npmrc --no-git-tag-version --allow-same-version
npm ERR! Cannot read properties of null (reading 'matches')

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-08-21T19_01_59_152Z-debug-0.log
ember-deep-tracked
v2.0.0
    at makeError (/home/runner/work/ember-deep-tracked/ember-deep-tracked/node_modules/.pnpm/execa@5.1.1/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/home/runner/work/ember-deep-tracked/ember-deep-tracked/node_modules/.pnpm/execa@5.1.1/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/home/runner/work/ember-deep-tracked/ember-deep-tracked/node_modules/.pnpm/@semantic-release+npm@9.0.1_semantic-release@19.0.3/node_modules/@semantic-release/npm/lib/prepare.js:22:3)
    at async prepare (/home/runner/work/ember-deep-tracked/ember-deep-tracked/node_modules/.pnpm/@semantic-release+npm@9.0.1_semantic-release@19.0.3/node_modules/@semantic-release/npm/index.js:68:3)
    at async validator (/home/runner/work/ember-deep-tracked/ember-deep-tracked/node_modules/.pnpm/semantic-release@19.0.3/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/ember-deep-tracked/ember-deep-tracked/node_modules/.pnpm/semantic-release@19.0.3/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async Promise.all (index 0)
    at async next (/home/runner/work/ember-deep-tracked/ember-deep-tracked/node_modules/.pnpm/p-reduce@2.1.0/node_modules/p-reduce/index.js:16:18) {
  shortMessage: 'Command failed with exit code 1: npm version 2.0.0 --userconfig /tmp/5600fb90b2ba77a0de6001859b2fc798/.npmrc --no-git-tag-version --allow-same-version',
  command: 'npm version 2.0.0 --userconfig /tmp/5600fb90b2ba77a0de6001859b2fc798/.npmrc --no-git-tag-version --allow-same-version',
  escapedCommand: 'npm version 2.0.0 --userconfig "/tmp/5600fb90b2ba77a0de6001859b2fc798/.npmrc" --no-git-tag-version --allow-same-version',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: 'ember-deep-tracked\nv2.0.0',
  stderr: "npm ERR! Cannot read properties of null (reading 'matches')\n" +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /home/runner/.npm/_logs/2022-08-21T19_01_59_152Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/npm'
}
```

### Expected behavior

publish suceeds

### `semantic-release` version

19.0.3

### CI environment

Github Action

### Plugins used

    "@semantic-release/changelog": "^6.0.1",
    "@semantic-release/git": "^10.0.1",

### `semantic-release` configuration

```
  "release": {
    "branches": [
      "main",
      "master"
    ],
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      "@semantic-release/npm",
      "@semantic-release/github",
      "@semantic-release/git"
    ]
  },
```

### CI logs

Pasted above.

Link: https://github.com/NullVoxPopuli/ember-deep-tracked/runs/7941006950?check_suite_focus=true 

(until retention deletes it)

Additionally, I could only get release working with npm locally (I don't run npm on C.I.)
so grabbing the difference in versions, just in case it's useful:
```
❯ npm ls semantic-release
ember-deep-tracked@0.0.0 <repo>
└─┬ ember-deep-tracked@2.0.0 -> ./ember-deep-tracked
  ├─┬ @semantic-release/changelog@6.0.1
  │ └── semantic-release@19.0.3 deduped
  ├─┬ @semantic-release/git@10.0.1
  │ └── semantic-release@19.0.3 deduped
  └─┬ semantic-release@19.0.3
    ├─┬ @semantic-release/commit-analyzer@9.0.2
    │ └── semantic-release@19.0.3 deduped
    ├─┬ @semantic-release/github@8.0.5
    │ └── semantic-release@19.0.3 deduped
    ├─┬ @semantic-release/npm@9.0.1
    │ └── semantic-release@19.0.3 deduped
    └─┬ @semantic-release/release-notes-generator@10.0.3
      └── semantic-release@19.0.3 deduped


ember-deep-tracked/ember-deep-tracked on  main [$!?⇡] 
❯ npm ls @semantic-release/npm
ember-deep-tracked@0.0.0 <repo>
└─┬ ember-deep-tracked@2.0.0 -> ./ember-deep-tracked
  └─┬ semantic-release@19.0.3
    └── @semantic-release/npm@9.0.1}
```

and then with pnpm:

```
❯ pnpm why semantic-release
Legend: production dependency, optional only, dev only

ember-deep-tracked@2.0.0 <repo>/ember-deep-tracked

devDependencies:
@semantic-release/changelog 6.0.1
└─┬ semantic-release 19.0.3 peer
  ├─┬ @semantic-release/commit-analyzer 9.0.2
  │ └── semantic-release 19.0.3 peer
  ├─┬ @semantic-release/github 8.0.5
  │ └── semantic-release 19.0.3 peer
  ├─┬ @semantic-release/npm 9.0.1
  │ └── semantic-release 19.0.3 peer
  └─┬ @semantic-release/release-notes-generator 10.0.3
    └── semantic-release 19.0.3 peer
@semantic-release/git 10.0.1
└─┬ semantic-release 19.0.3 peer
  ├─┬ @semantic-release/commit-analyzer 9.0.2
  │ └── semantic-release 19.0.3 peer
  ├─┬ @semantic-release/github 8.0.5
  │ └── semantic-release 19.0.3 peer
  ├─┬ @semantic-release/npm 9.0.1
  │ └── semantic-release 19.0.3 peer
  └─┬ @semantic-release/release-notes-generator 10.0.3
    └── semantic-release 19.0.3 peer
semantic-release 19.0.3
├─┬ @semantic-release/commit-analyzer 9.0.2
│ └── semantic-release 19.0.3 peer
├─┬ @semantic-release/github 8.0.5
│ └── semantic-release 19.0.3 peer
├─┬ @semantic-release/npm 9.0.1
│ └── semantic-release 19.0.3 peer
└─┬ @semantic-release/release-notes-generator 10.0.3
  └── semantic-release 19.0.3 peer}


❯ pnpm why @semantic-release/npm
Legend: production dependency, optional only, dev only

ember-deep-tracked@2.0.0 <repo>/ember-deep-tracked

devDependencies:
@semantic-release/changelog 6.0.1
└─┬ semantic-release 19.0.3 peer
  └── @semantic-release/npm 9.0.1
@semantic-release/git 10.0.1
└─┬ semantic-release 19.0.3 peer
  └── @semantic-release/npm 9.0.1
semantic-release 19.0.3
└── @semantic-release/npm 9.0.1}




```

**Comment by zhbhun** [comment]
I encountered the same problem and found out that npm version is not working properly under pnpm.

https://github.com/semantic-release/npm/blob/master/lib/prepare.js#L12

`npm version` may add option --no-workspaces-update to prevent issue.

**Comment by travi** [comment]
Please refer to https://github.com/semantic-release/npm/issues/495#issuecomment-1230379945 for our stance on this matter
