### ISSUE TITLE
semantic release ignoring configured branch

### ISSUE THREAD

**Issue by JamesMHenderson** [semantic-release/semantic-release#2535]
### Current behavior

Semantic release is configured to publish a prerelease version on any branch. 

within the debug logs for semantic release you can see the following branches are configured

```
branches: [
    'master',
    { name: 'develop', prerelease: 'alpha' },
    {
      name: 'chore/semantic-release',
      prerelease: 'chore-semantic-release'
    }
  ],
```

When running the pipeline in gitlab ci for the branch named `chore/semantic-release` i see the following error

Running semantic release on prerelease branch does not run as it is configured to only publish from master

### Expected behavior

publish a prerelease version of the package for the branch `chore/semantic-release`

### `semantic-release` version

19.0.4

### CI environment

gitlab

### Plugins used

@semantic-release/commit-analyzer
@semantic-release/release-notes-generator
@semantic-release/changelog
@semantic-release/npm
@semantic-release/gitlab

### `semantic-release` configuration

```
const branch = process.env.CI_COMMIT_BRANCH ?? '';

const config = {
  branches: [
    'master',
    {
      name: 'develop',
      prerelease: 'alpha'
    },
    {
      name: branch,
      prerelease: `${process.env.CI_COMMIT_REF_SLUG}`,
    },
  ],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    '@semantic-release/npm',
    '@semantic-release/gitlab',
  ],
};

if (config.branches.some((it) => it === branch || (it.name === branch && !it.prerelease))) {
  config.plugins.push('@semantic-release/git');
}

module.exports = config;
```

### CI logs

```
[8:23:25 AM] [semantic-release] › ℹ  Running semantic-release version 19.0.4
(node:44) Warning: "version" is a reserved word.
Please do one of the following:
- Disable version with `yargs.version(false)` if using "version" as an option
- Use the built-in `yargs.version` method instead (if applicable)
- Use a different option key
https://yargs.js.org/docs/#api-reference-version
(Use `node --trace-warnings ...` to show where the warning was created)
2022-08-24T08:23:25.813Z semantic-release:config load config from: /builds/redwood/prettier/package.json
2022-08-24T08:23:25.826Z semantic-release:config options values: {
  branches: [
    'master',
    { name: 'develop', prerelease: 'alpha' },
    {
      name: 'chore/semantic-release',
      prerelease: 'chore-semantic-release'
    }
  ],
  repositoryUrl: 'https://gitlab.redwood.com/redwood/js-react-coding-stardards.git',
  tagFormat: 'v${version}',
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    '@semantic-release/changelog',
    '@semantic-release/npm',
    '@semantic-release/gitlab'
  ],
  _: [],
  debug: true,
  '$0': 'node_modules/.bin/semantic-release'
}
2022-08-24T08:23:26.156Z semantic-release:plugins options for @semantic-release/changelog/verifyConditions: {}
2022-08-24T08:23:26.157Z semantic-release:plugins options for @semantic-release/npm/verifyConditions: {}
2022-08-24T08:23:26.158Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: {}
2022-08-24T08:23:26.159Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2022-08-24T08:23:26.159Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
2022-08-24T08:23:26.160Z semantic-release:plugins options for @semantic-release/changelog/prepare: {}
2022-08-24T08:23:26.160Z semantic-release:plugins options for @semantic-release/npm/prepare: {}
2022-08-24T08:23:26.161Z semantic-release:plugins options for @semantic-release/npm/publish: {}
2022-08-24T08:23:26.161Z semantic-release:plugins options for @semantic-release/gitlab/publish: {}
2022-08-24T08:23:26.162Z semantic-release:plugins options for @semantic-release/npm/addChannel: {}
2022-08-24T08:23:26.162Z semantic-release:plugins options for @semantic-release/gitlab/success: {}
2022-08-24T08:23:26.163Z semantic-release:plugins options for @semantic-release/gitlab/fail: {}
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/gitlab"
[8:23:26 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/gitlab"
2022-08-24T08:23:26.213Z semantic-release:get-git-auth-url Verifying ssh auth by attempting to push to  https://gitlab.redwood.com/redwood/js-react-coding-stardards.git
2022-08-24T08:23:26.612Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://gitlab.redwood.com/redwood/js-react-coding-stardards.git HEAD:chore/semantic-release
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.redwood.com/redwood/js-react-coding-stardards.git/'
    at makeError (/builds/redwood/prettier/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/builds/redwood/prettier/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async verifyAuth (/builds/redwood/prettier/node_modules/semantic-release/lib/git.js:207:5)
    at async module.exports (/builds/redwood/prettier/node_modules/semantic-release/lib/get-git-auth-url.js:91:5)
    at async run (/builds/redwood/prettier/node_modules/semantic-release/index.js:64:27)
    at async module.exports (/builds/redwood/prettier/node_modules/semantic-release/index.js:269:22)
    at async module.exports (/builds/redwood/prettier/node_modules/semantic-release/cli.js:55:5)
2022-08-24T08:23:26.612Z semantic-release:get-git-auth-url SSH key auth failed, falling back to https.
2022-08-24T08:23:27.867Z semantic-release:get-tags found tags for branch master: [ { gitTag: 'v0.4.0', version: '0.4.0', channels: [ null ] }, { gitTag: 'v0.4.1', version: '0.4.1', channels: [ null ] }, { gitTag: 'v0.4.2', version: '0.4.2', channels: [ null ] }, { gitTag: 'v0.5.0', version: '0.5.0', channels: [ null ] }, { gitTag: 'v0.5.1', version: '0.5.1', channels: [ null ] }, { gitTag: 'v1.0.0', version: '1.0.0', channels: [ null ] }, { gitTag: 'v1.0.1', version: '1.0.1', channels: [ null ] }, { gitTag: 'v1.0.2', version: '1.0.2', channels: [ null ] } ]
[8:23:27 AM] [semantic-release] › ℹ  This test run was triggered on the branch chore/semantic-release, while semantic-release is configured to only publish from master, therefore a new version won’t be published.
```

**Comment by JamesMHenderson** [comment]
Turns out I the repository url was configured incorrectly in my package.json.
