### ISSUE TITLE
ERELEASEBRANCHES error after adding maintenance branches

### ISSUE THREAD

**Issue by ghicks-rmn** [semantic-release/semantic-release#2560]
### Current behavior

I have a new repo where I'm trying to use `main` as my primary release branch, and `v#.#.x` as maintenance branches. These are automatically created by a GitHub Actions step after the release:

```
         git fetch --tags origin
          git pull
          tags=$(git tag --points-at HEAD)
          echo "Found tags: $tags"
          while read line; do 
            if echo "${line}" | grep -Eq '^v([0-9]+)\.([0-9]+)\.([0-9]+)$'; then
              RELEASE_TAG="${line}"
              echo "Tag '${RELEASE_TAG}' matches the release pattern." 
            fi
          done <<< "$tags"
          MINOR_VERSION=$(echo $RELEASE_TAG | cut -d . -f 1,2)
          MAJOR_VERSION=$(echo $RELEASE_TAG | cut -d . -f 1)
          echo "Creating release branches from tag '${RELEASE_TAG}': '${MAJOR_VERSION}.x' and '${MINOR_VERSION}.x'."
          git checkout -B "${MAJOR_VERSION}.x"
          git push origin "${MAJOR_VERSION}.x"
          git checkout -B "${MINOR_VERSION}.x"
          git push origin "${MINOR_VERSION}.x"
```

After semantic-release creates 1.0.1, this creates branches `v1.0.x` and `v1.x` at the new release commit. 

On the next release, when `v1.0.x` and `v1.x` already exist, semantic-release fails:

```
[5:52:23 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [ { channel: undefined, tags: [ [Object], [Object] ], type: 'release', name: 'main', range: '>=1.1.0', accept: [ 'patch', 'minor', 'major' ], main: true }, { channel: 'v1.0.x', tags: [ [Object] ], type: 'release', name: 'v1.0.x', range: '>=1.1.0', accept: [ 'patch', 'minor', 'major' ], main: false }, { channel: 'v1.1.x', tags: [ [Object], [Object] ], type: 'release', name: 'v1.1.x', range: '>=1.1.0', accept: [ 'patch', 'minor', 'major' ], main: false }, { channel: 'v1.x', tags: [ [Object], [Object] ], type: 'release', name: 'v1.x', range: '>=1.1.0', accept: [ 'patch', 'minor', 'major' ], main: false } ].
```

If I don't include `'v+([0-9])?(.{+([0-9]),x}).x'` in my set of `branches` in .releaserc, the release works just fine; but I *want* these to be maintenance release branches, so I need semantic-release to be aware of them. What am I doing wrong?

### Expected behavior

A release created on `main`. 

### `semantic-release` version

"^18.0.0"

### CI environment

GitHub Actions

### Plugins used

    "@semantic-release/changelog": "^6.0.0",
    "@semantic-release/commit-analyzer": "^9.0.1",
    "@semantic-release/git": "^10.0.0",
    "@semantic-release/github": "^8.0.1",
    "@semantic-release/release-notes-generator": "^10.0.2",

### `semantic-release` configuration

```
---
branches:
- main
- name: beta
  prerelease: true
- name: alpha
  prerelease: true
- 'v+([0-9])?(.{+([0-9]),x}).x'
plugins:
- - "@semantic-release/commit-analyzer"
  - preset: conventionalcommits
    releaseRules:
    - type: docs
      release: patch
    - type: refactor
      release: patch
    - type: test
      release: patch
    - type: style
      release: patch
    parserOpts:
      noteKeywords:
      - BREAKING CHANGE
      - BREAKING CHANGES
      - BREAKING
- - "@semantic-release/release-notes-generator"
  - preset: conventionalcommits
    parserOpts:
      noteKeywords:
      - BREAKING CHANGE
      - BREAKING CHANGES
      - BREAKING
- - "@semantic-release/changelog"
  - changelogFile: CHANGELOG.md
- - "@semantic-release/git"
  - assets:
    - CHANGELOG.md
- - "@semantic-release/github"
  - assets:
    - CHANGELOG.md```

### CI logs

```
[5:52:19 PM] [semantic-release] › ℹ  Running semantic-release version 18.0.0
[5:52:20 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[5:52:20 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[5:52:20 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[5:52:20 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[5:52:20 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[5:52:20 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[5:52:20 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[5:52:20 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[5:52:20 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[5:52:20 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[5:52:20 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[5:52:23 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[5:52:23 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com/)
[5:52:23 PM] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
[5:52:23 PM] [semantic-release] › ✖  An error occurred while running semantic-release: TypeError: Cannot read properties of undefined (reading 'name')
    at module.exports (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/@semantic-release/github/lib/get-fail-comment.js:19:10)
    at module.exports (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/@semantic-release/github/lib/fail.js:28:74)
    at async fail (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/@semantic-release/github/index.js:64:3)
    at async validator (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as fail] (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async callFail (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/index.js:235:7)
    at async module.exports (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/index.js:264:7)
    at async module.exports (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/cli.js:55:5) {
  pluginName: '@semantic-release/github'
}
[5:52:23 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [ { channel: undefined, tags: [ [Object], [Object] ], type: 'release', name: 'main', range: '>=1.1.0', accept: [ 'patch', 'minor', 'major' ], main: true }, { channel: 'v1.0.x', tags: [ [Object] ], type: 'release', name: 'v1.0.x', range: '>=1.1.0', accept: [ 'patch', 'minor', 'major' ], main: false }, { channel: 'v1.1.x', tags: [ [Object], [Object] ], type: 'release', name: 'v1.1.x', range: '>=1.1.0', accept: [ 'patch', 'minor', 'major' ], main: false }, { channel: 'v1.x', tags: [ [Object], [Object] ], type: 'release', name: 'v1.x', range: '>=1.1.0', accept: [ 'patch', 'minor', 'major' ], main: false } ].

AggregateError: 
    SemanticReleaseError: The release branches are invalid in the `branches` configuration.
        at module.exports (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/lib/get-error.js:6:10)
        at /home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/lib/branches/index.js:44:19
        at Array.reduce (<anonymous>)
        at module.exports (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/lib/branches/index.js:34:46)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
        at async run (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/index.js:57:22)
        at async module.exports (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/index.js:260:22)
        at async module.exports (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/cli.js:55:5)
    at module.exports (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/lib/branches/index.js:66:11)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async run (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/index.js:57:22)
    at async module.exports (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/runner/work/tf-workflow-testing/tf-workflow-testing/node_modules/semantic-release/cli.js:55:5)
Error: Process completed with exit code 1.
```

**Comment by jcornaz** [comment]
I found [here](https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#release-branches]

>  The order of the release branch definitions is significant, as versions released on a given branch must always be higher than the last release made on the previous branch.

So you should change the order like this:

```yaml
branches:
- 'v+([0-9])?(.{+([0-9]),x}).x'
- main
- name: beta
  prerelease: true
- name: alpha
  prerelease: true
```

**Comment by ghicks-rmn** [comment]
@jcornaz I tried both configurations and get the same error. From what I can tell, `'v+([0-9])?(.{+([0-9]),x}).x'` should be interpreted as a series of *maintenance* branches, not *release* branches, so I'm not sure whether that requirement would apply here? Either way, the reported error is the same, though the parsed result is slightly different:

```[5:07:45 PM] [semantic-release] › ✖  ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [ { channel: undefined, tags: [ [Object] ], type: 'release', name: 'v1.0.x', range: '>=1.0.0 <1.1.0', accept: [ 'patch' ], main: true }, { channel: 'v1.1.x', tags: [ [Object], [Object] ], type: 'release', name: 'v1.1.x', range: '>=1.1.0', accept: [ 'patch', 'minor', 'major' ], main: false }, { channel: 'v1.x', tags: [ [Object], [Object] ], type: 'release', name: 'v1.x', range: '>=1.1.0', accept: [ 'patch', 'minor', 'major' ], main: false }, { channel: 'main', tags: [ [Object], [Object] ], type: 'release', name: 'main', range: '>=1.1.0', accept: [ 'patch', 'minor', 'major' ], main: false } ].```

**Comment by ghicks-rmn** [comment]
Quick update: for some reason, using `'+([0-9])?(.{+([0-9]),x}).x'`, and converting everything else to use #.#.# (branch names, github actions trigger, and release tag), looks like it works fine. That leads me to 2 questions:

1. semantic-release seems to prefer `v#.#.#` for release tags, but `#.#.#` for maintenance branches. (This is shown in the default configuation for both.) Why is this the case? Wouldn't it be better to default to the same method for both? This is particularly irritating for languages that can use git for distribution, like Terraform - maintenance branches allow end-users to pin either to a specific release (v2.0.0) or a family of releases (2.x), but the syntax is inconsistent.

2. semantic-release not only _prefers_ `#.#.#` for branches, but apparently doesn't _support_ a prefix for them at all, unless I'm doing something totally wrong here. Would that be a bug?

**Comment by albert-a** [comment]
I think it's better to have distinction in names between branches and tags, because in some cases git does not make differences between tags and branches, and it can lead to confusion. For example when you remotely delete a tag
`git push --delete origin tagname`
you can accidentally remove a branch with the same name, so to handle this you should explicitly specify that you are deleting a tag:
`git push origin :refs/tags/tagname`
which is more complex to my taste, I think it's better to keep tag and branch names different. 
See: https://stackoverflow.com/questions/5480258/how-can-i-delete-a-remote-tag

**Comment by hpe-ykoehler** [comment]
The issue is that the error msg is not helping find the problem and that the fact that semantic-release wants certain patterns doesn't make sense when using a config file, you can't ask people to configure something but then only allow some configuration only...
