### ISSUE TITLE
Prerelease regex error: 'ReferenceError: g is not defined'

### ISSUE THREAD

**Issue by jfairley** [semantic-release/semantic-release#2595]
### Current behavior

I set up a prerelease branch following steps described in the SR documentation.

https://semantic-release.gitbook.io/semantic-release/usage/workflow-configuration#prerelease

Specifically, I tried using a regex within my `prerelease` value similar to the documented `{name: 'pre/rc', prerelease: '${name.replace(/^pre\\//g, "")}'}`.

I am running SR from a branch called `feature/additional-reports`. Based on my configuration, I expect `feature/` to be stripped away, resulting in a tag like `N.N.N-additional-reports.N`.

I received an error in CI. See my configuration and CI logs below.

Because this feature relies on lodash, I expect this is relevant. My project uses lodash version  `4.17.21`.

```bash
yarn why lodash                                                                                                                                                                                                     8b497575  ✂ ✈
yarn why v1.22.17
[1/4] 🤔  Why do we have the module "lodash"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "lodash@4.17.21"
```

### Expected behavior

SR tags my prerelease according to the given pattern.

### `semantic-release` version

19.0.5

### CI environment

CircleCI

### Plugins used

Using the default plugins

### `semantic-release` configuration

```yaml
---
branches:
  - name: main
  - name: (\d+\.)+x
  - name: next
    channel: beta
    prerelease: true
  - name: 'feature/*'
    channel: alpha
    prerelease: '${name.replace(/^feature\\//g, "")}'
npmPublish: false
tagFormat: "${version}"
```

### CI logs

```
[4:07:25 PM] [semantic-release] › ✖  An error occurred while running semantic-release: ReferenceError: g is not defined
    at eval (lodash.templateSources[3]:9:36)
    at /home/********/project/node_modules/semantic-release/lib/branches/expand.js:13:89
    at /home/********/project/node_modules/lodash/lodash.js:13469:38
    at /home/********/project/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/********/project/node_modules/lodash/lodash.js:3032:24)
    at mapValues (/home/********/project/node_modules/lodash/lodash.js:13468:7)
    at /home/********/project/node_modules/semantic-release/lib/branches/expand.js:13:12
    at Array.map (<anonymous>)
    at /home/********/project/node_modules/semantic-release/lib/branches/expand.js:11:93
    at Array.reduce (<anonymous>)
ReferenceError: g is not defined
    at eval (lodash.templateSources[3]:9:36)
    at /home/********/project/node_modules/semantic-release/lib/branches/expand.js:13:89
    at /home/********/project/node_modules/lodash/lodash.js:13469:38
    at /home/********/project/node_modules/lodash/lodash.js:4967:15
    at baseForOwn (/home/********/project/node_modules/lodash/lodash.js:3032:24)
    at mapValues (/home/********/project/node_modules/lodash/lodash.js:13468:7)
    at /home/********/project/node_modules/semantic-release/lib/branches/expand.js:13:12
    at Array.map (<anonymous>)
    at /home/********/project/node_modules/semantic-release/lib/branches/expand.js:11:93
    at Array.reduce (<anonymous>)error Command failed with exit code 1.
```

I removed the `g` from the regex in my config and ran it again. The next error was: 

```
[4:56:08 PM] [semantic-release] › ✖  An error occurred while running semantic-release: SyntaxError: Unexpected token ','
    at Function (<anonymous>)
    at /home/********/project/node_modules/lodash/lodash.js:14942:16
    at apply (/home/********/project/node_modules/lodash/lodash.js:487:27)
    at /home/********/project/node_modules/lodash/lodash.js:15326:16
    at apply (/home/********/project/node_modules/lodash/lodash.js:489:27)
    at /home/********/project/node_modules/lodash/lodash.js:6627:16
    at template (/home/********/project/node_modules/lodash/lodash.js:14941:20)
    at /home/********/project/node_modules/semantic-release/lib/branches/expand.js:13:74
    at /home/********/project/node_modules/lodash/lodash.js:13469:38
    at /home/********/project/node_modules/lodash/lodash.js:4967:15 {
  source: 'function(obj) {\n' +
    'obj || (obj = {});\n' +
    "var __t, __p = '';\n" +
    'with (obj) {\n' +
    '__p +=\n' +
    `((__t = (name.replace(/^feature\\\\//, ""))) == null ? '' : __t);\n` +
    '\n' +
    '}\n' +
    'return __p\n' +
    '}'
}
SyntaxError: Unexpected token ','
    at Function (<anonymous>)
    at /home/********/project/node_modules/lodash/lodash.js:14942:16
    at apply (/home/********/project/node_modules/lodash/lodash.js:487:27)
    at /home/********/project/node_modules/lodash/lodash.js:15326:16
    at apply (/home/********/project/node_modules/lodash/lodash.js:489:27)
    at /home/********/project/node_modules/lodash/lodash.js:6627:16
    at template (/home/********/project/node_modules/lodash/lodash.js:14941:20)
    at /home/********/project/node_modules/semantic-release/lib/branches/expand.js:13:74
    at /home/********/project/node_modules/lodash/lodash.js:13469:38
    at /home/********/project/node_modules/lodash/lodash.js:4967:15 {
  source: 'function(obj) {\n' +
    'obj || (obj = {});\n' +
    "var __t, __p = '';\n" +
    'with (obj) {\n' +
    '__p +=\n' +
    `((__t = (name.replace(/^feature\\\\//, ""))) == null ? '' : __t);\n` +
    '\n' +
    '}\n' +
    'return __p\n' +
    '}'
```

**Comment by jfairley** [comment]
___UPDATE:___

I found success by completely removing the regex.

`'${name.replace("feature/", "")}'`

**Comment by romfil-trim** [comment]
I have also come across this exact issue. Would you please remove it from the documentation, at least?
