### ISSUE TITLE
npx semantic-release-cli setup fails when answering no to Are you using GitHub Enterprise?

### ISSUE THREAD

**Issue by magick93** [semantic-release/semantic-release#2600]
### Current behavior

1. When I run `npx semantic-release-cli setup` I'm asked `? Are you using GitHub Enterprise?`.
2. I type `n` then `ENTER`.

**Result**

```
ERR! semantic-release Error: GitHub repository URL is invalid: https:undefined.git
ERR! semantic-release     at module.exports (/home/anton/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/repository.js:69:11)
ERR! semantic-release     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR! semantic-release     at module.exports (/home/anton/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/index.js:86:5)
ERR! semantic-release  Error: GitHub repository URL is invalid: https:undefined.git
ERR! semantic-release     at module.exports (/home/anton/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/lib/repository.js:69:11)
ERR! semantic-release     at processTicksAndRejections (node:internal/process/task_queues:96:5)
ERR! semantic-release     at module.exports (/home/anton/.npm/_npx/4b6729947d3d91fc/node_modules/semantic-release-cli/src/index.js:86:5)
```

### Expected behavior

Expect it to not error, and probably asking my what my gitlab username and repo is, or something meaningful rather than `ERR`.

### `semantic-release` version

v5.4.4

### CI environment

local

### `semantic-release` configuration

none

### CI logs

none

**Comment by ChristianLMI** [comment]
I'm facing the same issue. Looking into the code, this has been introduced in https://github.com/semantic-release/cli/issues/100 however this belongs to [semantic-release-cli](https://github.com/semantic-release/cli) and as this apparently never had support for anything else than GitHub (even though the docs are rather silent) it's probably better tracked through: https://github.com/semantic-release/cli/issues/319 and https://github.com/semantic-release/cli/issues/172.
