### ISSUE TITLE
401 error when merging to my main branch

### ISSUE THREAD

**Issue by JordanMed** [semantic-release/semantic-release#2677]
When I merge my release candidate branch into my main brach i receive a 401 error. 
I have a release candidate "rc" branch that is at 1.06. I am trying to merge that branch into my main branch "release" which is still at 1.0. I'm pretty new to using gitlab CI and semantic release so any help is welcome. 

here is the code from my ci pipeline. The token has access full access to my repo. 

```
semantic_release:
        stage: semantic_release
        cache:
                key: ${CI_COMMIT_REF_SLUG}
                paths:
                        - .npm/
        rules:
                - if: $CI_COMMIT_BRANCH == "release" || $CI_COMMIT_BRANCH == "rc"
        variables:
                NPM_TOKEN: ${PACKAGE_TOKEN_KEY}
        script:
                - git tag --delete $(git tag) # delete all local tags
                - git fetch --all
                - npm install
                - npm config set strict-ssl false
                - npm run semantic-release
        artifacts:
                paths:
                        - public
```

.releaserc.json
```
{
	"branches": ["release", { "name": "rc", "channel": "rc" }],
	"plugins": [
		"@semantic-release/commit-analyzer",
		{
			"preset": "angular",
			"releaseRules": [
				{ "tag": "breaking", "release": "major" },
				{ "tag": "feat", "release": "minor" },
				{ "tag": "style", "release": "patch" },
				{ "tag": "refactor", "release": "patch" },
				{ "tag": "test", "release": "patch" },
				{ "tag": "chore", "release": "patch" },
				{ "tag": "fix", "release": "patch" },
				{ "tag": "docs", "release": "patch" }
			]
		},
		"@semantic-release/release-notes-generator",
		"@semantic-release/gitlab",
		"@semantic-release/npm",
		[
			"@semantic-release/git",
			{
				"assets": ["package.json"],
				"message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
			}
		]
	]
}

```
here is the error i'm getting. 

```
$ npm run semantic-release
> @XX/XX-mx@1.0.6 semantic-release
> semantic-release
[6:25:30 PM] [semantic-release] › ℹ  Running semantic-release version 19.0.5
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/gitlab"
[6:25:30 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/gitlab"
[6:25:36 PM] [semantic-release] › ✔  Run automated release from branch release on repository http://gitlab.apps.XXXX.ca/XX/XX-mx.git
[6:25:36 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[6:25:36 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/gitlab"
[6:25:36 PM] [semantic-release] [@semantic-release/gitlab] › ℹ  Verify GitLab authentication (http://gitlab.apps.XXXX.ca/api/v4)
[6:25:36 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/gitlab"
[6:25:36 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[6:25:36 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://gitlab.apps.XXXX.ca/api/v4/packages/npm/
[6:25:36 PM] [semantic-release] [@semantic-release/npm] › ℹ  Reading npm config from /root/.npmrc, /builds/XX/XX-mx/.npmrc
[6:25:36 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[6:25:36 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[6:25:36 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[6:25:36 PM] [semantic-release] › ℹ  Found 4 commits since last release
[6:25:36 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:25:36 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[6:25:37 PM] [semantic-release] › ✔  Add default channel to tag v1.0.6
[6:25:37 PM] [semantic-release] › ℹ  Start step "addChannel" of plugin "@semantic-release/npm"
[6:25:37 PM] [semantic-release] [@semantic-release/npm] › ℹ  Adding version 1.0.6 to npm registry on dist-tag latest
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://gitlab.apps.XXXX.ca/api/v4/packages/npm/-/package/@XX%2fXX-mx/dist-tags
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-17T18_25_38_061Z-debug-0.log
[6:25:38 PM] [semantic-release] › ✖  Failed step "addChannel" of plugin "@semantic-release/npm"
[6:25:38 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: Command failed with exit code 1: npm dist-tag add @XX/XX-mx@1.0.6 latest --userconfig /tmp/7e8eda1cc43d05fd4fea64ab46ee5829/.npmrc --registry https://gitlab.apps.XXXX.ca/api/v4/packages/npm/
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://gitlab.apps.XXXX.ca/api/v4/packages/npm/-/package/@XX%2fXX-mx/dist-tags
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-17T18_25_38_061Z-debug-0.log
    at makeError (/builds/XX/XX-mx/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/builds/XX/XX-mx/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/builds/XX/XX-mx/node_modules/@semantic-release/npm/lib/add-channel.js:32:5)
    at async validator (/builds/XX/XX-mx/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /builds/XX/XX-mx/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /builds/XX/XX-mx/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as addChannel] (/builds/XX/XX-mx/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/builds/XX/XX-mx/node_modules/semantic-release/index.js:140:24)
    at async module.exports (/builds/XX/XX-mx/node_modules/semantic-release/index.js:269:22) {
  shortMessage: 'Command failed with exit code 1: npm dist-tag add @XX/XX-mx@1.0.6 latest --userconfig /tmp/7e8eda1cc43d05fd4fea64ab46ee5829/.npmrc --registry https://gitlab.apps.XXXX.ca/api/v4/packages/npm/',
  command: 'npm dist-tag add @XX/XX-mx@1.0.6 latest --userconfig /tmp/7e8eda1cc43d05fd4fea64ab46ee5829/.npmrc --registry https://gitlab.apps.XXXX.ca/api/v4/packages/npm/',
  escapedCommand: 'npm dist-tag add "@XX/XX-mx@1.0.6" latest --userconfig "/tmp/7e8eda1cc43d05fd4fea64ab46ee5829/.npmrc" --registry "https://gitlab.apps.XXXX.ca/api/v4/packages/npm/"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm ERR! code E401\n' +
    'npm ERR! 401 Unauthorized - GET https://gitlab.apps.XXXX.ca/api/v4/packages/npm/-/package/@XX%2fXX-mx/dist-tags\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /root/.npm/_logs/2023-01-17T18_25_38_061Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/npm'
}
Error: Command failed with exit code 1: npm dist-tag add @XX/XX-mx@1.0.6 latest --userconfig /tmp/7e8eda1cc43d05fd4fea64ab46ee5829/.npmrc --registry https://gitlab.apps.XXXX.ca/api/v4/packages/npm/
npm ERR! code E401
npm ERR! 401 Unauthorized - GET https://gitlab.apps.XXXX.ca/api/v4/packages/npm/-/package/@XX%2fXX-mx/dist-tags
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-01-17T18_25_38_061Z-debug-0.log
    at makeError (/builds/XX/XX-mx/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/builds/XX/XX-mx/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async module.exports (/builds/XX/XX-mx/node_modules/@semantic-release/npm/lib/add-channel.js:32:5)
    at async validator (/builds/XX/XX-mx/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
    at async /builds/XX/XX-mx/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
    at async /builds/XX/XX-mx/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
    at async Object.pluginsConf.<computed> [as addChannel] (/builds/XX/XX-mx/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/builds/XX/XX-mx/node_modules/semantic-release/index.js:140:24)
    at async module.exports (/builds/XX/XX-mx/node_modules/semantic-release/index.js:269:22) {
  shortMessage: 'Command failed with exit code 1: npm dist-tag add @XX/XX-mx@1.0.6 latest --userconfig /tmp/7e8eda1cc43d05fd4fea64ab46ee5829/.npmrc --registry https://gitlab.apps.XXXX.ca/api/v4/packages/npm/',
  command: 'npm dist-tag add @XX/XX-mx@1.0.6 latest --userconfig /tmp/7e8eda1cc43d05fd4fea64ab46ee5829/.npmrc --registry https://gitlab.apps.XXXX.ca/api/v4/packages/npm/',
  escapedCommand: 'npm dist-tag add "@XX/XX-mx@1.0.6" latest --userconfig "/tmp/7e8eda1cc43d05fd4fea64ab46ee5829/.npmrc" --registry "https://gitlab.apps.XXXX.ca/api/v4/packages/npm/"',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'npm ERR! code E401\n' +
    'npm ERR! 401 Unauthorized - GET https://gitlab.apps.XXXX.ca/api/v4/packages/npm/-/package/@XX%2fXX-mx/dist-tags\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /root/.npm/_logs/[202](https://gitlab.apps.XXXX.ca/XX/XX-mx/-/jobs/839661#L202)3-01-17T18_25_38_061Z-debug-0.log',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false,
  pluginName: '@semantic-release/npm'
}

```

Edit i was looking back through my release pipeline and noticed this error when i created my 1.0 release. the 1.0 release was still created so i never noticed the error. 

```
npm notice Publishing to https://gitlab.apps.XXXX.ca/api/v4/projects/1951/packages/npm/
+ @XX/XX-mx@1.0.0
[7:46:40 PM] [semantic-release] [@semantic-release/npm] › ℹ  Published @XX/XX-mx@1.0.0 to dist-tag @latest on https://gitlab.apps.XXXX.ca/api/v4/packages/npm/
[7:46:40 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/npm"
[7:46:40 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/gitlab"
[7:46:44 PM] [semantic-release] [@semantic-release/gitlab] › ✖  An error occurred while posting comments to related issues and merge requests:
HTTPError: Response code 502 (Bad Gateway)
    at Request.<anonymous> (/builds/XX/XX-mx/node_modules/got/dist/source/as-promise/index.js:118:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1673984804899,
    socket: 1673984804900,
    lookup: 1673984804902,
    connect: 1673984804903,
    secureConnect: undefined,
    upload: 1673984804903,
    response: 1673984804907,
    end: 1673984804907,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 2,
      tcp: 1,
      tls: undefined,
      request: 0,
      firstByte: 4,
      download: 0,
      total: 8
    }
  }
}
[7:46:44 PM] [semantic-release] › ✖  Failed step "success" of plugin "@semantic-release/gitlab"
[7:46:44 PM] [semantic-release] › ✖  An error occurred while running semantic-release: HTTPError: Response code 502 (Bad Gateway)
    at Request.<anonymous> (/builds/XX/XX-mx/node_modules/got/dist/source/as-promise/index.js:118:42)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_NON_2XX_3XX_RESPONSE',
  timings: {
    start: 1673984804899,
    socket: 1673984804900,
    lookup: 1673984804902,
    connect: 1673984804903,
    secureConnect: undefined,
    upload: 1673984804903,
    response: 1673984804907,
    end: 1673984804907,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 1,
      dns: 2,
      tcp: 1,
      tls: undefined,
      request: 0,
      firstByte: 4,
      download: 0,
      total: 8
    }
  },
  pluginName: '@semantic-release/gitlab'
}
AggregateError: 
    HTTPError: Response code 502 (Bad Gateway)
        at Request.<anonymous> (/builds/XX/XX-mx/node_modules/got/dist/source/as-promise/index.js:118:42)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at /builds/XX/XX-mx/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.pluginsConf.<computed> [as success] (/builds/XX/XX-mx/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/builds/XX/XX-mx/node_modules/semantic-release/index.js:209:3)
    at async module.exports (/builds/XX/XX-mx/node_modules/semantic-release/index.js:269:22)
    at async module.exports (/builds/XX/XX-mx/node_modules/semantic-release/cli.js:55:5)

```

**Comment by yeelimtse** [comment]
How did you solve the 502?
