### ISSUE TITLE
Problems with Git repo detection

### ISSUE THREAD

**Issue by mwaldheim** [semantic-release/semantic-release#2711]
### Current behavior

Since the update 20.1.0 there is the problem that the pipeline of all my projects do not work correctly anymore. It thinks it is not a git repository. Locally it works correctly, just not in the pipeline.

Supplementary: The pipeline was not changed and all of a sudden it does not work anymore. The problems occur all at once.

```cmd
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/gitlab"
2023-02-12T14:40:00.408Z semantic-release:plugins options for @semantic-release/exec/fail: {
  verifyReleaseCmd: 'echo ${nextRelease.version} > VERSION.txt',
  prepareCmd: 'npx replace-json-property package.json version ${nextRelease.version} && npm i --legacy-peer-deps && npm run build && npm run zip'
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
2023-02-12T14:40:00.409Z semantic-release:plugins options for @semantic-release/gitlab/fail: {
  assets: [
    { path: 'VERSION.txt', label: 'Release Version' },
    { path: 'dist/**/*.zip', label: 'Compiled Files', type: 'package' }
  ]
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/gitlab"
(node:26) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
2023-02-12T14:40:00.422Z semantic-release:git Error: Command failed with exit code 128: git rev-parse --git-dir
fatal: detected dubious ownership in repository at '/builds/forestdesign/ecodrive/ecodrive'
To add an exception for this directory, call:
	git config --global --add safe.directory /builds/forestdesign/ecodrive/ecodrive
    at makeError (file:///node_modules/semantic-release/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///node_modules/semantic-release/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async isGitRepo (file:///node_modules/semantic-release/lib/git.js:192:13)
    at async default (file:///node_modules/semantic-release/lib/verify.js:14:9)
    at async run (file:///node_modules/semantic-release/index.js:65:3)
    at async Module.default (file:///node_modules/semantic-release/index.js:275:22)
    at async default (file:///node_modules/semantic-release/cli.js:55:5)
[2:40:00 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/exec" in dry-run mode
[2:40:00 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/gitlab" in dry-run mode
[2:40:00 PM] [semantic-release] › ✘  ENOGITREPO Not running from a git repository.
The semantic-release command must be executed from a Git repository.
The current working directory is /builds/forestdesign/ecodrive/ecodrive.
Please verify your CI configuration to make sure the semantic-release command is executed from the root of the cloned repository.
AggregateError: 
    SemanticReleaseError: Not running from a git repository.
        at default (file:///node_modules/semantic-release/lib/get-error.js:6:10)
        at default (file:///node_modules/semantic-release/lib/verify.js:15:17)
        at async run (file:///node_modules/semantic-release/index.js:65:3)
        at async Module.default (file:///node_modules/semantic-release/index.js:275:22)
        at async default (file:///node_modules/semantic-release/cli.js:55:5)
    at default (file:///node_modules/semantic-release/lib/verify.js:41:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async run (file:///node_modules/semantic-release/index.js:65:3)
    at async Module.default (file:///node_modules/semantic-release/index.js:275:22)
    at async default (file:///node_modules/semantic-release/cli.js:55:5) {
  errors: [
    SemanticReleaseError: Not running from a git repository.
        at default (file:///node_modules/semantic-release/lib/get-error.js:6:10)
        at default (file:///node_modules/semantic-release/lib/verify.js:15:17)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async run (file:///node_modules/semantic-release/index.js:65:3)
        at async Module.default (file:///node_modules/semantic-release/index.js:275:22)
        at async default (file:///node_modules/semantic-release/cli.js:55:5) {
      code: 'ENOGITREPO',
      details: 'The `semantic-release` command must be executed from a Git repository.\n' +
        '\n' +
        'The current working directory is `/builds/forestdesign/ecodrive/ecodrive`.\n' +
        '\n' +
        'Please verify your CI configuration to make sure the `semantic-release` command is executed from the root of the cloned repository.',
      semanticRelease: true
    }
  ]
}
```

### Expected behavior

Correct would be a clean release.

### `semantic-release` version

20.1

### CI environment

gitlab

### Plugins used
```json
{
  "dependencies": {
    "@semantic-release/changelog": "6.0.x",
    "@semantic-release/exec": "6.0.x",
    "@semantic-release/git": "10.0.x",
    "@semantic-release/gitlab": "10.1.x",
    "semantic-release": "20.1.x",
  }
}
```

### `semantic-release` configuration
```yml
plugins:
  - "@semantic-release/commit-analyzer"
  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
      presetConfig:
        types:
          - type: "feat"
            section: ":sparkles: Features"
            hidden: false
          - type: "feature"
            section: ":sparkles: Features"
            hidden: false
          - type: "fix"
            section: ":bug: Fixes"
            hidden: false
          - type: "docs"
            section: ":memo: Documentation"
            hidden: false
          - type: "style"
            section: ":barber: Style"
            hidden: false
          - type: "refactor"
            section: ":zap: Refactoring"
            hidden: false
          - type: "revert"
            section: ":zap: Reverts"
            hidden: false
          - type: "perf"
            section: ":fast_forward: Performance Improvements"
            hidden: false
          - type: "test"
            section: ":white_check_mark: Tests"
            hidden: false
          - type: "ci"
            section: ":repeat: CI"
            hidden: false
          - type: "chore"
            section: ":repeat: Chores"
            hidden: true
          - type: "build"
            section: ":repeat: Build System"
            hidden: false
  - - "@semantic-release/changelog"
    - changelogFile: "CHANGELOG.md"
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
      prepareCmd: "npx replace-json-property package.json version ${nextRelease.version} && npm i --legacy-peer-deps && npm run build && npm run zip"
  - - "@semantic-release/git"
    - assets:
        - "CHANGELOG.md"
        - "package.json"
  - - "@semantic-release/gitlab"
    - assets:
        - path: "VERSION.txt"
          label: "Release Version"
        - path: "dist/**/*.zip"
          label: "Compiled Files"
          type: 'package'
branches:
  - "main"
  - "+([0-9])?(.{+([0-9]),x}).x"
  - name: "pre"
    prerelease: 'rc'
  - name: "beta"
    prerelease: 'beta'
  - name: "next"
    prerelease: true
```

### CI logs

```cmd
[0KRunning with gitlab-runner 15.9.0~beta.84.gdf5ed1cb (df5ed1cb)[0;m
[0K  on green-2.shared.runners-manager.gitlab.com/default ns46NMmJ, system ID: s_88851e7db4f3[0;m
section_start:1676212768:prepare_executor
[0K[0K[36;1mPreparing the "docker+machine" executor[0;m[0;m
[0KUsing Docker executor with image registry.gitlab.com/mwaldheim/container/version ...[0;m
[0KAuthenticating with credentials from job payload (GitLab Registry)[0;m
[0KPulling docker image registry.gitlab.com/mwaldheim/container/version ...[0;m
[0KUsing docker image sha256:9a4d47398109c110feed598b09b52ab25be0303ba929776ec4a3af8f2e082101 for registry.gitlab.com/mwaldheim/container/version with digest registry.gitlab.com/mwaldheim/container/version@sha256:b66aa40cb86138c1651a78d372e9049e9371bb94058e240de55e51841cd56beb ...[0;m
section_end:1676212791:prepare_executor
[0Ksection_start:1676212791:prepare_script
[0K[0K[36;1mPreparing environment[0;m[0;m
Running on runner-ns46nmmj-project-34624605-concurrent-0 via runner-ns46nmmj-shared-1676212718-35902e5a...
section_end:1676212794:prepare_script
[0Ksection_start:1676212794:get_sources
[0K[0K[36;1mGetting source from Git repository[0;m[0;m
[32;1m$ eval "$CI_PRE_CLONE_SCRIPT"[0;m
[32;1mFetching changes with git depth set to 20...[0;m
Initialized empty Git repository in /builds/forestdesign/ecodrive/ecodrive/.git/
[32;1mCreated fresh repository.[0;m
[32;1mChecking out c76833f2 as detached HEAD (ref is next)...[0;m

[32;1mSkipping Git submodules setup[0;m
section_end:1676212796:get_sources
[0Ksection_start:1676212796:step_script
[0K[0K[36;1mExecuting "step_script" stage of the job script[0;m[0;m
[0KUsing docker image sha256:9a4d47398109c110feed598b09b52ab25be0303ba929776ec4a3af8f2e082101 for registry.gitlab.com/mwaldheim/container/version with digest registry.gitlab.com/mwaldheim/container/version@sha256:b66aa40cb86138c1651a78d372e9049e9371bb94058e240de55e51841cd56beb ...[0;m
[32;1m$ ls -la[0;m
total 944
drwxrwxrwx 6 root root   4096 Feb 12 14:39 .
drwxrwxrwx 4 root root   4096 Feb 12 14:39 ..
-rw-rw-rw- 1 root root    274 Feb 12 14:39 .editorconfig
-rw-rw-rw- 1 root root    986 Feb 12 14:39 .eslintrc.json
-rw-rw-rw- 1 root root     56 Feb 12 14:39 .firebaserc
drwxrwxrwx 6 root root   4096 Feb 12 14:39 .git
-rw-rw-rw- 1 root root    593 Feb 12 14:39 .gitignore
-rw-rw-rw- 1 root root   1636 Feb 12 14:39 .gitlab-ci.yml
drwxrwxrwx 2 root root   4096 Feb 12 14:39 .husky
-rw-rw-rw- 1 root root    121 Feb 12 14:39 .npmrc
-rw-rw-rw- 1 root root   2089 Feb 12 14:39 .releaserc.yml
-rw-rw-rw- 1 root root  55570 Feb 12 14:39 CHANGELOG.md
-rw-rw-rw- 1 root root   1080 Feb 12 14:39 LICENSE
-rw-rw-rw- 1 root root    611 Feb 12 14:39 README.md
-rw-rw-rw- 1 root root   3757 Feb 12 14:39 angular.json
-rw-rw-rw- 1 root root     67 Feb 12 14:39 build.env
drwxrwxrwx 5 root root   4096 Feb 12 14:39 cypress
-rw-rw-rw- 1 root root    329 Feb 12 14:39 cypress.config.ts
-rw-rw-rw- 1 root root    299 Feb 12 14:39 firebase.json
-rw-rw-rw- 1 root root    755 Feb 12 14:39 jest.config.js
-rw-rw-rw- 1 root root    631 Feb 12 14:39 ngsw-config.json
-rw-rw-rw- 1 root root 795376 Feb 12 14:39 package-lock.json
-rw-rw-rw- 1 root root   2342 Feb 12 14:39 package.json
-rw-rw-rw- 1 root root   1734 Feb 12 14:39 prebuild.mjs
drwxrwxrwx 4 root root   4096 Feb 12 14:39 src
-rw-rw-rw- 1 root root    263 Feb 12 14:39 tsconfig.app.json
-rw-rw-rw- 1 root root   1019 Feb 12 14:39 tsconfig.json
-rw-rw-rw- 1 root root    334 Feb 12 14:39 tsconfig.spec.json
-rw-rw-rw- 1 root root    353 Feb 12 14:39 zip.js
[32;1m$ git config --global --add safe.directory ./[0;m
[32;1m$ npx semantic-release --generate-notes false --dry-run --debug[0;m
[2:39:59 PM] [semantic-release] › ℹ  Running semantic-release version 20.1.0
2023-02-12T14:40:00.051Z semantic-release:config load config from: /builds/forestdesign/ecodrive/ecodrive/.releaserc.yml
2023-02-12T14:40:00.057Z semantic-release:config options values: {
  branches: [
    'main',
    '+([0-9])?(.{+([0-9]),x}).x',
    { name: 'pre', prerelease: 'rc' },
    { name: 'beta', prerelease: 'beta' },
    { name: 'next', prerelease: true }
  ],
  repositoryUrl: 'https://gitlab.com/forestdesign/ecodrive/ecodrive.git',
  tagFormat: 'v${version}',
  plugins: [
    '@semantic-release/commit-analyzer',
    [ '@semantic-release/release-notes-generator', [Object] ],
    [ '@semantic-release/changelog', [Object] ],
    [ '@semantic-release/exec', [Object] ],
    [ '@semantic-release/git', [Object] ],
    [ '@semantic-release/gitlab', [Object] ]
  ],
  _: [],
  'generate-notes': [],
  generateNotes: [],
  'dry-run': true,
  d: true,
  dryRun: true,
  debug: true,
  '$0': '/node_modules/.bin/semantic-release'
}
2023-02-12T14:40:00.393Z semantic-release:plugins options for @semantic-release/changelog/verifyConditions: { changelogFile: 'CHANGELOG.md' }
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
2023-02-12T14:40:00.395Z semantic-release:plugins options for @semantic-release/exec/verifyConditions: {
  verifyReleaseCmd: 'echo ${nextRelease.version} > VERSION.txt',
  prepareCmd: 'npx replace-json-property package.json version ${nextRelease.version} && npm i --legacy-peer-deps && npm run build && npm run zip'
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
2023-02-12T14:40:00.396Z semantic-release:plugins options for @semantic-release/git/verifyConditions: { assets: [ 'CHANGELOG.md', 'package.json' ] }
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
2023-02-12T14:40:00.397Z semantic-release:plugins options for @semantic-release/gitlab/verifyConditions: {
  assets: [
    { path: 'VERSION.txt', label: 'Release Version' },
    { path: 'dist/**/*.zip', label: 'Compiled Files', type: 'package' }
  ]
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/gitlab"
2023-02-12T14:40:00.398Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
2023-02-12T14:40:00.399Z semantic-release:plugins options for @semantic-release/exec/analyzeCommits: {
  verifyReleaseCmd: 'echo ${nextRelease.version} > VERSION.txt',
  prepareCmd: 'npx replace-json-property package.json version ${nextRelease.version} && npm i --legacy-peer-deps && npm run build && npm run zip'
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
2023-02-12T14:40:00.400Z semantic-release:plugins options for @semantic-release/exec/verifyRelease: {
  verifyReleaseCmd: 'echo ${nextRelease.version} > VERSION.txt',
  prepareCmd: 'npx replace-json-property package.json version ${nextRelease.version} && npm i --legacy-peer-deps && npm run build && npm run zip'
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
2023-02-12T14:40:00.401Z semantic-release:plugins options for @semantic-release/changelog/prepare: { changelogFile: 'CHANGELOG.md' }
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
2023-02-12T14:40:00.402Z semantic-release:plugins options for @semantic-release/exec/prepare: {
  verifyReleaseCmd: 'echo ${nextRelease.version} > VERSION.txt',
  prepareCmd: 'npx replace-json-property package.json version ${nextRelease.version} && npm i --legacy-peer-deps && npm run build && npm run zip'
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
2023-02-12T14:40:00.403Z semantic-release:plugins options for @semantic-release/git/prepare: { assets: [ 'CHANGELOG.md', 'package.json' ] }
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
2023-02-12T14:40:00.404Z semantic-release:plugins options for @semantic-release/exec/publish: {
  verifyReleaseCmd: 'echo ${nextRelease.version} > VERSION.txt',
  prepareCmd: 'npx replace-json-property package.json version ${nextRelease.version} && npm i --legacy-peer-deps && npm run build && npm run zip'
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
2023-02-12T14:40:00.404Z semantic-release:plugins options for @semantic-release/gitlab/publish: {
  assets: [
    { path: 'VERSION.txt', label: 'Release Version' },
    { path: 'dist/**/*.zip', label: 'Compiled Files', type: 'package' }
  ]
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/gitlab"
2023-02-12T14:40:00.405Z semantic-release:plugins options for @semantic-release/exec/addChannel: {
  verifyReleaseCmd: 'echo ${nextRelease.version} > VERSION.txt',
  prepareCmd: 'npx replace-json-property package.json version ${nextRelease.version} && npm i --legacy-peer-deps && npm run build && npm run zip'
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/exec"
2023-02-12T14:40:00.406Z semantic-release:plugins options for @semantic-release/exec/success: {
  verifyReleaseCmd: 'echo ${nextRelease.version} > VERSION.txt',
  prepareCmd: 'npx replace-json-property package.json version ${nextRelease.version} && npm i --legacy-peer-deps && npm run build && npm run zip'
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
2023-02-12T14:40:00.407Z semantic-release:plugins options for @semantic-release/gitlab/success: {
  assets: [
    { path: 'VERSION.txt', label: 'Release Version' },
    { path: 'dist/**/*.zip', label: 'Compiled Files', type: 'package' }
  ]
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/gitlab"
2023-02-12T14:40:00.408Z semantic-release:plugins options for @semantic-release/exec/fail: {
  verifyReleaseCmd: 'echo ${nextRelease.version} > VERSION.txt',
  prepareCmd: 'npx replace-json-property package.json version ${nextRelease.version} && npm i --legacy-peer-deps && npm run build && npm run zip'
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
2023-02-12T14:40:00.409Z semantic-release:plugins options for @semantic-release/gitlab/fail: {
  assets: [
    { path: 'VERSION.txt', label: 'Release Version' },
    { path: 'dist/**/*.zip', label: 'Compiled Files', type: 'package' }
  ]
}
[2:40:00 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/gitlab"
(node:26) ExperimentalWarning: Importing JSON modules is an experimental feature and might change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
2023-02-12T14:40:00.422Z semantic-release:git Error: Command failed with exit code 128: git rev-parse --git-dir
fatal: detected dubious ownership in repository at '/builds/forestdesign/ecodrive/ecodrive'
To add an exception for this directory, call:

	git config --global --add safe.directory /builds/forestdesign/ecodrive/ecodrive
    at makeError (file:///node_modules/semantic-release/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///node_modules/semantic-release/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async isGitRepo (file:///node_modules/semantic-release/lib/git.js:192:13)
    at async default (file:///node_modules/semantic-release/lib/verify.js:14:9)
    at async run (file:///node_modules/semantic-release/index.js:65:3)
    at async Module.default (file:///node_modules/semantic-release/index.js:275:22)
    at async default (file:///node_modules/semantic-release/cli.js:55:5)
[2:40:00 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/exec" in dry-run mode
[2:40:00 PM] [semantic-release] › ⚠  Skip step "fail" of plugin "@semantic-release/gitlab" in dry-run mode
[2:40:00 PM] [semantic-release] › ✘  ENOGITREPO Not running from a git repository.
The semantic-release command must be executed from a Git repository.

The current working directory is /builds/forestdesign/ecodrive/ecodrive.

Please verify your CI configuration to make sure the semantic-release command is executed from the root of the cloned repository.

AggregateError: 
    SemanticReleaseError: Not running from a git repository.
        at default (file:///node_modules/semantic-release/lib/get-error.js:6:10)
        at default (file:///node_modules/semantic-release/lib/verify.js:15:17)
        at async run (file:///node_modules/semantic-release/index.js:65:3)
        at async Module.default (file:///node_modules/semantic-release/index.js:275:22)
        at async default (file:///node_modules/semantic-release/cli.js:55:5)
    at default (file:///node_modules/[4msemantic-release[24m/lib/verify.js:41:11)
[90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
    at async run (file:///node_modules/[4msemantic-release[24m/index.js:65:3)
    at async Module.default (file:///node_modules/[4msemantic-release[24m/index.js:275:22)
    at async default (file:///node_modules/[4msemantic-release[24m/cli.js:55:5) {
  errors: [
    SemanticReleaseError: Not running from a git repository.
        at default (file:///node_modules/[4msemantic-release[24m/lib/get-error.js:6:10)
        at default (file:///node_modules/[4msemantic-release[24m/lib/verify.js:15:17)
    [90m    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)[39m
        at async run (file:///node_modules/[4msemantic-release[24m/index.js:65:3)
        at async Module.default (file:///node_modules/[4msemantic-release[24m/index.js:275:22)
        at async default (file:///node_modules/[4msemantic-release[24m/cli.js:55:5) {
      code: [32m'ENOGITREPO'[39m,
      details: [32m'The `semantic-release` command must be executed from a Git repository.\n'[39m +
        [32m'\n'[39m +
        [32m'The current working directory is `/builds/forestdesign/ecodrive/ecodrive`.\n'[39m +
        [32m'\n'[39m +
        [32m'Please verify your CI configuration to make sure the `semantic-release` command is executed from the root of the cloned repository.'[39m,
      semanticRelease: [33mtrue[39m
    }
  ]
}section_end:1676212799:step_script
[0Ksection_start:1676212799:cleanup_file_variables
[0K[0K[36;1mCleaning up project directory and file based variables[0;m[0;m
section_end:1676212800:cleanup_file_variables
[0K[31;1mERROR: Job failed: exit code 1
[0;m
```

**Comment by mwaldheim** [comment]
Supplementary: The pipeline was not changed and all of a sudden it does not work anymore. The problems occur all at once.

**Comment by mwaldheim** [comment]
Problem I could find so far. Git requires a safe directory and that must be released before:

```cmd
$ git config --global --add safe.directory '*'
```
