### ISSUE TITLE
Authentication doesn't work with bitbucket server even after exporting BB_TOKEN_BASIC_AUTH in ENV

### ISSUE THREAD

**Issue by rahul3887** [semantic-release/semantic-release#2728]
Hi All,

Authentication doesn't work with bitbucket server even after exporting BB_TOKEN_BASIC_AUTH in ENV.

Please find the debug log for the same. 
Please note, it is trying SSH based auth first and then it falls back to HTTPS url even after providing repositoryUrl in .releaserc.yaml file.

BB_TOKEN_BASIC_AUTH : user:token

[9:23:03 AM] [semantic-release] › ℹ  Running semantic-release version 20.1.1
2023-03-10T09:23:03.484Z semantic-release:config load config from: /var/lib/jenkins/workspace/******/.releaserc.yaml
2023-03-10T09:23:03.516Z semantic-release:config options values: {
  branches: [ 'release_branch_1', 'release_branch_2' ],
  repositoryUrl: 'https://example.com/scm/****/*****.git,
  
============================================================================

2023-03-10T09:23:04.070Z semantic-release:get-git-auth-url Verifying ssh auth by attempting to push to  https://example.com/scm/****/*****.git
2023-03-10T09:23:05.392Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://example.com/scm/****/*****.git HEAD:origin/*****
fatal: Authentication failed for 'https://example.com/scm/****/*****.git'
    at makeError (file:///usr/local/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/semantic-release/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async verifyAuth (file:///usr/local/lib/node_modules/semantic-release/lib/git.js:209:5)
    at async default (file:///usr/local/lib/node_modules/semantic-release/lib/get-git-auth-url.js:93:5)
    at async run (file:///usr/local/lib/node_modules/semantic-release/index.js:67:27)
    at async Module.default (file:///usr/local/lib/node_modules/semantic-release/index.js:275:22)
    at async default (file:///usr/local/lib/node_modules/semantic-release/cli.js:55:5)
2023-03-10T09:23:05.392Z semantic-release:get-git-auth-url SSH key auth failed, falling back to https.
[9:23:06 AM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Command failed with exit code 128: git ls-remote --heads https://example.com/scm/****/*****.git
fatal: Authentication failed for 'https://example.com/scm/****/*****.git'
    at makeError (file:///usr/local/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:59:11)
    at handlePromise (file:///usr/local/lib/node_modules/semantic-release/node_modules/execa/index.js:119:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getBranches (file:///usr/local/lib/node_modules/semantic-release/lib/git.js:68:11)
    at async default (file:///usr/local/lib/node_modules/semantic-release/lib/branches/expand.js:6:23)
    at async default (file:///usr/local/lib/node_modules/semantic-release/lib/branches/index.js:14:26)
    at async run (file:///usr/local/lib/node_modules/semantic-release/index.js:68:22)
    at async Module.default (file:///usr/local/lib/node_modules/semantic-release/index.js:275:22)
    at async default (file:///usr/local/lib/node_modules/semantic-release/cli.js:55:5) {
  shortMessage: 'Command failed with exit code 128: git ls-remote --heads https://example.com/scm/****/*****.git',
  command: 'git ls-remote --heads https://example.com/scm/****/*****.git',
  escapedCommand: 'git ls-remote --heads "https://example.com/scm/****/*****.git"',
  exitCode: 128,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: "fatal: Authentication failed for 'https://example.com/scm/****/*****.git'",
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}

Can someone please help to debug the issue here?

Thanks in advance.

**Comment by asotog** [comment]
same for me :( tried with those variables always getting no access despite the token has access, trying to use it using bitbucket only way seems to work is like 

```
git ls-remote --heads https://{username}:{apiToken}@bitbucket.org/.....
```
those 2 keys only achievable it seems with `GIT_CREDENTIALS` variable

Also the token I generated, assigned all the scopes from bitbucket
