### ISSUE TITLE
ENOPKG Missing `package.json` file on Github Actions

### ISSUE THREAD

**Issue by talohana** [semantic-release/semantic-release#2735]
### Current behavior

I've migrated to Github Actions in [talohana/angular-dark-mode](https://github.com/talohana/angular-dark-mode) and I added the following release step:

```yml
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      
      - name: Install Dependencies
        run: yarn install

      - name: Semantic Release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn semantic-release
```

When pushing to main I get the following error:
```
 SemanticReleaseError: Missing `package.json` file.
```

### Expected behavior

Package to be released to npm registry

### `semantic-release` version

20.1.3

### CI environment

Github Actions

### Plugins used

- @semantic-release/commit-analyzer
- @semantic-release/release-notes-generator
- @semantic-release/changelog
- @semantic-release/git
- @semantic-release/npm

### `semantic-release` configuration

https://github.com/talohana/angular-dark-mode/blob/main/.releaserc.json

### CI logs

```
Run yarn semantic-release
  yarn semantic-release
  shell: /usr/bin/bash -e {0}
  env:
    GH_TOKEN: ***
    NPM_TOKEN: ***
yarn run v1.22.19
$ semantic-release
[4:37:54 PM] [semantic-release] › ℹ  Running semantic-release version 17.1.2
[4:37:54 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[4:37:54 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[4:37:54 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[4:37:54 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[4:37:54 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[4:37:54 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[4:37:54 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[4:37:54 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[4:37:54 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[4:37:54 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[4:37:56 PM] [semantic-release] › ✔  Run automated release from branch main on repository https://github.com/talohana/angular-dark-mode
[4:37:56 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[4:37:56 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[4:37:56 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[4:37:56 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[4:37:56 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[4:37:56 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[4:37:56 PM] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[4:37:56 PM] [semantic-release] › ✖  ENOPKG Missing `package.json` file.
A package.json file (https://docs.npmjs.com/files/package.json) at the root of your project is required to release on npm.

Please follow the npm guideline (https://docs.npmjs.com/getting-started/creating-node-modules) to create a valid package.json file.

AggregateError: 
    SemanticReleaseError: Missing `package.json` file.
        at module.exports (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/@semantic-release/npm/lib/get-pkg.js:17:33)
        at async verifyConditions (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/@semantic-release/npm/index.js:32:17)
        at async validator (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/lib/plugins/normalize.js:34:24)
        at async /home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/lib/plugins/pipeline.js:37:34
        at async /home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/lib/plugins/pipeline.js:31:3
        at async pluginsConf.<computed> [as verifyConditions] (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/lib/plugins/index.js:80:11)
        at async run (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/index.js:95:3)
        at async module.exports (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/index.js:260:22)
        at async module.exports (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/cli.js:55:5)
    at /home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/lib/plugins/pipeline.js:54:11
    at async pluginsConf.<computed> [as verifyConditions] (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/lib/plugins/index.js:80:11)
    at async run (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/index.js:95:3)
    at async module.exports (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/index.js:260:22)
    at async module.exports (/home/runner/work/angular-dark-mode/angular-dark-mode/node_modules/semantic-release/cli.js:55:5)error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by travi** [comment]
Unsure if this was a change as part of your transition, but you have a `pkgRoot` configured for the npm plugin. That changes the directory where the publish command executes. Is that actually your goal, or would it be more appropriate to set the `files` property in the `package.json` instead?

**Comment by talohana** [comment]
Thanks @travi! Actually I saw that the dist/angular-dark-json isn't preset at the release job, so I probably misconfigured something in the ci/cd, I'll debug and re-open if this will be related to semantic-release.
