### ISSUE TITLE
Error, semantic release failing to get the github_token using github actions

### ISSUE THREAD

**Issue by Abeinevincent** [semantic-release/semantic-release#2761]
### Current behavior

I keep on getting the error, SemanticReleaseError: No GitHub token specified. when I push to github, 

### Expected behavior

I expect github actions to automatically pick up the GITHUB_TOKEN without explicitly specifying it in the repository secrets

### `semantic-release` version

"semantic-release": "^21.0.1"

### CI environment

Github Actions

### `semantic-release` configuration

Link to repo: https://github.com/Abeinevincent/semanticreleasecwv

### CI logs

> semanticreleasecwv@0.0.0-development semantic-release
> semantic-release

[9:46:00 AM] [semantic-release] › ℹ  Running semantic-release version 21.0.1
[9:46:01 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[9:46:01 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[9:46:01 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:46:01 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[9:46:01 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[9:46:01 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[9:46:01 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[9:46:01 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[9:46:01 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[9:46:01 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[9:46:01 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[9:46:03 AM] [semantic-release] › ✔  Run automated release from branch master on repository https://github.com/Abeinevincent/semanticreleasecwv.git
[9:46:03 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:46:03 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[9:46:03 AM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[9:46:03 AM] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /tmp/951fd6193fd9dd613a2c13[8](https://github.com/Abeinevincent/semanticreleasecwv/actions/runs/4627557037/jobs/8185702526#step:5:9)65058cee8/.npmrc
abeinevincent
[[9](https://github.com/Abeinevincent/semanticreleasecwv/actions/runs/4627557037/jobs/8185702526#step:5:10):46:04 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[9:46:04 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[9:46:04 AM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[9:46:04 AM] [semantic-release] › ✘  Failed step "verifyConditions" of plugin "@semantic-release/github"
[9:46:04 AM] [semantic-release] › ✘  An error occurred while running semantic-release: AggregateError: 
    SemanticReleaseError: No GitHub token specified.
        at module.exports (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/lib/get-error.js:6:[10](https://github.com/Abeinevincent/semanticreleasecwv/actions/runs/4627557037/jobs/8185702526#step:5:11))
        at module.exports (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/lib/verify.js:97:17)
        at verifyConditions (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/index.js:27:9)
        at validator (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
        at file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/pipeline.js:38:42
        at next (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/p-reduce/index.js:16:10)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at module.exports (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/lib/verify.js:101:[11](https://github.com/Abeinevincent/semanticreleasecwv/actions/runs/4627557037/jobs/8185702526#step:5:12))
    at verifyConditions (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/index.js:27:9)
    at validator (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/pipeline.js:38:42
    at next (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/p-reduce/index.js:16:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  pluginName: '@semantic-release/github'
}
AggregateError: 
    AggregateError: 
        SemanticReleaseError: No GitHub token specified.
            at module.exports (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/lib/get-error.js:6:10)
            at module.exports (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/lib/verify.js:97:17)
            at verifyConditions (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/index.js:27:9)
            at validator (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
            at file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/pipeline.js:38:42
            at next (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/p-reduce/index.js:16:10)
        at module.exports (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/lib/verify.js:101:11)
        at verifyConditions (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/index.js:27:9)
        at validator (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
        at file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/pipeline.js:38:42
        at next (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/p-reduce/index.js:16:10)
    at file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/pipeline.js:55:[13](https://github.com/Abeinevincent/semanticreleasecwv/actions/runs/4627557037/jobs/8185702526#step:5:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async pluginsConfigAccumulator.<computed> [as verifyConditions] (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/index.js:106:3)
    at async Module.default (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/index.js:275:22)
    at async default (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/cli.js:55:5) {
  errors: [
    AggregateError: 
        SemanticReleaseError: No GitHub token specified.
            at module.exports (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/lib/get-error.js:6:10)
            at module.exports (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/lib/verify.js:97:17)
            at verifyConditions (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/index.js:27:9)
            at validator (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
            at file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/pipeline.js:38:42
            at next (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/p-reduce/index.js:[16](https://github.com/Abeinevincent/semanticreleasecwv/actions/runs/4627557037/jobs/8185702526#step:5:17):10)
            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at module.exports (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/lib/verify.js:101:11)
        at verifyConditions (/home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/@semantic-release/github/index.js:[27](https://github.com/Abeinevincent/semanticreleasecwv/actions/runs/4627557037/jobs/8185702526#step:5:28):9)
        at validator (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/normalize.js:36:[30](https://github.com/Abeinevincent/semanticreleasecwv/actions/runs/4627557037/jobs/8185702526#step:5:31))
        at file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/semantic-release/lib/plugins/pipeline.js:[38](https://github.com/Abeinevincent/semanticreleasecwv/actions/runs/4627557037/jobs/8185702526#step:5:39):[42](https://github.com/Abeinevincent/semanticreleasecwv/actions/runs/4627557037/jobs/8185702526#step:5:43)
        at next (file:///home/runner/work/semanticreleasecwv/semanticreleasecwv/node_modules/p-reduce/index.js:16:10)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
      pluginName: '@semantic-release/github'
    }
  ]
}
Error: Process completed with exit code 1.

**Comment by travi** [comment]
> I expect github actions to automatically pick up the GITHUB_TOKEN without explicitly specifying it in the repository secrets

it isnt clear to me what you are asking semantic-release to do differently. semantic-release does not control how github actions behave, but simply executes within that context. while actions do automatically provide a `GITHUB_TOKEN` within `secrets`, that is not made available to the execution environment without your workflow being configured to provide it somehow. 

the current version of you workflow [provides the token to the environment](https://github.com/Abeinevincent/semanticreleasecwv/blob/7bd5adb4a8fc88fbdd3da3b46a5c400071d6f3db/.github/workflows/main.yml#L51) as semantic-release expects it. what is it that you are asking to be changed?

**Comment by R3ven6eR** [comment]
Thanks
