### ISSUE TITLE
Teamcity ENOGITREPO

### ISSUE THREAD

**Issue by M4TY** [semantic-release/semantic-release#2808]
### Current behavior

When I am running a build, semantic release errors with ENOGITREPO: SemanticReleaseError: Not running from a git repository.

### Expected behavior

Since it is running from a git repo (made sure with echo ls -a), it should work as expected.

### `semantic-release` version

21.0.2

### CI environment

TeamCity

### Plugins used

"@semantic-release/commit-analyzer"

### `semantic-release` configuration

{
  "branches": [
    "master"
  ],
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "preset": "conventionalcommits",
        "releaseRules": [
          {
            "type": "model",
            "release": "patch"
          },
          {
            "type": "graph",
            "release": "patch"
          }
        ]
      }
    ]
  ],
  "tagFormat": "${version}"
}

### CI logs

`npm WARN exec The following package was not found and will be installed: semantic-release@21.0.2
05:57:00   [5:57:00 AM] [semantic-release] › ℹ  Running semantic-release version 21.0.2
05:57:00   [5:57:00 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
05:57:00   [5:57:00 AM] [semantic-release] › ✘  ENOGITREPO Not running from a git repository.
05:57:00   The semantic-release command must be executed from a Git repository.
05:57:00   
05:57:00   The current working directory is /opt/buildagent/work/f0725d252ab8b836.
05:57:00   
05:57:00   Please verify your CI configuration to make sure the semantic-release command is executed from the root of the cloned repository.
05:57:00   
05:57:00   AggregateError:
05:57:00       SemanticReleaseError: Not running from a git repository.
05:57:00           at default (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/get-error.js:6:10)
05:57:00           at default (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/verify.js:15:17)
05:57:00           at async run (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:65:3)
05:57:00           at async Module.default (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:275:22)
05:57:00           at async default (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/cli.js:55:5)
05:57:00       at default (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/verify.js:41:11)
05:57:00       at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
05:57:00       at async run (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:65:3)
05:57:00       at async Module.default (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:275:22)
05:57:00       at async default (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/cli.js:55:5) {
05:57:00     errors: [
05:57:00       SemanticReleaseError: Not running from a git repository.
05:57:00           at default (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/get-error.js:6:10)
05:57:00           at default (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/verify.js:15:17)
05:57:00           at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
05:57:00           at async run (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:65:3)
05:57:00           at async Module.default (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/index.js:275:22)
05:57:00           at async default (file:///root/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/cli.js:55:5) {
05:57:00         code: 'ENOGITREPO',
05:57:00         details: 'The `semantic-release` command must be executed from a Git repository.\n' +
05:57:00           '\n' +
05:57:00           'The current working directory is `/opt/buildagent/work/f0725d252ab8b836`.\n' +
05:57:00           '\n' +
05:57:00           'Please verify your CI configuration to make sure the `semantic-release` command is executed from the root of the cloned repository.',
05:57:00         semanticRelease: true
05:57:00       }
05:57:00     ]
05:57:00   Docker event: {"status":"die","id":"0ba3eef18bc890fa2f6f4a1d1568d55604c4d3fb5fd04bc0b8b84206d4f0ca1f","from":"node:lts","Type":"container","Action":"die","Actor":{"ID":"0ba3eef18bc890fa2f6f4a1d1568d55604c4d3fb5fd04bc0b8b84206d4f0ca1f","Attributes":{"exitCode":"1","image":"node:lts","jetbrains.teamcity.buildId":"1111","name":"kind_pasteur"}},"scope":"local","time":1684994220,"timeNano":1684994220574889442}
05:57:01   Docker event: {"status":"destroy","id":"0ba3eef18bc890fa2f6f4a1d1568d55604c4d3fb5fd04bc0b8b84206d4f0ca1f","from":"node:lts","Type":"container","Action":"destroy","Actor":{"ID":"0ba3eef18bc890fa2f6f4a1d1568d55604c4d3fb5fd04bc0b8b84206d4f0ca1f","Attributes":{"image":"node:lts","jetbrains.teamcity.buildId":"1111","name":"kind_pasteur"}},"scope":"local","time":1684994221,"timeNano":1684994221599677290}
05:57:01   }
05:57:01   Process exited with code 1`

**Comment by Badisi** [comment]
Had the same issue today trying to set up my Jenkins pipeline.

After digging, I found that the error comes from there:
https://github.com/semantic-release/semantic-release/blob/45bf9d601591bf7649926e54a9459c643136b485/lib/verify.js#L14-L18

**Line 15** is swallowing the real error thrown by `isGitRepo()`:
https://github.com/semantic-release/semantic-release/blob/45bf9d601591bf7649926e54a9459c643136b485/lib/git.js#L187-L193

So, running `git rev-parse --git-dir .` in my pipeline unveil the real issue:
```sh
+ git rev-parse --git-dir .
fatal: detected dubious ownership in repository at '/home/jenkins/agent/workspace/test'
To add an exception for this directory, call:

	git config --global --add safe.directory /home/jenkins/agent/workspace/test
```

And indeed, running the recommended `git config` command solves the issue.
