### ISSUE TITLE
Error due to ES Module not supported in `node_modules/cli-table3/src/utils.js`

### ISSUE THREAD

**Issue by zeshuaro** [semantic-release/semantic-release#2877]
### Current behavior

I've been trying to set up semantic-release on my repo and dry running it but got into this error which I couldn't find any relevant issues:

```
[2:30:34 AM] [semantic-release] › ✘  An error occurred while running semantic-release: Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/vscode-poetry/vscode-poetry/node_modules/string-width/index.js from /home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/utils.js not supported.
Instead change the require of index.js in /home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/utils.js:1:21)
    at Object.<anonymous> (/home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/table.js:2:15)
    at Object.<anonymous> (/home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/index.js:1:18) {
  code: 'ERR_REQUIRE_ESM'
}
Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/vscode-poetry/vscode-poetry/node_modules/string-width/index.js from /home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/utils.js not supported.
Instead change the require of index.js in /home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/utils.js:1:21)
    at Object.<anonymous> (/home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/table.js:2:15)
    at Object.<anonymous> (/home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/index.js:1:18) {
  code: 'ERR_REQUIRE_ESM'
}/home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/utils.js:1
const stringWidth = require('string-width');
                    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /home/runner/work/vscode-poetry/vscode-poetry/node_modules/string-width/index.js from /home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/utils.js not supported.
Instead change the require of index.js in /home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/utils.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/utils.js:1:21)
    at Object.<anonymous> (/home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/src/table.js:2:15)
    at Object.<anonymous> (/home/runner/work/vscode-poetry/vscode-poetry/node_modules/cli-table3/index.js:1:18) {
  code: 'ERR_REQUIRE_ESM'
}
```

### Expected behavior

I would have expected the dry run to succeed.

### `semantic-release` version

21.0.7

### CI environment

GitHub Actions

### Plugins used

- @semantic-release/commit-analyzer
- @semantic-release/release-notes-generator
- @semantic-release/git
- semantic-release-vsce
- @semantic-release/github

### `semantic-release` configuration

https://github.com/zeshuaro/vscode-poetry/blob/7ae3b308d957e8f09f3ff68639ec0ea95271cd8a/.releaserc

### CI logs

https://github.com/zeshuaro/vscode-poetry/actions/runs/5559945247/jobs/10156525701

**Comment by seebeen** [comment]
As far I as I can tell from your repo - the issue is fixed, and SR works as expected? 🙂

**Comment by zeshuaro** [comment]
Yeah, so it seems like running without the dry run option doesn't error out. But it errors out when using the dry run option.
