### ISSUE TITLE
release-notes-generator failing to import "importFrom"

### ISSUE THREAD

**Issue by reecebrend** [semantic-release/semantic-release#2971]
### Current behavior

Recently my builds on CircleCI have been failing, and the error presenting itself is as follows:

`An error occurred while running semantic-release: TypeError: (importFrom.silent(...) || importFrom(...)) is not a function
    at default (file:///home/circleci/repo/node_modules/@semantic-release/release-notes-generator/lib/load-changelog-config.js:28:105)
    at generateNotes (file:///home/circleci/repo/node_modules/@semantic-release/release-notes-generator/index.js:34:44)
    at validator (file:///home/circleci/repo/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///home/circleci/repo/node_modules/semantic-release/lib/plugins/pipeline.js:38:42
    at next (file:///home/circleci/repo/node_modules/semantic-release/node_modules/p-reduce/index.js:16:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  pluginName: '@semantic-release/release-notes-generator'`

This causes the build to fail.

### Expected behavior

The build should continue and finish successfully.

### `semantic-release` version

v22.0.0 currently, but also failed on v21.1.1

### Node version
v20.6.1

### CI environment

CircleCI

### `semantic-release` configuration

Config.yml relevant section:
`      - run:
          name: Deploy to Docker hub
          command: |
            npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
            npm install
            docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
            bash ./.circleci/tools/deploy`

Deploy script:
`today=$(date +%D)
git config --global user.name "$GIT_COMMITTER_NAME"
git config --global user.email "$GIT_COMMITTER_EMAIL"
git remote set-url origin https://${GIT_COMMITTER_NAME}:${GH_TOKEN}@github.com/ORG/REPO.git
git checkout master
git add package.json
git commit --allow-empty -m "feat: build - $today [skip ci]"
npx semantic-release`

### CI logs

`npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated string-similarity@4.0.4: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated fastify-static@4.7.0: Please use @fastify/static@5.0.0 instead
npm WARN deprecated fastify-multipart@5.4.0: Please use @fastify/multipart@6.0.0 instead
npm WARN deprecated fastify-helmet@7.1.0: Please use @fastify/helmet@8.0.0 instead
npm WARN deprecated fastify-cors@6.1.0: Please use @fastify/cors@7.0.0 instead
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.

added 1069 packages, and audited 1333 packages in 59s

173 packages are looking for funding
  run `npm fund` for details

33 vulnerabilities (16 moderate, 17 high)

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
WARNING! Your password will be stored unencrypted in /home/circleci/.docker/config.json.
Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

Login Succeeded
M       package.json
Already on 'master'
Your branch is up to date with 'origin/master'.
[master c34c7e2] feat: build - 09/20/23 [skip ci]
 1 file changed, 44 insertions(+), 44 deletions(-)
[10:53:08 AM] [semantic-release] › ℹ  Running semantic-release version 22.0.0
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/exec"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[10:53:08 AM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[10:53:15 AM] [semantic-release] › ✔  Run automated release from branch master on repository 
[10:53:15 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[10:53:15 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[10:53:15 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[10:53:15 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[10:53:15 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[10:53:15 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[10:53:15 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[10:53:15 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
[10:53:15 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
[10:53:15 AM] [semantic-release] › ℹ  Found git tag v1.1368.0 associated with version 1.1368.0 on branch master
[10:53:15 AM] [semantic-release] › ℹ  Found 5 commits since last release
[10:53:15 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"

COMMIT ANALYSIS REMOVED

[10:53:15 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[10:53:15 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/exec"
[10:53:15 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/exec"
[10:53:15 AM] [semantic-release] › ℹ  The next release version is 1.1369.0
[10:53:15 AM] [semantic-release] › ℹ  Start step "verifyRelease" of plugin "@semantic-release/exec"
[10:53:15 AM] [semantic-release] › ✔  Completed step "verifyRelease" of plugin "@semantic-release/exec"
[10:53:15 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:53:15 AM] [semantic-release] › ✘  Failed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[10:53:15 AM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: (importFrom.silent(...) || importFrom(...)) is not a function
    at default (file:///home/circleci/repo/node_modules/@semantic-release/release-notes-generator/lib/load-changelog-config.js:28:105)
    at generateNotes (file:///home/circleci/repo/node_modules/@semantic-release/release-notes-generator/index.js:34:44)
    at validator (file:///home/circleci/repo/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///home/circleci/repo/node_modules/semantic-release/lib/plugins/pipeline.js:38:42
    at next (file:///home/circleci/repo/node_modules/semantic-release/node_modules/p-reduce/index.js:16:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  pluginName: '@semantic-release/release-notes-generator'
}
TypeError: (importFrom.silent(...) || importFrom(...)) is not a function
    at default (file:///home/circleci/repo/node_modules/@semantic-release/release-notes-generator/lib/load-changelog-config.js:28:105)
    at generateNotes (file:///home/circleci/repo/node_modules/@semantic-release/release-notes-generator/index.js:34:44)
    at validator (file:///home/circleci/repo/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
    at file:///home/circleci/repo/node_modules/semantic-release/lib/plugins/pipeline.js:38:42
    at next (file:///home/circleci/repo/node_modules/semantic-release/node_modules/p-reduce/index.js:16:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  pluginName: '@semantic-release/release-notes-generator'
}
Exited with code exit status 1`

**Comment by travi** [comment]
It looks like you are using a custom preset. There are breaking changes with the recent major release that require changes to presets to align with recent changes in official conventional-changelog presets. If you maintain the custom preset, please refer to recent conventional-changelog releases for details of the changes to match. Otherwise, reach out to the maintainers of that preset to suggest that they update.

**Comment by reecebrend** [comment]
Okay, thanks for your swift response travi, I'll close down this issue and take a look at the presets.

Thanks again,
Reece
