### ISSUE TITLE
Patch releases don't accurately leverage branch names

### ISSUE THREAD

**Issue by Tbhesswebber** [semantic-release/semantic-release#3063]
### Current behavior

I have released v1.1.1 successfully via branch `1.1.x`, but the wrong build output was produced and I am trying to update things to debug.  In trying to release v1.1.2 from the same branch, I get an error indicating that it won't release anything higher than 1.1.1

### Expected behavior

Branch `1.1.x` should correctly be used to release all versions in the range 1.1.x

### `semantic-release` version

22.0.7

### CI environment

Github Actions

### Plugins used

None

### `semantic-release` configuration

  "release": {
    "branches": [
      "+([0-9])?(.{+([0-9]),x}).x",
      "main",
      "next",
      "next-major",
      {
        "name": "beta",
        "prerelease": true
      },
      {
        "name": "alpha",
        "prerelease": true
      }
    ]
  }

### CI logs

```
> style-object-to-css-string@0.0.0-development release
> semantic-release

[9:17:13 PM] [semantic-release] › ℹ  Running semantic-release version 22.0.7
[9:17:14 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[9:17:14 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[9:17:14 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[9:17:14 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[9:17:14 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[9:17:14 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[9:17:14 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[9:17:14 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[9:17:14 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[9:17:14 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[9:17:14 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[9:17:16 PM] [semantic-release] › ✔  Run automated release from branch 1.1.x on repository https://github.com/Tbhesswebber/style-object-to-css-string.git
[9:17:16 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[9:17:16 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[9:17:16 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[9:17:16 PM] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /tmp/428b944fb616a0b7293f7a307748d3f5/.npmrc
tbhesswebber
[9:17:17 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
[9:17:17 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[9:17:17 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[9:17:17 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[9:17:17 PM] [semantic-release] › ℹ  Found 1 commits since last release
[9:17:17 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:17:17 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[9:17:18 PM] [semantic-release] › ✔  Add channel 1.1.x to tag v1.1.1
[9:17:18 PM] [semantic-release] › ℹ  Start step "addChannel" of plugin "@semantic-release/npm"
[9:17:18 PM] [semantic-release] [@semantic-release/npm] › ℹ  Adding version 1.1.1 to npm registry on dist-tag release-1.1.x
+release-1.1.x: style-object-to-css-string@1.1.1
[9:17:19 PM] [semantic-release] [@semantic-release/npm] › ℹ  Added style-object-to-css-string@1.1.1 to dist-tag @release-1.1.x on https://registry.npmjs.org/
[9:17:19 PM] [semantic-release] › ✔  Completed step "addChannel" of plugin "@semantic-release/npm"
[9:17:19 PM] [semantic-release] › ℹ  Start step "addChannel" of plugin "@semantic-release/github"
[9:17:20 PM] [semantic-release] [@semantic-release/github] › ℹ  Updated GitHub release: https://github.com/Tbhesswebber/style-object-to-css-string/releases/tag/v1.1.1
[9:17:20 PM] [semantic-release] › ✔  Completed step "addChannel" of plugin "@semantic-release/github"
[9:17:20 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
[9:17:22 PM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #30: https://github.com/Tbhesswebber/style-object-to-css-string/pull/30#issuecomment-1815328569
[9:17:23 PM] [semantic-release] [@semantic-release/github] › ℹ  Added labels [ 'released on @1.1.x' ] to issue #30
[9:17:24 PM] [semantic-release] [@semantic-release/github] › ℹ  Closed issue #51: https://github.com/Tbhesswebber/style-object-to-css-string/issues/51.
[9:17:24 PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/github"
[9:17:24 PM] [semantic-release] › ℹ  Found git tag v1.1.1 associated with version 1.1.1 on branch 1.1.x
[9:17:24 PM] [semantic-release] › ℹ  Found 1 commits since last release
[9:17:24 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[9:17:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: fix(release): updates build output for cjs/esm (#52)
[9:17:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[9:17:24 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1 commits complete: patch release
[9:17:24 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[9:17:24 PM] [semantic-release] › ℹ  The next release version is 1.1.2
[9:17:24 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
[9:17:26 PM] [semantic-release] [@semantic-release/github] › ℹ  Created issue #53: https://github.com/Tbhesswebber/style-object-to-css-string/issues/53.
[9:17:26 PM] [semantic-release] › ✘  EINVALIDNEXTVERSION The release `1.1.2` on branch `1.1.x` cannot be published as it is out of range.
[9:17:26 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"
Based on the releases published on other branches, only versions within the range >=1.1.1 <1.1.1 can be published from branch 1.1.x.

The following commit is responsible for the invalid release:

    * fix(release): updates build output for cjs/esm (#52) (8b830f6)

This commit should be moved to a valid branch with git merge (https://git-scm.com/docs/git-merge) or git cherry-pick (https://git-scm.com/docs/git-cherry-pick) and removed from branch 1.1.x with git revert (https://git-scm.com/docs/git-revert) or git reset (https://git-scm.com/docs/git-reset).

A valid branch could be main.

See the workflow configuration documentation (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/workflow-configuration.md) for more details.

SemanticReleaseError: The release `1.1.2` on branch `1.1.x` cannot be published as it is out of range.
    at default (file:///home/runner/work/style-object-to-css-string/style-object-to-css-string/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (file:///home/runner/work/style-object-to-css-string/style-object-to-css-string/node_modules/semantic-release/index.js:187:[11](https://github.com/Tbhesswebber/style-object-to-css-string/actions/runs/6896594593/job/18763021431#step:7:12))
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Module.default (file:///home/runner/work/style-object-to-css-string/style-object-to-css-string/node_modules/semantic-release/index.js:275:[22](https://github.com/Tbhesswebber/style-object-to-css-string/actions/runs/6896594593/job/18763021431#step:7:23))
    at async default (file:///home/runner/work/style-object-to-css-string/style-object-to-css-string/node_modules/semantic-release/cli.js:55:5) {
  code: 'EINVALIDNEXTVERSION',
  details: 'Based on the releases published on other branches, only versions within the range `>=1.1.1 <1.1.1` can be published from branch `1.1.x`.\n' +
    '\n' +
    'The following commit is responsible for the invalid release:\n' +
    '- fix(release): updates build output for cjs/esm (#52) (8b8[30](https://github.com/Tbhesswebber/style-object-to-css-string/actions/runs/6896594593/job/18763021431#step:7:31)f6)\n' +
    '\n' +
    'This commit should be moved to a valid branch with [git merge](https://git-scm.com/docs/git-merge) or [git cherry-pick](https://git-scm.com/docs/git-cherry-pick) and removed from branch `1.1.x` with [git revert](https://git-scm.com/docs/git-revert) or [git reset](https://git-scm.com/docs/git-reset).\n' +
    '\n' +
    'A valid branch could be `main`.\n' +
    '\n' +
    'See the [workflow configuration documentation](https://github.com/semantic-release/semantic-release/blob/master/docs/usage/workflow-configuration.md) for more details.',
  semanticRelease: true
}
```

**Comment by sheerlox** [comment]
It looks like you tried creating a maintenance branch for `1.1.x` while your main branch was still at `v1.1.1`, as "Add channel 1.1.x to tag v1.1.1" suggests `v1.1.1` tag was the released on another dist-channel.

Because the purpose of maintenance branches is to backport bugfixes/features to previous versions, they will only work if the `main` branch is ahead on a "higher type" of version (e.g. it would have worked if your `main` branch was at `v1.2.0`).

As a reference, here's the code determining the authorized range for a maintenance branch: [`lib/branches/normalize.js#L37-L44`](https://github.com/semantic-release/semantic-release/blob/v22.0.8/lib/branches/normalize.js#L37-L44).
