### ISSUE TITLE
22.0.8 doesn't support extending config from another workspace

### ISSUE THREAD

**Issue by bryanjtc** [semantic-release/semantic-release#3084]
### Current behavior

A new dependency was added to resolve an issue with windows paths in 22.0.8, import-from-esm. Now I have an error if I extend from a local config or a local package from another workspace.

### Expected behavior

No error

### `semantic-release` version

22.0.8

### CI environment

Gitlab

### `semantic-release` configuration

```js
/* eslint-disable import/no-extraneous-dependencies */
const { readFile } = require('fs');
const { join } = require('path');
const { promisify } = require('util');
const { gitmojis } = require('gitmojis');

/**
 * Read async file.
 */
const readFileAsync = promisify(readFile);

/**
 * Read template.
 */
const template = readFileAsync(join(__dirname, 'default-template.hbs'));
/**
 * Read commit template.
 */
const commitTemplate = readFileAsync(join(__dirname, 'commit-template.hbs'));

module.exports = {
  branches: ['dev'],
  plugins: [
    [
      require.resolve('semantic-release-gitmoji'),
      {
        releaseRules: {
          major: gitmojis.filter(({ semver }) => semver === 'major').map(({ code }) => code),
          minor: gitmojis.filter(({ semver }) => semver === 'minor').map(({ code }) => code),
          patch: gitmojis.filter(({ semver }) => semver === 'patch').map(({ code }) => code),
        },
        releaseNotes: {
          template,
          partials: { commitTemplate },
          helpers: {
            /**
             * Helper to group commits.
             * @param commits Commits.
             * @param options Helper options.
             * @returns Grouped commits.
             */
            groupCommits(commits, options) {
              /**
               * Get all commits.
               */
              const allCommits = Object.values(commits).flat();
              /**
               * Grouped commits.
               */
              let groupedCommits = {};

              allCommits
                .filter((commit) => commit !== undefined)
                .forEach((commit) => {
                  const gitmoji = gitmojis.find(
                    ({ emoji }) => emoji.localeCompare(commit.gitmoji) === 0,
                  );

                  if (gitmoji === undefined) {
                    return;
                  }

                  groupedCommits = {
                    ...groupedCommits,
                    [gitmoji.semver]: [...(groupedCommits[gitmoji.semver] || []), commit],
                  };
                });

              return options.fn(groupedCommits);
            },
          },
        },
      },
    ],
    require.resolve('@semantic-release/changelog'),
    [
      require.resolve('@semantic-release/exec'),
      {
        prepareCmd:
          // eslint-disable-next-line no-template-curly-in-string
          "yarn version ${nextRelease.version} && echo '::set-output name=version::${nextRelease.version}'",
        publishCmd: 'yarn npm publish --access public',
      },
    ],
    require.resolve('@tech-ayudinga/semantic-release-gitlab-cjs'),
    [
      require.resolve('@semantic-release/git'),
      {
        message:
          // eslint-disable-next-line no-template-curly-in-string
          '🚀 RELEASE: chore(release) - ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
      },
    ],
  ],
};
```

### CI logs

![Screenshot_20231201-223443_Brave](https://github.com/semantic-release/semantic-release/assets/49354825/14998384-f9ba-4dcb-8987-1cbb46ea8339)

**Comment by brummelte** [comment]
```
❯ DEBUG=import-from-esm yarn semantic-release
[3:40:45 PM] [semantic-release] › ℹ  Running semantic-release version 22.0.8
(node:4486) [MODULE_NOT_FOUND] Error: debug tried to access supports-color (a peer dependency) but it isn't provided by its ancestors; this makes the require call ambiguous and unsound.
(Use `node --trace-warnings ...` to show where the warning was created)
  import-from-esm Executing importFrom('/mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib', 'my-repository-with-release-config') +0ms
  import-from-esm 'my-repository-with-release-config' is not a file module +0ms
  import-from-esm Trying to resolve 'my-repository-with-release-config' from 'file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js' +1ms
  import-from-esm Failed to resolve 'my-repository-with-release-config' from 'file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'my-repository-with-release-config' imported from /mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js +2ms
  import-from-esm Trying to resolve 'my-repository-with-release-config.js' from 'file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'my-repository-with-release-config.js' from 'file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'my-repository-with-release-config.js' imported from /mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js +1ms
  import-from-esm Trying to resolve 'my-repository-with-release-config.mjs' from 'file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js' +1ms
  import-from-esm Failed to resolve 'my-repository-with-release-config.mjs' from 'file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'my-repository-with-release-config.mjs' imported from /mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js +1ms
  import-from-esm Trying to resolve 'my-repository-with-release-config.cjs' from 'file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'my-repository-with-release-config.cjs' from 'file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'my-repository-with-release-config.cjs' imported from /mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js +1ms
  import-from-esm Trying to resolve 'my-repository-with-release-config.json' from 'file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js' +0ms
  import-from-esm Failed to resolve 'my-repository-with-release-config.json' from 'file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'my-repository-with-release-config.json' imported from /mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/noop.js +2ms
  import-from-esm Cannot find module 'my-repository-with-release-config' +0ms
  import-from-esm Executing importFrom('/mnt/c/projects/current-repository', 'my-repository-with-release-config') +0ms
  import-from-esm 'my-repository-with-release-config' is not a file module +0ms
  import-from-esm Trying to resolve 'my-repository-with-release-config' from 'file:///mnt/c/projects/current-repository/noop.js' +0ms
  import-from-esm Failed to resolve 'my-repository-with-release-config' from 'file:///mnt/c/projects/current-repository/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'my-repository-with-release-config' imported from /mnt/c/projects/current-repository/noop.js +1ms
  import-from-esm Trying to resolve 'my-repository-with-release-config.js' from 'file:///mnt/c/projects/current-repository/noop.js' +1ms
  import-from-esm Failed to resolve 'my-repository-with-release-config.js' from 'file:///mnt/c/projects/current-repository/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'my-repository-with-release-config.js' imported from /mnt/c/projects/current-repository/noop.js +0ms
  import-from-esm Trying to resolve 'my-repository-with-release-config.mjs' from 'file:///mnt/c/projects/current-repository/noop.js' +1ms
  import-from-esm Failed to resolve 'my-repository-with-release-config.mjs' from 'file:///mnt/c/projects/current-repository/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'my-repository-with-release-config.mjs' imported from /mnt/c/projects/current-repository/noop.js +1ms
  import-from-esm Trying to resolve 'my-repository-with-release-config.cjs' from 'file:///mnt/c/projects/current-repository/noop.js' +0ms
  import-from-esm Failed to resolve 'my-repository-with-release-config.cjs' from 'file:///mnt/c/projects/current-repository/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'my-repository-with-release-config.cjs' imported from /mnt/c/projects/current-repository/noop.js +0ms
  import-from-esm Trying to resolve 'my-repository-with-release-config.json' from 'file:///mnt/c/projects/current-repository/noop.js' +1ms
  import-from-esm Failed to resolve 'my-repository-with-release-config.json' from 'file:///mnt/c/projects/current-repository/noop.js': Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'my-repository-with-release-config.json' imported from /mnt/c/projects/current-repository/noop.js +0ms
  import-from-esm Cannot find module 'my-repository-with-release-config' +0ms
[3:40:45 PM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot find module 'my-repository-with-release-config'
    at importFrom (file:///mnt/c/projects/current-repository/.yarn/cache/import-from-esm-npm-1.3.3-4c64f297d5-3f30a7bcce.zip/node_modules/import-from-esm/index.js:100:17)
    at async file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/get-config.js:36:85
    at async default (file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/get-config.js:34:11)
    at async Module.default (file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/index.js:271:34)
    at async default (file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/cli.js:55:5) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module 'my-repository-with-release-config'
    at importFrom (file:///mnt/c/projects/current-repository/.yarn/cache/import-from-esm-npm-1.3.3-4c64f297d5-3f30a7bcce.zip/node_modules/import-from-esm/index.js:100:17)
    at async file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/get-config.js:36:85
    at async default (file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/lib/get-config.js:34:11)
    at async Module.default (file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/index.js:271:34)
    at async default (file:///mnt/c/projects/current-repository/.yarn/cache/semantic-release-npm-22.0.8-d7a4b93b5a-5e82076661.zip/node_modules/semantic-release/cli.js:55:5) {
  code: 'MODULE_NOT_FOUND'
}%
```

**Comment by sheerlox** [comment]
@brummelte please provide more information about your setup. Your issue doesn't seem related to this one at first glance.

**Comment by brummelte** [comment]
semantic release 22.0.7 works, 22.0.8 doesn't.

Using yarn with
```
pnpFallbackMode: all
pnpMode: loose
```

**Comment by sheerlox** [comment]
Hey @bryanjtc, @brummelte.

Sorry for the delay, having very little free time lately. 

Could you please provide a minimum reproduction repository so I can look into these issues further?

That would be really appreciated. Thanks in advance!

**Comment by francoisauclair911** [comment]
@sheerlox  jumping in 
this is a minimum reproduction repository : https://github.com/francoisauclair911/semantic-extend-repro
Step to reproduce
`cd playground/`
`npx semantic-release`

error log
```[12:16:07 p.m.] [semantic-release] › ℹ  Running semantic-release version 23.0.2
[12:16:07 p.m.] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot find module '@adranetwork/semantic-release-preset'
    at importFrom (file:///Users/some-user/Code/changelog-playground/playground/node_modules/import-from-esm/index.js:100:17)
    at async file:///Users/some-user/Code/changelog-playground/playground/node_modules/semantic-release/lib/get-config.js:36:85
    at async default (file:///Users/some-user/Code/changelog-playground/playground/node_modules/semantic-release/lib/get-config.js:34:11)
    at async Module.default (file:///Users/some-user/Code/changelog-playground/playground/node_modules/semantic-release/index.js:274:34)
    at async default (file:///Users/some-user/Code/changelog-playground/playground/node_modules/semantic-release/cli.js:55:5) {
  code: 'MODULE_NOT_FOUND'
}
Error: Cannot find module '@adranetwork/semantic-release-preset'
    at importFrom (file:///Users/some-user/Code/changelog-playground/playground/node_modules/import-from-esm/index.js:100:17)
    at async file:///Users/some-user/Code/changelog-playground/playground/node_modules/semantic-release/lib/get-config.js:36:85
    at async default (file:///Users/some-user/Code/changelog-playground/playground/node_modules/semantic-release/lib/get-config.js:34:11)
    at async Module.default (file:///Users/some-user/Code/changelog-playground/playground/node_modules/semantic-release/index.js:274:34)
    at async default (file:///Users/some-user/Code/changelog-playground/playground/node_modules/semantic-release/cli.js:55:5) {
  code: 'MODULE_NOT_FOUND'
}%```

**Comment by sheerlox** [comment]
@francoisauclair911 thank you for providing that, I'll do my best to free some time in the next 48h hours to see what I can do!

**Comment by sheerlox** [comment]
@francoisauclair911 your problem is not related to this issue, which is specifically about yarn workspaces.

Your issue is that the top-level `package.json` declares `@adranetwork/semantic-release-preset` as a `module`, however, the content of `.releaserc.js` is CommonJS.

To resolve your issue, you should either convert your config to ESM, or change the extension to `.cjs` and update the `main` field of your `package.json`.

The error can be seen with `DEBUG=import-from=esm`, but since it should be more explicit about it without the debug flag, I've opened [an issue to track this](https://github.com/sheerlox/import-from-esm/issues/103). Thanks for reporting.

**Comment by brummelte** [comment]
My error was with just using yarn and not in a monorepo. Maybe it is a different problem, but the logs don't say anything relevant.

**Comment by sheerlox** [comment]
Thanks for providing a way for me to reproduce the error @bryanjtc, I'll try my best to tackle this issue in the coming weeks.

@brummelte I don't think the issue is with `semantic-release-monorepo`, probably because of yarn workspaces. I already tackled a similar issue end of December: https://github.com/sheerlox/import-from-esm/issues/80.

I'll dig deeper when I get the chance!

**Comment by brummelte** [comment]
I'm neither using semantic-release-monorepo, nor yarn workspaces, nor esm in the project that is not working anymore. Just yarn pnp and a shared semantic release config with common js.
