### ISSUE TITLE
moving release.config.js to .config folder not reading configuration correctly. version 23.0.0

### ISSUE THREAD

**Issue by coderatchet** [semantic-release/semantic-release#3157]
### Current behavior

When running a release, the config is not being picked up even though the breaking changes section says explicitly that i should move the `release.config.js` file into the `.config` folder.

with a file `.config/release.config.js` containing a branch configuration:

```javascript
module.exports = {
  branches: ['main'],
  // ...
}
```

When running `semantic-release`, it has an error saying it must have 1-3 release branches configured:

```
A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).

This may occur if your repository does not have a release branch, such as master.

Your configuration for the problematic branches is [].
```

To Reproduce:

Have a basic node library with a minimum `release.config.js` file in the .config folder and branches configured to ['main']

run the `semantic-release --dry-run` (with local repo and branches if necessary)

This works fine if the `release.config.js` file is in the project's root directory, which is also unexpected behaviour

### Expected behavior

Expect for the release to pick up the correct `.config/release.config.js` file as described in the [breaking-changes of version 23.0.0](https://github.com/semantic-release/semantic-release/releases/tag/v23.0.0)

### `semantic-release` version

23.0.0

### CI environment

buildkite

### Plugins used

commit-analyzer, release-notes-generator, npm, github, git

### `semantic-release` configuration

module.exports = {
  branches: ['main'],
  dryRun: false,
  repositoryUrl: 'https://github.com/XXX',
  plugins: [
    [
      '@semantic-release/commit-analyzer',
      {
        releaseRules: [{ type: 'chore', scope: 'deps', release: 'patch' }],
      },
    ],
    [
      '@semantic-release/release-notes-generator',
      {
        preset: 'conventionalcommits',
        presetConfig: {
          types: [
            { type: 'feat', section: 'Features' },
            { type: 'fix', section: 'Bug Fixes' },
            { type: 'build', section: 'Dependencies' },
            { type: 'chore', hidden: true },
            { type: 'docs', hidden: true },
            { type: 'style', hidden: true },
            { type: 'refactor', hidden: true },
            { type: 'perf', section: 'Performance Improvements' },
            { type: 'test', hidden: true },
            { type: 'ci', hidden: true },
          ],
        },
      },
    ],
    '@semantic-release/npm',
    '@semantic-release/github',
    [
      '@semantic-release/changelog',
      {
        changelogFile: 'CHANGELOG.md',
      },
    ],
    [
      '@semantic-release/git',
      {
        assets: ['package.json', 'yarn.lock', 'CHANGELOG.md'],
        message: 'chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
      },
    ],
  ],
};

### CI logs

ERELEASEBRANCHES The release branches are invalid in the `branches` configuration.
--
  | [2024-01-23T06:04:30Z] [ci:release] A minimum of 1 and a maximum of 3 release branches are required in the branches configuration (https://github.com/semantic-release/semantic-release/blob/master/docs/usage/configuration.md#branches).
  | [2024-01-23T06:04:30Z] [ci:release]
  | [2024-01-23T06:04:30Z] [ci:release] This may occur if your repository does not have a release branch, such as master.
  | [2024-01-23T06:04:30Z] [ci:release]
  | [2024-01-23T06:04:30Z] [ci:release] Your configuration for the problematic branches is [].
  | [2024-01-23T06:04:30Z] [ci:release]
  | [2024-01-23T06:04:30Z] [ci:release] AggregateError:
  | [2024-01-23T06:04:30Z] [ci:release]     SemanticReleaseError: The release branches are invalid in the `branches` configuration.
  | [2024-01-23T06:04:30Z] [ci:release]         at default (file:///opt/app/node_modules/semantic-release/lib/get-error.js:6:10)
  | [2024-01-23T06:04:30Z] [ci:release]         at file:///opt/app/node_modules/semantic-release/lib/branches/index.js:45:19
  | [2024-01-23T06:04:30Z] [ci:release]         at Array.reduce (<anonymous>)

**Comment by travi** [comment]
could you switch to using a `.releaserc.js` instead? if so, does that result in different behavior? this breaking change is the result of upgrading cosmiconfig, as mentioned in our release notes. could you raise an issue there to get a better understanding of what might be causing your issue?
