### ISSUE TITLE
Can't setup private repos

### ISSUE THREAD

**Issue by ByteDefault** [semantic-release/semantic-release#322]
When I try to setup with semantic-release a private Github repo and a private NPM repo I get the next error:

``` bash
? What CI are you using? Travis CI Pro
ERR! semantic-release Could not create Travis CI hook.
ERR! semantic-release Error: Travis encountered an error, sorry :(
ERR! semantic-release     at /Users/davidwells/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:49:30
ERR! semantic-release     at Request._callback (/Users/davidwells/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
ERR! semantic-release     at Request.self.callback (/Users/davidwells/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:148:22)
ERR! semantic-release     at emitTwo (events.js:87:13)
ERR! semantic-release     at Request.emit (events.js:172:7)
ERR! semantic-release     at Request.<anonymous> (/Users/davidwells/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:886:14)
ERR! semantic-release     at emitOne (events.js:82:20)
ERR! semantic-release     at Request.emit (events.js:169:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/Users/davidwells/.nvm/versions/node/v4.2.4/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/index.js:837:12)
ERR! semantic-release     at emitNone (events.js:72:20)
ERR! semantic-release  [Error: Travis encountered an error, sorry :(]
```

To workaround this problem I've tried manual configuration and it doesn't work for private repos because semantic-release tries to connect with travis-ci.org instead of travis-ci.com (which is the server for private repos).

Here's the error:

``` bash
$ npm run semantic-release
> @fsinvestments/trade-platform-web@ semantic-release /home/travis/build/FSInvestments/trade-platform-web
> semantic-release pre && npm publish && semantic-release post
[travis-after-all] Job succeeded (6187a2b66a2804035af859521998135d492f58a6b9900dc63b4efe5e847204b4)
[travis-after-all] Failed to parse JSON from "https://api.travis-ci.org/builds/33555304".
Error: Unexpected end of JSON input
semantic-release ERR! pre Failed to parse JSON from "https://api.travis-ci.org/builds/33555304".
semantic-release ERR! pre Error: Unexpected end of JSON input
npm ERR! Linux 3.13.0-40-generic
npm ERR! argv "/home/travis/.nvm/versions/node/v6.9.1/bin/node" "/home/travis/.nvm/versions/node/v6.9.1/bin/npm" "run" "semantic-release"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! @fsinvestments/trade-platform-web@ semantic-release: `semantic-release pre && npm publish && semantic-release post`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @fsinvestments/trade-platform-web@ semantic-release script 'semantic-release pre && npm publish && semantic-release post'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the @fsinvestments/trade-platform-web package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     semantic-release pre && npm publish && semantic-release post
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs @fsinvestments/trade-platform-web
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls @fsinvestments/trade-platform-web
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     /home/travis/build/FSInvestments/trade-platform-web/npm-debug.log
```

Probably this is related with this issue: https://github.com/semantic-release/semantic-release/issues/245

**Comment by terales** [comment]
Thanks for creating separate issue.

Root problem is [`travis-after-all`](https://github.com/alrra/travis-after-all) module, which is used in [`condition-travis`](https://github.com/semantic-release/condition-travis/blob/7f1eacb51117c9b4a736fb5c96b5b4613531e6d8/index.js#L1)

There is a pull request from 7th January :no_mouth: which hasn't merged yet: alrra/travis-after-all#15

Even if this PR will be merged somehow, then some modifications would be needed in the [`condition-travis` call of the `travis-after-all` module](https://github.com/semantic-release/condition-travis/blob/7f1eacb51117c9b4a736fb5c96b5b4613531e6d8/index.js#L46) and [in the list of known options](https://github.com/semantic-release/semantic-release/blob/a5cb9ea7f7a66657f95f0d913126e812adb6d9f8/bin/semantic-release.js#L18). So it won't be implemented in the next days, as I can see from current repository pulse.

**Comment by ByteDefault** [comment]
Ok, thank you for the info 😄 

Any possible workarounds?

**Comment by terales** [comment]
You can make changes yourself 😈, use it in production from yours repo and create PR. 

Also, try https://github.com/Netflix/unleash . It hasn't automatic builds, but it can do one-line manual releases like semantic-release does.

**Comment by boennemann** [comment]
Fixed via https://github.com/semantic-release/semantic-release/releases/tag/v6.3.2 and https://github.com/semantic-release/cli/releases/tag/v2.0.0
