### ISSUE TITLE
Publishing a GitHub release & triggering another workflow

### ISSUE THREAD

**Issue by Shereef** [semantic-release/semantic-release#3274]
### Current behavior

When a the tag is pushed it doesn't trigger other workflows

### Expected behavior

It triggers other workflows

### `semantic-release` version

23.0.8

### CI environment

Github Actions

### Plugins used

```
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "releaseRules": [
          {
            "type": "chore",
            "release": "patch"
          },
          {
            "type": "ci",
            "release": "patch"
          },
          {
            "type": "build",
            "release": "patch"
          },
          {
            "type": "docs",
            "release": "patch"
          },
          {
            "type": "refactor",
            "release": "patch"
          }
        ],
        "preset": "angular"
      }
    ],
    "@semantic-release/release-notes-generator",
    "@semantic-release/github",
    "@semantic-release/changelog",
    "@semantic-release/git",
    [
      "@semantic-release/exec",
      {
        "verifyReleaseCmd": "echo version=${nextRelease.version} >> $GITHUB_OUTPUT"
      }
    ]
  ]

```

### `semantic-release` configuration

https://github.com/Shereef/semantic-gha-trigger-tag/tree/master

### CI logs

```
Run npx semantic-release --debug --verbose
  npx semantic-release --debug --verbose
  shell: /usr/bin/bash -e {0}
  env:
    GITHUB_TOKEN: ***
[1[2](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:2):20:10 PM] [semantic-release] › ℹ  Running semantic-release version 2[3](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:3).0.8
2024-04-26T12:20:11.369Z semantic-release:config load config from: /home/runner/work/semantic-gha-trigger-tag/semantic-gha-trigger-tag/.releaserc
202[4](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:4)-04-26T12:20:11.377Z semantic-release:config options values: {
  branches: [ 'master' ],
  repositoryUrl: 'https://github.com/Shereef/semantic-gha-trigger-tag',
  tagFormat: 'v${version}',
  plugins: [
    [ '@semantic-release/commit-analyzer', [Object] ],
    '@semantic-release/release-notes-generator',
    '@semantic-release/github',
    '@semantic-release/changelog',
    '@semantic-release/git',
    [ '@semantic-release/exec', [Object] ]
  ],
  _: [],
  debug: true,
  verbose: true,
  '$0': '/opt/hostedtoolcache/node/20.12.2/x64/bin/semantic-release'
}
2024-04-26T12:20:11.936Z semantic-release:plugins options for @semantic-release/github/verifyConditions: {}
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
2024-04-26T12:20:11.937Z semantic-release:plugins options for @semantic-release/changelog/verifyConditions: {}
2024-04-26T12:20:11.937Z semantic-release:plugins options for @semantic-release/git/verifyConditions: {}
2024-04-26T12:20:11.938Z semantic-release:plugins options for @semantic-release/exec/verifyConditions: {
  verifyReleaseCmd: 'echo version=${nextRelease.version} >> $GITHUB_OUTPUT'
}
2024-04-26T12:20:11.939Z semantic-release:plugins options for @semantic-release/commit-analyzer/analyzeCommits: {
  releaseRules: [
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
    { type: 'chore', release: 'patch' },
    { type: 'ci', release: 'patch' },
    { type: 'build', release: 'patch' },
    { type: 'docs', release: 'patch' },
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
    { type: 'refactor', release: 'patch' }
  ],
  preset: 'angular'
}
2024-04-26T12:20:11.939Z semantic-release:plugins options for @semantic-release/exec/analyzeCommits: {
  verifyReleaseCmd: 'echo version=${nextRelease.version} >> $GITHUB_OUTPUT'
}
2024-04-26T12:20:11.939Z semantic-release:plugins options for @semantic-release/exec/verifyRelease: {
  verifyReleaseCmd: 'echo version=${nextRelease.version} >> $GITHUB_OUTPUT'
}
2024-04-26T12:20:11.940Z semantic-release:plugins options for @semantic-release/release-notes-generator/generateNotes: {}
2024-04-26T12:20:11.940Z semantic-release:plugins options for @semantic-release/exec/generateNotes: {
  verifyReleaseCmd: 'echo version=${nextRelease.version} >> $GITHUB_OUTPUT'
}
2024-04-26T12:20:11.941Z semantic-release:plugins options for @semantic-release/changelog/prepare: {}
2024-04-26T12:20:11.941Z semantic-release:plugins options for @semantic-release/git/prepare: {}
2024-04-26T12:20:11.942Z semantic-release:plugins options for @semantic-release/exec/prepare: {
  verifyReleaseCmd: 'echo version=${nextRelease.version} >> $GITHUB_OUTPUT'
}
2024-04-26T12:20:11.942Z semantic-release:plugins options for @semantic-release/github/publish: {}
2024-04-26T12:20:11.942Z semantic-release:plugins options for @semantic-release/exec/publish: {
  verifyReleaseCmd: 'echo version=${nextRelease.version} >> $GITHUB_OUTPUT'
}
2024-04-26T12:20:11.943Z semantic-release:plugins options for @semantic-release/github/addChannel: {}
2024-04-26T12:20:11.943Z semantic-release:plugins options for @semantic-release/exec/addChannel: {
  verifyReleaseCmd: 'echo version=${nextRelease.version} >> $GITHUB_OUTPUT'
}
2024-04-26T12:20:11.943Z semantic-release:plugins options for @semantic-release/github/success: {}
2024-04-26T12:20:11.943Z semantic-release:plugins options for @semantic-release/exec/success: {
  verifyReleaseCmd: 'echo version=${nextRelease.version} >> $GITHUB_OUTPUT'
}
2024-04-26T12:20:11.944Z semantic-release:plugins options for @semantic-release/github/fail: {}
2024-04-26T12:20:11.944Z semantic-release:plugins options for @semantic-release/exec/fail: {
  verifyReleaseCmd: 'echo version=${nextRelease.version} >> $GITHUB_OUTPUT'
}
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/exec"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[12:20:11 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
2024-04-26T12:20:11.963Z semantic-release:get-git-auth-url Verifying ssh auth by attempting to push to  https://github.com/Shereef/semantic-gha-trigger-tag
2024-04-26T12:20:12.101Z semantic-release:git Error: Command failed with exit code 128: git push --dry-run --no-verify https://github.com/Shereef/semantic-gha-trigger-tag HEAD:master
remote: Support for password authentication was removed on August 13, 2021.
remote: Please see https://docs.github.com/get-started/getting-started-with-git/about-remote-repositories#cloning-with-https-urls for information on currently recommended modes of authentication.
fatal: Authentication failed for 'https://github.com/Shereef/semantic-gha-trigger-tag/'
    at makeError (file:///opt/hostedtoolcache/node/20.12.2/x64/lib/node_modules/semantic-release/node_modules/execa/lib/error.js:60:11)
    at handlePromise (file:///opt/hostedtoolcache/node/20.12.2/x64/lib/node_modules/semantic-release/node_modules/execa/index.js:124:26)
    at process.processTicksAndRejections (node:internal/process/task_queues:9[5](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:5):5)
    at async verifyAuth (file:///opt/hostedtoolcache/node/20.12.2/x[6](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:7)4/lib/node_modules/semantic-release/lib/git.js:206:5)
    at async default (file:///opt/hostedtoolcache/node/20.12.2/x64/lib/node_modules/semantic-release/lib/get-git-auth-url.js:93:5)
    at async run (file:///opt/hostedtoolcache/node/20.12.2/x64/lib/node_modules/semantic-release/index.js:6[7](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:8):27)
    at async Module.default (file:///opt/hostedtoolcache/node/20.12.2/x64/lib/node_modules/semantic-release/index.js:278:22)
    at async default (file:///opt/hostedtoolcache/node/20.12.2/x64/lib/node_modules/semantic-release/cli.js:55:5)
2024-04-26T12:20:12.101Z semantic-release:get-git-auth-url SSH key auth failed, falling back to https.
2024-04-26T12:20:12.[8](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:9)15Z semantic-release:get-tags found tags for branch master: [ { gitTag: 'v1.0.0', version: '1.0.0', channels: [ null ] }, { gitTag: 'v1.0.1', version: '1.0.1', channels: [ null ] } ]
[12:20:12 PM] [semantic-release] › ✔  Run automated release from branch master on repository https://github.com/Shereef/semantic-gha-trigger-tag
[12:20:13 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[12:20:13 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[12:20:13 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://api.github.com)
[12:20:13 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[12:20:13 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[12:20:13 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[12:20:13 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[12:20:13 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[12:20:13 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/exec"
[12:20:13 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/exec"
[12:20:13 PM] [semantic-release] › ℹ  Found git tag v1.0.1 associated with version 1.0.1 on branch master
2024-04-26T12:20:13.043Z semantic-release:get-commits Use from: 702f355a0558fad8f7f8d33da2[9](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:10)c131085fd3fa7
[12:20:13 PM] [semantic-release] › ℹ  Found 2 commits since last release
2024-04-26T12:20:13.055Z semantic-release:get-commits Parsed commits: [ { commit: { long: 'f00c427f66fb4f8ca03ca04f9aa49a61c91bb2b4', short: 'f00c427' }, tree: { long: '399949641855517a5aeef0e17dbd520ace332c86', short: '3999496' }, author: { name: 'Shereef Marzouk', email: 'shereef.marzouk@daysmart.com', date: 2024-04-26T12:19:32.000Z }, committer: { name: 'Shereef Marzouk', email: 'shereef.marzouk@daysmart.com', date: 2024-04-26T12:19:37.000Z }, subject: 'ci: changed the trigger of the `Test` workflow', body: '', hash: 'f00c427f66fb4f8ca03ca04f9aa49a61c91bb2b4', committerDate: 2024-04-26T12:19:37.000Z, message: 'ci: changed the trigger of the `Test` workflow', gitTags: '(HEAD -> master, origin/master)' }, { commit: { long: '3289edacd9ffd0d4e8e1252195aa1234448edc24', short: '3289eda' }, tree: { long: '71a1a07b83804e81aee3ca84f8cf70fe62d709c3', short: '71a1a07' }, author: { name: 'Shereef Marzouk', email: 'shereef.marzouk@daysmart.com', date: 2024-04-26T12:18:59.000Z }, committer: { name: 'Shereef Marzouk', email: 'shereef.marzouk@daysmart.com', date: 2024-04-26T12:19:37.000Z }, subject: 'bug: fixed the text showing on the same line', body: '', hash: '3289edacd9ffd0d4e8e1252195aa1234448edc24', committerDate: 2024-04-26T12:19:37.000Z, message: 'bug: fixed the text showing on the same line', gitTags: '' } ]
[12:20:13 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:20:13 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: ci: changed the trigger of the `Test` workflow
2024-04-26T12:20:13.063Z semantic-release:commit-analyzer Analyzing with custom rules
2024-04-26T12:20:13.065Z semantic-release:commit-analyzer The rule { type: 'ci', release: 'patch' } match commit with release type 'patch'
2024-04-26T12:20:13.065Z semantic-release:commit-analyzer Analyzing with custom rules
[12:20:13 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is patch
[12:20:13 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: bug: fixed the text showing on the same line
2024-04-26T12:20:13.066Z semantic-release:commit-analyzer Analyzing with default rules
[12:20:13 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[12:20:13 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 2 commits complete: patch release
[12:20:13 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[12:20:13 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/exec"
[12:20:13 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/exec"
[12:20:13 PM] [semantic-release] › ℹ  The next release version is 1.0.2
[12:20:13 PM] [semantic-release] › ℹ  Start step "verifyRelease" of plugin "@semantic-release/exec"
[12:20:13 PM] [semantic-release] [@semantic-release/exec] › ℹ  Call script echo version=1.0.2 >> $GITHUB_OUTPUT
[12:20:13 PM] [semantic-release] › ✔  Completed step "verifyRelease" of plugin "@semantic-release/exec"
[12:20:13 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2024-04-26T12:20:13.085Z semantic-release:release-notes-generator version: '1.0.2'
2024-04-26T12:20:13.085Z semantic-release:release-notes-generator host: undefined
2024-04-26T12:20:13.085Z semantic-release:release-notes-generator owner: 'Shereef'
2024-04-26T12:20:13.085Z semantic-release:release-notes-generator repository: 'semantic-gha-trigger-tag'
2024-04-26T12:20:13.085Z semantic-release:release-notes-generator previousTag: 'v1.0.1'
2024-04-26T12:20:13.085Z semantic-release:release-notes-generator currentTag: 'v1.0.2'
2024-04-26T12:20:13.085Z semantic-release:release-notes-generator host: 'https://github.com'
2024-04-26T12:20:13.085Z semantic-release:release-notes-generator linkReferences: undefined
2024-04-26T12:20:13.085Z semantic-release:release-notes-generator issue: 'issues'
2024-04-26T12:20:13.085Z semantic-release:release-notes-generator commit: 'commit'
[12:20:13 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:20:13 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/exec"
[12:20:13 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/exec"
[12:20:13 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/changelog"
[12:20:13 PM] [semantic-release] [@semantic-release/changelog] › ℹ  Update /home/runner/work/semantic-gha-trigger-tag/semantic-gha-trigger-tag/CHANGELOG.md
[12:20:13 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/changelog"
[12:20:13 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/git"
[12:20:13 PM] [semantic-release] [@semantic-release/git] › ℹ  Found 1 file(s) to commit
2024-04-26T12:20:13.130Z semantic-release:git add file to git index {
  command: 'git add --force --ignore-errors CHANGELOG.md',
  escapedCommand: 'git add --force --ignore-errors CHANGELOG.md',
  exitCode: 0,
  stdout: '',
  stderr: '',
  all: undefined,
  failed: false,
  timedOut: false,
  isCanceled: false,
  killed: false
}
2024-04-26T12:20:13.130Z semantic-release:git commited files: [ 'CHANGELOG.md' ]
[12:20:13 PM] [semantic-release] [@semantic-release/git] › ℹ  Prepared Git release: v1.0.2
[12:20:13 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/git"
[12:20:13 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
2024-04-26T12:20:13.787Z semantic-release:release-notes-generator version: '1.0.2'
2024-04-26T12:20:13.787Z semantic-release:release-notes-generator host: undefined
2024-04-26T12:20:13.787Z semantic-release:release-notes-generator owner: 'Shereef'
2024-04-26T12:20:13.787Z semantic-release:release-notes-generator repository: 'semantic-gha-trigger-tag'
2024-04-26T12:20:13.787Z semantic-release:release-notes-generator previousTag: 'v1.0.1'
2024-04-26T12:20:13.787Z semantic-release:release-notes-generator currentTag: 'v1.0.2'
2024-04-26T12:20:13.787Z semantic-release:release-notes-generator host: 'https://github.com'
2024-04-26T12:20:13.787Z semantic-release:release-notes-generator linkReferences: undefined
2024-04-26T12:20:13.787Z semantic-release:release-notes-generator issue: 'issues'
2024-04-26T12:20:13.787Z semantic-release:release-notes-generator commit: 'commit'
[12:20:13 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[12:20:13 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/exec"
[12:20:13 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/exec"
[12:20:13 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/exec"
[12:20:13 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/exec"
[12:20:15 PM] [semantic-release] › ✔  Created tag v1.0.2
[12:20:15 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
2024-04-26T12:20:15.120Z semantic-release:github release object: {
  owner: 'Shereef',
  repo: 'semantic-gha-trigger-tag',
  tag_name: 'v1.0.2',
  target_commitish: 'master',
  name: 'v1.0.2',
  body: '## [1.0.2](https://github.com/Shereef/semantic-gha-trigger-tag/compare/v1.0.1...v1.0.2) (2024-04-26)\n' +
    '\n' +
    '\n' +
    '\n',
  prerelease: false
}
[[12](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:13):20:15 PM] [semantic-release] [@semantic-release/github] › ℹ  Published GitHub release: https://github.com/Shereef/semantic-gha-trigger-tag/releases/tag/v1.0.2
[12:20:[15](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:16) PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/github"
[12:20:15 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/exec"
[12:20:15 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/exec"
[12:20:15 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
2024-04-26T12:20:[17](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:18).783Z semantic-release:github found pull requests: []
2024-04-26T12:[20](https://github.com/Shereef/semantic-gha-trigger-tag/actions/runs/8848128169/job/24297352007#step:5:21):17.784Z semantic-release:github found issues via comments: []
2024-04-26T12:20:17.915Z semantic-release:github found semantic-release issues: []
[12:20:17 PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/github"
[12:20:17 PM] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/exec"
[12:20:17 PM] [semantic-release] › ✔  Completed step "success" of plugin "@semantic-release/exec"
[12:20:17 PM] [semantic-release] › ✔  Published release 1.0.2 on default channel
```

**Comment by travi** [comment]
please avoid spamming semantic-release repos with support requests that are beyond the scope of semantic-release. you've already posted multiple requests for help in the [discussion thread](https://github.com/semantic-release/semantic-release/discussions/1906#discussioncomment-9236615). 

unfortunately, we do not have the bandwidth to provide support. all of the details related to the parts semantic-release plays in the process are already answered in the thread you already found. semantic-release is successfully pushing the tag in your example repo. the fact that your other workflows are not triggered is beyond the scope of semantic-release and we ask that you please seek support about github actions through proper support channels
