### ISSUE TITLE
An error occurred while running semantic-release: Error: Cannot find module `@semantic-release/changelog`

### ISSUE THREAD

**Issue by AbdUlHamedMaree** [semantic-release/semantic-release#3285]
### Current behavior

Whenever I try to use `npx semantic-release` it failed and throws error about not finding `@semantic-release/changelog`,

it started yesterday and before that it was working fine.

### Expected behavior

running `npx semantic-release` doesn't throws error about not finding `@semantic-release/changelog`

### `semantic-release` version

^23.0.8

### CI environment

GitHub Actions, GitHub act

### Plugins used

```js
[
  '@semantic-release/commit-analyzer',
  '@semantic-release/release-notes-generator',
  '@semantic-release/changelog',
  '@sebbo2002/semantic-release-jsr',
  '@semantic-release/npm',
  '@semantic-release/github',
  '@semantic-release/git',
];
```

### `semantic-release` configuration

```js
/**@type {import('semantic-release').GlobalConfig} */
module.exports = {
  branches: ['main'],
  plugins: [
    '@semantic-release/commit-analyzer',
    '@semantic-release/release-notes-generator',
    [
      '@semantic-release/changelog',
      {
        changelogFile: 'CHANGELOG.md',
      },
    ],
    '@sebbo2002/semantic-release-jsr',
    '@semantic-release/npm',
    '@semantic-release/github',
    [
      '@semantic-release/git',
      {
        assets: ['CHANGELOG.md', 'package.json', 'bun.lockb'],
        message:
          'chore(release): set `package.json` to ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}',
      },
    ],
  ],
};
```

### CI logs

```
[4:53:45 AM] [semantic-release] › ℹ  Running semantic-release version 23.0.8
[4:53:45 AM] [semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot find module '@semantic-release/changelog'
Require stack:
- /home/runner/work/lbundle/lbundle/noop.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:[11](https://github.com/AbdUlHamedMaree/lbundle/actions/runs/8953132417/job/24596896674#step:9:12)43:15)
    at resolveFileName (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:46:47)
    at loadPlugin (file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/utils.js:59:54)
    at file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:18:43
    at async file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:15:29
    at async file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:15:29
    at async file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:15:29
    at async file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:15:29 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/lbundle/lbundle/noop.js' ]
}
Error: Cannot find module '@semantic-release/changelog'
Require stack:
- /home/runner/work/lbundle/lbundle/noop.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1[14](https://github.com/AbdUlHamedMaree/lbundle/actions/runs/8953132417/job/24596896674#step:9:15)3:15)
    at resolveFileName (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/resolve-from/index.js:46:47)
    at loadPlugin (file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/utils.js:59:54)
    at file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:18:43
    at async file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:[15](https://github.com/AbdUlHamedMaree/lbundle/actions/runs/8953132417/job/24596896674#step:9:16):29
    at async file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:15:29
    at async file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:15:29
    at async file:///home/runner/.npm/_npx/cdf31b77322f1d44/node_modules/semantic-release/lib/plugins/index.js:15:29 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/runner/work/lbundle/lbundle/noop.js' ]
}
Error: Process completed with exit code 1.
```

**Comment by AbdUlHamedMaree** [comment]
this is the action that [failed](https://github.com/AbdUlHamedMaree/lbundle/actions/runs/8953132417/job/24596896674) yesterday, and [this working](https://github.com/AbdUlHamedMaree/lbundle/actions/runs/8940423725/job/24558510814) one from the day before,

both of them uses the same version of `semantic-release`, but the second one failed.

**Comment by AbdUlHamedMaree** [comment]
removed `bun.lockb` and reinstall fixed the issue, seems bun isn't updating `bun.lockb` sometimes

**Comment by 1xtr** [comment]
I have same issue but I don't have Bun
