### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by wassimbensalem** [semantic-release/semantic-release#3299]
### Current behavior

I am setting semantic release for all my projects through a gitlab CI/CD pipeline. Currently I am facing an "error occurred while running semantic-release: RangeError: Invalid time value". Any ideas why? I ve been using semantic release since a long time and never faced this error. I appreciate any help!
My CI/CD Job:
`release_job:
  tags:
    - $RUNNER_TAGS
  image: node:lts-buster-slim
  stage: changelog_release
  before_script: []
  script:
    - apt-get update && apt-get install -y --no-install-recommends git-core ca-certificates
    - npm install -g semantic-release@22.0.12 @semantic-release/git @semantic-release/gitlab @semantic-release/changelog conventional-changelog-conventionalcommits
    - semantic-release
  when: manual
  extends:
    .on_merge`

### Expected behavior

Normaly it should trigger the release smoothly.

### `semantic-release` version

22.0.12 

### CI environment

generateNotes

### `semantic-release` configuration

{
    "branches": ["main", "next"],
    "plugins": [
        [
            "@semantic-release/commit-analyzer", {
                "preset": "angular",
                "releaseRules": [
                {
                    "type": "build",
                    "release": false
                },
                {
                    "type": "ci",
                    "release": false
                },
                {
                    "type": "docs",
                    "release": false
                },
                {
                    "type": "feat",
                    "release": "minor"
                },
                {
                    "type": "fix",
                    "release": "patch"
                },
                {
                    "type": "perf",
                    "release": "patch"
                },
                {
                    "type": "refactor",
                    "release": "patch"
                },
                {
                    "type": "test",
                    "release": false
                }
                ],
                "parserOpts": {
                "noteKeywords": ["BREAKING CHANGE", "BREAKING CHANGES"]
                    }
            }
        ],
        [
        "@semantic-release/release-notes-generator", {
                "preset": "conventionalcommits"
            }
        ], 
        [ 
            "@semantic-release/changelog",
            {
                "changelogTitle": "# Changelog\n\nAll notable changes to this project will be documented in this file. See\n[Conventional Commits](https://conventionalcommits.org) for commit guidelines."
            }
        ],
        [
            "@semantic-release/git",
            {
                "message": "chore: Release ${nextRelease.version}\n\n${nextRelease.notes}"
            }
        ]
    ]
}

### CI logs

semantic-release
[8:57:01 AM] [semantic-release] › ℹ  Running semantic-release version 22.0.12
[8:57:01 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[8:57:01 AM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[8:57:01 AM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[8:57:01 AM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[8:57:01 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[8:57:01 AM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[8:57:04 AM] [semantic-release] › ✔  Run automated release from branch main on repository [https://gitlab-ci-token:[secure]@gitlab.com/compredict/ml/packages/optimization-library.git](https://gitlab-ci-token:%5Bsecure%5D@gitlab.com/compredict/ml/packages/optimization-library.git)
[8:57:05 AM] [semantic-release] › ✔  Allowed to push to the Git repository
[8:57:05 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/changelog"
[8:57:05 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/changelog"
[8:57:05 AM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/git"
[8:57:05 AM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/git"
[8:57:05 AM] [semantic-release] › ℹ  Found git tag v1.3.0 associated with version 1.3.0 on branch main
[8:57:05 AM] [semantic-release] › ℹ  Found 8 commits since last release
[8:57:05 AM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: read releaserc config from file directly
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: change semantic release version
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: change date format in release job
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: add releaserc as env variable
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: test: empty commit
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: test: revert to old release file
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: test: remove releaserc file creation from pipeline
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: Adding support for raytune checkpoints.
closes #86bykvtuf[Done]
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[8:57:05 AM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 8 commits complete: minor release
[8:57:05 AM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[8:57:05 AM] [semantic-release] › ℹ  The next release version is 1.4.0
[8:57:05 AM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[8:57:05 AM] [semantic-release] › ✘  Failed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[8:57:05 AM] [semantic-release] › ✘  An error occurred while running semantic-release: RangeError: Invalid time value
    at committerDate (/usr/local/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/index.js:80:30)
    at /usr/local/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/lib/util.js:202:17
    at Array.forEach (<anonymous>)
    at processCommit (/usr/local/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/lib/util.js:198:31)
    at /usr/local/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/index.js:123:32 {
  pluginName: '@semantic-release/release-notes-generator'
}
RangeError: Invalid time value
    at committerDate (/usr/local/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/index.js:80:30)
    at /usr/local/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/lib/util.js:202:17
    at Array.forEach (<anonymous>)
    at processCommit (/usr/local/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/lib/util.js:198:31)
    at /usr/local/lib/node_modules/semantic-release/node_modules/conventional-changelog-writer/index.js:123:32 {
  pluginName: '@semantic-release/release-notes-generator'
}

**Comment by Joseminosa** [comment]
Same problem

**Comment by MrGadget1024** [comment]
see https://github.com/semantic-release/release-notes-generator/issues/633

**Comment by travi** [comment]
thank you for providing guidance @MrGadget1024 

closing in favor of the linked issue
