### ISSUE TITLE
After using semantic release version 24.0.0 getting error  An error occurred while running semantic-release: TypeError: this is not a Date object. 

### ISSUE THREAD

**Issue by Gokul19797** [semantic-release/semantic-release#3392]
### Current behavior
```
[4:22:43 AM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: this is not a Date object.
    at Proxy.valueOf (<anonymous>)
    at [Symbol.toPrimitive] (<anonymous>)
    at Proxy.toJSON (<anonymous>)
    at JSON.stringify (<anonymous>)
    at stringify (file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/utils.js:46:17)
    at getTemplateContext (file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/context.js:111:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/template.js:73:33
    at async write (file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/writers.js:72:18)
    at async nextAsync (node:internal/streams/from:182:33) {
  pluginName: '@semantic-release/release-notes-generator'
}
```

### Expected behavior

2024-07-17T04:30:16.8061382Z [4:30:16 AM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"

### `semantic-release` version

24.0.0

### CI environment

Azure semver using semver.yaml configuration

### Plugins used

 "@semantic-release/release-notes-generator",
  "@semantic-release/github",
    "@semantic-release/commit-analyzer"

### `semantic-release` configuration

can't specify

### CI logs
```
[4:22:43 AM] [semantic-release] › ✘  An error occurred while running semantic-release: TypeError: this is not a Date object.
    at Proxy.valueOf (<anonymous>)
    at [Symbol.toPrimitive] (<anonymous>)
    at Proxy.toJSON (<anonymous>)
    at JSON.stringify (<anonymous>)
    at stringify (file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/utils.js:46:17)
    at getTemplateContext (file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/context.js:111:46)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/template.js:73:33
    at async write (file:///home/vsts/.npm/_npx/cdf31b77322f1d44/node_modules/conventional-changelog-writer/dist/writers.js:72:18)
    at async nextAsync (node:internal/streams/from:182:33) {
  pluginName: '@semantic-release/release-notes-generator'
}
```

**Comment by novohit** [comment]
I have same problem

**Comment by nsgpriyanshu** [comment]
Have you updated your `conventional-changelog` packages?

**Comment by serhiykrupka** [comment]
faced with same issue

**Comment by drackp2m** [comment]
The same error happens to me using version ^24.2.0, downgrade to ^23.0.0 fix the problem.

@nsgpriyanshu what do you mean by updating `conventional-changelog` packages?

In fact, the only related package I use is `conventional-changelog-conventionalcommits`, targeting to ^8.0.0

**Comment by nsgpriyanshu** [comment]
Use `cliff-jumper` package.

**Comment by kunal-saini** [comment]
any workaround for it? thanks!

**Comment by travi** [comment]
closing in favor of #3571
