### ISSUE TITLE
`git push --dry-run --no-verify` fails "branch tip is behind its remote"

### ISSUE THREAD

**Issue by davidnormo** [semantic-release/semantic-release#3437]
### Current behavior

When semantic-release runs `verifyAuth` it does a push. This may fail if master is behind origin/master - e.g. if multiple merges to master happen in quick succession.

### Expected behavior

I don't believe `verifyAuth` should fail in this scenario as it should just be trying to work out if the user is authorised to make changes to remote. I would expect semantic-release be able to verify auth even if the current master is behind origin/master.

Would it make sense to update `verifyAuth` to push tags only (`--tags`) so as not to conflict with changes on remote?

### `semantic-release` version

24.1.0

### CI environment

gitlab

### Plugins used

@semantic-release/commit-analyzer
@semantic-release/release-notes-generator
@semantic-release/gitlab
@semantic-release/npm

### `semantic-release` configuration

```js
const { parserOpts, releaseRules } = require('./commit-parser-opts.js');

module.exports = {
    repositoryUrl: '[redacted]',
    branch: 'master',
    plugins: [
        [
            '@semantic-release/commit-analyzer',
            {
                releaseRules,
                parserOpts
            }
        ],
        [
            '@semantic-release/release-notes-generator',
            {
                parserOpts
            }
        ],
        '@semantic-release/gitlab',
        [
            '@semantic-release/npm',
            {
                tarballDir: 'dist',
                npmPublish: false
            }
        ]
    ],
    ci: true,
    debug: false
};

```

### CI logs

```
2024-09-05T10:03:04.662Z semantic-release:git ExecaError: Command failed with exit code 1: git push --dry-run --no-verify 'https://gitlab-ci-token:[secure]@gitlab.[redacted]/[redacted]/[redacted].git' 'HEAD:master'
To https://gitlab.[redacted]/[redacted]/[redacted].git
 ! [rejected]            HEAD -> master (non-fast-forward)
error: failed to push some refs to 'https://gitlab.[redacted]/[redacted]/[redacted].git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
    at getFinalError (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/return/result.js:108:16)
    at getAsyncResult (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/methods/main-async.js:167:4)
    at handlePromise (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/methods/main-async.js:150:17)
    at async verifyAuth (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/git.js:206:5)
    at async ensureValidAuthUrl (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/get-git-auth-url.js:43:5)
    at async Promise.all (index 1)
    at async default (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/get-git-auth-url.js:114:35)
    at async run (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/index.js:67:27)
    at async Module.default (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/index.js:278:22)
2024-09-05T10:03:04.662Z semantic-release:get-git-auth-url ExecaError: Command failed with exit code 1: git push --dry-run --no-verify 'https://gitlab-ci-token:[secure]@gitlab.[redacted]/[redacted]/[redacted].git' 'HEAD:master'
To https://gitlab.[redacted]/[redacted]/[redacted].git
 ! [rejected]            HEAD -> master (non-fast-forward)
error: failed to push some refs to 'https://gitlab.[redacted]/[redacted]/[redacted].git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
    at getFinalError (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/return/result.js:108:16)
    at getAsyncResult (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/methods/main-async.js:167:4)
    at handlePromise (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/methods/main-async.js:150:17)
    at async verifyAuth (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/git.js:206:5)
    at async ensureValidAuthUrl (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/get-git-auth-url.js:43:5)
    at async Promise.all (index 1)
    at async default (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/get-git-auth-url.js:114:35)
    at async run (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/index.js:67:27)
    at async Module.default (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/index.js:278:22)
2024-09-05T10:03:04.665Z semantic-release:git ExecaError: Command failed with exit code 1: git push --dry-run --no-verify 'https://gitlab-ci-token:[secure]@gitlab.[redacted]/[redacted]/[redacted].git' 'HEAD:master'
To https://gitlab.[redacted]/[redacted]/[redacted].git
 ! [rejected]            HEAD -> master (non-fast-forward)
error: failed to push some refs to 'https://gitlab.[redacted]/[redacted]/[redacted].git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
    at getFinalError (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/return/result.js:108:16)
    at getAsyncResult (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/methods/main-async.js:167:4)
    at handlePromise (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/methods/main-async.js:150:17)
    at async verifyAuth (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/git.js:206:5)
    at async ensureValidAuthUrl (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/get-git-auth-url.js:43:5)
    at async Promise.all (index 0)
    at async default (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/get-git-auth-url.js:114:35)
    at async run (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/index.js:67:27)
    at async Module.default (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/index.js:278:22)
2024-09-05T10:03:04.665Z semantic-release:get-git-auth-url ExecaError: Command failed with exit code 1: git push --dry-run --no-verify 'https://gitlab-ci-token:[secure]@gitlab.[redacted]/[redacted]/[redacted].git' 'HEAD:master'
To https://gitlab.[redacted]/[redacted]/[redacted].git
 ! [rejected]            HEAD -> master (non-fast-forward)
error: failed to push some refs to 'https://gitlab.[redacted]/[redacted]/[redacted].git'
hint: Updates were rejected because a pushed branch tip is behind its remote
hint: counterpart. Check out this branch and integrate the remote changes
hint: (e.g. 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
    at getFinalError (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/return/final-error.js:6:9)
    at makeError (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/return/result.js:108:16)
    at getAsyncResult (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/methods/main-async.js:167:4)
    at handlePromise (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/node_modules/execa/lib/methods/main-async.js:150:17)
    at async verifyAuth (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/git.js:206:5)
    at async ensureValidAuthUrl (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/get-git-auth-url.js:43:5)
    at async Promise.all (index 0)
    at async default (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/lib/get-git-auth-url.js:114:35)
    at async run (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/index.js:67:27)
    at async Module.default (file:///builds/[redacted]/[redacted]/node_modules/semantic-release/index.js:278:22)
```

**Comment by davidnormo** [comment]
Related: #793 #821

**Comment by babblebey** [comment]
Hey @davidnormo,

Thanks for reporting this case. I have given the approach a shot and I think it will work just fine seating in the context of just `write` permission check. Dry run pushing a tag.

```sh
git push --dry-run [REPO_URL] --tags
```

This means we can simulate pushing a git tag to repo instead of a change to a branch. But kindly note, the check is done against a specific branch/ref which signifies a write check against the specific branch like so...

```sh
git push --dry-run --no-verify [REPO_URL] HEAD:[BRANCH_NAME]
```

...doing the dry tag push helps check `write` permission on the entire repo removing the lens from the specific branch.... for this reason I'm very interested in the thought behind why the check was intentionally scoped to specific branch/ref instead of just the repo in the first place,.

🤔

**Comment by travi** [comment]
> I don't believe `verifyAuth` should fail in this scenario as it should just be trying to work out if the user is authorised to make changes to remote. I would expect semantic-release be able to verify auth even if the current master is behind origin/master.

i agree that this should not fail, ideally. i'm supportive of a change that would improve this situation. however, keep in mind that semantic-release will not move forward with a release when behind the remote because that would prevent actions that depend on releasing from the tip of the release branch (like making commits with the git plugin) a problem. just highlighting that the overall situation when attempting to release when the pipeline tip is behind the remote would still result in not releasing.

**Comment by davidnormo** [comment]
Thanks for pointing that out @travi - in my case there's no new commit, just a git tag so it should still be able to push even through behind - I hope

**Comment by travi** [comment]
Because we cannot know what actions are performed by plugging configured within a project, semantic-release will not release when behind the remote. While it does delay things slightly, the build triggered by the push that made it behind will do the release instead

**Comment by trp-dave-normington** [comment]
Oh dear. In our case, we have some commits that are added that don't kickoff another CI pipeline. Perhaps we could we add a config option to push anyway in this scenario?

**Comment by davidnormo** [comment]
Oh dear. In our case, we have some commits that are added that don't kickoff another CI pipeline. Perhaps we could we add a config option to push anyway in this scenario?
