### ISSUE TITLE
tagFormat template reports nextRelease.version not defined (${verison} also undefined)

### ISSUE THREAD

**Issue by warrenronsiek** [semantic-release/semantic-release#3458]
### Current behavior

Semantic release fails with an error saying that the version template variable is not defined. This happens whether you use `"${version}"` or `"${nextRelease.version}"`.  

### Expected behavior

Runs normally.

### `semantic-release` version

24.1.1

### CI environment

circle ci

### Plugins used
```
    "@semantic-release/changelog": "6.0.3",
    "@semantic-release/commit-analyzer": "13.0.0",
    "@semantic-release/exec": "6.0.3",
    "@semantic-release/git": "10.0.1",
    "@semantic-release/npm": "12.0.1",
    "@semantic-release/release-notes-generator": "14.0.1",
```
### `semantic-release` configuration
```
{
  "branches": [
    {
      "name": "master",
      "tagFormat": "v${nextRelease.version}"
    },
    {
      "name": "dev",
      "prerelease": true,
      "tagFormat": "dev-v${nextRelease.version}"
    }
  ],
  "plugins": [
    [
      "@semantic-release/commit-analyzer",
      {
        "preset": "conventionalcommits",
        "releaseRules": [
          {
            "scope": "docs",
            "release": false
          },
          {
            "type": "feat",
            "release": "minor"
          },
          {
            "scope": "ci",
            "release": false
          },
          {
            "type": "ci",
            "release": false
          },
          {
            "type": "fix",
            "release": "minor"
          },
          {
            "scope": "build",
            "release": "patch"
          },
          {
            "type": "perf",
            "release": "patch"
          },
          {
            "type": "test",
            "release": false
          },
          {
            "scope": "test",
            "release": false
          },
          {
            "type": "refactor",
            "release": "patch"
          },
          {
            "scope": "no-release",
            "release": false
          }
        ]
      }
    ],
    "@semantic-release/release-notes-generator",
    "@semantic-release/changelog",
    [
      "@semantic-release/npm",
      {
        "npmPublish": false
      }
    ],
    [
      "@semantic-release/exec",
      {
        "prepareCmd": "node versionUpdate.js"
      }
    ],
    [
      "@semantic-release/git",
      {
        "assets": [
          "package.json",
          "CHANGELOG.md",
          "windows/ChronoKeep/Package.appxmanifest",
          "macos/ChronoKeep-macOS/Info.plist"
        ],
        "message": "task(release): ${nextRelease.version} \n\n${nextRelease.notes}"
      }
    ],
    [
      "@semantic-release/github",
      {
        "assets": [
          "CHANGELOG.md"
        ]
      }
    ]
  ]
}
```

### CI logs
```
npx semantic-release --dry-run
[8:34:44 PM] [semantic-release] › ℹ  Running semantic-release version 24.1.1
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/exec"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/git"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/exec"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "verifyRelease" from "@semantic-release/exec"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/exec"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/exec"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/git"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/exec"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/npm"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/exec"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "addChannel" from "@semantic-release/github"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/exec"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/exec"
[8:34:44 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[8:34:45 PM] [semantic-release] › ✘  An error occurred while running semantic-release: ReferenceError: nextRelease is not defined
    at eval (eval at <anonymous> (file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/lodash-es/template.js:259:12), <anonymous>:8:10)
    at file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/semantic-release/lib/branches/expand.js:13:89
    at file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/lodash-es/mapValues.js:38:34
    at file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/lodash-es/_createBaseFor.js:17:11
    at baseForOwn (file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/lodash-es/_baseForOwn.js:13:20)
    at mapValues (file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/lodash-es/mapValues.js:37:3)
    at file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/semantic-release/lib/branches/expand.js:13:12
    at Array.map (<anonymous>)
    at file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/semantic-release/lib/branches/expand.js:11:93
    at Array.reduce (<anonymous>)
ReferenceError: nextRelease is not defined
    at eval (eval at <anonymous> (file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/lodash-es/template.js:259:12), <anonymous>:8:10)
    at file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/semantic-release/lib/branches/expand.js:13:89
    at file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/lodash-es/mapValues.js:38:34
    at file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/lodash-es/_createBaseFor.js:17:11
    at baseForOwn (file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/lodash-es/_baseForOwn.js:13:20)
    at mapValues (file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/lodash-es/mapValues.js:37:3)
    at file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/semantic-release/lib/branches/expand.js:13:12
    at Array.map (<anonymous>)
    at file:///Users/warrenronsiek/Projects/ChronoKeep/node_modules/semantic-release/lib/branches/expand.js:11:93
```

**Comment by babblebey** [comment]
Hi @warrenronsiek,

Thanks for reporting this! From the looks of your config, it appears the error is just as expected. Here's why...

- important to state that the `tagFormat` is NOT a valid config property under the `branches` interface in semantic-release config options (it is instead a stand-alone config property see [`tagFormat`](https://semantic-release.gitbook.io/semantic-release/usage/configuration#tagformat)), the following properties are the available ones under the `branches` 

```js
{
    /**
     * The name of git branch.
     */
    name: string;

    /**
     * The distribution channel on which to publish releases from this
     * branch.
     */
    channel?: string | false | undefined;

    /**
     * The range of [semantic versions](https://semver.org/) to support on
     */
    range?: string | undefined;

    /**
     * The pre-release identifier to append to [semantic versions](https://semver.org/)
     * released from this branch.
     */
    prerelease?: string | boolean | undefined;
}
```
- the `nextRelease` is a property on the `result` object which is only available/defined after a release as been published in the release lifecycle; this means the `nextRelease` is undefined at your point of consumption in the config. learn more at https://semantic-release.gitbook.io/semantic-release/developer-guide/js-api#result
- the `version` variable doesn't exist within any config property except in `tagFormat` 

### USING `tagFormat` CORRECTLY

The `tagFormat` (as previously stated) is on its own a config option property, meaning you configure it in the same level as other semantic-release configuration properties such `branches`, `plugins`, `extends` etc... and that is where the `version` variable exists as placeholder the version number to use as your format when creating you tags on GitHub. See https://semantic-release.gitbook.io/semantic-release/usage/configuration#tagformat

So, kindly remove the `tagFormat` from your `branches` config option...

```
"branches": [
    {
      "name": "master",
      "tagFormat": "v${nextRelease.version}"  // 👈 👈 👈  REMOVE
    },
    {
      "name": "dev",
      "prerelease": true,
      "tagFormat": "dev-v${nextRelease.version}" // 👈 👈 👈  REMOVE 
    }
  ]
```
...and add a `tagFormat` configuration seperately if you wish to have your tag look any differently from `v1.0.0`

```
"branches": [
    "master"
    {
      "name": "dev",
      "prerelease": true,
    }
  ]
"tagFormat": "version${version}"
```

I also see your effort of trying to give the `dev` branch (which is your `pre-release` branch) a different tagFormat; This isn't something you should worry about, semantic-release automatically helps you address using the [semVer pre-release precedence](https://semver.org/#spec-item-11); it appends your branch name at the end of your version tag like `1.0.0-dev`, which in this case will let your tag with your configured format end up like `v1.0.0-dev` or `version1.0.0-dev`.

😉

**Comment by warrenronsiek** [comment]
Thank you for the response!
