### ISSUE TITLE
Cannot find package 'marked-terminal'. Code: ERR_MODULE_NOT_FOUND

### ISSUE THREAD

**Issue by syphernl** [semantic-release/semantic-release#3484]
### Current behavior

When a plugin fails for some reason (in this case it is [semantic-release-backmerge](https://github.com/kilianpaquier/semantic-release-backmerge)) it seems semantic-release has some trouble writing the output of the error.:

```bash
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'marked-terminal' imported from /usr/local/lib/node_modules/semantic-release/index.js
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:472:34)
    at defaultImportModuleDynamicallyForModule (node:internal/modules/esm/utils:214:31)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:253:12)
    at terminalOutput (file:///usr/local/lib/node_modules/semantic-release/index.js:29:43) {
  code: 'ERR_MODULE_NOT_FOUND'
```

This dependency however exists and is part of our container:

```bash
/workspace # npm ls -g -a | grep marked
  +-- marked-terminal@7.1.0
  | +-- marked@12.0.2 deduped
  +-- marked@12.0.2
```

I have tried to install `marked-terminal` explicitly before running, but it makes no diference.

### Expected behavior

The dependency `marked-terminal` is installed, so it should not give an `ERR_MODULE_NOT_FOUND`

### `semantic-release` version

24.1.3

### CI environment

GitLab

### Plugins used

* `@bpgeck/semantic-release-kaniko@2.0.2`
* `@codedependant/semantic-release-docker@5.0.3`
* `@kilianpaquier/semantic-release-backmerge@1.3.2`
* `@semantic-release/exec@6.0.3`
* `@semantic-release/gitlab@13.2.1`
* `conventional-changelog-conventionalcommits@8.0.0`
* `semantic-release-helm3@2.9.3`
* `semantic-release-slack-bot@4.0.2`

### `semantic-release` configuration

module.exports = {
  plugins: [
    [
      '@semantic-release/commit-analyzer',
      {
        preset: 'angular',
        parserOpts: {
          noteKeywords: ['BREAKING CHANGE', 'BREAKING CHANGES', 'BREAKING']
        },
        releaseRules: [
          { type: 'build', release: 'patch' },
          { type: 'deploy', release: 'patch' },
          { type: 'chore', release: 'patch' },
          { type: 'docs', release: 'patch' },
          { type: 'test', release: 'patch' },
          { type: 'style', release: 'patch' },
          { type: 'ci', release: 'patch' }
        ]
      }
    ],
    [
      '@semantic-release/release-notes-generator',
      {
        preset: 'conventionalcommits',
        parserOpts: {
          noteKeywords: ['BREAKING CHANGE', 'BREAKING CHANGES', 'BREAKING']
        },
        writerOpts: {
          commitsSort: ['subject', 'scope']
        },
        presetConfig: {
          types: [
            { type: 'feat', section: 'Features' },
            { type: 'fix', section: 'Bug Fixes' },
            { type: 'chore', section: 'Chores', hidden: false },
            { type: 'refactor', section: 'Internal', hidden: false },
            { type: 'perf', section: 'Performance', hidden: false },
            { type: 'docs', section: 'Documentation', hidden: false },
            { type: 'ci', section: 'DevOps', hidden: false },
            { type: 'test', section: 'Tests', hidden: false }
          ]
        }
      }
    ],
    [
      '@bpgeck/semantic-release-kaniko',{ }
    ],
    [
      '@semantic-release/gitlab',
      {
        successComment: ':tada: This ${issue ? "issue" : "MR"} is included in version [v${nextRelease.version}](${releases.find(release => /gitlab\\.com/i.test(release.url)).url}).',
        labels: 'semantic-release'
      }
    ],
    [
      'semantic-release-slack-bot',
      {
        notifyOnSuccess: true,
        markdownReleaseNotes: true,
        onSuccessTemplate: {
          blocks: [
            {
              type: 'section',
              text: {
                type: 'mrkdwn',
                text: `A new version of \`$package_name\` has been released!\nCurrent version is *$npm_package_version*`
              }
            },
            { type: 'divider' },
            {
              type: 'section',
              text: {
                type: 'mrkdwn',
                text: '$release_notes'
              }
            }
          ],
          attachments: [
            {
              blocks: [
                {
                  type: 'context',
                  elements: [
                    {
                      type: 'mrkdwn',
                      text: `:link: <${process.env.CI_ENVIRONMENT_URL}|View ${process.env.CI_ENVIRONMENT_NAME} website>`
                    }
                  ]
                }
              ]
            }
          ]
        }
      }
    ],
    [
      "@kilianpaquier/semantic-release-backmerge",
      {
        targets: [
          { from: "production", to: "develop" },
          { from: "acceptance", to: "develop" }
        ],
        title: "ci(release): fix mergeback from ${ from } into ${ to }",
      }
    ],
  ],
  branches: [
    { name: 'main', prerelease: true },
    { name: 'review', prerelease: true },
    { name: 'acceptance', prerelease: true },
    { name: 'production', prerelease: false }
  ]
};

### CI logs

[6:25:34 AM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/gitlab"
[6:25:34 AM] [semantic-release] › ℹ  Start step "fail" of plugin "semantic-release-slack-bot"
[6:25:34 AM] [semantic-release] [semantic-release-slack-bot] › ℹ  Notifying on fail skipped
[6:25:34 AM] [semantic-release] › ✔  Completed step "fail" of plugin "semantic-release-slack-bot"
[6:25:34 AM] [semantic-release] › ✘  EBACKMERGE Failed to backmerge branches.
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'marked-terminal' imported from /usr/local/lib/node_modules/semantic-release/index.js
    at packageResolve (node:internal/modules/esm/resolve:854:9)
    at moduleResolve (node:internal/modules/esm/resolve:927:18)
    at defaultResolve (node:internal/modules/esm/resolve:1169:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:239:38)
    at ModuleLoader.import (node:internal/modules/esm/loader:[472](https://gitlab.com/REDACTED/-/jobs/REDACTED#L472):34)
    at defaultImportModuleDynamicallyForModule (node:internal/modules/esm/utils:214:31)
    at importModuleDynamicallyCallback (node:internal/modules/esm/utils:253:12)
    at terminalOutput (file:///usr/local/lib/node_modules/semantic-release/index.js:29:43) {
  code: 'ERR_MODULE_NOT_FOUND'
}

**Comment by travi** [comment]
without a public reproduction, i'm afraid that there is not much we can do to investigate this. we clearly define the appropriate dependency and it looks like it is installed in your project. are you in the context of a monorepo or use a different package manager than npm? it seems most likely that you somehow have an invalid dependency tree that node is failing to find the appropriate package at runtime.

are you interested in providing a public minimal reproduction to help us understand what the problem could be?
