### ISSUE TITLE
EINVALIDGHTOKEN Invalid GitHub token

### ISSUE THREAD

**Issue by coopernicholas** [semantic-release/semantic-release#3529]
### Current behavior

EINVALIDGHTOKEN Invalid GitHub token

### Expected behavior

Should authenticate successfully. 

### `semantic-release` version

24.2.0

### CI environment

On-Prem DevOps

### `semantic-release` configuration
```
"release": {
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "semantic-release-ado",
      [
        "@semantic-release/npm",
        {
          "npmPublish": false
        }
      ],
      [
        "@semantic-release/changelog",
        {
          "changelogFile": "docs/CHANGELOG.md"
        }
      ],
      [
        "@semantic-release/github",
        {
          "assets": [
            "docs/CHANGELOG.md"
          ]
        }
      ]
    ]
```
### CI logs
```
[12:54:38 PM] [semantic-release] » ×  Failed step "verifyConditions" of plugin "@semantic-release/github"
[12:54:38 PM] [semantic-release] » i  Start step "fail" of plugin "@semantic-release/github"
[12:54:38 PM] [semantic-release] [@semantic-release/github] » i  Verify GitHub authentication
[12:54:38 PM] [semantic-release] » ×  Failed step "fail" of plugin "@semantic-release/github"
[12:54:38 PM] [semantic-release] » ×  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository MTA%20Collection/MTA%20Scanner/_git/MTA%20Scanner.

[12:54:38 PM] [semantic-release] » ×  ENOGHTOKEN No GitHub token specified.
A GitHub personal token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) must be created and set in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment.

Please make sure to create a GitHub personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) and to set it in the GH_TOKEN or GITHUB_TOKEN environment variable on your CI environment. The token must allow to push to the repository MTA%20Collection/MTA%20Scanner/_git/MTA%20Scanner.

AggregateError: 
    SemanticReleaseError: No GitHub token specified.
        at getError (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/d181a3c2436651c2/node_modules/@semantic-release/github/lib/get-error.js:7:10)
        at verify (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/d181a3c2436651c2/node_modules/@semantic-release/github/lib/verify.js:152:17)
        at verifyConditions (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/d181a3c2436651c2/node_modules/@semantic-release/github/index.js:51:9)
        at validator (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/d181a3c2436651c2/node_modules/semantic-release/lib/plugins/normalize.js:36:30)
        at file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/d181a3c2436651c2/node_modules/semantic-release/lib/plugins/pipeline.js:38:42
        at next (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/d181a3c2436651c2/node_modules/semantic-release/node_modules/p-reduce/index.js:16:10)
    at file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/d181a3c2436651c2/node_modules/semantic-release/lib/plugins/pipeline.js:55:13
    at async pluginsConfigAccumulator.<computed> [as verifyConditions] (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/d181a3c2436651c2/node_modules/semantic-release/lib/plugins/index.js:87:11)
    at async run (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/d181a3c2436651c2/node_modules/semantic-release/index.js:106:3)
    at async Module.default (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/d181a3c2436651c2/node_modules/semantic-release/index.js:278:22)
    at async default (file:///C:/Users/Administrator/AppData/Local/npm-cache/_npx/d181a3c2436651c2/node_modules/semantic-release/cli.js:55:5) {
  errors: [
    SemanticReleaseError: No GitHub token specified.
```

**Comment by travi** [comment]
According to the error, you have not provided a GitHub token. If you believe you have, please provide details
