### ISSUE TITLE
Feature: Setup a configurable work directory

### ISSUE THREAD

**Issue by EAJ-EAJGlobal** [semantic-release/semantic-release#3540]
### New feature motivation

I am working in a CIS Hardened environment which has a read only file system so I have to use a custom volume (Kubernetes) to be able to run scripts.

Semantic Release seems to be calling tempy to create a directory to operate in which fails because of this read only file system not allowing write access to /tmp by the user

The following is the Error copied from Gitlab Pipeline (Works without CIS hardening).
```
npx -y -p @semantic-release/commit-analyzer@9.0.2 -p @semantic-release/git@10.0.1 -p @semantic-release/gitlab@9.5.0 -p @semantic-release/release-notes-generator@10.0.3 -p @semantic-release/exec@6.0.3 -p @semantic-release/changelog@6.0.2 -p conventional-changelog-conventionalcommits@5.0.0 -p semantic-release@19.0.5 semantic-release
npm warn deprecated glob@7.2.3: Glob versions prior to v9 are no longer supported
npm warn deprecated inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
npm warn deprecated rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
npm warn deprecated q@1.5.1: You or someone you depend on is using Q, the JavaScript Promise library that gave JavaScript developers strong feelings about promises. They can almost certainly migrate to the native JavaScript promise now. Thank you literally everyone for joining me in this bet against the odds. Be excellent to each other.
npm warn deprecated
npm warn deprecated (For a CapTP with native promises, see @endo/eventual-send and @endo/captp)
[4:08:16 PM] [semantic-release] › ℹ  Running semantic-release version 19.0.5
[4:08:16 PM] [semantic-release] › ✖  An error occurred while running semantic-release: Error: EROFS: read-only file system, mkdir '/tmp/52cc7a9f01be4d12538d9b48aee5ab68'
    at Object.mkdirSync (node:fs:1363:26)
    at module.exports.directory (/ephemeral_build_home/.npm/_npx/0175b00e0e8ce1f1/node_modules/tempy/index.js:49:5)
    at module.exports.file (/ephemeral_build_home/.npm/_npx/0175b00e0e8ce1f1/node_modules/tempy/index.js:39:35)
    at Object.<anonymous> (/ephemeral_build_home/.npm/_npx/0175b00e0e8ce1f1/node_modules/@semantic-release/npm/index.js:14:21)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24) {
  errno: -30,
  code: 'EROFS',
  syscall: 'mkdir',
  path: '/tmp/52cc7a9f01be4d12538d9b48aee5ab68'
}
Error: EROFS: read-only file system, mkdir '/tmp/52cc7a9f01be4d12538d9b48aee5ab68'
    at Object.mkdirSync (node:fs:1363:26)
    at module.exports.directory (/ephemeral_build_home/.npm/_npx/0175b00e0e8ce1f1/node_modules/tempy/index.js:49:5)
    at module.exports.file (/ephemeral_build_home/.npm/_npx/0175b00e0e8ce1f1/node_modules/tempy/index.js:39:35)
    at Object.<anonymous> (/ephemeral_build_home/.npm/_npx/0175b00e0e8ce1f1/node_modules/@semantic-release/npm/index.js:14:21)
    at Module._compile (node:internal/modules/cjs/loader:1565:14)
    at Object..js (node:internal/modules/cjs/loader:1708:10)
    at Module.load (node:internal/modules/cjs/loader:1318:32)
    at Function._load (node:internal/modules/cjs/loader:1128:12)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:219:24) {
  errno: -30,
  code: 'EROFS',
  syscall: 'mkdir',
  path: '/tmp/52cc7a9f01be4d12538d9b48aee5ab68'
}
```

### New feature description

Allow us to override the directory in which semantic-release operates in particular its temp files.

### New feature implementation

Create a cli/feature/config flag that allows us to prefix the where the tmp folder is.

**Comment by travi** [comment]
semantic-release takes this step pretty intentionally in order to avoid conflicts with `.npmrc` in standard locations, like the root of a checked out project. we have lots and lots of users that have been successful without the proposed capability and we are attempting to minimize new configuration options. you've described the context you are wanting to operate in that creates the need for such a feature, but we need some details on the use case that requires a context like you describe. could you provide more information to help us decide if this is something we can justify adding and maintaining for the remainder of the life of the project?
