### ISSUE TITLE
[FAIL] semantic-release ERR! init No npm token specified. ENONPMTOKEN

### ISSUE THREAD

**Issue by dalisoft** [semantic-release/semantic-release#373]
Hi. I am newbie for @semantic-release and i am trying to release with semver, but fails.
How i can use this?

```bash
D:\GitHub\es6-tween>npm run semantic-release

> es6-tween@1.4.0 semantic-release D:\GitHub\es6-tween
> semantic-release pre && npm publish && semantic-release post

semantic-release ERR! init No npm token specified. ENONPMTOKEN

npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "run" "semantic-release"
npm ERR! node v6.3.1
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! es6-tween@1.4.0 semantic-release: `semantic-release pre && npm publish
&& semantic-release post`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the es6-tween@1.4.0 semantic-release script 'semantic-release
 pre && npm publish && semantic-release post'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the es6-tween package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     semantic-release pre && npm publish && semantic-release post
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs es6-tween
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls es6-tween
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\GitHub\es6-tween\npm-debug.log
```

### `npm-debug.log`
```bash
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'semantic-release' ]
2 info using npm@3.10.3
3 info using node@v6.3.1
4 verbose run-script [ 'presemantic-release',
4 verbose run-script   'semantic-release',
4 verbose run-script   'postsemantic-release' ]
5 info lifecycle es6-tween@1.4.0~presemantic-release: es6-tween@1.4.0
6 silly lifecycle es6-tween@1.4.0~presemantic-release: no script for presemantic-release, continuing
7 info lifecycle es6-tween@1.4.0~semantic-release: es6-tween@1.4.0
8 verbose lifecycle es6-tween@1.4.0~semantic-release: unsafe-perm in lifecycle true
9 verbose lifecycle es6-tween@1.4.0~semantic-release: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;D:\GitHub\es6-tween\node_modules\.bin;C:\Program Files\nodejs;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\TortoiseGit\bin;C:\Program Files\nodejs\;C:\Program Files\Brackets\command;C:\Program Files\Yarn\bin;C:\Program Files\Git\cmd;C:\Program Files\OpenVPN\bin;C:\Users\Dalerjon\AppData\Roaming\npm;C:\Users\Dalerjon\AppData\Local\Yarn\.bin;C:\Program Files\Heroku\bin;C:\Program Files\Microsoft VS Code\bin
10 verbose lifecycle es6-tween@1.4.0~semantic-release: CWD: D:\GitHub\es6-tween
11 silly lifecycle es6-tween@1.4.0~semantic-release: Args: [ '/d /s /c',
11 silly lifecycle   'semantic-release pre && npm publish && semantic-release post' ]
12 silly lifecycle es6-tween@1.4.0~semantic-release: Returned: code: 1  signal: null
13 info lifecycle es6-tween@1.4.0~semantic-release: Failed to exec semantic-release script
14 verbose stack Error: es6-tween@1.4.0 semantic-release: `semantic-release pre && npm publish && semantic-release post`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid es6-tween@1.4.0
16 verbose cwd D:\GitHub\es6-tween
17 error Windows_NT 6.1.7600
18 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "semantic-release"
19 error node v6.3.1
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error es6-tween@1.4.0 semantic-release: `semantic-release pre && npm publish && semantic-release post`
22 error Exit status 1
23 error Failed at the es6-tween@1.4.0 semantic-release script 'semantic-release pre && npm publish && semantic-release post'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the es6-tween package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     semantic-release pre && npm publish && semantic-release post
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs es6-tween
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls es6-tween
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

#### `package.json`
```javascript
{
	"name": "es6-tween",
	"version": "1.4.0",
	"description": "ES6 implementation of amazing tween.js",
	"main": "dist/Tween.js",
	"directories": {
		"example": "examples"
	},
	"scripts": {
		"build": "webpack --env build",
		"source": "webpack --progress --colors --env dev",
		"dev": "webpack --progress --colors --watch --env dev",
		"dist": "npm run source && npm run build",
		"dist_test": "npm run dist && npm run test",
		"test": "npm run test-unit && npm run test-correctness && npm run test-style",
		"test-unit": "nodeunit test/unit/nodeunitheadless.js",
		"test-correctness": "jshint --config test/jshintrc src/Tween.js",
		"test-style": "jscs --config test/jscs.json src/Tween.js",
		"semantic-release": "semantic-release pre && npm publish && semantic-release post"
	},
	"release": {
		"debug": false,
		"githubToken": "32558a13585b92da451b3d55f1623f36513586ea",
		"NPM_TOKEN": "063bdee0-66dc-4a7f-afbe-9e957d61c223"
	},
	"repository": {
		"type": "git",
		"url": "git+https://github.com/tweenjs/es6-tween.git"
	},
	"keywords": [
		"tween",
		"tweening",
		"es6",
		"numeric",
		"interpolation",
		"easing",
		"emit"
	],
	"author": "sole, dalisoft",
	"license": "MIT",
	"bugs": {
		"url": "https://github.com/tweenjs/es6-tween/issues"
	},
	"homepage": "https://github.com/tweenjs/es6-tween#readme",
	"devDependencies": {
		"babel": "6.5.2",
		"babel-core": "6.22.1",
		"babel-eslint": "7.1.1",
		"babel-loader": "6.2.10",
		"babel-plugin-add-module-exports": "0.1.2",
		"babel-plugin-transform-es2015-classes": "latest",
		"babel-plugin-transform-proto-to-assign": "latest",
		"babel-plugin-transform-react-jsx": "latest",
		"babel-preset-es2015": "6.22.0",
		"eslint": "1.7.2",
		"eslint-loader": "1.6.1",
		"webpack": "2.2.1",
		"yargs": "6.6.0",
		"jscs": "^2.2.0",
		"jshint": "^2.8.0",
		"nodeunit": "^0.9.1",
		"semantic-release": "^6.3.2"
	},
	"dependencies": {}
}

```

**Comment by zot24** [comment]
Try adding `NPM_TOKEN ` as an env var instead that on your `package.json` as it's `npm` what will use it no `semantic-release`

I just hope those are not your real tokens 👇 

```
"githubToken": "32558a13585b92da451b3d55f1623f36513586ea",
"NPM_TOKEN": "063bdee0-66dc-4a7f-afbe-9e957d61c223"
```

**Comment by dalisoft** [comment]
Thanks. I try. I am not worry about token and even password. Github is home of open source and peoples doesnt uses other code (always good peoples more than bads).  Thanks a lot for reply
