### ISSUE TITLE
Should the github user have admin permission?

### ISSUE THREAD

**Issue by fernandogmar** [semantic-release/semantic-release#394]
Hi!

I am giving a shot to semantic release in one project at work... we have a [machine-user](https://developer.github.com/v3/guides/managing-deploy-keys/#machine-users) on github  for automatic tasks but I can not get it working with semantic release. It works with my user but is doesn't work with this machine-user, the main difference between both is the permissions... I have admin permission for the reposistory and this machine-user has write permission... Just in case below you can see the error I got. Thanks in advance!

```
? What CI are you using? Travis CI Pro
ERR! semantic-release Error: Sorry, we experienced an error.
ERR! semantic-release     at maybeWrapAsError (/home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/util.js:61:12)
ERR! semantic-release     at /home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/nodeback.js:38:50
ERR! semantic-release     at /home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21
ERR! semantic-release     at Request._callback (/home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
ERR! semantic-release     at Request.self.callback (/home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:187:22)
ERR! semantic-release     at emitTwo (events.js:106:13)
ERR! semantic-release     at Request.emit (events.js:191:7)
ERR! semantic-release     at Request.<anonymous> (/home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:1044:10)
ERR! semantic-release     at emitOne (events.js:96:13)
ERR! semantic-release     at Request.emit (events.js:188:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:965:12)
ERR! semantic-release     at emitNone (events.js:91:20)
ERR! semantic-release     at IncomingMessage.emit (events.js:185:7)
ERR! semantic-release     at endReadableNT (_stream_readable.js:974:12)
ERR! semantic-release     at _combinedTickCallback (internal/process/next_tick.js:74:11)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:98:9)
ERR! semantic-release  { Error: Sorry, we experienced an error.
ERR! semantic-release     at maybeWrapAsError (/home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/util.js:61:12)
ERR! semantic-release     at /home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/bluebird/js/release/nodeback.js:38:50
ERR! semantic-release     at /home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-ci.js:51:21
ERR! semantic-release     at Request._callback (/home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/lib/travis-http.js:49:13)
ERR! semantic-release     at Request.self.callback (/home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:187:22)
ERR! semantic-release     at emitTwo (events.js:106:13)
ERR! semantic-release     at Request.emit (events.js:191:7)
ERR! semantic-release     at Request.<anonymous> (/home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:1044:10)
ERR! semantic-release     at emitOne (events.js:96:13)
ERR! semantic-release     at Request.emit (events.js:188:7)
ERR! semantic-release     at IncomingMessage.<anonymous> (/home/fernando/.nvm/versions/node/v6.5.0/lib/node_modules/semantic-release-cli/node_modules/travis-ci/node_modules/request/request.js:965:12)
ERR! semantic-release     at emitNone (events.js:91:20)
ERR! semantic-release     at IncomingMessage.emit (events.js:185:7)
ERR! semantic-release     at endReadableNT (_stream_readable.js:974:12)
ERR! semantic-release     at _combinedTickCallback (internal/process/next_tick.js:74:11)
ERR! semantic-release     at process._tickCallback (internal/process/next_tick.js:98:9)
ERR! semantic-release   cause: 
ERR! semantic-release    Error: Sorry, we experienced an error.
[....]
```

**Comment by gr2m** [comment]
Hey there,

I’m sorry for the late response :(

I think that indeed the github user needs admin authentication on the org, otherwise it cannot create the webhook required for semantic-release. We should return a more helpful error in that case though. As a workaround, I would suggest to just log out the tokens and add them manually to Travis setting, does that work for you?

**Comment by pvdlg** [comment]
Closing for now has it seems the question was answered. Please re-open if you are still experiencing an issue.
