### ISSUE TITLE
How do you publish a repository that doesn't output a node.js module?

### ISSUE THREAD

**Issue by ts-npm** [semantic-release/semantic-release#698]
## Current behavior

When attempting to publish a javascript project that outputs a bundle instead of a node package, the script requires an NPM token.

Basically I want to publish some built assets to a cdn, but semantic-release is requiring an NPM token.

## Expected behavior

The build shouldn't require an NPM token.

## Environment

- **semantic-release** version: 15.0.2
- CI environment: CircleCI
- Plugins used: @semantic-release/exec, condition-circle, @semantic-release/github
- **semantic-release** configuration: 
.releaserc.json

```
{
  "release": {
    "publish": [
      {
        "path": "@semantic-release/exec",
        "cmd": "echo ${nextRelease.version}.min.js"
      },
      {
        "path": "@semantic-release/github"
      }
    ],
    "verifyConditions": "condition-circle"
  }
}
```

- CI logs: 

## Current behavior

When attempting to publish a javascript project that outputs a bundle instead of a node package, the script requires an NPM token.

## Expected behavior

The build shouldn't require an NPM token.

## Environment

- **semantic-release** version: 15.0.2
- CI environment: CircleCI
- Plugins used: @semantic-release/exec, condition-circle
- **semantic-release** configuration: 
.releaserc.json
```
{
  "release": {
    "publish": [
      {
        "path": "@semantic-release/exec",
        "cmd": "echo ${nextRelease.version}.min.js"
      },
      {
        "path": "@semantic-release/github"
      }
    ],
    "verifyConditions": "condition-circle"
  }
}
```
- CI logs: 
```
circleci build -e GH_TOKEN=<redacted> -e NPM_TOKEN=000000000000-0000-0000-000000000000

INFO: There's a newer version of CircleCI build-agent available. Run 'circleci update' for update
====>> Spin up Environment
Build-agent version 0.0.4710-44beb0a (2018-02-27T20:05:34+0000)
Starting container circleci/node:8.9.4
  using image circleci/node@sha256:b0fa2a8158710ba49cf4f42fe5b31715694026517207ff141fffb6ab45b24ab0

Using build environment variables:
  BASH_ENV=/tmp/.bash_env-localbuild-1520892408
  CI=true
  CIRCLECI=true
  CIRCLE_BRANCH=master
  CIRCLE_BUILD_NUM=
  CIRCLE_JOB=build
  CIRCLE_NODE_INDEX=0
  CIRCLE_NODE_TOTAL=1
  CIRCLE_REPOSITORY_URL=<redacted>
  CIRCLE_SHA1=3a78a4324a14578eaf523887d7f35e5178b3f395
  CIRCLE_SHELL_ENV=/tmp/.bash_env-localbuild-1520892408
  CIRCLE_WORKING_DIRECTORY=~/repo

====>> Checkout code
  #!/bin/sh
mkdir -p /home/circleci/repo && cp -r /tmp/_circleci_local_build_repo/. /home/circleci/repo
====>> Restoring Cache
Error: Skipping cache - error checking storage: not supported

Step failed
====>> Run semantic-release
  #!/bin/bash -eo pipefail
sudo npm i -g semantic-release@15.0.2
/usr/local/bin/semantic-release -> /usr/local/lib/node_modules/semantic-release/bin/semantic-release.js
+ semantic-release@15.0.2
added 387 packages in 10.944s
====>> Run semantic-release
  #!/bin/bash -eo pipefail
semantic-release
[Semantic release]: Running semantic-release version 15.0.2
Username for 'https://<redacted>': [Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Wrote NPM_TOKEN to .npmrc.
[Semantic release]: Verify GitHub authentication
DEPRECATED: protocol option is no longer supported
DEPRECATED: host option is no longer supported
DEPRECATED: port option is no longer supported
DEPRECATED: pathPrefix option is no longer supported
[Semantic release]: Verify GitHub authentication
DEPRECATED: protocol option is no longer supported
DEPRECATED: host option is no longer supported
DEPRECATED: port option is no longer supported
DEPRECATED: pathPrefix option is no longer supported
[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository <redacted>.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


[Semantic release]: EINVALIDNPMTOKEN Invalid npm token.
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry https://registry.npmjs.org/.

If you are using Two-Factor Authentication, make configure the auth-only level (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) is supported. semantic-release cannot publish with the default auth-and-writes level.

Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.


[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository <redacted>.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


{ AggregateError: 
    SemanticReleaseError: Invalid npm token.
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/verify-auth.js:23:33)
        at <anonymous>
    SemanticReleaseError: Invalid GitHub token.
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/get-error.js:6:10)
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/verify.js:86:21)
        at <anonymous>
    at Object.verifyConditions (/usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:52:45)
    at <anonymous> name: 'AggregateError' }
Error: Exited with code 1
Step failed
```

**Comment by pvdlg** [comment]
I think this [FAQ](https://semantic-release.gitbooks.io/semantic-release/content/docs/support/FAQ.html#can-i-skip-the-release-to-the-npm-registry) should answer your exact question.

Also you shouldn't use `condition-circle` as CI related verify plugins are not required since several version of semantic-release.

**Comment by ts-npm** [comment]
Thank you for your help, but this doesn't fully answer my question. How do I deploy without the need 
for an npm token?

As for the constraints listed in your FAQ I am doing the following:
- [x] Running a globally installed semantic release
- [x] Set semantic-release options via CLI arguments or rc file
- [x] Make sure your CI job executing the semantic-release command has access to Node >= 8 to execute the semantic-release command

I've updated my configurations based upon your recommendations, here's what I have so far:

.releaserc.json

```
{
  "release": {
    "verifyConditions": ["t@semantic-release/git", "@semantic-release/github"],
    "publish": [
      {
        "path": "@semantic-release/npm",
        "npmPublish": false,
        "tarballDir": "dist"
      },
      {
        "path": "@semantic-release/github",
        "assets": "dist/*.tgz"
      }
    ]
  }
}
```
package.json

```
...
  "devDependencies": {
    "@semantic-release/exec": "^2.2.3",
    "@semantic-release/github": "^4.2.8",
    "@semantic-release/git": "^4.0.1",
...
```

In my CircleCI config I have the following for testing it out with your recommended configurations

```
# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.9.4
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          key: project-name-{{ .Branch }}-{{ checksum "package.json" }}
      - run:
          name: Run semantic-release
          command: sudo npm i -g semantic-release@15.0.2
      - run:
          name: Install Dependencies
          command: yarn
      - run:
          name: Run semantic-release
          command: semantic-release
      - save_cache:
          key: project-name-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - ~/.cache/yarn
            - node_modules
workflows:
  version: 2
  build-and-lint:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
```

Build output

```
#!/bin/bash -eo pipefail
semantic-release
[Semantic release]: Running semantic-release version 15.0.2
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Wrote NPM_TOKEN to .npmrc.
[Semantic release]: Verify GitHub authentication
[Semantic release]: Verify GitHub authentication
[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


[Semantic release]: EINVALIDNPMTOKEN Invalid npm token.
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry https://registry.npmjs.org/.

If you are using Two-Factor Authentication, make configure the auth-only level (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) is supported. semantic-release cannot publish with the default auth-and-writes level.

Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.


[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


{ AggregateError: 
    SemanticReleaseError: Invalid npm token.
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/verify-auth.js:23:33)
        at <anonymous>
    SemanticReleaseError: Invalid GitHub token.
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/get-error.js:6:10)
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/verify.js:86:21)
        at <anonymous>
    at Object.verifyConditions (/usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:52:45)
    at <anonymous> name: 'AggregateError' }
Exited with code 1
```

**Comment by ts-npm** [comment]
Furthermore, if I do define a valid NPM_TOKEN and GH_TOKEN I recieve the following when running semantic release:

```
#!/bin/bash -eo pipefail
semantic-release
[Semantic release]: Running semantic-release version 15.0.2
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Wrote NPM_TOKEN to .npmrc.
[Semantic release]: Verify GitHub authentication
[Semantic release]: Verify GitHub authentication
[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


{ SemanticReleaseError: Invalid GitHub token.
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/get-error.js:6:10)
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/verify.js:86:21)
    at <anonymous>
  name: 'SemanticReleaseError',
  code: 'EINVALIDGHTOKEN',
  details: 'The [GitHub token](https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the `GH_TOKEN` or `GITHUB_TOKEN` environment variable must be a valid [personnal token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.\n\nPlease make sure to set the `GH_TOKEN` or `GITHUB_TOKEN` environment variable in your CI with the exact value of the GitHub personnal token.',
  semanticRelease: true,
  pluginName: '@semantic-release/github' }
Exited with code 1```

**Comment by pvdlg** [comment]
The npm plugin is used for the `publish`, the `verifyConditons` and the `prepare` step.
You need to set `npmPublish` in the 3 of them. Or for more simplicity you can set `npmPublish` directly in  the `release` object.

Even if you don't publish on npm, you still need to configure `GH_TOKEN` to publish on GitHub. This is why you get an error message.

**Comment by ts-npm** [comment]
After updating the .releaserc.json file based upon your feedback I am still receiving errors relating to not having an NPM token defined.

I am setting a GH_TOKEN and a no longer setting an NPM_TOKEN in circle.

I am setting the personal access token as a variable in CircleCI under the name of `GH_TOKEN`. I've verified that I can use the token to push and pull to and from the repo locally and yet for some reason the gh token isn't being registered.

Updated .releaserc.json file based upon your feedback

```
{
  "release": {
    "prepare": [
      {
        "path": "@semantic-release/npm",
        "npmPublish": false,
        "tarballDir": "dist"
      }
    ],
    "verifyConditions": [
      {
        "path": "@semantic-release/npm",
        "npmPublish": false,
        "tarballDir": "dist"
      }
    ],
    "publish": [
      {
        "path": "@semantic-release/npm",
        "npmPublish": false,
        "tarballDir": "dist"
      }
    ]
  }
}
```
Command output
```
#!/bin/bash -eo pipefail
semantic-release
[Semantic release]: Running semantic-release version 15.0.2
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify authentication for registry https://registry.npmjs.org/
[Semantic release]: Verify GitHub authentication
[Semantic release]: Verify GitHub authentication
[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


[Semantic release]: ENONPMTOKEN No npm token specified.
An npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) must be created and set in the NPM_TOKEN environment variable on your CI environment.

Please make sure to create an npm token (https://docs.npmjs.com/getting-started/working_with_tokens#how-to-create-new-tokens) and to set it in the NPM_TOKEN environment variable on your CI environment. The token must allow to publish to the registry https://registry.npmjs.org/.


[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


{ AggregateError: 
    SemanticReleaseError: No npm token specified.
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/set-npmrc-auth.js:21:31)
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/npm/lib/verify-auth.js:17:9)
        at <anonymous>
    SemanticReleaseError: Invalid GitHub token.
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/get-error.js:6:10)
        at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/verify.js:86:21)
        at <anonymous>
    at Object.verifyConditions (/usr/local/lib/node_modules/semantic-release/lib/plugins/pipeline.js:52:45)
    at <anonymous> name: 'AggregateError' }
Exited with code 1
```

**Comment by pvdlg** [comment]
This because your `.releaserc.json` is not formatted properly. It should be:
```json
{
  "verifyConditions": [...],
  "prepare": [...],
  "publish": [...]
}
```

**Comment by ts-npm** [comment]
Doh...

**Comment by ts-npm** [comment]
Ok, thanks for that, sorry for bothering you with the dumb mistake. That fixed the npm problems.

Interestingly I'm still getting problems with the github token being labeled as invalid. That breadcrumb may give me more information for debugging the rest of this.

**Comment by pvdlg** [comment]
The `GH_TOKEN` must belong to a user with push access to your repo. Maybe that's the problem.

**Comment by ts-npm** [comment]
Here is an example showing I have access. I know that the GH_TOKEN is being injected into the environment on Circle.

![Uploading package.json [tsh… 2018-03-13 12-10-37.png…]()

**Comment by ts-npm** [comment]
Whoo! Getting closer @pvdlg.

I've run into something that's kind of weird. I'm still getting the Invalid GitHub token error, but running semantic-release against a test repo generates the new tags and pushes them to the GitHub repo just fine.

Any thoughts?

.releaserc.json
```
#!/bin/bash -eo pipefail
semantic-release
[Semantic release]: Running semantic-release version 15.0.2
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/exec
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Found git tag v1.1.0 associated with version 1.1.0
[Semantic release]: Found 1 commits since last release
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analyzing commit: feat(foo): has a baz

BREAKING CHANGE: breaks everything
[Semantic release]: The release type for the commit is major
[Semantic release]: Analysis of 1 commits complete: major release
[Semantic release]: The next release version is 2.0.0
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Call plugin prepare
[Semantic release]: Wrote version 2.0.0 to package.json
[Semantic release]: Creating npm package version 2.0.0
[Semantic release]: Create tag v2.0.0
[Semantic release]: Call plugin publish
[Semantic release]: Call script echo 2.0.0.min.js
2.0.0.min.js
[Semantic release]: The command echo ${nextRelease.version}.min.js wrote invalid JSON to stdout. The stdout content will be ignored.
[Semantic release]: Verify GitHub authentication
[Semantic release]: Verify GitHub authentication
[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


{ SemanticReleaseError: Invalid GitHub token.
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/get-error.js:6:10)
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/verify.js:86:21)
    at <anonymous>
  name: 'SemanticReleaseError',
  code: 'EINVALIDGHTOKEN',
  details: 'The [GitHub token](https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the `GH_TOKEN` or `GITHUB_TOKEN` environment variable must be a valid [personnal token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.\n\nPlease make sure to set the `GH_TOKEN` or `GITHUB_TOKEN` environment variable in your CI with the exact value of the GitHub personnal token.',
  semanticRelease: true,
  pluginName: '@semantic-release/github' }
Exited with code 1
```
Semantic release output:

```
#!/bin/bash -eo pipefail
semantic-release
[Semantic release]: Running semantic-release version 15.0.2
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/exec
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Found git tag v1.1.0 associated with version 1.1.0
[Semantic release]: Found 1 commits since last release
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analyzing commit: feat(foo): has a baz

BREAKING CHANGE: breaks everything
[Semantic release]: The release type for the commit is major
[Semantic release]: Analysis of 1 commits complete: major release
[Semantic release]: The next release version is 2.0.0
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Call plugin prepare
[Semantic release]: Wrote version 2.0.0 to package.json
[Semantic release]: Creating npm package version 2.0.0
[Semantic release]: Create tag v2.0.0
[Semantic release]: Call plugin publish
[Semantic release]: Call script echo 2.0.0.min.js
2.0.0.min.js
[Semantic release]: The command echo ${nextRelease.version}.min.js wrote invalid JSON to stdout. The stdout content will be ignored.
[Semantic release]: Verify GitHub authentication
[Semantic release]: Verify GitHub authentication
[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


[Semantic release]: EINVALIDGHTOKEN Invalid GitHub token.
The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personnal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.

Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personnal token.


{ SemanticReleaseError: Invalid GitHub token.
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/get-error.js:6:10)
    at module.exports (/usr/local/lib/node_modules/semantic-release/node_modules/@semantic-release/github/lib/verify.js:86:21)
    at <anonymous>
  name: 'SemanticReleaseError',
  code: 'EINVALIDGHTOKEN',
  details: 'The [GitHub token](https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the `GH_TOKEN` or `GITHUB_TOKEN` environment variable must be a valid [personnal token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository timecapture/tsheets-frontend-app-ci-example.\n\nPlease make sure to set the `GH_TOKEN` or `GITHUB_TOKEN` environment variable in your CI with the exact value of the GitHub personnal token.',
  semanticRelease: true,
  pluginName: '@semantic-release/github' }
Exited with code 1
```

**Comment by pvdlg** [comment]
I don't know there must be a difference between the 2 repo in the way you create or set the GitHub token.

The check for the GitHub token permission is done here: https://github.com/semantic-release/github/blob/7b6bc952e03e5215f6d2862b983431f71f457ccd/lib/verify.js#L77-L92

**Comment by ts-npm** [comment]
Is there a way to just disable this verification then? I'm confused how one repo would work and the other doesn't. I'm just setting the GH_TOKEN as an environment variable. This is exactly what the docs say is required by the plugin. The only thing that I can think would impact this would be something in regards to my repo being on a github enterprise account.

**Comment by pvdlg** [comment]
No you can't disable it, and even if you could it wouldn't solve the problem as the permission is required to make the GitHub release. So it would fail later in the process but still fail.

You can run this code to check what is the permission associated with your token:
```js
const Octokit = require('@octokit/rest');

const token = '...';
const owner = '...';
const repo = '...';

const client = new Octokit();
client.authenticate({type: 'token', token});

client.repos.get({repo, owner}).then(result => console.log(result.data.permissions));

// => { admin: true, push: true, pull: true }
```
If your token is configured properly you should have `push: true` in the logged object.

**Comment by pvdlg** [comment]
@ts-npm did you manage to find the problem regarding the permissions? Is semantic-release working on your repo?

**Comment by ts-npm** [comment]
Just want to say thank you for your help. At the end of the day, it came down to to major roadblocks:
- `npmPublish: false` at top level in your release configuration
- configuring the `semantic-release/github` plugin correctly

Here's the .releaserc.json configuration that I used

```
{
  "npmPublish": false,
  "githubUrl": "https://github.intuit.com",
  "githubApiPathPrefix": "/api/v3",
  "publish": [
    {
      "path": "@semantic-release/github"
    },
    {
      "path": "@semantic-release/exec",
      "cmd": "yarn version-assets -d ./dist -r ${nextRelease.version}"
    }
  ],
  "analyzeCommits": {
    "preset": "angular",
    "releaseRules": [
      {
        "type": "docs",
        "scope": "README",
        "release": "patch"
      },
      {
        "type": "refactor",
        "release": "patch"
      },
      {
        "type": "style",
        "release": "patch"
      }
    ],
    "parserOpts": {
      "noteKeywords": [
        "BREAKING CHANGE",
        "BREAKING CHANGES",
        "BREAKING"
      ]
    }
  }
}
```

**Comment by pvdlg** [comment]
Thanks for the feedback! Glad everything works now.

> It's unclear that if you want to set a configuration to override all aspects you have to set that at the top level of the configuration object (e.g. "npmPublish: false) or setting it for every single plugin config.

I think this is mentioned in the [plugin configuration doc](https://semantic-release.gitbooks.io/semantic-release/content/docs/usage/plugins.html#configuration).

> The semantic-release-cli does not take a private github url into account when creating a gh token

Yes the CLI needs several improvement in that regard. I think there is some issue opened for that. If not feel free to open one.

> The required configurations for the github token are not super clear, they're defined in the semantic-release-cli as

Yes indeed. However it's mentioned in the [github plugin doc](https://github.com/semantic-release/github#configuration).

**Comment by ts-npm** [comment]
I'll submit some pull requests per each repo vs trying to delineate what can be improved further. Thanks again! Love the tooling.
