### ISSUE TITLE
Verify Github Authentication is failing

### ISSUE THREAD

**Issue by juliocanares** [semantic-release/semantic-release#718]
## Current behavior

I am running `semantic-release` on my `release` job using `circle ci workflows` filtering to the master branch.

## Expected behavior

It should just publish it without any error since I already have setup the `GITHUB_TOKEN` on my environment variables.

## Environment

- **semantic-release** version: `15.1.3`
- CI environment: `Circle CI`
- Plugins used: `none`
- **semantic-release** configuration:
```
module.exports = {
  publish: [
    {
      path: '@semantic-release/npm',
      npmPublish: false
    },
    {
      path: '@semantic-release/github'
    }
  ]
}
```
- CI logs: 
```bash
#!/bin/bash -eo pipefail
yarn semantic-release
yarn run v1.3.2
$ semantic-release
[Semantic release]: Running semantic-release version 15.1.3
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Verify GitHub authentication
[Semantic release]: An error occurred while running semantic-release: { HttpError: {"message":"Validation Failed","errors":[{"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/search/"}
    at response.text.then.message (/home/circleci/app/node_modules/@octokit/rest/lib/request/request.js:56:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HttpError',
  code: 422,
  status: undefined,
  headers: 
   { 'access-control-allow-origin': '*',
     'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
     'cache-control': 'no-cache',
     connection: 'close',
     'content-length': '306',
     'content-security-policy': 'default-src \'none\'',
     'content-type': 'application/json; charset=utf-8',
     date: 'Thu, 22 Mar 2018 23:22:57 GMT',
     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
     server: 'GitHub.com',
     status: '422 Unprocessable Entity',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-accepted-oauth-scopes': '',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-media-type': 'github.v3; format=json',
     'x-github-request-id': '9608:2A96:57B1F51:B6B0D87:5AB43AD1',
     'x-oauth-scopes': 'admin:repo_hook, read:org, read:user, repo, user:email',
     'x-ratelimit-limit': '30',
     'x-ratelimit-remaining': '26',
     'x-ratelimit-reset': '1521761029',
     'x-runtime-rack': '0.047652',
     'x-xss-protection': '1; mode=block' },
  pluginName: '@semantic-release/github' }
[Semantic release]: EGITNOPERMISSION The push permission to the Git repository is required.
semantic-release cannot push the version tag to the branch master on remote Git repository.

Please refer to the authentication configuration documentation (https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment.


{ SemanticReleaseError: The push permission to the Git repository is required.
    at module.exports (/home/circleci/app/node_modules/semantic-release/lib/get-error.js:6:10)
    at run (/home/circleci/app/node_modules/semantic-release/index.js:51:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'SemanticReleaseError',
  code: 'EGITNOPERMISSION',
  details: '**semantic-release** cannot push the version tag to the branch `master` on remote Git repository.\n\nPlease refer to the [authentication configuration documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment.',
  semanticRelease: true }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

**Comment by pvdlg** [comment]
It seems the user associated with the token you configured doesn't have push access to your repo.
Can your run semantic-release with the `--debug` option (or the `DEBUG` environment variable set to `semantic-release:*`) and post the logs?

Also what is the repository URL you configured in your `package.json`?

**Comment by juliocanares** [comment]
it actually pushes the release to my github repo, but I don't know why it shows that error.

**Comment by pvdlg** [comment]
According to the logs you provided, the verification error happens way before semantic-release push the tag or the release. Unless you provided the wrong logs, it's not semantic-release that create this release.
Can you provide the information requested?

**Comment by juliocanares** [comment]
yeah, I got back to circle ci and seen that there is actually 2 pipelines failing. 
One with the error I sent first, and another one with the following.

```bash
#!/bin/bash -eo pipefail
yarn semantic-release
yarn run v1.3.2
$ semantic-release
[Semantic release]: Running semantic-release version 15.1.3
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify GitHub authentication
[Semantic release]: Found git tag v1.1.1 associated with version 1.1.1
[Semantic release]: Found 10 commits since last release
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analyzing commit: Merge pull request #191 from riqra/initial-structure-for-roles-and-permissions

Initial database structure for roles and permissions
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: Merge pull request #181 from riqra/180-order-statuses-customized-by-distributor

Order statuses customized by distributor
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: Merge branch 'master' into 180-order-statuses-customized-by-distributor
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: refactor: changes filename for add-distributor-id and add-is-default-column in order statuses table
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: feat: adds initial database structure for roles and permissions
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analyzing commit: Merge pull request #189 from riqra/upgrade-semantic-release-to-v15.1.3

Updates semantic-release to v15.1.3
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: chore(package.json): updates semantic-release to v15.1.3
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: test(order-statuses.js): fixes orderStatuses root query
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: test: adds tests for custom distributor order statuses
[Semantic release]: The commit should not trigger a release
[Semantic release]: Analyzing commit: feat: adds database structure to have customized order statuses by distributor
[Semantic release]: The release type for the commit is minor
[Semantic release]: Analysis of 10 commits complete: minor release
[Semantic release]: The next release version is 1.2.0
[Semantic release]: Call plugin verify-release
[Semantic release]: Call plugin generateNotes
[Semantic release]: Call plugin prepare
[Semantic release]: Wrote version 1.2.0 to package.json
[Semantic release]: Create tag v1.2.0
[Semantic release]: Call plugin publish
[Semantic release]: Published GitHub release: https://github.com/riqra/riqra-saas-api/releases/tag/v1.2.0
[Semantic release]: An error occurred while running semantic-release: { HttpError: {"message":"Validation Failed","errors":[{"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/search/"}
    at response.text.then.message (/home/circleci/app/node_modules/@octokit/rest/lib/request/request.js:56:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HttpError',
  code: 422,
  status: undefined,
  headers: 
   { 'access-control-allow-origin': '*',
     'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
     'cache-control': 'no-cache',
     connection: 'close',
     'content-length': '306',
     'content-security-policy': 'default-src \'none\'',
     'content-type': 'application/json; charset=utf-8',
     date: 'Thu, 22 Mar 2018 23:24:13 GMT',
     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
     server: 'GitHub.com',
     status: '422 Unprocessable Entity',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-accepted-oauth-scopes': '',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-media-type': 'github.v3; format=json',
     'x-github-request-id': 'E8FE:5F56:29F6AFF:5AC1A0B:5AB43B1D',
     'x-oauth-scopes': 'admin:repo_hook, read:org, read:user, repo, user:email',
     'x-ratelimit-limit': '30',
     'x-ratelimit-remaining': '23',
     'x-ratelimit-reset': '1521761101',
     'x-runtime-rack': '0.035382',
     'x-xss-protection': '1; mode=block' },
  pluginName: '@semantic-release/github' }
{ HttpError: {"message":"Validation Failed","errors":[{"message":"The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them.","resource":"Search","field":"q","code":"invalid"}],"documentation_url":"https://developer.github.com/v3/search/"}
    at response.text.then.message (/home/circleci/app/node_modules/@octokit/rest/lib/request/request.js:56:19)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HttpError',
  code: 422,
  status: undefined,
  headers: 
   { 'access-control-allow-origin': '*',
     'access-control-expose-headers': 'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
     'cache-control': 'no-cache',
     connection: 'close',
     'content-length': '306',
     'content-security-policy': 'default-src \'none\'',
     'content-type': 'application/json; charset=utf-8',
     date: 'Thu, 22 Mar 2018 23:24:13 GMT',
     'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
     server: 'GitHub.com',
     status: '422 Unprocessable Entity',
     'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
     'x-accepted-oauth-scopes': '',
     'x-content-type-options': 'nosniff',
     'x-frame-options': 'deny',
     'x-github-media-type': 'github.v3; format=json',
     'x-github-request-id': 'E8FE:5F56:29F6AFF:5AC1A0B:5AB43B1D',
     'x-oauth-scopes': 'admin:repo_hook, read:org, read:user, repo, user:email',
     'x-ratelimit-limit': '30',
     'x-ratelimit-remaining': '23',
     'x-ratelimit-reset': '1521761101',
     'x-runtime-rack': '0.035382',
     'x-xss-protection': '1; mode=block' },
  pluginName: '@semantic-release/github' }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Exited with code 1
```

this is the pipeline that is pushing the release without saying anything about the `GITHUB_TOKEN`

**Comment by juliocanares** [comment]
I am also running the pipeline again with the `DEBUG` enabled.

**Comment by juliocanares** [comment]
@pvdlg 
this is what I got

```bash
#!/bin/bash -eo pipefail
yarn semantic-release
yarn run v1.3.2
$ semantic-release
[Semantic release]: Running semantic-release version 15.1.3
  semantic-release:config options values: { branch: 'master',
  semantic-release:config   repositoryUrl: 'https://github.com/riqra/riqra-graphql',
  semantic-release:config   tagFormat: 'v${version}',
  semantic-release:config   publish: 
  semantic-release:config    [ { path: '@semantic-release/npm', npmPublish: false },
  semantic-release:config      { path: '@semantic-release/github' } ],
  semantic-release:config   _: [],
  semantic-release:config   '$0': 'node_modules/.bin/semantic-release' } +0ms
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
  semantic-release:git Error: Command failed: git push --dry-run https://github.com/riqra/riqra-graphql HEAD:master
  semantic-release:git ERROR: The key you are authenticating with has been marked as read only.
  semantic-release:git fatal: Could not read from remote repository.
  semantic-release:git 
  semantic-release:git Please make sure you have the correct access rights
  semantic-release:git and the repository exists.
  semantic-release:git 
  semantic-release:git 
  semantic-release:git     at makeError (/home/circleci/app/node_modules/execa/index.js:172:9)
  semantic-release:git     at Promise.all.then.arr (/home/circleci/app/node_modules/execa/index.js:277:16)
  semantic-release:git     at <anonymous>
  semantic-release:git     at process._tickCallback (internal/process/next_tick.js:188:7) +0ms
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify GitHub authentication
  semantic-release:get-last-release found tags: [ { gitTag: 'v1.2.0', version: '1.2.0' }, { gitTag: 'v1.1.1', version: '1.1.1' }, { gitTag: 'v1.1.0', version: '1.1.0' }, { gitTag: 'v1.0.0', version: '1.0.0' } ] +0ms
[Semantic release]: Found git tag v1.2.0 associated with version 1.2.0
  semantic-release:get-commits Use gitHead: de4271c7d9cd78f40d7799a66642797319a8db5a +0ms
[Semantic release]: Found 0 commits since last release
  semantic-release:get-commits Parsed commits: [] +18ms
[Semantic release]: Call plugin analyze-commits
[Semantic release]: Analysis of 0 commits complete: no release
[Semantic release]: There are no relevant changes, so no new version is released.
Done in 2.08s.
```

**Comment by juliocanares** [comment]
this is the token scope

![image](https://user-images.githubusercontent.com/5007653/37805038-bfe7e97e-2e05-11e8-8812-7aa74262b99e.png)

**Comment by pvdlg** [comment]
All the logs you provided show different errors. It seems they were not generated with the same configuration...

First, you shouldn't have multiple pipeline running semantic-release. You should have only one that runs after all the test pipeline are successful as explain here: https://semantic-release.gitbooks.io/semantic-release/content/docs/usage/ci-configuration.html#run-semantic-release-only-after-all-tests-succeeded

 In one of the log you provided you have the error `ERROR: The key you are authenticating with has been marked as read only.` so it seems your token (or ssh key if you are using one) doesn't allow you to write to your repo.

In an other logs you have an error when semantic-release call the [search issue API](https://developer.github.com/v3/search/#search-issues): `The listed users and repositories cannot be searched either because the resources do not exist or you do not have permission to view them`.

The permission of the Token are correct, but probably the user associated with the token doesn't have the permission to push or search issues.

As requested before what is the repository URL configured in your package.json?
Is it `https://github.com/riqra/riqra-graphql`? Is this repo exists?

**Comment by pvdlg** [comment]
You have some logs that reference `https://github.com/riqra/riqra-saas-api` and other that reference `https://github.com/riqra/riqra-graphql` so it's really confusing.
Either mixup the logs you provided in this issue or you mixed up the repository urls in your package.json.

**Comment by juliocanares** [comment]
it does not exist, it was renamed to `riqra-saas-api`. in the package.json we still keep the `riqra-graphql`. I guess I must change it, but when I enter to `riqra-graphql` via github it redirects to `riqra-saas-api`

**Comment by juliocanares** [comment]
will try again with that change.

**Comment by juliocanares** [comment]
@pvdlg seems like it works now. thank you 🙌 🎉
