### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by ethanneff** [semantic-release/semantic-release#719]
```
$ semantic-release-cli setup
ERR! semantic-release TypeError: Cannot read property '0' of undefined
ERR! semantic-release     at getRegistry (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:89:7)
ERR! semantic-release     at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:105:16)
ERR! semantic-release     at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/index.js:84:11)
ERR! semantic-release     at <anonymous>
ERR! semantic-release  { TypeError: Cannot read property '0' of undefined
ERR! semantic-release     at getRegistry (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:89:7)
ERR! semantic-release     at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:105:16)
ERR! semantic-release     at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/index.js:84:11)
ERR! semantic-release     at <anonymous>
ERR! semantic-release   stack: 'TypeError: Cannot read property \'0\' of undefined\n    at getRegistry (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:89:7)\n    at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/lib/npm.js:105:16)\n    at module.exports (/usr/local/lib/node_modules/semantic-release-cli/src/index.js:84:11)\n    at <anonymous>' }
```

**Comment by ethanneff** [comment]
missing `name` field within `package.json`.
