### ISSUE TITLE
builtinModules.indexOf is not a function

### ISSUE THREAD

**Issue by jedwards1211** [semantic-release/semantic-release#751]
Perhaps the `is-builtin-module` package (at least version 1.0.0) can't be trusted:

```
[Semantic release]: Running semantic-release version 15.1.4
[Semantic release]: Load plugin verifyConditions from @semantic-release/npm
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/npm
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: Run automated release from branch master
[Semantic release]: Call plugin verify-conditions
[Semantic release]: Verify GitHub authentication
[Semantic release]: An error occurred while running semantic-release: { TypeError: builtinModules.indexOf is not a function
    at module.exports (/home/travis/build/jcoreio/react-view-slider/node_modules/is-builtin-module/index.js:9:24)
    at Object.fixNameField (/home/travis/build/jcoreio/react-view-slider/node_modules/normalize-package-data/lib/fixer.js:216:9)
    at /home/travis/build/jcoreio/react-view-slider/node_modules/normalize-package-data/lib/normalize.js:32:38
    at Array.forEach (<anonymous>)
    at normalize (/home/travis/build/jcoreio/react-view-slider/node_modules/normalize-package-data/lib/normalize.js:31:15)
    at pathType.dir.then.then.x (/home/travis/build/jcoreio/react-view-slider/node_modules/read-pkg/index.js:24:38)
    at <anonymous> pluginName: '@semantic-release/npm' }
```

**Comment by jedwards1211** [comment]
Nevermind, yarn seems to have messed up and put the `browserify-aes` package in the folder for `builtin-modules`.
