### ISSUE TITLE
semantic-release/exec not found in travis-ci build

### ISSUE THREAD

**Issue by texel-sensei** [semantic-release/semantic-release#779]
## Current behavior
Running on travis-ci the semantic-release/exec plugin is not found. Running semantic-release on my local machine works as expected.

Travis log:
```
+npx semantic-release@15
npx: installed 376 in 9.65s
[Semantic release]: Running semantic-release version 15.3.1
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/exec
[Semantic release]: An error occurred while running semantic-release: { Error: Cannot find module '@semantic-release/exec'
    at Function.Module._resolveFilename (module.js:547:15)
    at resolveFileName (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:41)
    at module.exports (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/lib/plugins/normalize.js:29:53)
    at plugins.(anonymous function).castArray.map.conf (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/lib/plugins/index.js:31:42)
    at Array.map (<anonymous>)
    at Object.keys.reduce (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/lib/plugins/index.js:31:30)
    at Array.reduce (<anonymous>)
    at module.exports (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/lib/plugins/index.js:10:52) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module '@semantic-release/exec'
    at Function.Module._resolveFilename (module.js:547:15)
    at resolveFileName (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:43:9)
    at module.exports (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/node_modules/resolve-from/index.js:46:41)
    at module.exports (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/lib/plugins/normalize.js:29:53)
    at plugins.(anonymous function).castArray.map.conf (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/lib/plugins/index.js:31:42)
    at Array.map (<anonymous>)
    at Object.keys.reduce (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/lib/plugins/index.js:31:30)
    at Array.reduce (<anonymous>)
    at module.exports (/home/travis/.npm/_npx/5818/lib/node_modules/semantic-release/lib/plugins/index.js:10:52) code: 'MODULE_NOT_FOUND' }
Script failed with status 1
```

Log on local machine:
```
> npx semantic-release                                                                                  (git)-[master]
[Semantic release]: Running semantic-release version 15.3.1
[Semantic release]: Load plugin verifyConditions from @semantic-release/github
[Semantic release]: Load plugin analyzeCommits from @semantic-release/commit-analyzer
[Semantic release]: Load plugin generateNotes from @semantic-release/release-notes-generator
[Semantic release]: Load plugin prepare from @semantic-release/exec
[Semantic release]: Load plugin publish from @semantic-release/github
[Semantic release]: Load plugin success from @semantic-release/github
[Semantic release]: Load plugin fail from @semantic-release/github
[Semantic release]: This run was not triggered in a known CI environment, running in dry-run mode.
```

## Expected behavior

Plugin should be found in CI as on local machine

## Environment

- **semantic-release** version: 15.3.1
- CI environment: Travis CI
- Plugins used: @semantic-release/github, @semantic-release/commit-analyzer, @semantic-release/release-notes-generator, @semantic-release/exec
- **semantic-release** configuration: https://github.com/texel-sensei/ayayaa/blob/master/.releaserc
- CI logs: [Travis log](https://travis-ci.org/texel-sensei/ayayaa/builds/375508463)

**Comment by pvdlg** [comment]
semantic-release comes with the `github` and `npm` plugin as they are the default ones.
For any other one you have to install them.
You can either add them as a `devDependency` if you have a `package.json` or globally with `npm install -g <plugin name>`.

**Comment by texel-sensei** [comment]
Thank you, that fixed it. Maybe add that to the docs somewhere, for me it was not clear that only two plugins are shipped per default.

Especially the documentation for non javascript projects makes it look like you just have to do a `npm install -g semantic-release`.
