### ISSUE TITLE
Wrong GL_TOKEN passed to semantic-release

### ISSUE THREAD

**Issue by kopax** [semantic-release/semantic-release#871]
I am setting using the git credentials store a new `GL_TOKEN`, the default one from `Gitlab-CI` doesn't allow push.

## Reproduciton

This help me set my `personal_access_token` so `@semantic-release/git` can push.

```sh
$ mkdir -p /root/.config/git
$ echo https://gitlab-ci-token:s4cR4tPers0n4lKey@gitlab.example.com/ > /root/.config/git/credentials
$ git config --global credential.helper store
$  GL_TOKEN=s4cR4tPers0n4lKey npx semantic-release --debug
```

## Expected

I expect to use the new personal access token during the release.

## Result

It use the default CI token, not the newly set `GL_TOKEN`, the error look like: 

```sh
[Semantic release]: Running semantic-release version 15.8.1
2018-07-26T13:19:53.472Z semantic-release:config options values: { branch: 'master',
  repositoryUrl: 'https://module.example.com/basic/email-templates.git',
  tagFormat: 'v${version}',
  success: false,
  fail: false,
  npmPublish: true,
  verifyConditions:
   [ '@semantic-release/changelog',
     '@semantic-release/npm',
     '@semantic-release/git',
     { path: '@semantic-release/gitlab',
       gitlabUrl: 'https://gitlab.example.com' } ],
  prepare:
   [ '@semantic-release/changelog',
     '@semantic-release/npm',
     { path: '@semantic-release/git', assets: [Array] } ],
  publish:
   [ '@semantic-release/npm',
     { path: '@semantic-release/gitlab',
       gitlabUrl: 'https://gitlab.example.com' },
    ],
  _: [],
  debug: true,
  '$0': 'node_modules/.bin/semantic-release' }
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/changelog
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/npm
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/git
[Semantic release]: Load plugin "verifyConditions" from @semantic-release/gitlab
[Semantic release]: Load plugin "analyzeCommits" from @semantic-release/commit-analyzer
[Semantic release]: Load plugin "generateNotes" from @semantic-release/release-notes-generator
[Semantic release]: Load plugin "prepare" from @semantic-release/changelog
[Semantic release]: Load plugin "prepare" from @semantic-release/npm
[Semantic release]: Load plugin "prepare" from @semantic-release/git
[Semantic release]: Load plugin "publish" from @semantic-release/npm
[Semantic release]: Load plugin "publish" from @semantic-release/gitlab
2018-07-26T13:19:54.263Z semantic-release:git Error: Command failed: git push --dry-run https://gitlab.example.com/basic/email-templates.git HEAD:master
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.example.com/basic/email-templates.git/'
    at makeError (/mnt/mesos/sandbox/builds/basic/email-templates/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/mnt/mesos/sandbox/builds/basic/email-templates/node_modules/execa/index.js:277:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2018-07-26T13:19:54.478Z semantic-release:git Error: Command failed: git push --dry-run https://gitlab-ci-token:[secure]@gitlab.example.com/basic/email-templates.git HEAD:master
remote: The project you were looking for could not be found.
fatal: repository 'https://gitlab-ci-token:[secure]@gitlab.example.com/basic/email-templates.git/' not found  at makeError (/mnt/mesos/sandbox/builds/basic/email-templates/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/mnt/mesos/sandbox/builds/basic/email-templates/node_modules/execa/index.js:277:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2018-07-26T13:19:54.824Z semantic-release:git Error: Command failed: git ls-remote --heads origin master
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab-ci-token:Z4nQXqhK7Qp1W8vcXrPP@gitlab.example.com/basic/email-templates.git/'
    at makeError (/mnt/mesos/sandbox/builds/basic/email-templates/node_modules/execa/index.js:172:9)
    at Promise.all.then.arr (/mnt/mesos/sandbox/builds/basic/email-templates/node_modules/execa/index.js:277:16)
    at process._tickCallback (internal/process/next_tick.js:68:7)
[Semantic release]: The local branch master is behind the remote one, therefore a new version won't be published.
```

## Version

- semantic-release 15.8.1
- @semantic-release/changelog 3.0.0
- @semantic-release/git 7.0.1
- @semantic-release/gitlab 2.1.4
- @semantic-release/npm 4.0.1

## Question

- The error message state `The local branch master is behind the remote one, therefore a new version won't be published.`, shouldn't have it been corrected in #838 ?
- How/where does [`@param {String} origin The remote repository URL.`](https://github.com/semantic-release/git/blob/master/lib/git.js#L45) is retrieved by `semantic-release` ?

**Comment by kopax** [comment]
What a shame when I realized the group was not containing the proper user that own the token. Sorry for opening this.
