### ISSUE TITLE
semantic-release fails with "TypeError: Path must be a string"

### ISSUE THREAD

**Issue by jwalton** [semantic-release/semantic-release#891]
## Current behavior

```
[Semantic release]: An error occurred while running semantic-release: { TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1171:7)
    at module.exports (/home/travis/build/benbria/node-amqp-connection-manager/node_modules/@semantic-release/changelog/lib/prepare.js:7:30)
    at prepare (/home/travis/build/benbria/node-amqp-connection-manager/node_modules/@semantic-release/changelog/index.js:25:9)
    at Object.defineProperty (/home/travis/build/benbria/node-amqp-connection-manager/node_modules/semantic-release/lib/plugins/normalize.js:44:30)
    at pReduce (/home/travis/build/benbria/node-amqp-connection-manager/node_modules/semantic-release/lib/plugins/pipeline.js:36:40)
    at Promise.all.then.value (/home/travis/build/benbria/node-amqp-connection-manager/node_modules/p-reduce/index.js:16:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) pluginName: '@semantic-release/changelog' }
{ TypeError: Path must be a string. Received undefined
    at assertPath (path.js:28:11)
    at Object.resolve (path.js:1171:7)
    at module.exports (/home/travis/build/benbria/node-amqp-connection-manager/node_modules/@semantic-release/changelog/lib/prepare.js:7:30)
    at prepare (/home/travis/build/benbria/node-amqp-connection-manager/node_modules/@semantic-release/changelog/index.js:25:9)
    at Object.defineProperty (/home/travis/build/benbria/node-amqp-connection-manager/node_modules/semantic-release/lib/plugins/normalize.js:44:30)
    at pReduce (/home/travis/build/benbria/node-amqp-connection-manager/node_modules/semantic-release/lib/plugins/pipeline.js:36:40)
    at Promise.all.then.value (/home/travis/build/benbria/node-amqp-connection-manager/node_modules/p-reduce/index.js:16:10)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) pluginName: '@semantic-release/changelog' }
```
See full log here: https://travis-ci.org/benbria/node-amqp-connection-manager/jobs/414246609

Doing a "dry run" locally does not reproduce the problem.

## Expected behavior

Semantic-release should publish a release.

## Environment

- **semantic-release** version: ^15.2.0
- CI environment: Travis
- Plugins used: @semantic-release/changelog
- **semantic-release** configuration: https://github.com/benbria/node-amqp-connection-manager/blob/master/release.config.js
- CI logs: https://travis-ci.org/benbria/node-amqp-connection-manager/jobs/414246609

**Comment by jwalton** [comment]
Oops.  Just realized semantic-release/changelog needs semantic-release >= 15.8.0.  That's probably the issue.

**Comment by jwalton** [comment]
Yup, I'm dumb.  :)
