### ISSUE TITLE
Tag is created & pushed before publish steps, i.e. even if publish fails

### ISSUE THREAD

**Issue by felixfbecker** [semantic-release/semantic-release#896]
## Current behavior

I had an issue where the publish step failed. But the git tag seems to be created and pushed between the prepare and publish phase. So when I retried the build, semantic-release would not reattempt the release, because it would detect the git tag and assume the release was successful.

## Expected behavior

It's fine to create the git tag locally, but it should only be pushed after all publish steps succeeded.

## Environment

- **semantic-release** version: 15.9.6
- CI environment: Buildkite
- Plugins used: 
- **semantic-release** configuration: 
- CI logs:

**Comment by pvdlg** [comment]
The tag is pushed to the remote between the `prepare` and `publish` steps because some plugins, such as `apm` require to have the tag on the remote.

For example, when running `apm` publish` it will:
- Check if the tag exist on the remote repo
- Publish the package referencing the URL of that tag

I though about deleting the remote tag in case the `publish` step fails, but that might create other issues in case some `publish` fails but other succeed. For example is the `apm` plugin create the release but the `github` plugin fails, if we delete the tag then the apm release will probably be broken.
If we re-run semantic-release and try to publish the apm release it will probably fails.

Similarly if the npm publish works but the github fails, if we delete the tag, then on next run npm will try to release the same version again and fails as it's not allowed by the registry.

One solution I thought about would be to maintain a "state" of which plugin was successful, so when semantic-release re-run it would call only the plugin that previously failed. But the only way for semantic-release to maintain a "state" between execution is via tags.

So we would have to do something like that:
- After `prepare` and before `publish`, create a tag like `v${version}#{pluginName}` for each `publish` plugin configured, in addition of the regular one
- Call each `publish` plugin (passing the regular tag as of now)
- For each `publish` successful remove the corresponding `v${version}#{pluginName}` tag
- For each semantic-release run, check if there is a `v${version}#{pluginName}`, and in such case re-re-run the corresponding `publish` plugin and delete the tag if successful

I din't think too much about all the edge cases though, and I'm sure there would be a lot. Also, it kind of feel like abuse the tag system and it might be problematic and confusing for some users (if one trigger something based on tag creation for example) to have all those tags lingering.

**Comment by felixfbecker** [comment]
Ah, that makes sense.
The only way I see to make this reliable is to reintroduce `get-last-release` plugins, and have semantic-release ask each publish step individually what its last release was, so some publish step might have to retry a previously failed publish while the other had succeeded and does nothing.

**Comment by pvdlg** [comment]
That wouldn't solve the problem as some platform might not provide a good way to figure out what was the last version released. In addition that would create a huge complexity to handle cases where two plugins return different versions for the last release.

It would also force every plugin with a `publish` step to implement a `get-last-release` one.

This is why we choose to use Git tags only:
- One source of truth for versionning: the tag which is attached to the codebase
- Works independently of the features provided by package manager (it doesn't matter if the provider doesn't allow to search previous releases)
- Make plugin development more simple

**Comment by pvdlg** [comment]
Another solution to explore would be to offer users the possibility to run locally `semantic-release recover <tag>` which would be interactive and allow them to choose each `publish` plugin if they want to run it.
When a `publish` plugin fails we could add something to the error message mentioning to use this command to re-run the failed plugin.
It's not the most automated way possible to recover, but it would give more flexibility as I don't think we can automatically handle all recovery cases in an automated way, or at least not without a huge added complexity.

**Comment by felixfbecker** [comment]
That would be amazing. I've needed to "correct" so many half-done releases in my time of using semantic-release.

**Comment by felixfbecker** [comment]
I just met this again, the Chrome extension release failed because of a `503 Service Unavailable`, leaving the Firefox extension released, but not Chrome, and not GitHub or npm (because the plugins happen to be specified in that order) and no easy way to retry only the missing releases.

```
[8:08:53 PM] [semantic-release] › ℹ  Start step "publish" of plugin "semantic-release-chrome"
[8:09:18 PM] [semantic-release] › ✖  Failed step "publish" of plugin "semantic-release-chrome"
[8:09:18 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { HTTPError: Response code 503 (Service Unavailable)
    at stream.catch.then.data (/home/travis/build/sourcegraph/browser-extensions/node_modules/got/index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message: 'Response code 503 (Service Unavailable)',
  host: 'www.googleapis.com',
  hostname: 'www.googleapis.com',
  method: 'POST',
  path:
   '/chromewebstore/v1.1/items/dgjhfomjieaadpoljlnidmbgkdffpack/publish?publishTarget=default',
  statusCode: 503,
  statusMessage: 'Service Unavailable',
  pluginName: 'semantic-release-chrome' }
{ HTTPError: Response code 503 (Service Unavailable)
    at stream.catch.then.data (/home/travis/build/sourcegraph/browser-extensions/node_modules/got/index.js:123:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  message: 'Response code 503 (Service Unavailable)',
  host: 'www.googleapis.com',
  hostname: 'www.googleapis.com',
  method: 'POST',
  path:
   '/chromewebstore/v1.1/items/dgjhfomjieaadpoljlnidmbgkdffpack/publish?publishTarget=default',
  statusCode: 503,
  statusMessage: 'Service Unavailable',
  pluginName: 'semantic-release-chrome' }
```

**Comment by mike-north** [comment]
I have hit this a few times in cases where my npm credentials for publish are valid, but publish is set up to require 2FA. Somehow I get through the `verifyConditions` phase (i.e., my npm user has rights to write to the registry for this package) and then fail at the publish step.

In my case, I'm left with github releases going through, but the npm package is left behind. Maybe some subset of these problems can be handled by more robust `verifyConditions` steps?

**Comment by pvdlg** [comment]
@mike-north see https://github.com/semantic-release/npm/issues/11 and https://github.com/semantic-release/npm/issues/93.

I'm also working on a solution that would allow to publish npm package with 2FA enable for publish. The solution would to publish to a temporary server and send an email to the package owner. The package owner would then login to a UI and enter their one-time password to do the actual publish to the real npm registry.

**Comment by pie-r** [comment]
Interested on that, but I think there is not easy solution to solve this issue. There are a lot of edge cases.
In my case I'm planning to manually push from my localhost if something is wrong in the publish step!

**Comment by nelson6e65** [comment]
There is a way to retry the publishing? In my case, there was an error in my `.npmrc`. Git tag created, but the `publish` step failed. I solved, but old git tag version has not the releases changes on GitHub. 😅
