### ISSUE TITLE
Invalid NPM_TOKEN attempting to release with --no-ci option

### ISSUE THREAD

**Issue by ryexley** [semantic-release/semantic-release#899]
## Current behavior

I'm attempting to release a package locally using the `--no-ci` option, but every time I try to run it with `--dry-run` option (just to make sure that everything is working as expected) I get an error in the `verifyConditions` step from the `@semantic-release/npm` plugin telling me that the `NPM_TOKEN` environment variable that I have setup (which was generated by using `semantic-release-cli setup`) is invalid. I'm not sure what it is I'm doing wrong here. This is my first time trying out semantic-release, so I'm not sure if there's something that I've missed in configuration or what.

Having run `semantic-release-cli setup` successfully with no errors, my `package.json` file was updated as expected. I am wanting to release a publicly accessibly scoped package, so I updated it to also include:

```json
"publishConfig": {
	"access": "public"
}
```

My release task looks like this: `"release": "semantic-release --no-ci"` (yes, I modified it slightly, but only changed the task name to be slightly less verbose is all). So now, when I run `npm run release -- --dry-run` from the command line, I get the following output:

```
[08:23:26] [semantic-release] › ℹ  Running semantic-release version 15.9.8
[08:23:26] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
[08:23:27] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"
[08:23:27] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[08:23:27] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[08:23:27] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[08:23:27] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[08:23:27] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[08:23:27] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[08:23:27] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[08:23:27] [semantic-release] › ✔  Run automated release from branch master
[08:23:28] [semantic-release] › ✔  Allowed to push to the Git repository
[08:23:28] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
[08:23:28] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[08:23:30] [semantic-release] › ✖  Failed step "verifyConditions" of plugin "@semantic-release/npm"
[08:23:30] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/github"
[08:23:30] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
[08:23:30] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/github"
[08:23:30] [semantic-release] › ✖  EINVALIDNPMTOKEN Invalid npm token.
The npm token (https://github.com/semantic-release/npm/blob/master/README.md#npm-registry-authentication) configured in the NPM_TOKEN environment variable must be a valid token (https://docs.npmjs.com/getting-started/working_with_tokens) allowing to publish to the registry https://registry.npmjs.org/.

If you are using Two-Factor Authentication, make configure the auth-only level (https://docs.npmjs.com/getting-started/using-two-factor-authentication#levels-of-authentication) is supported. semantic-release cannot publish with the default auth-and-writes level.

Please make sure to set the NPM_TOKEN environment variable in your CI with the exact value of the npm token.

{ AggregateError:
    SemanticReleaseError: Invalid npm token.
        at module.exports (/Users/me/path/to/my/project/node_modules/@semantic-release/npm/lib/get-error.js:6:10)
        at module.exports (/Users/me/path/to/my/project/node_modules/@semantic-release/npm/lib/verify-auth.js:21:33)
        at <anonymous>
    at /Users/me/path/to/my/project/node_modules/semantic-release/lib/plugins/pipeline.js:53:11
```

I was able to verify that the token that was generated by the setup command actually exists on npm in my profile there. I added it as an export to my `.zshrc` file, and when I run `echo $NPM_TOKEN` I get the expected value for it. I'm not using 2FA, so I don't believe that is a factor.

Anyone have any ideas of what I'm missing here? I'm not using CI for this particular package, and would really like to be able to just run it locally to manually handle my releases. Am I misunderstanding that being an option for how to use the tool? Any nudge in the right direction would be greatly appreciated. Thanks.

## Expected behavior

I'm expecting a successful dry run of a local release.

## Environment

- **semantic-release** version: 15.9.8
- CI environment: none
- Plugins used: Whatever the defaults are, I've not configured anything differently.
- **semantic-release** configuration: no custom config file, just passing the `--no-ci` flag on the CLI
- CI logs: n/a (as far as I know)

**Comment by pvdlg** [comment]
The `semantic-release-cli setup` creates a token on npmjs.com and add it to Travis but doesn't set it locally. Once created on npmjs.com a token cannot be displayed anymore, so I guess what you configured in your local `NPM_TOKEN` environment variable is not that one.

Just create a token with `npm token create` and then export the value with `export NPM_TOKEN=<the_token_return_by_npm_command>`.

**Comment by ryexley** [comment]
That did it. Thanks so much.
