### ISSUE TITLE
Not able to push the version tag `git push --dry-run` are redirected to authentication page

### ISSUE THREAD

**Issue by XiaZhang0414** [semantic-release/semantic-release#904]
## Current behavior
I run `npm run semantic-release` in travis for deployment. But it deployment is always fail because of error like

```{ SemanticReleaseError: The push permission to the Git repository is required.

    at module.exports (/home/travis/build/digital-marketplace/ibmdbg-messagehub/node_modules/semantic-release/lib/get-error.js:6:10)

    at run (/home/travis/build/digital-marketplace/ibmdbg-messagehub/node_modules/semantic-release/index.js:71:11)

    at process._tickCallback (internal/process/next_tick.js:68:7)

  name: 'SemanticReleaseError',

  code: 'EGITNOPERMISSION',

  details:

   '**semantic-release** cannot push the version tag to the branch `master` on remote Git repository with URL `https://[secure]@github.ibm.com/digital-marketplace/ibmdbg-messagehub`.\n\nPlease refer to the [authentication configuration documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#repositoryurl) is configured with a [valid Git URL](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).',

  semanticRelease: true }
```

## Expected behavior
`npm run semantic-release` show run successfully and push the  version tag to the branch master

## Environment

- **semantic-release** version: 15.9.9
- CI environment: travis ci enterprise, GH_TOKEN , NPM_TOKEN and NPM_USERNAME are added as environment variables
- Plugins used: @semantic-release/github, @semantic-release/npm, @semantic-release/changelog
- **semantic-release** configuration: in package.json
```
"release": {
    "tagFormat": "v${version}",
    "verifyConditions": [
      "@semantic-release/changelog",
      "@semantic-release/github",
      "@semantic-release/npm"
    ],
    "prepare": [
      "@semantic-release/changelog",
      "@semantic-release/npm"
    ],
    "publish": [
      "@semantic-release/github",
      "@semantic-release/npm"
    ],
    "fail": [
      "@semantic-release/github"
    ],
    "githubUrl": "https://github.ibm.com",
    "githubApiPathPrefix": "/api/v3"
  }
```
- CI logs: 
```
[7:37:02 PM] [semantic-release] › ℹ  Running semantic-release version 15.9.9

[7:37:02 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/changelog"

[7:37:03 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/github"

[7:37:03 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"

[7:37:03 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"

[7:37:03 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"

[7:37:03 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/changelog"

[7:37:03 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"

[7:37:03 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"

[7:37:03 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"

[7:37:03 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"

[7:37:03 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"

[7:37:03 PM] [semantic-release] › ✔  Run automated release from branch master

[7:37:05 PM] [semantic-release] › ✖  The command "git push --dry-run https://[secure]@github.ibm.com/path/to/repo HEAD:master" failed with the error message fatal: unable to update url base from redirection:

  asked for: https://[secure]@github.ibm.com/github.ibm.com/path/to/repo/info/refs?service=git-receive-pack

   redirect: https://w3id.sso.ibm.com/auth/sps/samlidp/saml20/logininitial?RequestBinding=HTTPPost&PartnerId=https://github.ibm.com&NameIdFormat=email

.

[7:37:05 PM] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"

[7:37:05 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication (https://github.ibm.com/api/v3)

[7:37:05 PM] [semantic-release] [@semantic-release/github] › ℹ  Found existing semantic-release issue #40.

[7:37:08 PM] [semantic-release] [@semantic-release/github] › ℹ  Added comment to issue #40: https://github.ibm.com/digital-marketplace/ibmdbg-messagehub/issues/40#issuecomment-7366506.

[7:37:08 PM] [semantic-release] › ✔  Completed step "fail" of plugin "@semantic-release/github"

[7:37:08 PM] [semantic-release] › ✖  EGITNOPERMISSION The push permission to the Git repository is required.

semantic-release cannot push the version tag to the branch master on remote Git repository with URL https://[secure]@github.ibm.com/path/to/repo.

Please refer to the authentication configuration documentation (https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the repositoryUrl (https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#repositoryurl) is configured with a valid Git URL (https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).

{ SemanticReleaseError: The push permission to the Git repository is required.

    at module.exports (/home/travis/build/path/to/repo/node_modules/semantic-release/lib/get-error.js:6:10)

    at run (/home/travis/build/path/to/repo/node_modules/semantic-release/index.js:71:11)

    at process._tickCallback (internal/process/next_tick.js:68:7)

  name: 'SemanticReleaseError',

  code: 'EGITNOPERMISSION',

  details:

   '**semantic-release** cannot push the version tag to the branch `master` on remote Git repository with URL `https://[secure]@github.ibm.com/digital-marketplace/ibmdbg-messagehub`.\n\nPlease refer to the [authentication configuration documentation](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/ci-configuration.md#authentication) to configure the Git credentials on your CI environment and make sure the [repositoryUrl](https://github.com/semantic-release/semantic-release/blob/caribou/docs/usage/configuration.md#repositoryurl) is configured with a [valid Git URL](https://git-scm.com/book/en/v2/Git-on-the-Server-The-Protocols).',

  semanticRelease: true }npm ERR! code ELIFECYCLE

npm ERR! errno 1

npm ERR! @owb-digital/ibmdbg-messagehub@0.0.0-development semantic-release: `semantic-release`

npm ERR! Exit status 1

npm ERR! 

npm ERR! Failed at the @owb-digital/ibmdbg-messagehub@0.0.0-development semantic-release script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

npm ERR!     /home/travis/.npm/_logs/2018-08-20T19_37_08_830Z-debug.log
```

**Comment by pvdlg** [comment]
Semantic-release needs to be able to execute `git` commands to the remote repo you configured in the `repository` fields of your `package.json`.
It seems that with the URL and authentication you configured your GitHub instance returns a redirect.
```
The command "git push --dry-run https://[secure]@github.ibm.com/path/to/repo HEAD:master" failed with the error message fatal: unable to update url base from redirection:

  asked for: https://[secure]@github.ibm.com/github.ibm.com/path/to/repo/info/refs?service=git-receive-pack

   redirect: https://w3id.sso.ibm.com/auth/sps/samlidp/saml20/logininitial?RequestBinding=HTTPPost&PartnerId=https://github.ibm.com&NameIdFormat=email
```

It seems it's related to your SSO configuration. There is nothing we can do here, you have to configure your environment to allow `git` commands.

**Comment by XiaZhang0414** [comment]
@pvdlg But there is still something I don't understand. I run the command `npm run semantic-release` in travis enterprise. I got above when I run the semantic-release in travis deploy stage:
```
deploy:
 deploy:
   skip_cleanup: true
   skip_cleanup: true
   provider: script
   provider: script
   script: npm run semantic-release
   script: npm run semantic-release
   on:
   on:
     tags: false
     tags: false
     branch: master
     branch: master
node: 10.6.0
```

But if I run the semantic-release in after-success stage, it works fine.
```
after_success:
  - echo ".travis.yml" >> ./.npmignore
  - echo "coverage" >> ./.npmignore
  - npm run prepublishOnly
  - npm run upload-coverage
- npm run semantic-release
```

**Comment by XiaZhang0414** [comment]
@travi When I said works fine, I mean the semantic-release can successfully publish the package to GitHub and npm registry (when I run semantic-release in the travis after_success stage). I get the GitHub authentication issue when I ran semantic-release in deploy stage.

**Comment by pvdlg** [comment]
The Travis stage in which you run semantic-release doesn't affect the authentication.
So it might be some interaction between your SSO and the Travis stage.
