### ISSUE TITLE
Semantic Release 15.9 / Generate release notes 7.0.0 introduces regression for ecosystem plugins

### ISSUE THREAD

**Issue by jimthedev** [semantic-release/semantic-release#909]
## Current behavior

The current behavior is best described here https://github.com/Updater/semantic-release-monorepo/issues/52

## Expected behavior

The desired behavior is that the error described would not be thrown when publishing. 

## Environment

- **semantic-release** version: 15.9
- CI environment: drone/travis/any
- Plugins used: generate release notes
- **semantic-release** configuration: 
- CI logs: 

```
[5:18:28 PM] [semantic-release] [[Function: ]] › ℹ  The release type for the commit is minor
[5:18:28 PM] [semantic-release] [[Function: ]] › ℹ  Analysis of 1 commits complete: minor release
[5:18:28 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "[Function: ]"
[5:18:28 PM] [semantic-release] › ℹ  The next release version is 4.4.0
[5:18:28 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "[Function: ]"
[5:18:28 PM] [semantic-release] › ✖  Failed step "generateNotes" of plugin "[Function: ]"
[5:18:28 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { TypeError: Expected `moduleId` to be of type `string`, got `object`
    at resolveFrom (/drone/src/github.com/org/my-package/node_modules/resolve-from/index.js:11:9)
    at module.exports (/drone/src/github.com/org/my-package/node_modules/resolve-from/index.js:34:41)
    at module.exports (/drone/src/github.com/org/my-package/node_modules/import-from/index.js:4:49)
    at requirePlugin (/drone/src/github.com/org/my-package/node_modules/semantic-release-plugin-decorators/src/index.js:4:33)
    at resolvePluginFn (/drone/src/github.com/org/my-package/node_modules/semantic-release-plugin-decorators/src/index.js:18:18)
    at /drone/src/github.com/org/my-package/node_modules/semantic-release-plugin-decorators/src/index.js:26:20
    at validator (/drone/src/github.com/org/my-package/node_modules/semantic-release/lib/plugins/normalize.js:34:28)
    at pReduce (/drone/src/github.com/org/my-package/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/drone/src/github.com/org/my-package/node_modules/p-reduce/index.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '[Function: ]' }
{ TypeError: Expected `moduleId` to be of type `string`, got `object`
    at resolveFrom (/drone/src/github.com/org/my-package/node_modules/resolve-from/index.js:11:9)
    at module.exports (/drone/src/github.com/org/my-package/node_modules/resolve-from/index.js:34:41)
    at module.exports (/drone/src/github.com/org/my-package/node_modules/import-from/index.js:4:49)
    at requirePlugin (/drone/src/github.com/org/my-package/node_modules/semantic-release-plugin-decorators/src/index.js:4:33)
    at resolvePluginFn (/drone/src/github.com/org/my-package/node_modules/semantic-release-plugin-decorators/src/index.js:18:18)
    at /drone/src/github.com/org/my-package/node_modules/semantic-release-plugin-decorators/src/index.js:26:20
    at validator (/drone/src/github.com/org/my-package/node_modules/semantic-release/lib/plugins/normalize.js:34:28)
    at pReduce (/drone/src/github.com/org/my-package/node_modules/semantic-release/lib/plugins/pipeline.js:37:40)
    at Promise.all.then.value (/drone/src/github.com/org/my-package/node_modules/p-reduce/index.js:16:10)
    at process._tickCallback (internal/process/next_tick.js:68:7) pluginName: '[Function: ]' }lerna ERR! exec Errored while executing 'npm whoami --registry=https://orginc.jfrog.io/orginc/api/npm/npm/ && npx --no-install semantic-release -e semantic-release-monorepo' in '@org/my-package'
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm whoami --registry=https://orginc.jfrog.io/orginc/api/npm/npm/ && npx --no-install semantic-release -e semantic-release-monorepo
lerna ERR!     at Promise.all.then.arr (/drone/src/github.com/org/my-package/node_modules/lerna/node_modules/execa/index.js:236:11)
{ Error: Command failed: npm whoami --registry=https://orginc.jfrog.io/orginc/api/npm/npm/ && npx --no-install semantic-release -e semantic-release-monorepo
    at Promise.all.then.arr (/drone/src/github.com/org/my-package/node_modules/lerna/node_modules/execa/index.js:236:11)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  code: 1,
  killed: false,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd:
   'npm whoami --registry=https://orginc.jfrog.io/orginc/api/npm/npm/ && npx --no-install semantic-release -e semantic-release-monorepo',
  timedOut: false,
  exitCode: 1 }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by pvdlg** [comment]
How is that a problem with semantic-release?
The error logs show that `semantic-release-plugin-decorators/src/index.js:18:18` calls `import-from` passing an object instead of a string in the second argument.

**Comment by pvdlg** [comment]
Closing as it's not related to semantic-release and no answer was provided in almost 10 days.
