### ISSUE TITLE
Release crashes because tag already exists but tag did not exist before semantic-release was run

### ISSUE THREAD

**Issue by adrianschmidt** [semantic-release/semantic-release#912]
## Current behavior

`semantic-release` correctly creates a new tag, and pushes the release to GitHub, but then fails, seemingly because it tries to push the same tag again.

## Expected behavior

`semantic-release` should not try to push the same tag twice, and therefore not fail on release.

## Environment

- **semantic-release** version: 15.9.12
- CI environment: Jenkins
- Plugins used: `@semantic-release/npm` and `@semantic-release/github`
- **semantic-release** configuration: 
```json
  "release": {
    "branch": "master",
    "verifyConditions": [
      "@semantic-release/npm",
      "@semantic-release/github"
    ],
    "prepare": [
      "@semantic-release/npm"
    ],
    "publish": [
      "@semantic-release/npm",
      "@semantic-release/github"
    ],
    "npmPublish": true
  }
```
- CI logs:
```
[13:52:18] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 11 commits complete: patch release
[13:52:18] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[13:52:18] [semantic-release] › ℹ  The next release version is 3.4.1
[13:52:18] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[13:52:18] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[13:52:18] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[13:52:18] [semantic-release] [@semantic-release/npm] › ℹ  Wrote version 3.4.1 to /lime/package.json
[13:52:18] [semantic-release] [@semantic-release/npm] › ℹ  Wrote version 3.4.1 to /lime/package-lock.json
[13:52:18] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[13:52:21] [semantic-release] › ✖  An error occurred while running semantic-release: { Error: Command failed: git push --tags https://[secure]@github.com/Lundalogik/lime-elements.git HEAD:master
To https://[secure]@github.com/Lundalogik/lime-elements.git
 ! [remote rejected] v3.4.1 -> v3.4.1 (cannot lock ref 'refs/tags/v3.4.1': reference already exists)
error: failed to push some refs to 'https://[secure]@github.com/Lundalogik/lime-elements.git'


    at makeError (/lime/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/lime/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: 1,
  stdout: '',
  stderr: 'To https://[secure]@github.com/Lundalogik/lime-elements.git\n ! [remote rejected] v3.4.1 -> v3.4.1 (cannot lock ref \'refs/tags/v3.4.1\': reference already exists)\nerror: failed to push some refs to \'https://[secure]@github.com/Lundalogik/lime-elements.git\'\n',
  failed: true,
  signal: null,
  cmd: 'git push --tags https://[secure]@github.com/Lundalogik/lime-elements.git HEAD:master',
  timedOut: false,
  killed: false }
{ Error: Command failed: git push --tags https://[secure]@github.com/Lundalogik/lime-elements.git HEAD:master
To https://[secure]@github.com/Lundalogik/lime-elements.git
 ! [remote rejected] v3.4.1 -> v3.4.1 (cannot lock ref 'refs/tags/v3.4.1': reference already exists)
error: failed to push some refs to 'https://[secure]@github.com/Lundalogik/lime-elements.git'


    at makeError (/lime/node_modules/semantic-release/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/lime/node_modules/semantic-release/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  code: [33m1[39m,
  stdout: [32m''[39m,
  stderr: [32m'To https://[secure]@github.com/Lundalogik/lime-elements.git\n ! [remote rejected] v3.4.1 -> v3.4.1 (cannot lock ref \'refs/tags/v3.4.1\': reference already exists)\nerror: failed to push some refs to \'https://[secure]@github.com/Lundalogik/lime-elements.git\'\n'[39m,
  failed: [33mtrue[39m,
  signal: [1mnull[22m,
  cmd: [32m'git push --tags https://[secure]@github.com/Lundalogik/lime-elements.git HEAD:master'[39m,
  timedOut: [33mfalse[39m,
  killed: [33mfalse[39m }npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! lime-elements@0.0.0-development publish: `npm run build && semantic-release`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the lime-elements@0.0.0-development publish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-08-31T13_52_21_598Z-debug.log
Makefile:26: recipe for target 'release' failed
make: *** [release] Error 1
[Pipeline] }
[Pipeline] // script
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // withCredentials
[Pipeline] }
[Pipeline] // stage
[Pipeline] }
[Pipeline] // withEnv
[Pipeline] }
[Pipeline] // node
[Pipeline] End of Pipeline

GitHub has been notified of this commit’s build result

ERROR: script returned exit code 2
Finished: FAILURE
```

**Comment by pvdlg** [comment]
It's probably because you already have the tag `v3.4.1` somewhere, but semantic-release doesn't find it because it's not in the history of the release branch.
You should delete this tag if it doesn't correspond to a release.

**Comment by adrianschmidt** [comment]
Well, that's the first thing I checked, and it's happened with three consecutive builds now, so I'm fairly sure the tag doesn't already exist.

Also, if they already existed before the release started, I think the release would fail when first pushing to GitHub. It doesn't. It creates the release just fine, with change-log and all. And the time of creation for the release and the tag seems to match as well.

It seems to me like it's just trying to push the tag twice…?

**Comment by pvdlg** [comment]
> Also, if they already existed before the release started, I think the release would fail when first pushing to GitHub. It doesn't. It creates the release just fine, with change-log and all. And the time of creation for the release and the tag seems to match as well.

Not according to the logs you provided. In those logs semantic-release fails on creating the tag, which happens before anything is published. No release is created by semantic-release here.

> It seems to me like it's just trying to push the tag twice…?

There is no indication of that in the logs you provided. And the problem doesn't seems to happen for anyone else.

Have you run `git tag` to verify `v3.4.1` doesn't exists?
What do you get from `git rev-list -1 v3.4.1`?

**Comment by adrianschmidt** [comment]
Argh!

I made this super-long post with log outputs and screenshots and everything, and just before I posted it, I thought I should just double check one thing… 😄

My colleagues had reset the build-process for some other projects, and accidentally included this one in a different pipeline. So it was indeed built twice.

Thanks for your help and sorry for wasting your time on a Friday night!
