### ISSUE TITLE
Disabling @semantic-release/github plugin

### ISSUE THREAD

**Issue by swapniljv** [semantic-release/semantic-release#922]
We want to use semantic-release for automating release with our scm gerrit repository.

Whenever we execute command : npm run semantic-release, it is always loading "success" and "fail" plugin from @semantic-release/github. Following is the output:

```
02:19:16 [20:49:16] [semantic-release] › ℹ  Running semantic-release version 15.9.12
02:19:16 [20:49:16] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "@semantic-release/npm"
02:19:17 [20:49:17] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
02:19:17 [20:49:17] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
02:19:17 [20:49:17] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
02:19:17 [20:49:17] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
02:19:17 [20:49:17] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
02:19:17 [20:49:17] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
02:19:17 [20:49:17] [semantic-release] › ✔  Run automated release from branch master
02:19:18 [20:49:18] [semantic-release] › ✔  Allowed to push to the Git repository
02:19:18 [20:49:18] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "@semantic-release/npm"
02:19:18 [20:49:18] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://artifactory.com/artifactory/api/npm/node
02:19:18 [20:49:18] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "@semantic-release/npm"
02:19:18 [20:49:18] [semantic-release] › ℹ  Found git tag v1.1.0 associated with version 1.1.0
02:19:18 [20:49:18] [semantic-release] › ℹ  Found 1 commits since last release
02:19:18 [20:49:18] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
02:19:18 [20:49:18] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat(disableGithub): trying to disable gitHub
02:19:18 
02:19:18 Change-Id: Idcf2b51ad172cb06c03ed39a7
02:19:18 [20:49:18] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
02:19:18 [20:49:18] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 1 commits complete: minor release
02:19:18 [20:49:18] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
02:19:18 [20:49:18] [semantic-release] › ℹ  The next release version is 1.2.0
02:19:18 [20:49:18] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
02:19:18 [20:49:18] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
02:19:18 [20:49:18] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
02:19:18 [20:49:18] [semantic-release] [@semantic-release/npm] › ℹ  Wrote version 1.2.0 to /home/ubuntu/workspace/experiments/package.json
02:19:19 [20:49:19] [semantic-release] [@semantic-release/npm] › ℹ  Wrote version 1.2.0 to /home/ubuntu/workspace/experiments/package-lock.json
02:19:19 [20:49:19] [semantic-release] [@semantic-release/npm] › ℹ  Creating npm package version 1.2.0 
```
intentionally ignored npm notice messages
```
02:19:20 [20:49:20] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
02:19:20 [20:49:20] [semantic-release] › ✔  Created tag v1.2.0
02:19:20 [20:49:20] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/npm"
02:19:20 [20:49:20] [semantic-release] [@semantic-release/npm] › ℹ  Publishing version 1.2.0 to npm registry
02:19:21 npm notice 
```
```
02:19:22 [20:49:22] [semantic-release] [@semantic-release/npm] › ℹ  Published web-components@1.2.0 on https://artifactory.com/artifactory/api/npm/node
02:19:22 [20:49:22] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/npm"
02:19:22 [20:49:22] [semantic-release] › ℹ  Start step "success" of plugin "@semantic-release/github"
02:19:22 [20:49:22] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
02:19:22 [20:49:22] [semantic-release] › ✖  Failed step "success" of plugin "@semantic-release/github"
02:19:22 [20:49:22] [semantic-release] › ℹ  Start step "fail" of plugin "@semantic-release/github"
02:19:22 [20:49:22] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
02:19:25 [20:49:25] [semantic-release] › ✖  Failed step "fail" of plugin "@semantic-release/github"
02:19:25 [20:49:25] [semantic-release] › ✖  EINVALIDGHTOKEN Invalid GitHub token.
02:19:25 The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository a/experiments.
02:19:25 
02:19:25 Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personal token.
02:19:25 
02:19:25 [20:49:25] [semantic-release] › ✖  EINVALIDGHTOKEN Invalid GitHub token.
02:19:25 The GitHub token (https://github.com/semantic-release/github/blob/master/README.md#github-authentication) configured in the GH_TOKEN or GITHUB_TOKEN environment variable must be a valid personal token (https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line) allowing to push to the repository a/experiments.
02:19:25 
02:19:25 Please make sure to set the GH_TOKEN or GITHUB_TOKEN environment variable in your CI with the exact value of the GitHub personal token.
02:19:25 
02:19:25 { AggregateError: 
02:19:25     SemanticReleaseError: Invalid GitHub token.
02:19:25         at module.exports (/home/ubuntu/workspace/experiments/node_modules/@semantic-release/github/lib/get-error.js:6:10)
02:19:25         at module.exports (/home/ubuntu/workspace/experiments/node_modules/@semantic-release/github/lib/verify.js:64:21)
02:19:25         at <anonymous>
02:19:25     at /home/ubuntu/workspace/experiments/node_modules/semantic-release/lib/plugins/pipeline.js:53:11
02:19:25     at <anonymous> name: [32m'AggregateError'[39m }npm ERR! code ELIFECYCLE
02:19:25 npm ERR! errno 1
02:19:25 npm ERR! web-components@1.0.0 semantic-release: `semantic-release`
02:19:25 npm ERR! Exit status 1
02:19:25 npm ERR! 
02:19:25 npm ERR! Failed at the web-components@1.0.0 semantic-release script.
02:19:25 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
02:19:25 
02:19:25 npm ERR! A complete log of this run can be found in:
02:19:25 npm ERR!     /home/ubuntu/.npm/_logs/2018-09-05T20_49_25_590Z-debug.log
```

Is there any way to disable github publish step.

Below is the config used:
```
 "publishConfig": {
    "registry": "https://artifactory.com/artifactory/api/npm/node",
    "tag": "latest"
  },
  "release": {
    "analyzeCommits": "@semantic-release/commit-analyzer",
    "verifyConditions": "@semantic-release/npm",
    "prepare": "@semantic-release/npm",
    "getLastRelease": "@semantic-release/npm",
    "generateNotes" : "@semantic-release/release-notes-generator",
    "publish": "@semantic-release/npm",
    "branch": "master",
    "npmPublish": true,
    "tarballDir": "dist",
    "assets": "dist/*.tgz"
  },
  "repository":{
    "type":"git",
    "url":"https://user@gerrit.com/a/experiments.git"
  }
```

**Comment by pvdlg** [comment]
Your config should be:
```json
{
"release": {
    "analyzeCommits": "@semantic-release/commit-analyzer",
    "verifyConditions": "@semantic-release/npm",
    "prepare": "@semantic-release/npm",
    "generateNotes" : "@semantic-release/release-notes-generator",
    "publish": "@semantic-release/npm",
    "success": false,
    "fail": false,
    "branch": "master",
    "npmPublish": true,
    "tarballDir": "dist",
    "assets": "dist/*.tgz"
  }
}
```

This is not really intuitive and should change soon: #827

**Comment by pvdlg** [comment]
Closing as a solution was provided.
