### ISSUE TITLE
Failed step "publish" of plugin "@semantic-release/github"

### ISSUE THREAD

**Issue by rolandjitsu** [semantic-release/semantic-release#995]
## Current behavior

When running this on CircleCI, it seems to fail to run the publish step of github.
What's weird, is that I can see 2 tags created and pushed to the repo.

## Expected behavior

It should not fail? 😕 

## Environment

- **semantic-release** version: 15.12.1
- CI environment: CircleCI
- Plugins used: 
- **semantic-release** configuration: [colormaps-client](https://github.com/thesoftwarecompany/colormaps-client)
- CI logs: 
```
[2:25:25 PM] [semantic-release] › ℹ  Running semantic-release version 15.12.1
[2:25:25 PM] [semantic-release] › ✔  Loaded plugin "verifyConditions" from "condition-circle"
[2:25:25 PM] [semantic-release] › ✔  Loaded plugin "analyzeCommits" from "@semantic-release/commit-analyzer"
[2:25:25 PM] [semantic-release] › ✔  Loaded plugin "generateNotes" from "@semantic-release/release-notes-generator"
[2:25:25 PM] [semantic-release] › ✔  Loaded plugin "prepare" from "@semantic-release/npm"
[2:25:25 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/npm"
[2:25:25 PM] [semantic-release] › ✔  Loaded plugin "publish" from "@semantic-release/github"
[2:25:25 PM] [semantic-release] › ✔  Loaded plugin "success" from "@semantic-release/github"
[2:25:25 PM] [semantic-release] › ✔  Loaded plugin "fail" from "@semantic-release/github"
[2:25:25 PM] [semantic-release] › ✔  Run automated release from branch master
[2:25:26 PM] [semantic-release] › ✔  Allowed to push to the Git repository
[2:25:26 PM] [semantic-release] › ℹ  Start step "verifyConditions" of plugin "condition-circle"
Getting git refs
ref HEAD hash 90b1a702374846eb73dd47e88b1e971cd4a76168
ref refs/heads/master hash 90b1a702374846eb73dd47e88b1e971cd4a76168
All done
[2:25:26 PM] [semantic-release] › ✔  Completed step "verifyConditions" of plugin "condition-circle"
[2:25:26 PM] [semantic-release] › ℹ  Found git tag v1.0.0 associated with version 1.0.0
[2:25:26 PM] [semantic-release] › ℹ  Found 3 commits since last release
[2:25:26 PM] [semantic-release] › ℹ  Start step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[2:25:26 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: feat: trick semantic-release into a release
[2:25:26 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The release type for the commit is minor
[2:25:26 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore: do not return true on deploy
[2:25:26 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:25:26 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analyzing commit: chore: set npm public access
[2:25:26 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  The commit should not trigger a release
[2:25:26 PM] [semantic-release] [@semantic-release/commit-analyzer] › ℹ  Analysis of 3 commits complete: minor release
[2:25:26 PM] [semantic-release] › ✔  Completed step "analyzeCommits" of plugin "@semantic-release/commit-analyzer"
[2:25:26 PM] [semantic-release] › ℹ  The next release version is 1.1.0
[2:25:26 PM] [semantic-release] › ℹ  Start step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:25:26 PM] [semantic-release] › ✔  Completed step "generateNotes" of plugin "@semantic-release/release-notes-generator"
[2:25:26 PM] [semantic-release] › ℹ  Start step "prepare" of plugin "@semantic-release/npm"
[2:25:26 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[2:25:26 PM] [semantic-release] [@semantic-release/npm] › ℹ  Wrote NPM_TOKEN to /home/circleci/colormaps-client/.npmrc
[2:25:27 PM] [semantic-release] [@semantic-release/npm] › ℹ  Write version 1.1.0 to package.json in /home/circleci/colormaps-client
v1.1.0
[2:25:27 PM] [semantic-release] › ✔  Completed step "prepare" of plugin "@semantic-release/npm"
[2:25:29 PM] [semantic-release] › ✔  Created tag v1.1.0
[2:25:29 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/npm"
[2:25:29 PM] [semantic-release] [@semantic-release/npm] › ℹ  Verify authentication for registry https://registry.npmjs.org/
[2:25:30 PM] [semantic-release] [@semantic-release/npm] › ℹ  Publishing version 1.1.0 to npm registry
...
+ colormaps@1.1.0
[2:25:35 PM] [semantic-release] [@semantic-release/npm] › ℹ  Published colormaps@1.1.0 on https://registry.npmjs.org/
[2:25:35 PM] [semantic-release] › ✔  Completed step "publish" of plugin "@semantic-release/npm"
[2:25:35 PM] [semantic-release] › ℹ  Start step "publish" of plugin "@semantic-release/github"
[2:25:35 PM] [semantic-release] [@semantic-release/github] › ℹ  Verify GitHub authentication
`error.code` is deprecated, use `error.status`.
`error.code` is deprecated, use `error.status`.
`error.code` is deprecated, use `error.status`.
`error.code` is deprecated, use `error.status`.
`error.code` is deprecated, use `error.status`.
`error.code` is deprecated, use `error.status`.
[2:25:45 PM] [semantic-release] › ✖  Failed step "publish" of plugin "@semantic-release/github"
[2:25:45 PM] [semantic-release] › ✖  An error occurred while running semantic-release: { HttpError: response.headers.entries(...) is not a function or its return value is not iterable
    at mockable.fetch.then.then.catch.error (/home/circleci/colormaps-client/node_modules/@octokit/request/lib/request.js:92:13)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  name: 'HttpError',
  status: 500,
  headers: {},
  pluginName: '@semantic-release/github' }
{ HttpError: response.headers.entries(...) is not a function or its return value is not iterable
    at mockable.fetch.then.then.catch.error (/home/circleci/colormaps-client/node_modules/@octokit/request/lib/request.js:92:13)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  name: 'HttpError',
  status: 500,
  headers: {},
  pluginName: '@semantic-release/github' }
```

**Comment by pvdlg** [comment]
Ok after more research the problem is due to an outdated version of `node-fetch`.

@rolandjitsu this is because you are forcing this outdated version with your `yarn.lock` file: https://github.com/thesoftwarecompany/colormaps-client/blob/master/yarn.lock#L3817

@gr2m, [@octokit/request.js](https://github.com/octokit/request.js) uses `node-fetch` [here](https://github.com/octokit/request.js/blob/e5a851dfc6e0feccff6b3b30aea8b5780c362897/lib/fetch.js#L2) but doesn't defined it in its `package.json`. If it was properly set in `dependencies` the problem wouldn't have happen as Yarn or npm would have guaranteed the version requested.

For info there is ESlint rules to check those type of things: [import/no-extraneous-dependencies](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-extraneous-dependencies.md).

**Comment by elevatebart** [comment]
Do you think https://github.com/vue-styleguidist/vue-styleguidist has the same issue ? I am having the same issue but use npm. I will check the package-lock when I get back

Happy Thanksgiving

**Comment by elevatebart** [comment]
It was !! Thank you @pvdlg, could we make sure that this plugin requires a recent enough version of node-fetch? Just for safety.

**Comment by pvdlg** [comment]
As explained above the problem is in `@octokit/request.js`. Adding a dependency to `node-fetch` will not solve the problem. Actually `@octokit/rest.js` which is a parent of `@octokit/request.js` already defines the dependency to `node-fetch`.

The problem is that you have something in your project that defines a dependency to `node-fetch@^1.0.0` and `@octokit/rest.js` has one to `node-fetch@^2.0.0`, but the way Yarn/npm resolves that is by providing `node-fetch@^2.0.0` to `@octokit/rest.js` and `node-fetch@^1.0.0` to everything else. I don't know exactly what the rules are in Yarn/npm, but in any case you can't expect Yarn/npm to provide you systematically the right version if you don't specifies it.

**Comment by elevatebart** [comment]
so a PR to octokit/request adding the dependency would make sense. Shoul I do it ?

**Comment by pvdlg** [comment]
I have one almost ready. Thanks though.

**Comment by gr2m** [comment]
it was fixed in https://github.com/octokit/request.js/pull/15/files, a new release is already out

**Comment by pvdlg** [comment]
Closing as it was already fixed in https://github.com/octokit/request.js/pull/15.
Just update your `yarn.lock` or `package-lock.json` to use up to date dependencies.
